### ISSUE TITLE
Testcafe allows me to click on overlapped elements.

### ISSUE THREAD

**Issue by mkubrycz** [DevExpress/testcafe#1007]
### Are you requesting a feature or reporting a bug?

Reporting a bug

### What is the current behavior?

When I run test trying to click button which is overlapped by another element my test passes.

### What is the expected behavior?

Test should fail to click element which is overlapped by another element as a browser user would.

### How would you reproduce the current behavior (if this is a bug)?

below I'm sending example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://jsfiddle.net/vsh207dn/

Test code

```js
import { Selector } from 'testcafe';

const element = Selector(query => document.querySelector(`${query}`));

fixture `Testing testcafe`
  .page `https://jsfiddle.net/vsh207dn/`;

test('Fail to click on overlapped element', async t => {
  await t
    .switchToIframe(element('*[name="result"]'))
    .click(element('button.center'));
});
```

### Specify your

* operating system: macOS Sierra
* testcafe version: 0.10.0
* node.js version: 6.9.1

**Comment by AlexanderMoskovkin** [comment]
Hi @mkubrycz,

TestCafe works properly here. If an element (for example `Element A`) is on the page TestCafe clicks at the point where the element is placed. But if the element is overlapped by another element (`Element B`) TestCafe raises clicks on the top element (`Element B`). It maybe useful in some test cases (for example you would like to check that the element is on the page, but it's not possible to click on it).

In your case click on the `button.center` element should lead to `alert()` dialog. Let's check it in the following test:
```js
import assert from 'assert';
import { Selector } from 'testcafe';

fixture `Testing testcafe`
  .page `https://jsfiddle.net/vsh207dn/`;

test('Fail to click on overlapped element', async t => {
  await t
    .switchToIframe('*[name="result"]')
    .setNativeDialogHandler(() => true)
    .click('button.center');

    const history = await t.getNativeDialogHistory();

    assert.deepEqual(history.length, 1);
});
```

The test is failed because `alert` dialog was not appeared.
But if you hide the `.center.over` element (https://jsfiddle.net/vsh207dn/5/) test will be successfull.

**Comment by mkubrycz** [comment]
Thank you! That explains my problem.
