### ISSUE TITLE
Add <object> handling similar to <iframe> switchToIframe function

### ISSUE THREAD

**Issue by mkubrycz** [DevExpress/testcafe#1021]
### Expected behavior

I would like to access <object> elements with something like switchToObject which would allow me to interact with elements within that object.

**Comment by helen-dikareva** [comment]
The <object> tag defines an embedded object within an HTML document. It's used to 
embed multimedia (like audio, video, Java applets, ActiveX, PDF, and Flash).
We do not have access to <object> contents because it's not a DOM structure. So we cannot execute actions and perform assertions with it. That's why we do not support testing of <object> contents.

**Comment by wentwrong** [comment]
I reopened this issue because the [\<object\>](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-object-element) element can represent an external resource that could be nested browser context.
