### ISSUE TITLE
TD - 0.12.0 - Test stalls on second or third time

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe#1154]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Test stalls 

### What is the expected behavior?

Test should work

### How would you reproduce the current behavior (if this is a bug)?

run test several times

#### Provide the test code and the tested page URL (if applicable)
```js
import { Selector, ClientFunction } from 'testcafe';

fixture("TD 0.12.0 FIRST")
    .page `https://jqueryui.com/selectable/#serialize`;

test('Test1', async t => {
    await t
        .switchToIframe('iframe')
        .click('#selectable > li:nth-child(2)')
        .click('#selectable > li:nth-child(5)', { modifiers: { ctrl: true } })
        .expect(Selector('#selectable > li:nth-child(2)').hasClass('ui-selected')).ok()
        .expect(Selector('#selectable > li:nth-child(5)').hasClass('ui-selected')).ok();
});

test('Test2', async t => {
    await t
        .switchToIframe('iframe')
        .click('#selectable > li:nth-child(2)')
        .click('#selectable > li:nth-child(5)', { modifiers: { ctrl: true } })
        .expect(Selector('#selectable > li:nth-child(2)').hasClass('ui-selected')).ok()
        .expect(Selector('#selectable > li:nth-child(5)').hasClass('ui-selected')).ok();
});

```

### Specify your

* operating system: win10
* testcafe version: 0.12.0
* node.js version: 4.4.7

**Comment by georgiy-abbasov** [comment]
I'm working on this

**Comment by georgiy-abbasov** [comment]
Target iframe changes `src` after page is opened. TestCafe getting stuck, when try to perform an action on iframe with "old" `src`, while iframe has the new value as `src`. It's due to the fact, that `ParentDriverLink` of the first iframe window has established connection with top window `Driver`, and it begin executing next command at the same time, when iframe `src` changes (in most of cases on this page). As the result, top window `Driver` infinitely waits for response from previous iframe content window.

**Comment by miherlosev** [comment]
Run 10 times on `0.19.2`. Tests are passed.
