### ISSUE TITLE
Tests pause while the browser window is not in focus

### ISSUE THREAD

**Issue by umaar** [DevExpress/testcafe#1198]
Not sure if this is intentional, but the tests pause while the browser window is not in focus (for example another window is in front of it). This is not great during development because while running your tests (which could take minutes to execute), you might have another window open like your code editor.

### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Tests pause when the browser window is not in focus.

### What is the expected behavior?

Tests continue when window is not in focus.

### How would you reproduce the current behavior (if this is a bug)?

Run some testcafe tests in Chrome.

### Specify your

* operating system: OS X 10.11.6
* testcafe version: 0.12.1
* node.js version: 7

**Comment by AlexanderMoskovkin** [comment]
When you switch to another window in full-screen mode in OS X, the OS switches the browser to lower resource consumption mode where tests are not guaranteed to be executed correctly. It's not recommended also to minimize the window and to switch to another tab in the same browser window. TestCafe can't do something here because it's related to the OS behavior. 
But you can switch to another window in not full-screen mode. In this case test works properly.

**Comment by umaar** [comment]
Got it, makes sense. Thanks for explaining.
