### ISSUE TITLE
Unable to run chrome at /Applications/Google_Chrome.app

### ISSUE THREAD

**Issue by mmakarios** [DevExpress/testcafe#1384]
### Are you requesting a feature or reporting a bug?

Reporting a bug

### What is the current behavior?

When executing `testcafe chrome test.js`, I get:
```
ERROR Was unable to open the browser "locally-installed:chrome" due to error.

Unable to run the browser. The file at /Applications/Google_Chrome.app does not exist or is not executable.
```
`testcafe -b` gives me `firefox`, `chrome` and `safari`. Running the test with Firefox or Safari works fine.

### What is the expected behavior?

A Chrome window should open.

### How would you reproduce the current behavior (if this is a bug)?
`npm install testcafe -g` and executing a test file with `testcafe chrome test.js`.

#### Provide the test code and the tested page URL (if applicable):

Tested page URL: https://devexpress.github.io/testcafe/example

Test code:

```js
fixture `Example page`
    .page `https://devexpress.github.io/testcafe/example`;

test('Emulate user actions and perform a verification', async t => {
    await t
        .setNativeDialogHandler(() => true)
        .click('#populate')
        .click('#submit-button');

    const location = await t.eval(() => window.location);

    await t.expect(location.pathname).eql('/testcafe/example/thank-you.html');
});
```

### Specify your

* operating system: macOS Sierra 10.12.4
* testcafe version: 0.14.0
* node.js version: 7.8.0

**Comment by AndreyBelym** [comment]
Hello @mmakarios! Are you sure that Chrome installed in `/Applications/Google_Chrome.app`? Can you try to delete Chrome, then in terminal execute `rm-rf /Applications/Google_Chrome.app`, and install Chrome back?

**Comment by mmakarios** [comment]
I got it working by right-clicking the Chrome icon in the Applications folder, clicking in "Get Info" and changing the admin privilege to "Read & Write" (it was "Read only").

![image](http://i63.tinypic.com/5190yq.jpg)

But then I changed it back to "Read only" and it still works, so I don't know what solved the issue.

Before that I tried deleting Chrome and fresh installing again, didn't work.
Also, I had to run `rm -rf /Applications/Google\ Chrome.app` without an underscore (`Google_Chrome`) to remove it.

Thanks @AndreyBelym!

**Comment by mbbaldwin** [comment]
I am also having this problem. But changing Chrome to  Read & Write did not solve the issue

**Comment by AndreyBelym** [comment]
Hello @mbbaldwin! Can you show me the text of the error and output of the 
``` 
ls -l /Applications/
``` 
command?

**Comment by mbbaldwin** [comment]
@AndreyBelym 

error in test cafe output:

ERROR Was unable to open the browser "locally-installed:chrome" due to error.

Unable to run the browser. The file at /Applications/Google Chrome.app does not exist or is not executable.


result of 'ls -l /Applications/'
total 0
drwxr-xr-x@  3 root         wheel  102 Jun 24  2016 App Store.app
drwxrwxrwx@  3 development  admin  102 May 18 02:38 Firefox.app
drwxrwxrwx@  3 development  admin  102 May  8 22:03 Google Chrome.app
drwxr-xr-x   3 root         wheel  102 Jun  1 16:09 Jenkins
drwxr-xr-x@  3 root         wheel  102 Jun 30  2016 Safari.app
drwxr-xr-x@  3 development  admin  102 May 15 04:03 Skype.app
drwxr-xr-x@  3 development  admin  102 Sep 23  2016 Sublime Text.app
drwxr-xr-x@  3 root         wheel  102 Oct 14  2016 TextEdit.app
drwxr-xr-x   3 root         wheel  102 May 24 15:29 Xcode.app

**Comment by AndreyBelym** [comment]
Can you please try to execute
```
open -n -a "/Applications/Google Chrome.app" --args http://www.google.com --no-first-run --new-window
```
Will it launch Chrome or not?

**Comment by mbbaldwin** [comment]
it opens a new window in chrome

**Comment by AndreyBelym** [comment]
Thank you, please try to run
```
testcafe 'path:/Applications/Google Chrome.app' tests
```

**Comment by mbbaldwin** [comment]
This was returned:

Using locally installed version of TestCafe.
ERROR Was unable to open the browser "path:/Applications/Google Chrome.app" due to error.

The specified browser name is not valid!

**Comment by AndreyBelym** [comment]
Please, can you submit an output of 
```
diskutil info /
```
And also
```
testcafe --version
```

Also, please, try
```
testcafe 'path:/Applications/Google Chrome' $TESTS
```
and
```
ln '/Applications/Google Chrome.app' /Applications/Chrome.app
testcafe chrome $TESTS
testcafe path:/Applications/Chrome $TESTS
testcafe path:/Applications/Chrome.app $TESTS
```

**Comment by mbbaldwin** [comment]
`diskutil info /`

 Device Identifier:        disk0s2
   Device Node:              /dev/disk0s2
   Whole:                    No
   Part of Whole:            disk0

   Volume Name:              Macintosh HD
   Mounted:                  Yes
   Mount Point:              /

   Partition Type:           Apple_HFS
   File System Personality:  Journaled HFS+
   Type (Bundle):            hfs
   Name (User Visible):      Mac OS Extended (Journaled)
   Journal:                  Journal size 81920 KB at offset 0x1d18000
   Owners:                   Enabled

   OS Can Be Installed:      Yes
   Recovery Disk:            disk0s3
   Media Type:               Generic
   Protocol:                 SATA
   SMART Status:             Verified
   Volume UUID:              97A4ED1E-CAFF-3AEB-B796-387D5AC7578B
   Disk / Partition UUID:    000020DF-7AF0-0000-CE2D-0000345B0000

   Disk Size:                898.0 GB (898000027648 Bytes) (exactly 1753906304 512-Byte-Units)
   Device Block Size:        512 Bytes

   Volume Total Space:       898.0 GB (898000027648 Bytes) (exactly 1753906304 512-Byte-Units)
   Volume Used Space:        38.6 GB (38561439744 Bytes) (exactly 75315312 512-Byte-Units) (4.3%)
   Volume Available Space:   859.4 GB (859438587904 Bytes) (exactly 1678590992 512-Byte-Units) (95.7%)
   Allocation Block Size:    4096 Bytes

   Read-Only Media:          No
   Read-Only Volume:         No

   Device Location:          Internal
   Removable Media:          Fixed

   Solid State:              No


`testcafe --version`

0.15.0

`testcafe 'path:/Applications/Google Chrome' $TESTS`

ERROR Was unable to open the browser "path:/Applications/Google Chrome" due to error.

The specified browser name is not valid!

`ln '/Applications/Google Chrome.app' /Applications/Chrome.app`

ln: /Applications/Google Chrome.app: Is a directory

`testcafe chrome test/integrationTests/donationTests.js`

Using locally installed version of TestCafe.
ERROR Was unable to open the browser "locally-installed:chrome" due to error.

Unable to run the browser. The file at /Applications/Google Chrome.app does not exist or is not executable.

`testcafe path:/Applications/Chrome test/integrationTests/donationTests.js`

Using locally installed version of TestCafe.
ERROR Was unable to open the browser "path:/Applications/Chrome" due to error.

The specified browser name is not valid!

`testcafe path:/Applications/Chrome.app test/integrationTests/donationTests.js`

Using locally installed version of TestCafe.
ERROR Was unable to open the browser "path:/Applications/Chrome.app" due to error.

The specified browser name is not valid!

**Comment by AndreyBelym** [comment]
Sorry, my mistake, the first commands must be `ln -s`:
```
ln -s '/Applications/Google Chrome.app' /Applications/Chrome.app
testcafe chrome $TESTS
testcafe path:/Applications/Chrome $TESTS
testcafe path:/Applications/Chrome.app $TESTS
```

**Comment by mbbaldwin** [comment]
I still get the same outputs after changing the first command to 
`ln -s '/Applications/Google Chrome.app' /Applications/Chrome.app`
returns:
ln: /Applications/Chrome.app/Google Chrome.app: File exists

**Comment by mbbaldwin** [comment]
I should mention that I am also running this with Jenkins

**Comment by dylanharrington** [comment]
I'm seeing the same issue as @mbbaldwin.

I've discovered that renaming `Google Chrome.app` to `Chrome.app` and then running `testcafe 'path:/Applications/Chrome.app' $TESTS` works where `testcafe 'path:/Applications/Google Chrome.app' $TESTS` did not.

**Comment by Pr60** [comment]
@dylanharrington , @AndreyBelym  - I still get the error but unable to get it up and running: 

`+ testcafe chrome uitests/tests/peopletest.js -r xunit:res.xml -e
Using locally installed version of TestCafe.
Error: Unable to run the browser. The file at /Applications/Google Chrome.app does not exist or is not executable.
    at Object.callee$0$0$ (/Users/Shared/Jenkins/Home/workspace/RpWeb/node_modules/testcafe-browser-tools/lib/api/open.js:137:23)
    at tryCatch (/Users/Shared/Jenkins/Home/workspace/RpWeb/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at Generator.invoke [as _invoke] (/Users/Shared/Jenkins/Home/workspace/RpWeb/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:334:22)
    at Generator.prototype.(anonymous function) [as throw] (/Users/Shared/Jenkins/Home/workspace/RpWeb/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at tryCatch (/Users/Shared/Jenkins/Home/workspace/RpWeb/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at invoke (/Users/Shared/Jenkins/Home/workspace/RpWeb/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:146:20)
    at /Users/Shared/Jenkins/Home/workspace/RpWeb/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:156:13
Build step 'Execute shell' marked build as failure
Recording test results
Finished: FAILURE`

Please update me if there is any wayout.

**Comment by AndreyBelym** [comment]
Have you tried renaming `/Applications/Google Chrome.app` to `/Applications/Chrome.app` as suggested in @dylanharrington's [comment](https://github.com/DevExpress/testcafe/issues/1384#issuecomment-308586005)?

Also, please note that in `Google Chrome.app` `Chrome` starts with the capital `C` and in the recent TestCafe versions, the `path` provider requires that a browser path with spaces [must be surrounded](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#portable-browsers) with the backticks (`):

```
testcafe 'path:`/Applications/Google Chrome.app`' uitests/tests/peopletest.js -r xunit:res.xml -e
```

**Comment by Pr60** [comment]
@AndreyBelym - Thanks. I tried changing `/Applications/Google Chrome.app` to `/Applications/Chrome.app` (from @dylanharrington ) as well but I got same error. Also, I tried with small case and uppercase `Chrome` as well but that throws same error. I'm using the latest `Chrome Version 71.0.3578.98`. Also, I tried the same stuffs with `Safari` as well but again I received the same error. It will be great if you have anything else to suggest.

**Comment by Pr60** [comment]
@AndreyBelym - Thanks for your detailed explanation. I tried to open Chrome from my terminal (using `jenkins` user) as mentioned above and it failed to open. If I try to open Chrome using `devuser` then Chrome opens successfully. The `jenkins` user is also an admin of the system.

Then, I followed the steps mentioned over [here](https://testcafe-discuss.devexpress.com/t/how-to-integrate-testcafe-with-jenkins-ci-system/607/7) and started the build and it throw the same error, which I didn't expect. 

When I did `ls -l /Applications/` - this is what I got: 
```
drwxrwxrwx@  4 devuser  admin   96 11 Dec 23:43 Google Chrome.app
drwxr-xr-x   3 root           wheel   96 24 Sep 13:10 Jenkins
```
Unfortunately, it looks like I'm missing some more settings which is not allowing `Chrome/Safari` to open.

**Comment by Pr60** [comment]
@AndreyBelym - Update on my above comment. I was able to make it work by changing the ownership of `Jenkins` user to `devuser`. The steps provided in this [link](https://testcafe-discuss.devexpress.com/t/how-to-integrate-testcafe-with-jenkins-ci-system/607/7) didn't work for me. I have to do a bit more modification. I did 2 more steps and not performed the last step mentioned in this comment. 

Firstly, I stopped the Jenkins as mentioned in this [link](https://stackoverflow.com/questions/24092295/change-the-jenkins-default-user-user-name-on-mac).
Secondly, I updated the JENKINS_HOME and USER_NAME as mentioned [link](https://testcafe-discuss.devexpress.com/t/how-to-integrate-testcafe-with-jenkins-ci-system/607/7).
Thirdly, I changed the ownership of `/var/log/jenkins` to the user I wanted to run Jenkins
Lastly, started Jenkins [link](https://stackoverflow.com/questions/24092295/change-the-jenkins-default-user-user-name-on-mac).

**Comment by AndreyBelym** [comment]
I'm happy to hear that you have resolved the problem, thank you for sharing the details with me. I've created issue #3370 about updating our Jenkins recipe to include the steps you described.

**Comment by valstu** [comment]
I struggled with similar problem for almost two days. When I started the tests the chrome browser didn't start for some reason, not even in headless mode. So I reinstalled Chrome, change the name from `Google Chrome.app` to `Chrome.app` and much more. I also noticed that when I ran it with `testcafe 'path:`/Applications/Google Chrome.app`' test.e2e.js` everything worked which pretty means that it is some kind of path problem with Chrome. I also have to mention that when I reinstalled the Chrome I did a complete reinstall, so the newly installed Chrome didn't have any plugins or extension.

So after I figured out it was some kind of path problem I made a custom version of Testcafe which added a lot of logging related to browser paths. After a while I noticed that the `chromeOpenParameters` (`/src/browser/provider/built-in/chrome/local-chrome.js`) contains the `path` property which is used to start the browser (Chrome in this case), so in my case the path should be `/Applications/Google Chrome.app`. Instead of that the path was `/Applications/TeliaCompanyOTTChromePlugin.app`. So the path pointed to a Chrome plugin 😱. 

Removing the plugin fixed everything. 🤷‍♂️

Why the path was wrong? I have no idea but hopefully this will help someone else struggling with similar issue or the Testcafe team debugging this.

**Comment by AndreyBelym** [comment]
@valstu Thank you for sharing your experience. TestCafe scans the `/Applications` folder and treats any app from this directory as a browser if its name contains `Chrome`. I suggested a more robust modification of the browsers detection algorithm: https://github.com/DevExpress/testcafe-browser-tools/pull/144, but it was slower and we decided that we should combine it with the current implementation to reduce the browser detection time. 

Also, we can improve the error message to include the path to the browser: #3589.
