### ISSUE TITLE
debug app under test from chrome devtools when using .debug()

### ISSUE THREAD

**Issue by mulyoved** [DevExpress/testcafe#1456]
When test stop in .debug() and open chrome dev tools cannot do much to debug the application under test

for example cannot right click on an element to see the DOM properties

Am I missing something?

```
fixture `debug-with-testcafe`
  .page `https://devexpress.github.io/testcafe/`;

test('debug', async t => {
  await t
    .debug()
});
```

**Comment by AlexanderMoskovkin** [comment]
Hi,

TestCafe prevents all real user actions (by mouse and keyboard, except scrolling and pressing key that executes some special commands, like opening browser devtools) during running a test. Otherwise you can change the page state (for example by clicking on a link) and the test will be invalid). Meanwhile you can inspect the page elements via developer tools, testcafe doesn't blocks them.

Usually when we see some unexpected page behavior during the test running we usually open the page in a new browser window and perform steps from the test manually and see what's wrong)

**Comment by mulyoved** [comment]
during test run this is clear

question/request is in debug pause mode

![5-3-2017 9-30-21 am](https://cloud.githubusercontent.com/assets/2309907/25650166/cae07c9a-2fe3-11e7-982d-64c911573cb7.png)

while in debug mode, cannot explore the app DOM elements

**Comment by AlexanderMoskovkin** [comment]
To be able to click on element on the page to see it in devtools click on the `Select an element in the page to inspect it` in the devtools panel before it (see https://www.screencast.com/t/xiCgt4UcV)

**Comment by mulyoved** [comment]
got you, this is working fine
