### ISSUE TITLE
zsh: command not found: testcafe

### ISSUE THREAD

**Issue by sibliss** [DevExpress/testcafe#1479]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
after installing testcafe in my terminal the command "testcafe" is not recognised

### How would you reproduce the current behavior (if this is a bug)?
⇒  npm install testcafe
⇒  testcafe chrome test/e2e/first_test.js
zsh: command not found: testcafe

### Specify your

* operating system: macOS Sierra 10.12.4 with zsh shell
* testcafe version: 15.1.2
* node.js version: v7.10.0

**Comment by AndreyBelym** [comment]
Hi @sibliss! You've got the error because TestCafe was installed locally with `npm install testcafe`.To use TestCafe as a regular CLI application, install it globally with `npm install -g testcafe`. Also if you have to stick with local installation, you can use `testcafe` script from `node_modules` folder: `./node_modules/.bin/testcafe chrome tests/` or event add `./node_modules/.bin` to the `PATH` environment variable.

**Comment by sibliss** [comment]
Thanks installing it globally solved the problem!

**Comment by AndreyBelym** [comment]
Please note, that `node_modules/.bin` folder is automatically added to the `PATH` when NPM runs its [scripts](https://docs.npmjs.com/misc/scripts), so you can just use `testcafe` command in NPM scripts, e.g. `npm test` even if TestCafe is installed locally!
