### ISSUE TITLE
Documentation "how to select an option"

### ISSUE THREAD

**Issue by dhoko** [DevExpress/testcafe#1570]
Hey :wave: 

I lost a lot of time trying to select an option inside a form :/, I found this link [How can I select a dropdown option](https://testcafe-discuss.devexpress.com/t/how-can-i-select-a-dropdown-option/69/3) which is useless as it doesn't work. 

Then, I read your tests and found [this line](https://github.com/DevExpress/testcafe/blob/master/examples/basic/test.js#L76), I tested it with my app, and it works :champagne: 

As there is nothing for this use case inside the documentation, should I add something inside the main documentation or create a new recipe ?

**Comment by AlexanderMoskovkin** [comment]
Hi @dhoko,

The approach described in the topic in the forum is outdated since we reworked Selector system in v0.11.0. Since this version `Selector` has the `withText()` function that allows to find an element by its text.
When you need to click on an `option` element you operate with it in the same way as with any other element on the page. You can find it via its text, attribute, index etc. with [Selectors](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors.html#creating-selectors).
I suppose we can describe it in a new recipe to make it clear.

**Comment by dhoko** [comment]
ok I will write a small recipe

**Comment by VasilyStrelyaev** [comment]
@dhoko, it just so happened that I already have the draft of such a recipe. You are welcome to review the pull request: https://github.com/DevExpress/testcafe/pull/1586
