### ISSUE TITLE
Unable to see text inside span using .hover

### ISSUE THREAD

**Issue by afcbpeter** [DevExpress/testcafe#1587]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
When using a .hover and using a span as a selector the hover over text doesn't appear and seems to select the wrong text. The text it does pick is Paused which is the div:nth-child(3)

### What is the expected behavior?
Would like to be able to check the hover over text. 

#### Provide the test code and the tested page URL (if applicable)
```js
test('Scenario: Viewing the filter titles', async t => {
    await setupPaused(t)
        .click(auditSearchPage.statusSearch)
        .typeText(auditSearchPage.statusSearch, 'Paused')
        .pressKey('enter')
        .click(auditSearchPage.searchBtn);
        let extractedStatusPaused = await Extractions.getInnerTextForRow(auditSearchPage.getStatusForRow);

        await t.hover(auditSearchPage.statusPaused)
            .wait(3000)
            .expect(auditSearchPage.statusPaused.innerText).contains("Failure to distribute message after 2 attempts. Pausing subscription");
    });
```
Selector Path:
 this.statusPaused = Selector('#app > div > div.audit-list > ol > li:nth-child(2) > div:nth-child(3) > span');

### Specify your

* operating system: OSX
* testcafe version: 0.15.0
* node.js version: 4.2.0

**Comment by AlexanderMoskovkin** [comment]
Hi,

It seems the issue is specific for you page and we need to see it to help you.
Could you please provide us with your page? Or you can create a simple markup example that allow to reproduce the issue (for example you can use jsfiddle.net).

You can use the [`await t.debug()`](https://devexpress.github.io/testcafe/documentation/test-api/debugging.html#client-side-debugging) command to stop the test in some place in the test and see your page markup and check what the element the `#app > div > div.audit-list > ol > li:nth-child(2) > div:nth-child(3) > span` css selector returns.

**Comment by afcbpeter** [comment]
Hi,

I tried the debug it's actually pretty cool but didn't really give me anything of any use to try and get to the bottom of this. 

I've done a JS Fiddle of the kind of stuff we are looking at. If you look at the hover over. The text on the over I can't seem to see when using the span class it always finds the Paused instead. I hope this helps let me know if you need anything else. 

https://jsfiddle.net/afcbpeter/0upte2ua/1/

**Comment by AlexanderMoskovkin** [comment]
Thanks for your example.
It seems you'd like to check the text that appears in the tooltip: `Failure to distribute message after 2 attempts. Pausing subscription.`

If take a look at the markup I see this text is not in the element inner html but in the `title` attribute. So you can check this attribute value:
```js
import { Selector } from 'testcafe';

fixture `fixture`;

test
    .page('https://jsfiddle.net/afcbpeter/0upte2ua/1/')
    ('test', async t => {
        const span = Selector('li span').nth(0);

        await t
             .switchToIframe('[name=result]')
            .hover(span)
             // check text content
             .expect(span.textContent).eql('paused')
             // check tooltip text
             .expect(span.getAttribute('title')).eql('Failure to distribute message after 2 attempts. Pausing subscription.');
	});

```

**Comment by afcbpeter** [comment]
Hi Alexander,

That worked perfectly.

Thank you.

**Comment by AlexanderMoskovkin** [comment]
You're welcome!

**Comment by srikanthchitla** [comment]
Can we get color of the text when hover on it ?

**Comment by aleks-pro** [comment]
Thank you for your inquiry. This issue looks like a question that would be best asked on [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template. Thank you in advance.
