### ISSUE TITLE
childElementCount returns an Object

### ISSUE THREAD

**Issue by ganlanyuan** [DevExpress/testcafe#1613]
### Are you requesting a feature or reporting a bug?
Bug.
It works well with 0.10.0, but not with 0.16.2.
Did the API change?

### What is the current behavior?
`childElementCount` returns an Object.
input:
``` javascript
var container = await Selector('#base');
console.log(container.childElementCount);
```
output:
```
ClientFunctionResultPromise { _then: [], _fn: [Function], _taskPromise: null }
```

### What is the expected behavior?
It should return a number as described in the [doc: DOM Node State](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/dom-node-state.html).

### Specify your
* operating system: macOS Sierra
* testcafe version: 0.16.2
* node.js version: v6.10.0

**Comment by AlexanderMoskovkin** [comment]
Hi @ganlanyuan,

The `var container = Selector('#base');` crerates a Selector, that exposes *async* methods and property getters to [get element state](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors.html#obtain-element-state), so they are should be called with `await`:
```js
var container = Selector('#base');

console.log(container.childElementCount); // => <Promise>
console.log(await container.childElementCount); // => <number>
```

If you'd like to get an [element snaphot](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors.html#dom-node-snapshot) that contains all property values exposed by the selector in a single object you need to call the selector with the await keyword like you would do with regular async functions:
```js
var container = Selector('#base');
var containerSnapshot = await container();

console.log(containerSnapshot.childElementCount); // => <number>
```
or
```js
var containerSnapshot = await Selector('#base')();

console.log(containerSnapshot.childElementCount); // => <number>
``` 
> Note, that we recommend to use the first way. When you use selector's property in assertions instead of snapshot properties TestCafe enables [Smart Assertion Query Mechanism](https://devexpress.github.io/testcafe/documentation/test-api/waiting-for-page-elements-to-appear.html#waiting-for-assertions-to-pass).

This behavior wasn't changed since 0.10.0 version. I've just run the following test in both versions and here are results:
```js
import { Selector } from 'testcafe';

fixture `fixture`
	.page `http://example.com`;
	
test('test', async t => {
	var container = await Selector('body');
	
	console.log('container.childElementCount:', container.childElementCount);
	console.log('await container.childElementCount:', await container.childElementCount);
});
```
![2017-07-14_0035](https://user-images.githubusercontent.com/12047804/28188910-a05301a0-67d8-11e7-83ef-5c22516cde71.png)

And I've just found that the description in the [DOM Node Snaphot](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors.html#dom-node-snapshot) article is correct but the example is not and I've created an issue for that: #1614

**Comment by ganlanyuan** [comment]
Hi, @AlexanderMoskovkin 
Thanks for your awesome explanation, so every time I want to use the selector property, I should add a `await` keyword?
``` javascript
var container = Selector('#base');
var parent = container.parent(); // no need to use `await` for selector, right?
expect(await parent.hasClass(['class1', 'class2']));
expect(await parent.boundingClientRect.left).to.equal(0);
```

**Comment by AlexanderMoskovkin** [comment]
Yes, you are right.

Note that we recommend to use built-in [Assertions](https://devexpress.github.io/testcafe/documentation/test-api/assertions/) that [were added in 0.11.0](https://devexpress.github.io/testcafe/blog/testcafe-v0-11-0-released.html#built-in-assertions-998). If you use it you can pass selector properties without await, TestCafe resolves it automatically:
```js
var container = Selector('#base');
var parent = container.parent();

await t
    .expect(parent.hasClass('classname')).ok()
    .expect(parent.boundingClientRect.left).eql(0);
```

**Comment by ganlanyuan** [comment]
Wow,
The built-in Assertions is excellent!
Thanks

**Comment by ganlanyuan** [comment]
Hi,
When I test
```javascript
const container = Selector('#base');
await t
    .expect(container.boundingClientRect.left).eql(0);
```
Got the error
```
1) AssertionError: expected undefined to deeply equal 0
```

But when I run
```javascript
console.log(await container.boundingClientRect);
```
I got
```
 Running tests in:
 - HeadlessChrome 0.0.0 / Mac OS X 10.12.5

 base
{ left: -5973.3310546875,
  right: 8959.9970703125,
  top: 304.8125,
  bottom: 663.8125,
  width: 14933.328125,
  height: 359 }
```
which shows `container.boundingClientRect` is an `Object`.
But why I couldn't get it's `left` property?

**Comment by AlexanderMoskovkin** [comment]
`container.boundingClientRect` returns a Promise. The Promise doesn't contain the `left` property. But the result of the Promise awaiting returns an object with the `left` property.
If you'd like to check the left property you can use the `getBoundingClientRectProperty` method:

```js
await t.expect(container.getBoundingClientRectProperty('left')).eql(0);
```

**Comment by ganlanyuan** [comment]
Thanks,
I got the `left` value use `getBoundingClientRectProperty`.
