### ISSUE TITLE
Support WSL

### ISSUE THREAD

**Issue by Hotell** [DevExpress/testcafe#1640]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
when providing `path` from WSL, testcafe errors out,

```sh
$ npx testcafe path:/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe test.js

ERROR Was unable to open the browser "path:/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" due to error.
```

![testcafe-doesnt-work-from-wsl](https://user-images.githubusercontent.com/1223799/28474952-c8bfeac2-6e4a-11e7-9375-77d2a48859e5.gif)

maybe @bitcrazed can help us with some insights why may this happening from WSL perspective 

### What is the expected behavior?
make parth properly work from WSL

### How would you reproduce the current behavior (if this is a bug)?
see attached gif

### Specify your

* operating system: Win 10 CU with WSL - ubuntu 16
* testcafe version: testcafe@0.16.2
* node.js version: 8.1.4

**Comment by bitcrazed** [comment]
Have you tried wrapping the entire path in quotes (due to the spaces)?

    $ npx testcafe path:'/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe test.js'

**Comment by Hotell** [comment]
thanks for stepping in @bitcrazed . That didn't help unfortunately, same error. I guess issue is with testcafe implementation

**Comment by Hotell** [comment]
ha! so I've spent few minutes on debugging async/await compiled to es5 ( feels like shooting yourself in the head btw ehm .... ) and I found the issue and got it working :)

command:
`npx testcafe path:"/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" test.js --hostname localhost`

![image](https://user-images.githubusercontent.com/1223799/28492970-97ba215e-6f0d-11e7-8c85-fe09cb6e8f90.png)

So where is the issue?
-> [_handleString ](https://github.com/DevExpress/testcafe/blob/a080d68f3ebe0f016289e6a4330a9f716b2b88a2/src/browser/provider/built-in/path.js#L8)

-> and most particular in [this call of splitQuotedText](https://github.com/DevExpress/testcafe/blob/a080d68f3ebe0f016289e6a4330a9f716b2b88a2/src/browser/provider/built-in/path.js#L9)

where `splitChar` param is set to `' '` which in will parse path to chrome badly -> like this

this ->
`path:"/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe"`

will be parsed to:
```js
{ str: '/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe',
  args: [ 'Files', '(x86)/Google/Chrome/Application/chrome.exe' ],
  path: '/mnt/c/Program' }
```

which is of course wrong and whole script will error

### So how to fix it?

Don't know why there is empty space as splitChar, but if we change it to for instance for comma `,` everything will start to work. I can submit PR if you want, this is indeed a deal breaker for my daily workflow as I'm using WSL 100% for work.

```diff
-var args = splitQuotedText(str, ' ', '`"\'');
+var args = splitQuotedText(str, ',', '`"\'');
```

**Comment by Hotell** [comment]
cc @kirovboris

**Comment by AlexanderMoskovkin** [comment]
Hi @Hotell,

You've found a right way to pass a browser argument, but our code works as we expect.
Let me explain why (meanwhile I suppose it should be described in the docs). 
You can pass a path to a browser executable file with some browser argruments in the following way:
`path:path/to/chrome.exe --incognito`. The `_handleString` function split this args by `' '`, so it's ok.
To make it workable you should wrap it with quotes:
`testcafe "path:path/to/chrome.exe --incognito" test.js`

Since the path can contain spaces too you should be able to wrap the path with some other quotes.
As you can see from [this](https://github.com/DevExpress/testcafe/blob/a080d68f3ebe0f016289e6a4330a9f716b2b88a2/src/browser/provider/built-in/path.js#L9) line TestCafe allows to use three types of quotes: `'`, `"`, `.

So, to make your example workable you can just wrap the path with quotes:
`testcafe "path:'path with space/to/chrome.exe' --incognito" test.js`

You can see this type of using in [our tests](https://github.com/DevExpress/testcafe/blob/master/test/server/browser-provider-test.js#L65).

**Comment by Hotell** [comment]
Thanks for explanation why is `' '` , although your quotes doesn't work for all your type of quotes , also your test is covering just one use case, when using backticks ``` ` ```

following does not work:
![image](https://user-images.githubusercontent.com/1223799/28499990-aee8b890-6fc1-11e7-8c85-927a44dfed35.png)

![image](https://user-images.githubusercontent.com/1223799/28499981-87fa2fd4-6fc1-11e7-8ba6-6bdc7fb9435d.png)

the only combination that works is backticks + single quotes as a wrapper:

![image](https://user-images.githubusercontent.com/1223799/28499993-de0094ea-6fc1-11e7-8ccc-1b2f525f8574.png)

So either way:
- it's a bug ( that it handles correctly only 3rd usecase ? )
- it's demanded behaviour ( that it works solely with backticks ) and a PR to the docs needs to happen 

Pls lemme know thx!

**Comment by AlexanderMoskovkin** [comment]
@Hotell You are right. We should check it

**Comment by Hotell** [comment]
I found it in docs actually ( my mistake that I didn't read thoroughly before :( ) but provided example doesn't work as I've mentioned 

https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#starting-browser-with-arguments

> You can also specify arguments for portable browsers. If a path to a browser contains spaces, the path should be surrounded with backticks:

> ```testcafe "path:`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` --start-fullscreen" tests/sample-fixture.js```

![image](https://user-images.githubusercontent.com/1223799/28500682-d4bbb2b0-6fcc-11e7-8d74-4adac0d518fd.png)

**Comment by AndreyBelym** [comment]
Hello @Hotell! The example from docs was written for `cmd` shell, but it seems like you are using `bash`. The case with double quotes didn't work for you because backticks have special semantics in `bash`, and should be escaped with `\` or should be inside single quotes (`bash` does some interpretation for strings inside `"` but not for strings inside `'`).  I think we should fix docs at least, add an example for *NIX-like shells. 

Also I'll try to improve quotes handling to allow using regular quotes to separate spaces-containing path and arguments in the `path` provider. Because experience shows that backticks are counter-intuitive, and people regularly runs into issues with them.

**Comment by Hotell** [comment]
sounds good @AndreyBelym, cheers ! 

> P.S.: yes I'm using windows subsystem linux for development, so bash

**Comment by eliw00d** [comment]
I'm running into a similar issue with WSL:
```
$ testcafe "path:`/mnt/c/PROGRA~2/Google/Chrome/Application/chrome.exe`" ./tests

TestCafe Live watches the files and reruns
the tests once you've saved your changes.

You can use the following keys in the terminal:
'ctrl+s' - stop current test run;
'ctrl+r' - restart current test run;
'ctrl+w' - turn off/on watching;
'ctrl+c' - close browsers and terminate the process.


Test run is starting...

Make changes in the source files or press ctrl+r to restart test run.
ERROR: Error: Was unable to open the browser "path:" due to error.

TypeError: Cannot read property 'trim' of undefined
    at Object.callee$0$0$ (/mnt/c/Users/eliw00d/Documents/GitHub/project/node_modules/testcafe-browser-tools/lib/api/get-browser-info.js:54:42)
    at tryCatch (/mnt/c/Users/eliw00d/Documents/GitHub/project/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at Generator.invoke [as _invoke] (/mnt/c/Users/eliw00d/Documents/GitHub/project/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:334:22)
    at Generator.prototype.(anonymous function) [as next] (/mnt/c/Users/eliw00d/Documents/GitHub/project/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at tryCatch (/mnt/c/Users/eliw00d/Documents/GitHub/project/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at invoke (/mnt/c/Users/eliw00d/Documents/GitHub/project/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:146:20)
    at /mnt/c/Users/eliw00d/Documents/GitHub/project/node_modules/testcafe-browser-tools/node_modules/babel-runtime/regenerator/runtime.js:154:13
    at <anonymous>
```
It does actually open Chrome in Windows, but then the above error is thrown.

**Comment by eliw00d** [comment]
If I change to single quotes, it just sits and spins.
```
$ testcafe 'path:`/mnt/c/PROGRA~2/Google/Chrome/Application/chrome.exe`' ./tests
⠴
```

**Comment by AndreyBelym** [comment]
Hi @eliw00d, don't use backticks inside double quotes in bash, because shell will execute the text quoted with backticks as a command: https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html#Command-Substitution. Just use single quotes (`'`) not double ones. We can't do much in this case because shell performs command substitution even before starting a TestCafe process.

To solve this problem, we need to find some argument syntax that is neutral to all major shells (bash, cmd.exe, PowerShell), convenient enough and has backward compatibility with current syntax.

**Comment by eliw00d** [comment]
Yeah, sorry about that, I realized my error and tried again with single quotes but get a connection error now.

**Comment by eliw00d** [comment]
@AndreyBelym What would cause the connection error I'm seeing above? Also, what do you look for in Linux when using the alias "chrome"? Is there a way I can create an environment variable that would work with that? I have `$BROWSER` set to `/mnt/c/PROGRA~2/Google/Chrome/Application/chrome.exe` for use with Hub, for example.

**Comment by AndreyBelym** [comment]
@eliw00d we use simple `which` detection on Linux, so in theory if you add the Chrome from `Program Files` to the `$PATH`, it must be autodetected by TestCafe. Unfortunately, my Windows force me to upgrade for installing the WSL, so I need some time to test it. 

To troubleshoot the infinite "Connected" screen I would recommend to check if and how remote browsers work. It means starting Chrome manually, opening DevTools and switching to the Network tab (also tick Preserve log flag in the toolbar) , then starting TestCafe with the `remote` argument: [see in the docs](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#remote-browsers). TestCafe will print remote connection URL to the reminal, navigate to it with the opened browser, and pay attention to requests in the Network tab in DevTools.

**Comment by eliw00d** [comment]
@AndreyBelym So `which chrome` would not work because it would be chrome.exe due to WSL interop. For example, if I do which notepad I get nothing, but which notepad.exe gives me the Windows path:
```
eliw00d@eliw00d-PC:~$ which notepad
eliw00d@eliw00d-PC:~$ which notepad.exe
/mnt/c/Windows/System32/notepad.exe
```
I actually ended up adding the Chrome folder to my path to confirm this:
```
eliw00d@eliw00d-PC:~$ which chrome
eliw00d@eliw00d-PC:~$ which chrome.exe
/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe
```

**Comment by eliw00d** [comment]
@AndreyBelym Remote worked fine, not sure why using the chrome.exe path causes it to have connection errors.

**Comment by miherlosev** [comment]
I've converted the issue to proposal.

> Also I'll try to improve quotes handling to allow using regular quotes to separate spaces-containing path and arguments in the path provider. Because experience shows that backticks are counter-intuitive, and people regularly runs into issues with them.

**Comment by mojjy** [comment]
@eliw00d  I had the same issue, wouldn't connect on WLS(windows linux subsytem), until I changed the **getLinuxOpenCommand()** method 
0<&- >/dev/null 2>&1 &'

**Comment by AndreyBelym** [comment]
@mojjy, if we don't close the `stdin` stream of a child process. the `child_process.exec` won't call its callback on real Linux systems until the child process is terminated. I think we should use `child_process.spawn` instead: https://github.com/DevExpress/testcafe-browser-tools/issues/159

**Comment by computamike** [comment]
I'm running tests using the API - also finding issues launching Chrome on WSL - like @mojjy found the same issue.

**Comment by computamike** [comment]
is there any update on this?

**Comment by Farfurix** [comment]
@computamike 

Hello.

We added this issue to "CLI suggestions" in [Enhancements processing](https://github.com/DevExpress/testcafe/projects/11#card-18273717). Please stay tuned to our updates in this issue.

**Comment by bogdan-calapod** [comment]
Is there any workaround for now until the issue is fixed ?

**Comment by LavrovArtem** [comment]
We haven't achieved any remarkable progress in implementing this suggestion. Moreover, additional difficulties were introduced since recent TestCafe versions use temporary profiles for testing in Chrome and Chrome for Windows doesn't allow using UNIX-style paths for temporary profiles.
 
For now, it's recommended to start the `cmd.exe` shell and use Node.js for Windows if you want to run Windows browsers from WSL, or install Chromium for Linux (`sudo apt update && sudo apt install chromium`) and run your tests in headless mode: `testcafe 'chromium:headless --no-sandbox' tests`

**Comment by bogdan-calapod** [comment]
I see. In the meantime I've found a way to make this work in WSL without needing to install a headless browser that works for my needs:

```
testcafe --ports 63305,63305 --live remote tests/
```

This keeps the `testcafe` on the same port (so that I can just bookmark the URL) and launches a remote server that I can connect to from the Windows side. 

It's not ideal, but it works well enough that I can use it for daily dev. I thought others might be struggling with the same thing 😅

Might it be a good idea to place this in the README somewhere as a workaround for WSL-based setups, seeing as with the coming of WSL2 and such I expect more people would begin working in this environment/setup ?

**Comment by arubtsov** [comment]
We are happy that you have found a workaround. Thank you for sharing it with us. This thread is a good place to keep it for now.

**Comment by EricWardner** [comment]
The workaround from @bogdan-calapod isn't working for me.  I just get an immediate disconnect when I browse to the page. Any updates overall on using testcafe with WSL2?

**Comment by SergeyShurygin** [comment]
Eric, please try Artem's solution:

> For now, it's recommended to start the cmd.exe shell and use Node.js for Windows if you want to run Windows browsers from WSL, or install Chromium for Linux (sudo apt update && sudo apt install chromium) and run your tests in headless mode: testcafe 'chromium:headless --no-sandbox' tests

[https://github.com/DevExpress/testcafe/issues/1640#issuecomment-510491429](url)

**Comment by danielskeeled** [comment]
Workaround: `testcafe 'path:'/mnt/c/explorer.exe' ./tests`
This will launch the default browser on the Windows environment

**Comment by gabrielizalo** [comment]
None of the previous workarounds worked for me.

Thanks to a company friend I'm just using:

1. GitBash App  'Bach app isntalled with Git
2. `npx testcafe chrome ./tests`

I continue using WSL to develop and for running tests I use that bash console.

**Comment by AndreyBelym** [comment]
It seems that `stdin` redirection (`0<&-`) [here](https://github.com/DevExpress/testcafe-browser-tools/blob/master/src/api/open.js#L46) prevents the Chrome executable from starting.

**Comment by fidalgodev** [comment]
Any fixes for this? Using WLS2 and can't run testcafe...

`testcafe path:"/mnt/c/WINDOWS/explorer.exe" tests.js --hostname localhost`

This works, opens the browser, but then it immediatly closes saying it can't find localhost. Even tho the server is running at `localhost:3000` and I can browse into it using Chrome...

**Comment by fidalgodev** [comment]
4 years later and WLS is still not supported properly...

**Comment by AndreyBelym** [comment]
Unfortunately, WSL is still a challenging task due to cross-platform differences and deep integrations between TestCafe and browsers. Please see this comment for explanations and more appropriate workarounds: https://github.com/DevExpress/testcafe/issues/1640#issuecomment-510491429.

I presume that @danielskeeled's workaround should work if you omit the `--hostname localhost` argument. Please note, that this argument instructs TestCafe to start its proxy server using the specified hostname, and it is not related to your web app server. The web app hostname can be configured only with the `fixture.page` and `test.page` properties.

**Comment by craigloewen-msft** [comment]
We're working on adding GUI app support to the Windows Subsystem for Linux! We are aiming for this to hit Windows Insiders in the near future. Thanks to a quick email from @bitcrazed , I tested this use case with WSL 2 and a browser running in Linux and it seemed to work well. I hope this can be an avenue to solve this support in the future!

Here's a gif of it in action on my machine: 
![gif6](https://user-images.githubusercontent.com/42221804/109092442-629fa380-76cb-11eb-8702-2d741170fc57.gif)

**Comment by aleks-pro** [comment]
This is good news, @craigloewen-msft. Thank you for sharing your results with us.

**Comment by craigloewen-msft** [comment]
Hi all, we just released our first preview of GUI app support in WSL that will help resolve this. I even included testcafe in my demos for the announce (Thank you for adding Microsoft Edge support it was rather timely :) )

Check out the info here:
https://devblogs.microsoft.com/commandline/the-initial-preview-of-gui-app-support-is-now-available-for-the-windows-subsystem-for-linux-2/

**Comment by VasilyStrelyaev** [comment]
Thanks for the good news, @craigloewen-msft! It's a pleasure to see TestCafe in a WSL blog post. Looking forward to the GUI support release. Looks quite interesting!

**Comment by illuminatux** [comment]
> For now, it's recommended to start the `cmd.exe` shell and use Node.js for Windows if you want to run Windows browsers from WSL, [...]

Hello, can you provide a small command line example of how to run a test with this configuration (WSL + cmd + Nodejs for Windows)?

**Comment by AlexKamaev** [comment]
It's better to use `powershell.exe` instead of `cmd.exe` for WSL2 due to the Linux filesystem being mounted as a network drive.
1. Type  `powershell.exe`  in the WSL shell, press `<Enter>`
2. Type `node .\node_modules\testcafe\bin\testcafe.js chrome test.js` for a local TestCafe installation, or `node "C:\Program Files\nodejs\node_modules\bin\testcafe.js" chrome test.js` for the global TestCafe installation.
