### ISSUE TITLE
Test duration is reported as time from epoch

### ISSUE THREAD

**Issue by ClaytonAstrom** [DevExpress/testcafe#1674]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Individual test durations are reported as ~47 years

### What is the expected behavior?
Individual test durations are reported accurately

### How would you reproduce the current behavior (if this is a bug)?
Run any test with a reporter that shows individual test time (such as xunit)

### Specify your

* operating system: Windows 7
* testcafe version: 0.17.0
* node.js version:  6.10.2

**Comment by helen-dikareva** [comment]
Hello @ClaytonAstrom.
We have reproduced this issue only in the case when a legacy API is used in a test and a test page is unreachable. It's a known problem; see more in this [ticket](https://github.com/DevExpress/testcafe-legacy-api/issues/22).
 > [Legacy API](https://testcafe.devexpress.com/Documentation/API_Reference/Test_Fixture_API/) is an old TestCafe API format; it was in the paid TestCafe version. An open source TestCafe has a [new API](https://devexpress.github.io/testcafe/documentation/test-api/) but still can run legacy API tests.

We also faced the [problem ](https://testcafe-discuss.devexpress.com/t/promise-rejection-warning-on-test-completion/184/15) when installed project packages break our testing time calculation mechanism. Do you use [a globally or locally](https://devexpress.github.io/testcafe/documentation/using-testcafe/installing-testcafe.html) installed TestCafe? If the latter, please try to run the problematic test outside your project.

Let us know about any your results. If your issue is different, please provide us with a test scenario so that we will be able to reproduce the issue on our side.

**Comment by ClaytonAstrom** [comment]
Thanks @helen-dikareva !  I am using both global and local (global installed on my machine, locally installed in CI environment).  This is happening for all tests I run.

Given the following code (./scripts/debug.js):
```js
import { Selector } from "testcafe"

fixture("Google test")
    .page("google.com")
test("Google 1", async t => {
    await t.expect(Selector("img#hplogo").visible).ok();
})
```
When I run:
```shell
testcafe chrome ./scripts/debug.js -r xunit
```
I get:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite name="TestCafe Tests: Chrome 60.0.3112 / Windows 7 0.0.0" tests="1" failures="0" skipped="0" errors="0" time="3.007" timestamp="Wed, 09 Aug 2017 13:32:38 GMT" >
  <testcase classname="Google test" name="Google 1" time="1502285558.496">
  </testcase>
</testsuite>
```

**Comment by helen-dikareva** [comment]
Thank you @ClaytonAstrom. I could reproduce your scenario, I will investigate this behavior and fix it it current sprint.
