### ISSUE TITLE
Does testcafe support chrome to save session

### ISSUE THREAD

**Issue by haoshasha** [DevExpress/testcafe#1677]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:mac
* testcafe version:
* node.js version:

**Comment by haoshasha** [comment]
I do not want to log in every time I use the test case

**Comment by AlexanderMoskovkin** [comment]
Hi @haoshasha,

The [User Roles](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html) feature should meet your need.

**Comment by fkartika** [comment]
Hello @AlekseyMartynov i tried using User Roles feature, but it's always failed when i try switch roles
can you provide an example how to use it as the helpers file? Thanks!

**Comment by AlexanderMoskovkin** [comment]
Hi @fkartika,

Take a look at the [An Easier Way to Authenticate Users in E2E Tests](https://hackernoon.com/an-easier-way-to-authenticate-users-in-e2e-tests-230d86071f48) article.
You can find an example in the `Example: Authenticating on GitHub` section there.

**Comment by fkartika** [comment]
Thanks for the reply @AlekseyMartynov !
and then i found the problem is the first credential still stored on session, so when i switch to other role the page is reloaded to login page, but not with the new credential. It's still previous credential. I test an Angular page. Do you know why this happen?

**Comment by AlexanderMoskovkin** [comment]
@fkartika Do you reproduce the same for example on github.com with the same test code?

**Comment by fitriakartika** [comment]
no @AlexanderMoskovkin it's not happen in your example. Your example works well.

**Comment by fkartika** [comment]
no @AlexanderMoskovkin it's not happen in your example. Your example works well.

**Comment by AlexanderMoskovkin** [comment]
In this case it seems the problem is specific for you page. Could you please share your page and test code with us or create a simple example that allows to reproduce the problem on our side?
Meanwhile try to set the [preserveUrl](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html#optionspreserveurl) option to `true`. It possible it has a sense for your project.

**Comment by haoshasha** [comment]
Is that settled?

**Comment by AlexanderMoskovkin** [comment]
@haoshasha TestCafe runs each test in a clear environment (with empty cookie, local storage etc..). Have you tried the [User Role](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html) feature? Does it meet your need?

**Comment by haoshasha** [comment]
@AlexanderMoskovkin   I'll try it

**Comment by haoshasha** [comment]
@AlexanderMoskovkin Each test case requires each login，but I don't want to
