### ISSUE TITLE
Add possibility to use config file or special section in a package.json

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#1714]
TestCafe has a lot of [options](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#options). 
Add possibility to store them into a `.testcaferc` file.
Also allow to use the special section in a `package.json` file.
```json
{
  "name": "my-package",
  "version": "1.0.0",
  "testcafe": {
       "browser": "chrome",
       "path": "tests/e2e/*.js",
       "app": "http-server -s -p 8080",
       "appInitDelay": "5000"
  }
}
```

* testcafe version: 0.17.0

**Comment by miherlosev** [comment]
> how's that different from specifying testcafe ...options
It is not different. It is another way to specify options.
It will be usefully (just easier to read them) then specified options take a several lines.

**Comment by inikulin** [comment]
Do you scratch some real itch here? Because I recall we already discussed it a few times

**Comment by inikulin** [comment]
> It is not different. It is another way to specify options.


Famous last words 😀
Do you scratch some real itch here? Because I recall we already discussed it a few times and was not able to find any real value in it. We even have closed issue for it somewhere around here

**Comment by bisubus** [comment]
@inikulin I came up with exactly same problem and I consider it a vital one.

Every other test runner supports config files for a good reason, because they are convenient. CLI arguments can be lengthy, harder to read and maintain. They aren't extendable.

Considering that there's a script:

```
  "scripts": {
    "test": "testcafe ...a lot of args... chrome:headless ./test/e2e/**/*.e2e.ts"
  },
```

If a user wants to change some of the options (e.g. concurrency and browser), entire command line should be pasted. We can't even override options with `npm run test -- -c 1 ie`, because testcafe args aren't parsed that way. While it would be enough to pick up config file and override some options: 
```
testcafe --config ./test/testcafe.json -c 1 ie
```

**Comment by lawrentiy** [comment]
config file is an extreme necessity.
Please, answer what is the reason to close that issue?
Is there some technical issues or something else?
Thnx!
