### ISSUE TITLE
Angular Augury extension is causing tests crashes in Chrome

### ISSUE THREAD

**Issue by Hotell** [DevExpress/testcafe#1720]
### What is the current behavior?
When [angular augury chrome extension](https://augury.angular.io/) is installed, all tests will fail caused by weird errors.

For instance when testing a SPA 

```ts
const historyURL = 'http://localhost:8080/#/history'

fixture(`/history#admin`).beforeEach(async t => {
  await t.useRole(admin).navigateTo(historyURL)
})
```

![image](https://user-images.githubusercontent.com/1223799/29465451-aa03a5b0-8439-11e7-98e9-3cc7c7a7e3ff.png)

it will not navigate to `localhost:8080`, instead to `about:blank`

### What is the expected behavior?
- explicitly state in docs that this extension will make devs life unconvenient
- somehow resolve the issue with augury team? 

### How would you reproduce the current behavior (if this is a bug)?
- install the extension and try to run any test in chrome

### Specify your

* operating system: WIN 10 with WSL/OSX sierra
* testcafe version: 17.1
* node.js version: 8.4.0

**Comment by AlexanderMoskovkin** [comment]
Hi @Hotell,

We'll check it. As a workaround you can run tests in a browser in the `incognito` mode:
```js
testcafe "chrome --incognito" test.js
```

**Comment by miherlosev** [comment]
To work properly, TestCafe processes all scripts on the page (actually, the [testcafe proxy](https://github.com/DevExpress/testcafe-hammerhead) does it). 
The Angury extension adds its own script to a page using the `chrome-extension` protocol. 
https://www.screencast.com/t/Vgh4HlmGzUiy.
TestCafe can't process scripts loaded by this protocol.
That's why we can't guarantee that these unprocessed scripts will work correctly.

In the case of Angury, an unprocessed script is failed and we can't handle it.

You can turn off the Angury extension before running the test.
Meanwhile, we plan to disable all chrome extensions before running tests by default.
We will work on it as a part of the #1623 issue

**Comment by Hotell** [comment]
yeah I know that's not your fault folks, just wanted to give heads up for you or users of testcafe. 

cheers
