### ISSUE TITLE
Permission dialogs aren't handled

### ISSUE THREAD

**Issue by jessehattabaugh** [DevExpress/testcafe#1727]
<img width="342" alt="nearby photos" src="https://user-images.githubusercontent.com/17991/29626395-6e4c06ae-87e3-11e7-8898-0dc305798883.png">

### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
There is no way to tell whether a permission request dialog has popped up, or to grant or deny that privilege programatically. 

### What is the expected behavior?
When a test causes a permission request dialog to appear it should trigger the `setNativeDialogHandler`, and appear in `getNativeDialogHistory `.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AlexanderMoskovkin** [comment]
Hi @jessehattabaugh,

Thanks for your proposal. Unfortunately, I guess we can't implement it with the current TestCafe architecture because of browser restrictions. You can try to setup permissions in browser's settings before test running. For example here is instruction how to do it in Chrome: [Allow or block content settings for certain sites](https://support.google.com/chrome/answer/3123708?hl=en)

**Comment by Farfurix** [comment]
Hello, @mostley.
Thank you for your interest in this feature.
While we do not have plans to implement it in the near future, we consider this idea as a potential improvement and keep it on our radar.
