### ISSUE TITLE
Unable to automate Social Media login with TestCafe as it opens a new window

### ISSUE THREAD

**Issue by dsayerjp** [DevExpress/testcafe#1759]
### Are you requesting a feature or reporting a bug?

This is a bit of both, certainly a limitation of TestCafe. If there's a workaround suggestion I would be very grateful for this as well.

### What is the current behavior?

The user journey is that Facebook opens the login in a new window, after valid details are supplied the pop-up closes and the original window redirects to our logged in screen. 

Currently TestCafe opens it in the existing window. Once valid login details have been supplied the page just hangs on a blank page. I believe this is because Facebook is trying to close what it thinks is a pop-up.

### How would you reproduce the current behavior (if this is a bug)?

Running the below Test Code will reproduce the error. I've included the BDD on the test case: 
Given I go to https://www.justpark.com/
When I Click on the login dropdown
And select Facebook as a login method
And enter valid facebook credentials
Then I can see I have logged in successfully

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://www.justpark.com/

Test code
Login details have been stripped but any valid Facebook credentials can be used.

```js
 test('Login using Facebook', async t => {

     await t
     .click(Selector('#header-nav > div.area-right > div'))
     .click(Selector('.btn-fb'))
     .typeText(Selector('#email'), "facebook-email-address")
     .typeText(Selector('#pass'), "facebook-password")
     .click(Selector('#loginbutton'))
     .expect(Selector('.dashboard-username > h2').innerText).contains("Username")
 })
```

### Specify your

* operating system: Mac OS
* testcafe version: 0.17.1
* node.js version: 8.4.0

**Comment by AlexanderMoskovkin** [comment]
Hi @dsayerjp,

This issue is related to the [Add ability to perform testing in multiple browser windows](https://github.com/DevExpress/testcafe/issues/912) feature request. For now TestCafe doesn't support it. Since this feature is very complex to implement we can't provide any estimates about it.
According to the Facebook authentication mechanism on this site it can be performed in a single-window way. Unfortunately, I don't see any ways to test it with TestCafe.
So, it's necessary to disable authentication or change it to a single-window mode (if possible) for the testing task (for example it can be a development mode of the application).

**Comment by sunainajain** [comment]
This was a blocker for my team to adopt TestCafe since our app uses google authentication.

**Comment by coakeson** [comment]
If there were a way to upvote this feature, I would.

**Comment by TestAndunR** [comment]
Hello everyone,
Have you guys able to implement this feature.

**Comment by miherlosev** [comment]
@coakeson 

Vote the [Add ability to perform testing in multiple browser windows](https://github.com/DevExpress/testcafe/issues/912) issue.
