### ISSUE TITLE
Concurrent Test Execution worker number

### ISSUE THREAD

**Issue by ervoiox** [DevExpress/testcafe#1778]
### Are you requesting a feature or reporting a bug?

Feature.

### What is the current behavior?

You can pass in a number to get a pool of browsers to run tests but there does not seem to be any way to determine which worker the test is running on.

### What is the expected behavior?

It would be helpful if testcafe could expose some sort of `WORKER_NUMBER` variable. For example - lets say I am testing against an api where the tests do something where a call has to be made to the api to modify state in the database. I don't think concurrency would work too well here if you had 4 tests running at the same time hitting the same api.

It would be helpful if a `WORKER_NUMBER` variable is exposed so users could set up their workers to an isolated api. For example, you could run your api on 4 different ports, which talk to separate databases this way any tests modifying state won't potentially contaminate the other.

```js
fixture `Example page`
    .page `localhost:300${WORKER_NUMBER}`;

// 4 workers =
//   worker 0: localhost:3000
//   worker 1: localhost:3001
//   worker 2: localhost:3002
//   worker 3: localhost:3003
```

Thanks!

**Comment by AlexanderMoskovkin** [comment]
Hi @ervoiox,

Thanks for your proposal. Since the test file is executed one time regardless of browsers count we can't add this number to the global scope as you did in your example.
For example if you run tests with the following command: `testcafe chrome,firefox test.js` it works in the following way:
```js
fixture `my fixture`;

// this code is executed once

test('Test', async t => {
    // this code is executed twice (in chrome and in firefox)
});
```

But we have proposal to [Implement `t.browserInfo`](https://github.com/DevExpress/testcafe/issues/481). I think we can add the concurrent worker number there.
So I close this issue in favor of the #481.
