### ISSUE TITLE
TestCafe doesn't scroll to elements inside ShadowDOM

### ISSUE THREAD

**Issue by varunkumar** [DevExpress/testcafe#1808]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
TestCafe doesn't scroll to show targets that are within shadowDOM

### What is the expected behavior?
TestCafe should scroll to show host element when target is within shadowDOM

### How would you reproduce the current behavior (if this is a bug)?
Test project for reproducing the issue -- https://github.com/varunkumar/testcafe-webcomponents/blob/master/tests/shadowdom.test.js

### Specify your

* operating system: Mac OSX 10.12.6
* testcafe version: 0.17.2
* node.js version: v8.4.0

**Comment by varunkumar** [comment]
@AlexanderMoskovkin I see that there is custom scroll handler -- https://github.com/DevExpress/testcafe/blob/master/src/client/automation/playback/scroll.js. Any reason why`[scrollIntoView()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)` is not used here? For now, I have added a customMethod to my selector and scrolling the node to view from there using `scrollIntoView()` API.

**Comment by AlexanderMoskovkin** [comment]
TestCafe allows to scroll/move to a specific point an element (with specific coordinates). This element can be larger than the viewport (for example it can be click on body with the `offsetY: 1000` option). Or it can be inside a cross-domain iframe. That's why we have our custom scroll implementation.

**Comment by AlexanderMoskovkin** [comment]
For simple cases your solution with custom `scrollIntoView` method is a good workaround

**Comment by varunkumar** [comment]
Please provide me pointers to get started with this bug. I would be happy to contribute the fix for this.

**Comment by AndreyBelym** [comment]
Hello @varunkumar! We have a function that [scroll all element's parents](https://github.com/DevExpress/testcafe/blob/master/src/client/automation/playback/scroll.js#L162), and this function [retrieves list of parents](https://github.com/DevExpress/testcafe/blob/7fd03a3889c360f552474d0b3c4cbd13826c1ff3/src/client/core/utils/style.js#L57) using [getParents](https://github.com/DevExpress/testcafe-hammerhead/blob/09ea85815e7cf0ae5013ea9cd47ff35be4ec6266/src/client/utils/dom.js#L747) function of `testcafe-hammerhead` . It's quite simple - just loops on `parentNode`'s and perform some checks on them. So when it reaches a root of ShadowRoot, it stops and doesn't get out to the other part of DOM, because it has `host` property instead of `parentNode`.

So would you kindly try to make `getParents`  using `host` property for retrieving ShadowRoot's parent element, and check if it fixes the problem? 😄 

The tricky part here is that `testcafe-hammerhead` is a NPM dependency, and likely you will have to build it together with TestCafe. Personally, for cases like this one, I prefer to [npm link](https://docs.npmjs.com/cli/link) a clone of `testcafe-hammerhead` repository. So likely for the first time you will need:

 1. clone https://github.com/DevExpress/testcafe-hammerhead and https://github.com/DevExpress/testcafe-hammerhead, 

 2. install their dependencies  (`npm i`), 

 3. build it (`npx gulp build`), 

 4. go to the `testcafe-hammerhead` and link it to global scope (`npm link`), 

 5. go to the `testcafe`, and link `testcafe-hammerhead` (`npm link testcafe-hammerhead`).

Now you can try to run some tests to be sure that the build is okay, and if it's so, you can just make some changes to `testcafe-hammerhead` and rebuild it to get the changes recognized by TestCafe, no other steps required.

**Comment by varunkumar** [comment]
@AndreyBelym Thanks for the pointer. That did help the scrolling bit. I have tested the fix locally and the page is getting scrolled to the element inside `shadowDOM` as well. However, I see that there are still issues with performing `actions` on elements not on viewport. The mouse cursor's position is not calculated properly. 

I would like to get an overview of the architecture of testcafe, core, hammerhead, etc so that I can fix these issues myself and contribute back. What would be the good place to start?

**Comment by miherlosev** [comment]
Hi @varunkumar.

Thank you for informing us that the original issue was fixed. 
As for the other issues, usually we avoid discussing several problems in a single thread. Please create a new issue and describe the problem in detail there. We will be happy to help you.
