### ISSUE TITLE
Console message before driver.start() throws "Cannot read property 'getItem' of null"

### ISSUE THREAD

**Issue by caseyWebb** [DevExpress/testcafe#1875]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

Event listeners in the driver which depend on contextStorage are registered before contextStorage is initialized, so if a JS error or console message is emitted before `driver.start()` is called, an error is thrown.

### What is the expected behavior?

No errors.

### How would you reproduce the current behavior (if this is a bug)?

Emit a console message on page load. IDK what/when driver.start() is called from just poking around, but as long as it's before that, it's reproducible.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: Can share privately, if necessary.

Test code

```js
test(url, async (t) => {
  await t
    .useRole(DefaultRole)
    .navigateTo(url)
    .expect(Selector('#ToolBar').with({ timeout: 60000 }).exists).ok()
    .expect(Selector('div[data-test="404"]').exists).notOk()
    .expect(Selector('div[data-test=errors]').exists).notOk()
})
```

### Specify your

* operating system: any
* testcafe version: v0.18
* node.js version: 8.7.0

---

In my poking around to make sure that the error was in TestCafe and not my code, I was able to fix this w/ trivial changes — the context storage just needs to be initialized in the constructor, before the event listeners are registered. If I'm missing something that prevents the initialization in the constructor, the event listeners could alternatively be registered in the `start` method.

**Comment by AlexanderMoskovkin** [comment]
Hi @caseyWebb,

Thanks for your report and the PR. 
Could you please clarify, do you reproduce the problem on the page with iframes?
I don't see a way how it can happen in the top window because the `Driver` constructor and the `start` function are called synchronously one after one (see [client/test-run/index.js.mustache#L38](https://github.com/DevExpress/testcafe/blob/master/src/client/test-run/index.js.mustache#L38)). So any js-error or console.log calls can't appear between these calls. 
But now I see that it can happen in iframes. The `contextStorage` in an `iframeDriver` is initialized anychronously (see [client/driver/iframe-driver.js#L76](https://github.com/DevExpress/testcafe/blob/master/src/client/driver/iframe-driver.js#L76)). The top driver keep `id`s for every iframe on the page. When an iframe driver is initialized it requests its `id` from the top driver and then initializes its own contextStorage with this `id`. That's why we can't do it in the constructor.
Could you please share the link to your page with me via my email (alexander.moskovkin@devexpress.com)? It'll help us to find the best way to resolve the issue.

**Comment by caseyWebb** [comment]
I was wondering that myself when looking at the code to be honest; it's testing a part of our app that is way before my time and I'm unfamiliar with, but it does use iframes heavily. I'll email you the link + login to check it out yourself.

**Comment by AlexanderMoskovkin** [comment]
Thanks, I've got your mail.
