### ISSUE TITLE
Using Docker image with remote browser causes redirect to the wrong hostname/port

### ISSUE THREAD

**Issue by richardxia** [DevExpress/testcafe#1880]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
When following the [Docker instructions](https://devexpress.github.io/testcafe/documentation/using-testcafe/installing-testcafe.html#using-testcafe-docker-image) for running tests through a remote browser, using the OS X equivalent of this command from the docs:

```sh
$ docker run -v //d/tests:/tests -P -it testcafe/testcafe remote /tests/test.js
```

After connecting my native Chrome browser running on OS X using http://localhost:32769/browser/connect (with the random port number generated with `-P`), the testcafe server attempts to redirect to http://172.17.0.4:1337/browser/connect/r1VKX3ZpZ, which uses the hostname and port number as seen by the Docker container, which is not accessible to OS X.

This can be worked around at the moment by explicitly passing `--hostname localhost` to testcafe and by forcing Docker to map the host's port 1337 to the container's port 1337. However, if this is the intended way to use the Docker image, it should at least be reflected in the documentation.

Note that this would also affect the case without Docker where a proxy is present between the testcafe server and the remote browser.

### What is the expected behavior?
testcafe should not redirect the browser to a different hostname and port. The redirect should only change the path of the URL, not the hostname or port.

I believe the bug is that [`BrowserConnection.url`](https://github.com/DevExpress/testcafe/blob/bff43b0f58ebe5304b1fbb3bdd9cb8e91c0133ad/src/browser/connection/index.js#L48) contains the fully qualified URL including the domain, and it is used as the [redirect target](https://github.com/DevExpress/testcafe/blob/ce192fb613449cf97f6b2df5232fdc795e543340/src/browser/connection/gateway.js#L127). Ideally a redirect would only change the URL path and use the originating HTTP request's domain and port, which is how I've seen this be handled in various web frameworks. However, I don't know this codebase well enough to understand whether there is a use case that relies on using a fully qualified URL.

### How would you reproduce the current behavior (if this is a bug)?
I feel this is adequately described above.

#### Provide the test code and the tested page URL (if applicable)
Not relevant.

### Specify your

* operating system: OS X 10.11.6, using Docker for Mac 17.09.0-ce-mac35 (19611)
* testcafe version: 0.17.2 (from Docker image 8ef9b778b25b, the current `latest`)
* node.js version: 6.10.3 (from Docker image 8ef9b778b25b)

**Comment by AndreyBelym** [comment]
Hello @richardxia !

I agree with you about that we have to correct the docs about usage of the Docker image.

I'm afraid we can't avoid changing hostname and ports, because we use special proxy server that analyzes and modifies content of a tested page (so-called URL rewritting). The only possibility here is to detect external IP/ports somehow, but I didn't find any information about how it could be done.

**Comment by richardxia** [comment]
I'm not sure I understand why the proxy server needs to rewrite the domain name and port part of the URL. I don't think in general it is possible to detect the external IP or ports because it's outside of the Docker container, and it would be tantamount to breaking out of the sandbox that is the container.

I can take a stab later this week at creating a pull request to demonstrate what I think can be done to make the browser connection server agnostic to the server's URL relative to the host. I believe as long as the rewriting preserves the host and port of the initial HTTP request, then the proxy doesn't need to detect the external IP or ports.

**Comment by bertBruynooghe** [comment]
@richardxia @VasilyStrelyaev due to this ticket and the resulting PR, I was under the impression that adding the ports to the docker command and the hostname to the testcafe command, I would be able to get through on MacOS, although it apparently is not that simple. (See my  [stack overflow question](https://stackoverflow.com/questions/51131781/dockerized-testcafe-remote-browser-tests/51132484#51132484))
Do you have any further advice on this?

**Comment by AndreyBelym** [comment]
Hi @bertBruynooghe, I've checked the Docker image on a Mac, and it works this way for me:
```
docker run -it -rm -v $HOME/Documents/Tests:/tests -p 1337:1337 -p 1338:1338 testcafe/testcafe remote /tests/test.js --hostname localhost
```

Key points are using the `localhost` for the hostname, explicitly publishing ports with `-p`, and not using `--` after the image name. You don't need `--` because Docker automatically threats everything after an image name (e.g. `testcafe/testcafe`) as arguments for a container.
