### ISSUE TITLE
Tests in docker-container are unstable

### ISSUE THREAD

**Issue by Thomblin** [DevExpress/testcafe#1883]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

I implemented a basic "Hello "World" test using docker. However the test passes only from time to time. In my experience so far, the test passes and fails until I change the browser to test with.

Example:

```
testcafe:
    image: testcafe/testcafe
    entrypoint: ["/opt/testcafe/docker/testcafe-docker.sh", "-c", "2", "-S", "-s", "/testcafe/screenshots", "firefox", "/testcafe/tests"]
```

passes.

I run it again and it fails with "ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure."

I run it again and it fails.

I change the browser to chromium and the test passes.

I run it again and it fails until I switch back to firefox ...

### How would you reproduce the current behavior (if this is a bug)?

See above

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AndreyBelym** [comment]
Hello @Thomblin!

Unfortunately, I can't reproduce your problem. Could you specify your host OS version and version of Docker, please? Also, does it works better when concurrency mode is disabled?

**Comment by Thomblin** [comment]
The behaviour does not change without "-c2". I have to switch the browser to pass the test twice. (It always works once, when I switch the browser)

I am using 
Kubuntu 14.04.01 
kernel 3.16.0-77-generic
64-bit
Docker version 17.05.0-ce, build 89658be

**Comment by Thomblin** [comment]
I found the problem. I use to execute `docker-compose up testcafe`.

I switched to `docker-compose run testcafe`. Tests are faster and stable now ...

**Comment by AlexanderMoskovkin** [comment]
Hi @Thomblin,

I'm wondered, how are your tests now? Are they stable now with your solution?

**Comment by Thomblin** [comment]
Hi @AlexanderMoskovkin 

I had no time to implement Testcafe so far. I have to postpone that issue for some month unfortunately

**Comment by tmcnag** [comment]
I'm actually experiencing the same/similar problems.

### What is the current behavior?

Running the following:

```
sudo docker run -v /tmp:/tmp -v /var/lib/jenkins/testcafe:/tests testcafe/testcafe -c 10 firefox:headless /tests/<redacted>/setup/ -S -s /tmp -e
```

or similar variations (adding `-it` to the `docker` command, removing the `-c` flag, replacing `firefox:headless` with just `firefox` or `chrome`, `chrome:headless --no-sandbox` etc.) causes, seemingly at random, the following outcomes:

- The tests run fine
- The command errors with the following immediately:

```
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

Type "testcafe -h" for help.
```

- The command errors with the following after starting the first test:

```
Running tests in:
 - Firefox 57.0.0 / Linux 0.0.0

 <redacted test name>
ERROR The Firefox 57.0.0 / Linux 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Type "testcafe -h" for help.
```

- The tests run, but some of them fail in random places (I believe this has to do more with how I write the tests, but including here for completeness)

### What is the expected behavior?

The tests run properly, the same way, every time.  No variation should exist between tests - if it fails a certain way in one run, the very next run should fail the same way, ad nauseum.

### How would you reproduce the current behavior (if this is a bug)?

While I cannot provide the exact test cases due to company policy, I can say that I have been able to reduce the test code down to just about the simplest meaningful tests that could be performed and still trigger the issue.

#### Provide the test code and the tested page URL (if applicable)

Can't share code for policy reasons.

### Specify your

* operating system: Debian GNU/Linux 9 (stretch)
* testcafe version: Whatever is included in your Docker image (seems to be 0.18.6)
* node.js version: Whatever is included in your Docker image
* docker version: 17.05.0-ce, build 89658be

**Comment by tmcnag** [comment]
Update again.

After further testing, it appears that the `-c` option makes no difference - present or not, greater than, less than, or equal to the number of tests, makes no difference.  Still getting `ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.` or similar.

**Comment by tmcnag** [comment]
For the time-being we have moved away from the Docker container due to the stability issues.  For posterity in case anyone else needs an alternative, we are running firefox:headless in a full Ubuntu Desktop 17, launched from Jenkins with a simple SSH worker setup and it is working perfectly.  Ran the same test pipeline 30 times in a row overnight, each one checked out.

**Comment by miherlosev** [comment]
Hi @Thomblin.

Unfortunately, we can not reproduce the issue. Try the latest docker image with `testcafe@0.19.2`. 
Feel free to reopen the issue if you can create an example on which we can reproduce the problem.

**Comment by AndreyBelym** [comment]
Thanks @gytisgreitai, I think we should add a note to the docs and describe how to configure Docker and provide additional resources for Docker containers.

**Comment by doomleika** [comment]
Same problem here. some times it work, some times it just hangs for no reason.

**Comment by gaborari** [comment]
I faced the same issue with docker compose up, within the docker container things are getting flaky.
I started to use docker-compose up with multiple containers to speed up the test run:
For 1-2 containers, it looks good, I haven't seen flakyness, but increasing the number of containers is making the tests flaky: the same exact tests are failing; Testcafe sometimes not finding the elements or hangs after a button click (validated with screenshots).
And also I saw that increasing the number of containers is having an impact on the test timing - for example a test which runs for 1 min with a single service, runs for 3 mins with 3 containers.

I tried to pass different ports (for the runner class), different volume mounts (for printscreens) for the each container, but no luck yet.
I tried on Win10 and Linux with Alpine and Node images, and with Chrome, Chromium, Firefox (headless, --no-sandbox options) but the result is the same.
Currently I'm using the latest TestCafe version (1.1.4)

**Comment by AndreyBelym** [comment]
@gaborari do you run your browsers in this container too? I guess the browsers are responsible for the high CPU usage. Try to start a browser from your host machine and connect it to the TestCafe Docker image as a remote browser: [Using TestCafe Docker image - Test on remote devices](https://devexpress.github.io/testcafe/documentation/using-testcafe/using-testcafe-docker-image.html#test-on-remote-devices).
