### ISSUE TITLE
testcafe should support IDs starting with a number

### ISSUE THREAD

**Issue by zoejobson** [DevExpress/testcafe#1899]
### Are you requesting a feature or reporting a bug?
feature/bug (testCafe is out of date with current javascript)

### What is the current behavior?
the  most recent version of javascript supports IDs which start with a number eg Selector('#1_AccountCode'), testcafe doesn't appear to
it errors telling e that the id doesn't exist in the dome, but if I use a selector Selector('[id=\'1_accountCode\']') then it works fine

### What is the expected behavior?
numbered IDs should be supported with the # operator

### How would you reproduce the current behavior (if this is a bug)?
create a page with numbered IDs and try to select them with # selectors

### Specify your

* operating system: windows 7
* testcafe version: 0.18.0
* node.js version: 6.11.4

**Comment by AlexanderMoskovkin** [comment]
Hi @zoejobson,

We just call the `document.querySelectorAll` function in the browser to find elements by a selector string. So, if you type `document.querySelectorAll('#1_input')` into a browser console the error `is not a valid selector` is appeared. 

Such ids are valid according to the [HTML5 specification](https://www.w3.org/TR/html5/dom.html#the-id-attribute). But they are not valid according to the [CSS specification](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier):

> they cannot start with a digit, two hyphens, or a hyphen followed by a digit

 E.g. you can't create a css style like:
```css
#1_AccountCode {
    display: none;
}
```
I suppose that's why the `querySelectorAll` function works in this way in browsers.

But you can easily workaround it by using the `withAttribute` method:
```js
Selector('input').withAttribute('id', '1_AccountCode')
```
