### ISSUE TITLE
Fullscreen doesn't seem to be working.

### ISSUE THREAD

**Issue by mnemanja** [DevExpress/testcafe#1910]
### Are you requesting a feature or reporting a bug?
A bug.

### What is the current behavior?
I've just upgraded from 1.16.x to 1.18.1 and the test window is no longer full screen. So I went and added the parameter `--start-fullscreen`, but it doesn't work.

This is my package.json script item `"e2eChrome": "testcafe 'chrome --start-fullscreen' ./src/**/*.e2eZ.js",`.
With this configuration, I'm getting the `ERROR No test file specified.` message.

### What is the expected behavior?
To have a full-screen window opened for testing

### How would you reproduce the current behavior (if this is a bug)?
Try the fullscreen feature.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: Windows 10
* testcafe version: 1.18.1
* node.js version: 8.7.0

**Comment by AlexanderMoskovkin** [comment]
Hi @mnemanja,

Since `0.18.0` TestCafe opens Chrome and Firefox with clean profiles by default (see [Release Notes](https://devexpress.github.io/testcafe/blog/testcafe-v0-18-0-released.html#chrome-and-firefox-are-opened-with-clean-profiles-by-default-1623)).

To run tests with your current user profile you can use the `userProfile` option: `testcafe chrome:userProfile test.js`.

You approach with the `--start-fullscreen` flag is ok too but it necessary to use `"` instead of `'` for wrapping arguments (it's Windows requirenments):
```json
"e2eChrome": "testcafe \"chrome --start-fullscreen\" ./src/**/*.e2eZ.js"
```

Optionally you can call the [maximizeWindow](https://devexpress.github.io/testcafe/documentation/test-api/actions/resize-window.html#maximizing-the-window) command in the [beforeEach](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#test-hooks) hook. In this case your browsers will always be maximized when tests are run.

**Comment by mnemanja** [comment]
Thanks @AlexanderMoskovkin
