### ISSUE TITLE
Firefox hangs with dialog asking to set it as standard browser

### ISSUE THREAD

**Issue by TauPan** [DevExpress/testcafe#1926]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

When starting tests with firefox, firefox shows the modal dialog to set itself as standard browser. No matter what is clicked here, the dialog appears every time. No tests are executed as long as the dialog is in place. The user needs to press escape or click a button to make tests run.

Since there's no error about a dialog handler, I guess that it won't help to try to install a dialog handler at that point. Also it's not clear from the documentation what would be the correct way to do this, if any.

### What is the expected behavior?

Tests should run without user interaction, i.e. modal dialogs should be dismissed.

### How would you reproduce the current behavior (if this is a bug)?

testcafe firefox ...

### Specify your

* operating system: 
```
NAME="openSUSE Leap"
VERSION="42.2"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.2"
PRETTY_NAME="openSUSE Leap 42.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```
* testcafe version:
testcafe@0.18.1
* node.js version:
v6.11.2
* firefox version
Firefox ESR 52.4.0 (64-bit)

**Comment by AlexanderMoskovkin** [comment]
Hi @TauPan,

Since the `0.18.0` version TestCafe opens a Firefox instance with a clean profile. We setup settings for Firefox testing profile there: https://github.com/DevExpress/testcafe/blob/master/src/browser/provider/built-in/firefox/runtime-info.js#L18.
It's possible we've missed some flag. @AndreyBelym will investigate it. 
As a workaround you can try to run your tests in your current user profile: `testcafe firefox:userProfile test.js`

**Comment by TauPan** [comment]
> As a workaround you can try to run your tests in your current user profile: testcafe firefox:userProfile test.js

Thanks, that helps.

**Comment by AndreyBelym** [comment]
Yes, we should include `"browser.usedOnWindows10"` flag to generated profile.
