### ISSUE TITLE
ClientFunction dependencies can’t be in another file

### ISSUE THREAD

**Issue by andrewbranch** [DevExpress/testcafe#2063]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
ClientFunction code errors with undefined references when injected `dependencies` are located in a separate file from the ClientFunction itself

### What is the expected behavior?
`dependencies` can be imported from anywhere

### How would you reproduce the current behavior (if this is a bug)?
```js
// get-location.ts
export const getLocation = () => window.location;
```

```js
// get-href.ts
import { getLocation } from './get-location';

const getHref = ClientFunction(() => getLocation().href, {
  dependencies: { getLocation }
});
```

```
An error occurred in ClientFunction code:
ReferenceError: get_location_1 is not defined
```

### Specify your

* operating system: macOS 10.13.3 Beta
* testcafe version: 0.18.6
* node.js version: v7.10.0
* TypeScript version: 2.6.2

**Comment by AlexanderMoskovkin** [comment]
Hi @andrewbranch,

It seems it relates to the way how `babel` compiles the code. 
Use the following way to resolve the issue:

```js
import * as utils from './get-location';

const getLocation = utils.getLocation;

const getHref = ClientFunction(() => getLocation().href, {
  dependencies: { getLocation }
});
```

**Comment by andrewbranch** [comment]
Hey, thanks for the quick response. Your workaround does indeed work. However, I don't understand why this was closed. This is still a bug with TestCafe, isn't it? That workaround isn't a tenable long-term solution; the code I posted initially _should_ work.

**Comment by AlexanderMoskovkin** [comment]
Unfortunately, I see no way of fixing it and retaining support for modern syntax in tests and a wide range of node.js versions and browsers. Should we fix this bug, we would lose a great amount of TestCafe benefits.

Let me explain this in detail.

Before running tests, we compile them with Babel. It allows using modern JavaScript in the tests (both in server-side and browser-side code using ClientFunctions). We do this because some of nodejs versions and browsers don't support certain modern syntax. The issue in your case appears because we compile both server-side and client-side code in one scope. As a result, the test is transformed to the code like this:

```js
var _getLocation = require('./get-location');
 var getHref = ClientFunction(function () {
  // this part will be executed in the browser. But browser's script doesn't have _getLocation definition
  return (0, _getLocation.getLocation)().href;
}, {
  dependencies: { getLocation: _getLocation.getLocation }
});
```

I'd be happy to get your case working, but I doubt that we can do it while we support the current suite of node.js versions and browsers. Meanwhile, it can be easily worked around in a test. For example, the following code works properly:

```js
import { getLocation } from './get-location';
 const getHref = ClientFunction(() => getLocationClient().href, {
  dependencies: { getLocationClient: getLocation }
});
```

**Comment by andrewbranch** [comment]
I guess I don't understand why Babel is being run on TypeScript code?

**Comment by AlexanderMoskovkin** [comment]
Sorry for a long response. `TypeScript` compiles the code in the same manner: see the [exapmle](https://www.typescriptlang.org/play/#src=%2F%2F%20get-href.ts%0D%0Aimport%20%7B%20getLocation%20%7D%20from%20'.%2Fget-location'%3B%0D%0A%0D%0Aconst%20getHref%20%3D%20ClientFunction(()%20%3D%3E%20getLocation().href%2C%20%7B%0D%0A%20%20dependencies%3A%20%7B%20getLocation%20%7D%0D%0A%7D)%3B). So the problem is actual here too.

**Comment by andrewbranch** [comment]
Ah, I think I understand now. Thanks for explaining. I bet a custom Babel plugin could fix this. If the compilation could be slightly tweaked to output either

```js
var _getLocation = require('./get-location');
 var getHref = ClientFunction(function () {
  // this part will be executed in the browser. But browser's script doesn't have _getLocation definition
  return (0, _getLocation.getLocation)().href;
}, {
  dependencies: { _getLocation: _getLocation }
});
```

or

```js
var _getLocation = require('./get-location');
 var getHref = ClientFunction(function () {
  // this part will be executed in the browser. But browser's script doesn't have _getLocation definition
  return (0, getLocation)().href;
}, {
  dependencies: { getLocation: _getLocation.getLocation }
});
```

it would work... I have no experience writing Babel plugins, so not sure how feasible this is, and not sure if something equivalent could be done with TypeScript. Just a thought.
