### ISSUE TITLE
VueSelector is not available in the docker image

### ISSUE THREAD

**Issue by thomasleveil** [DevExpress/testcafe#2064]
### Are you requesting a feature or reporting a bug?

requesting a feature

### What is the current behavior?

VueSelector is not available in the docker image

### What is the expected behavior?

All Framework-Specific Selectors should be available

**Comment by AlexanderMoskovkin** [comment]
Hi @thomasleveil,

Thanks for you proposal, it sounds reasonable.

As a workaround you can try to add the required modules into your project with tests.

**Comment by thomasleveil** [comment]
@AlexanderMoskovkin I made [my own docker image](https://github.com/thomasleveil/docker-testcafe) for that purpose, based on yours. I've tested it with Vue and it works.

**Comment by lucidtech** [comment]
so... since this is still open - jumping in here.  I am using the react selectors - but am unable to get it to work when placing them in the tests folder.  I always get this error...

```
ERROR Cannot prepare tests due to an error.

Error: ENOENT: no such file or directory, open '/tests/node_modules/testcafe/client/hammerhead.js'
    at readSync (/tests/node_modules/read-file-relative/index.js:24:22)
    at Object.<anonymous> (/tests/node_modules/testcafe/lib/testcafe.js:23:27)
    at Object.<anonymous> (/tests/node_modules/testcafe/lib/index.js:166:17)
    at Object.<anonymous> (/tests/node_modules/testcafe-react-selectors/lib/index.js:7:16)
    at Object.<anonymous> (/tests/password_setting.tests.js:2:1)
```

so +1 for bundling the other selector modules.

Interested to know if there are clearer instructions - but going to take the approach of building my own container.
