### ISSUE TITLE
Implement browser provider plugin system

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe#207]

**Comment by inikulin** [comment]
**Documentation notes** 
Document `PluginHost` API: helper methods, chalk, moment. 
Document custom error decorator.
Document `noColors` option.

**Comment by AndreyBelym** [comment]
I'll put here my thoughts about all the stuff, and update it as more will come out :smile: 

###### A BrowserProvider plugin
- must be a package with name `testcafe-provider-${pluginName}`. `pluginName` serves as id of the provider. 

- should export classes with following interface:
```js
class Browser {
    static async listAvailableIDs() => [string];
    static async isValidID(id: string) => boolean;

    static async getDescriptorDefaultValues(id: string|void) => object;

    constructor(descriptor: BrowserDescriptor);

    async open(startPage: string) => void;
    async close() => void;
   
    //optional part
    async resize(width: integer, height: integer) => void;
    async screenshot(screenshotPath: string) => void; 

    // not sure if it is needed, but may come in handy.
    // BTW, they can be implemented in plugin host part.
    get id() => string;
    get descriptor() => object;
}


```
###### A BrowserDescriptor object
- plain JS key-value object with required key `id`. Any other properties may be defined by each browser provider implementation. Some of these implementation-defined properties may be required, other may have default values.

- `id` is not required to be unique, or to contain all required information about browser. In fact, it is just textual human-friendly identifier that allows user distinguish between different browsers, e.g. an alias for autodetected local browser, or a path to a generic browser, or a capability string for saucelabs.

- the browser descriptor itself must store all required info for starting the browser.

Example:
- LocalBrowserDescriptor: `{ id: 'chrome', args: '--new-window', path:'C:\\Google\\chrome.exe }`;
- SaucelabsBrowserDescriptor: `{ id: 'chrome canary windows 10', sauceLogin: '****', saucePass: '******' }`

###### A Browser class
- `static async listAvailableIDs() => [string]` - list identifiers that are guaranteed to be valid as a browser `id`. It's not required to return all possible IDs: it is impossible in some cases, e.g. for direct browser paths.

- `static async isValidID(id: string) => boolean` - validates the specified ID. If it returned `true`, you can use the argument with `getDescriptorDefaultValues`, and can not otherwise.

-  `static async getDescriptorDefaultValues(id: string|void) => object` - should return a key-value object with default values for keys (properties), that may be used in a browser descriptor. Optional `id` parameter allows to have different default values for different browsers.

- constructor(descriptor: object) - stores the descriptor, does some implementation-defined preparations for the browser. This is how the descriptor is formed: user-specified 'id' + getDescriptorDefaultValues(id) + user specified values.

- `async open(startPage: string) => void` - starts the browser on a specified page url. It must be called before using `resize` and `screenshot`. Should throw an exception when calling it twice without calling `close` first. For local browsers, this method is supposed to store an OS-specific id of the created window for being able to address it in `close`, `resize`, and `screenshot`.

- `async close()` - closes the browser. 

- `async resize(width: integer, height: integer) => void` - optional, allows to resize the browser. Conversion from viewport names to numeric sizes can be performed internally by `testcafe` stuff.

- ` async screenshot(screenshotPath: string) => void;` - does a screenshot.

###### Helper functions
They can be infused through `Browser.prototype`. At least we need error reporting. 

Also I will really appreciate, if we will find a way to allow an execution of `Hybrid` functions. It will allow to execute code on a client, which is needed e.g. to solve https://github.com/DevExpress/testcafe-browser-natives/issues/57: guys from ASP team use `clientWidth`/`clientHeight` to determine actual client area of the browser, and then use it to calculate needed browser window adjustment and resize client area to exact specified size

###### Access through CLI
I'll try to explain handling of the browser arg on  a example:

`chrome,ie;local:chrome,ie;path:/../../,sauce:'chrome win 10',username='***',password='***'`

So it has grammar like:
```
BrowserArgument := ProviderString [';' ProviderString]
ProviderString := [PluginName ':' ] ID [',' ID]* [',' KeyValue]*
KeyValue := String '=' String
ID := String
String := NonControlChar* | ' " ' NonQuoteChar* ' " '
NonControlChar := Any character, except ' , ' ' ; ' ' = ' ' " ' 
NonQuoteChar := Any character, except ' " '
```
Legend:
`[]` - optional occurence
`*` - repeat `0..Inf`
`'x'` or `' x '` - literal `x`
`|` - alternative

if `PluginName ':'` part is omitted, `PluginName` becomes 'local`. `ID` is an alias, or path, or capability string - previously mentioned `BrowserDescriptor.id`. 

So it's mostly compatible with our current super-nice simple syntax, because `chrome,ie,firefox` =>  `local:chrome,ie,firefox` => `local:chrome;local:ie;local:firefox`. 

About remotes: we can just filter them from `local` IDs, it is similar what we are doing right now. But also it will be interesting to implement it as a provider, so you can write like `chrome,ff;remote:3;path:/usr/bin/firefox`.

**Comment by inikulin** [comment]
I'm not sure I understand how `Browser` class should be implemented. E.g. if I make saucelabs plugin and I have 50 browser there should I implement 50 classes with that interface?

> chrome,ie;local:chrome,ie;path:/../../,sauce:'chrome win 10',username='***',password='***'

It's a little bit inconsistent and complicated.

Maybe?:
```sh
testcafe-browsers-saucelabs login {username} {pass}
testcafe chrome,ie,saucelabs:ie-win10,saucelabs:chrome-win10
```

**Comment by inikulin** [comment]
Also the issue with the class approach is that you need to pass `Browser` base class somehow and user should not forget to extend their class with provided class. That's why we choose plain object + mixin approach for reporters. It would be nice to have it here as well: just export object and testcafe wil mixin stuff in in it

**Comment by AndreyBelym** [comment]
> I'm not sure I understand how Browser class should be implemented. E.g. if I make saucelabs plugin and I have 50 browser there should I implement 50 classes with that interface?

Nope, you implement a class, that starts a tunnel to Sauce, and starts a browser by specified capability string. Then `testcafe` create 50 instances of this class with different capability strings.

**Comment by inikulin** [comment]
>  listAvailableIDs

Maybe `listAvailableAliases`. Since we use term `alias` for run configurations. Then plugin creates browser instance via `open` which returns instance `id`
