### ISSUE TITLE
running from testcafe causes some views to occasionally render badly, and the tests to fail

### ISSUE THREAD

**Issue by zoejobson** [DevExpress/testcafe#2083]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Parts of the webapp do not appear - generally (ut sometimes they do appear)

### What is the expected behavior?

They should appear

### How would you reproduce the current behavior (if this is a bug)?

I'm not sure if its reproducible outside our internal environments and our webapp (which is behind various security measures), but I can provide comparable html or anything else which would help

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system: windows
* testcafe version: 0.18.6
* node.js version:6.11.4

**Comment by zoejobson** [comment]
badgridlist is the element for the grid when elements are hidden, gridlist is when they are not, they should not be hidden.

[badgridlist.txt](https://github.com/DevExpress/testcafe/files/1674119/badgridlist.txt)
[gridlist.txt](https://github.com/DevExpress/testcafe/files/1674120/gridlist.txt)

**Comment by miherlosev** [comment]
Hi, @zoejobson.
As I see, you use `Angularjs (1.x)` in your application. It does not seem possible to reproduce the problem using the markup you've sent, because `journalListGrid` performs client-side initialization. It is indicated by `initialized="ctrl.journalListGrid.init(s)"` and `items-source="ctrl.data"` attributes from your markup. 
We cannot reproduce the problem without an example. If you prepare one, please place it on http://jsfiddle.net, http://jsfiddle.net or send us directly.

**Comment by zoejobson** [comment]
It appears after help from colleagues that its our UI which has an intermittent bug so closing this issue
