### ISSUE TITLE
Files created by dockerized TestCafe have incorrect owner/permissions

### ISSUE THREAD

**Issue by shaikatz** [DevExpress/testcafe#2087]
### Are you requesting a feature or reporting a bug?
Improvement

### What is the current behavior?
Dockerfile sets
`USER user` + 
`ENTRYPOINT` automaticlly mapped to .sh file which prevents from `chmod`ing before running the tests, Which makes it impossible to write screenshots to mounted volume (which has access only for root)

### What is the expected behavior?
Use root user in the Dockerfile

I can make workaround with overriding the entrypoint by myself, but why not to use root to prevent those problems?

**Comment by AndreyBelym** [comment]
Hello @shaikatz!

Running dockerizedservices as root is insecure, and Docker documentation explicitly [suggests to run services as a regular user](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#user). Also, Google Chrome has problems running under the root user.

A process from a container can write to an attached volume, if you allow writing for everyone on the host directory. E.g.:
```sh
mkdir screenshots
chmod 0777 screenshots
sudo docker run -it -v ~/tests:/tests -v ~/screenshots:/screenshots testcafe/testcafe firefox /tests -s /screenshots
```

Unfortunately, you won't be able to delete created files without `sudo`, because they will be owned by the user from container. 

We really need to implement some workaround around this permission/ownership problem, but I don't think that running TestCafe as a superuser is a good idea.

**Comment by shaikatz** [comment]
Thanks Andrey, I'll use the method you described.
