### ISSUE TITLE
Math.trunc

### ISSUE THREAD

**Issue by xcb6** [DevExpress/testcafe#2100]
### Are you requesting a feature or reporting a bug?

bug

### What is the current behavior?

Math.trunc return ``ReferenceError: _trunc2 is not defined``

### What is the expected behavior?

Math.trunc return a value

### How would you reproduce the current behavior (if this is a bug)?

see script under

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: 

Test code

```js
import { Selector } from 'testcafe'
fixture('Math test')
test('Math.ceil', async (t) => {
  const result = await t.eval(() => Math.ceil(13.37)) // <=== OK
  await t.expect(result).eql(14)
})
test('Math.trunc', async (t) => {
  const result = await t.eval(() => Math.trunc(13.37)) // <== BAD
  await t.expect(result).eql(13)
})

```

### Specify your

* operating system: Win7.0.0
* testcafe version: 0.18.6
* node.js version: 6 and 8

**Comment by AlexanderMoskovkin** [comment]
Hi @xcb6,

Thanks for the issue. We've faced with such problems before. It happens because we compile the test code with [Babel](https://babeljs.io/). Server-side and client-side (code inside `ClientFunction` and `t.eval`) are compiled in the same scope thought actually they are executed in different environments. I described this in more details in my [comment](https://github.com/DevExpress/testcafe/issues/2063#issuecomment-360460738).

You can use one of the following workarounds:
- move the `Math.trunc` execution to the `server` side if it's possible;
- add the following line into your test: `const Math = global.Math;` (it's rather a hack but should work).

We already have an issue for such cases (see #1596). I close this one in favor of it and add the info about your case there.

**Comment by xcb6** [comment]
Thank
