### ISSUE TITLE
Question: Does it support Cucumber & other queries ?

### ISSUE THREAD

**Issue by vikramvi** [DevExpress/testcafe#2170]
### Are you requesting a feature or reporting a bug?
1. Queries 
1.1 What benefits I will get over Selenium ?
1.2 Does it have integration with Cucumber ?
1.3 Is there really need of another web UI automation tool / framework and if yes; why ?

thanks in advance.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by helen-dikareva** [comment]
Hello @vikramvi 
1. You can find TestCafe benefits over Selenium [here](https://testcafe-discuss.devexpress.com/t/why-not-use-selenium/47).
2. Please take a look at [this topic](https://testcafe-discuss.devexpress.com/t/testcafe-and-cucumber-js/207) on our forum to find Cucumber integration examples.
3. There are some good reasons to choose TestCafe for functional testing.
TestCafe doesn't use WebDriver under the hood in contrast to most analogues. This means that:

- You don't have to use any plugins for browsers support. All modern browser are supported out of the box.
- Easy installation and quick start testing
- No need to include waiting for element availability or callback finishing in tests
- Extremely stable tests due to assertions' auto-waiting mechanism

And also:
- Support for all latest JavaScript features
- Support for concurrent testing
- Integration with popular CI systems

Please visit [TestCafe site](https://devexpress.github.io/testcafe/) and [documentation ](https://devexpress.github.io/testcafe/documentation/getting-started/) to get more details about our features.

**Comment by vikramvi** [comment]
Thanks for detailed answer. I'm closing issue as clarified
