### ISSUE TITLE
Extend the Selector API to simplify testing ShadowDOM elements

### ISSUE THREAD

**Issue by sorin-davidoi** [DevExpress/testcafe#2172]
### Are you requesting a feature or reporting a bug?

Requesting a feature.

### What is the current behavior?

Selecting elements inside ShadowDOM is verbose:

```js
const submit = await Selector(() =>
  document
    .querySelector('x-app')
    .shadowRoot
    .querySelector('x-form')
    .shadowRoot
    .querySelector('form button[type="submit"]')
);
```

### What is the expected behavior?

Writing selectors should be easy.

```js
const submit = ShadowSelector('x-app |> x-form |> form button[type="submit"]');
```

Sample implementation (no edge case handling) I've written to achieve this:

```js
const ShadowSelector = Selector(
  (selector, element = document, separator = '|>') => {
    const segments = selector.split(separator);

    for (const segment of segments) {
      element = element.querySelector(segment);

      if (!element) {
        return null;
      }

      if (!!element.shadowRoot) {
        element = element.shadowRoot;
      }
    }

    return element;
  },
);
```

### Specify your

* testcafe version: 0.18.6

**Comment by AndreyBelym** [comment]
Hi @sorin-davidoi! Thank you for your proposal, we need some time to discuss it. Right now, you can [extend Selector with a custom method](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/extending-selectors.html#custom-methods), e.g.:
```
const myTable = Selector('x-app').addCustomMethods({
    getShadowRoot: host => {
        return host.shadowRoot;
    };
});
```

**Comment by jackblackCH** [comment]
+1, any updates here? Accessing nested shadowRoots is still a pita. Especially with custom elements where nested components are normal.

**Comment by daanhaitsma** [comment]
> Hi @sorin-davidoi! Thank you for your proposal, we need some time to discuss it. Right now, you can [extend Selector with a custom method](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/extending-selectors.html#custom-methods), e.g.:
> 
> ```
> const app = Selector('x-app').addCustomMethods({
>     getShadowRoot: host => {
>         return host.shadowRoot;
>     };
> });
> ```

Using this code results in the following error:

> `getShadowRoot cannot return DOM elements. Use Selector functions for this purpose.
`

Is there something I did wrong or has the functionality changed since this comment?

**Comment by AndreyBelym** [comment]
@jackblackCH I can't give you an estimate yet. The TestCafe team will be grateful if you can create a PR for this feature 😊. It's not so hard: you can use the [Selector.child`](https://github.com/DevExpress/testcafe/blob/v1.1.0/src/client-functions/selectors/add-api.js#L558) as a reference and return `node.shadowRoot` from it [here]( https://github.com/DevExpress/testcafe/blob/v1.1.0/src/client-functions/selectors/add-api.js#L579).

@daanhaitsma, yes, it was a change in the `Selector` API, I've updated the example.

**Comment by mostlyfabulous** [comment]
I really would like to see `shadowRoot` supported so I've started working on this functionality here:
https://github.com/mostlyfabulous/testcafe/commit/fb7e152aadb707241b5f0fb1456e60fabdcafc87

Since their can only be one `shadowRoot` on a DOM element, I'm not sure there's much else to add except the attempt to return the property if exists.

One consideration for `shadowRoot` is its 'visibility': 
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM

See this portion of the documentation:
![image](https://user-images.githubusercontent.com/15062048/93559557-e55e4e80-f934-11ea-85a0-7e4f3e6ca869.png)

If someone could direct me to the right places to write the unit and or functional tests (and the associated mock website/implementation) for this enhancement, I would appreciate it.

**Comment by AndreyBelym** [comment]
@mostlyfabulous, thank you for your contribution. I will review it in detail soon. I saw that you added a couple of raw API functional tests, it's impressive that you figured that on your own. Often we also add JS API tests for such functionality: 
https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/api/es-next/selector/test.js
https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js

And likely we should add a TypeScript definition for the new method here:
https://github.com/DevExpress/testcafe/blob/master/ts-defs-src/test-api/selector.d.ts#L211

**Comment by mostlyfabulous** [comment]
@AndreyBelym thank you for thr follow up and information on where to add tests.

While the API method I'm proposing let's developers write chainable Selector queries when working with the shadow DOM, it doesn't reduce the verbosity of these Selectors very much.

Is it possible to add a config variable to let all the Selector API methods check the `shadowRoot` of an element for a specified input?
e.g
This is ideal:
`Selector('css-selector').find('element-in-shadowRoot')`
Instead of: 
`Selector('css-selector').shadowRoot().find(element-in-shadowRoot')`

**Comment by AlexKamaev** [comment]
@mostlyfabulous
At this moment, we do not think that the described config option is required. 
 
Shadow DOM components are supposed to be isolated from the rest of the page, so it's not correct to use the same methods to search for elements inside and outside Shadow DOM. 
 
Thus, we think that the `.shadowRoot()` method will be sufficient for most cases.
