### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by corneliutusnea** [DevExpress/testcafe#2189]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
When I navigate to some pages I get an error from hammerhead in the console and that breaks all the JS on the page.

```
Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at <anonymous>:2:491
    at t.insertBeforeRoot (hammerhead.js:8)
    at t._addNodeCore (hammerhead.js:6)
    at HTMLBodyElement.insertBefore (hammerhead.js:6)
    at gtm.js?id=GTM-WL92VDV&l=dataLayer:21
    at Object.c (gtm.js?id=GTM-WL92VDV&l=dataLayer:24)
    at r (hammerhead.js:9)
    at value (hammerhead.js:2)
    at Sf (gtm.js?id=GTM-WL92VDV&l=dataLayer:46)
    at ll.H (gtm.js?id=GTM-WL92VDV&l=dataLayer:101)
```

### What is the expected behavior?
No error and page should continue working.

#### Provide the test code and the tested page URL (if applicable)
Open a trial account with www.bigcommerce.com
Create a test 
```
test("test", async t=>{
    await t.navigateTo("https://store-aaaa.mybigcommerce.com/manage/marketplace/apps/my-apps");
        await this.t.typeText("#user_email", user) // enter your user/pass
            .typeText("#user_password", pass)
            .click("input.login-form-button");
// page crashes
});
```

Tested page URL:
https://store-aaaaa.mybigcommerce.com/manage/marketplace/apps/my-apps
(or any other trial store

### Specify your
* operating system:
Windows 10
* testcafe version:
0.19.0
* node.js version:
6.11.1

**Comment by LavrovArtem** [comment]
Hi @corneliutusnea,
I've investigated this issue and it seems that the error occurs on the www.bigcommerce.com site(without testcafe). Try specifying the [--skip-js-errors](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) flag so that TestCafe will ignore js errors on the page and continue test execution.
![image](https://user-images.githubusercontent.com/5373460/36965669-69f5f58a-206b-11e8-9a48-428a214490c8.png)
