### ISSUE TITLE
Longevity of this project?

### ISSUE THREAD

**Issue by binarykitchen** [DevExpress/testcafe#2244]
Gave this library a try and it works well on first trial.

Although for a large project we question its longevity. Since it's not webdriver based which is a well established standard we're unsure about testcafe.

Would be good to know the long term plans and how long you intend to maintain it. And if one day webdriver API gets implemented too?

**Comment by VasilyStrelyaev** [comment]
Hi @binarykitchen and thanks for your interest in TestCafe.

We at [DevExpress](https://www.devexpress.com/) have been working on TestCafe since the beginning of 2010s. The first version debuted in 2013. It was a commercial testing framework shipped both as a part of the DevExpress Subscription and separately. You can find more information about it here: https://testcafe.devexpress.com/.

In 2016, we have decided to open-source the core of TestCafe. Since then, we've grown to more than [80K downloads per month](http://npm-stats.org/#/testcafe) and still counting actively.

And we have huge plans for TestCafe. In the nearest future, we are releasing a new commercial testing IDE called TestCafe Studio (currently in limited beta). It will be built on top of the open-source TestCafe. Thus, we are going to keep developing TestCafe because this will add new features to TestCafe Studio.

One more argument for TestCafe is that it has a trusted company behind it. DevExpress is known as a software component vendor since the beginning of 2000s. We have a huge community of customers and we earned multiple [industry awards](https://www.devexpress.com/Home/awards.xml).

As for the **WebDriver API**, currently we don't have plans to support it.

**Comment by VasilyStrelyaev** [comment]
You can read more about our motivations regarding WebDriver API on our forum: https://testcafe-discuss.devexpress.com/t/why-not-use-selenium/47
