### ISSUE TITLE
Investigate a possibility to run tests for webview-based applications.

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#2252]
Links:
- https://testcafe-discuss.devexpress.com/t/testing-ionic-phonegap-apps-with-testcafe/979

**Comment by viking2917** [comment]
Thanks - would love to see this!

**Comment by kirillgroshkov** [comment]
Any updates? Have someone try to connect to `testcafe remote` from a webview?

**Comment by miherlosev** [comment]
One more private request - https://www.devexpress.com/Support/Center/Question/Details/T735149/test-cordova-app-with-apk-file-in-testcafe-studio

**Comment by AlexSkorkin** [comment]
+1 request
https://www.devexpress.com/Support/Center/Question/Details/T748324/setting-up-test-for-all-our-cordova-apps-in-teststudio

**Comment by automationmaven** [comment]
Upvote.

**Comment by rob4629** [comment]
👋 Hey, just wondering, would this cover running tests in Facebook's Webview?

**Comment by miherlosev** [comment]
Hi @rob4629

To give you a precise answer regarding the support for Facebook's Webview, we need to research the possibility of running tests for webview-based applications.
As soon as we perform such investigation, we will create a list of supported webview-based application types: mobile, smart tv, facebook webview, etc.

**Comment by Agipsy** [comment]
Today I've tried to run testcafe on iOS install app that using cordova. 
I've got connect error 500 from server and response : "There are no available _connection to establish". 
Testcafe write a message: "ERROR The Safari 13.1.2 / iOS 13.7 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues."

In safari works good.

Do you have any updates to work with webview?

**Comment by miherlosev** [comment]
Hi @ilchenkoalexey

There is no update yet. As we will get any results, we will update this thread.

**Comment by miherlosev** [comment]
We decided to not implement this enhancement and focus on the TestCafe features.
