### ISSUE TITLE
Safari clicks not working - TypeError: tabs.select is not a function

### ISSUE THREAD

**Issue by dweber019** [DevExpress/testcafe#2286]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
test.spec.ts
```
✖ Should be able to enter a todo item

   1) Error on page "https://todomvc.com":

      TypeError: tabs.select is not a function. (In 'tabs.select(0)', 'tabs.select' is undefined)

      Browser: Safari 11.0.3 / Mac OS X 10.13.3

         16 |  });
         17 |
         18 |test.only('Should be able to enter a todo item', async (t) => {
         19 |
         20 |  await t
       > 21 |    .click(Selector('li').withText('Vue.js'))
         22 |    .expect(getBrowserTitle()).eql('Vue.js • TodoMVC');
         23 |
         24 |  await t
         25 |    .typeText(todoMvcPageModel.newInput, 'Buy milk')
         26 |    .pressKey('enter');
```

### What is the expected behavior?
No error and click is performed.

### How would you reproduce the current behavior (if this is a bug)?
See above.

#### Provide the test code and the tested page URL (if applicable)
See above

### Specify your

* operating system: Mac OS X 10.13.3
* testcafe version: 0.19.1
* node.js version: 8.x

**Comment by AlexanderMoskovkin** [comment]
Hi @dweber019,

The `todomvc.com` page contains a lot of error when you just open it in Safari (without TestCafe).
![image](https://user-images.githubusercontent.com/12047804/38372376-5381fe80-38f7-11e8-912a-93bb770f572d.png)
TestCafe reports JS errors that it finds on the webpage. Tests automatically fail because of that. 
To skip failure on throwing JS errors during test running, you can use [`--skip-js-errors`](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) flag in the Command Line Interface or the `skipJsErrors` option in [`runner.run()`](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#run) method in the Programming Interface.
