### ISSUE TITLE
Error while navigating sign-in page

### ISSUE THREAD

**Issue by vigneshwar-v** [DevExpress/testcafe#2291]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
Throwing error while signing in ,
"status":403,"error":"Forbidden","message":"Invalid CSRF Token '' was found on the request parameter '_csrf' or header 'X-C'.","path":"/api/login"

### What is the expected behavior?
Successful signin

### How would you reproduce the current behavior (if this is a bug)?
running testcafe against any sign-in page which expects csrf token

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

### Specify your

* operating system: mac OS sierra 10.13.4
* testcafe version: 0.19.1
* node.js version: 8.11.1

Hi All,

I have a authentication form which asks for username and password, then the url in the window is sent to another api to validate and thats when the error occurs

The expected url by the API from the browser window,
http://www.x.com

But the url received by the API when I use test-cafe,
http://192.xxx.xxx.xxx/qsqsqwwqwd/http://www.x.com

Give me a solution for this. I cant surely change the API's behavious, should happen from the testcafe end.

I am getting the below error as response -
"status":403,"error":"Forbidden","message":"Invalid CSRF Token '' was found on the request parameter '_csrf' or header 'X-C'.","path":"/api/login"

**Comment by vigneshwar-v** [comment]
Guys??

**Comment by vigneshwar-v** [comment]
I cant even go through the login page if this is not solved :(

**Comment by MarinaRukavitsyna** [comment]
Hi @vigneshwar-v,
 
The information you provided is insufficient to determine the exact cause of the issue. Nevertheless, this issue looks like one described in the following thread: [Can't interact with websites that require CSRF Tokens](https://github.com/DevExpress/testcafe/issues/2106).
 
If the described problem is different, please provide us with a link to a problematic page so that we can see the issue locally. If the link is private, describe how the CSRF Token is technically implemented in your project.

**Comment by vigneshwar-v** [comment]
https://testcafe-discuss.devexpress.com/t/csrf-issue-with-testcafe/1044/2

I have mentioned the urls and test scenario in test cafe forum. kindly refer to it

**Comment by miherlosev** [comment]
Hi @vigneshwar-v

The cause of the problem is described in https://github.com/DevExpress/testcafe-hammerhead/issues/1486. Track it to stay informed about our progress.

**Comment by AndreyBelym** [comment]
Hi @vigneshwar-v, thanks for sharing your problem. I close this because it's duplicated by https://github.com/DevExpress/testcafe-hammerhead/issues/1486. You can use https://github.com/DevExpress/testcafe-hammerhead/issues/1486 to track the progress in resolving this issue, and I will inform you when a fix is available on NPM.
