### ISSUE TITLE
Updated alpha version?

### ISSUE THREAD

**Issue by bsmithb2** [DevExpress/testcafe#2292]
### Are you requesting a feature or reporting a bug?
Asking a Question

### What is the current behavior?
Currently the 0.19.2-alpha2 reports 0.19.2-dev20180323 when package.json sets the version to 0.19.2-alpha2 and you run testcafe-v. 

### What is the expected behavior?
Just wondering when the version containing updated changes for https://github.com/DevExpress/testcafe/commit/095162e66afdbdf138dc3c4dc2cc85a62600fdd1 will be published to alpha?

### Specify your

* operating system: Linux WSL on Windows 10, Windows 10
* testcafe version: 0.19.2-alpha2
* node.js version: 9.8.0

**Comment by AlexanderMoskovkin** [comment]
Hi @bsmithb2,

We need a couple of days to do it (I guess it'll be ready today or tomorrow). We'll notify you about new version in the #2221 issue

**Comment by AndreyBelym** [comment]
Hi @bsmithb2, I guess you use caret version range `"testcafe": "^0.19.2-alpha2"` in your `package.json`. We've realized that using `alpha` and `dev` prefixes for alpha and nightly builds is a quite semver-breaking way, because `devXXXX` will always have precedence over `alphaXXXX` by semver rules.

I think we'll fix versioning in future releases, but now you shouldn't use version ranges with preliminary builds: use the exact version (`"testcafe": "0.19.2-alpha2" - pay attention: no caret), or use "alpha" or "dev" npm tags ("testcafe": "alpha").

**Comment by AlexanderMoskovkin** [comment]
@bsmithb2 , Meanwhile, we've published new version with the fix: `v0.19.2-alpha3`

**Comment by AndreyBelym** [comment]
Hi @bsmithb2, we've just published a new stable release `0.19.2`, so now you can specify "testcafe": "^0.19.2" in your pacakge.json.

**Comment by bsmithb2** [comment]
Awesome. Thankyou. Would you guys be interested in a provider that allows people to run testcafe on Samsung/android devices locally?
