### ISSUE TITLE
Proposal: Use "describe" in place of "fixture"

### ISSUE THREAD

**Issue by timwis** [DevExpress/testcafe#2302]
Forgive me if this is thoroughly discussed already -- I couldn't find it, and just wanted to propose it. My understanding of the word "fixture" is more akin to sample data used to ensure consistent unit or integration tests ([as described here](https://stackoverflow.com/a/14684400/633406)). I normally have a `fixtures` directory of JSON files that I stub XHR requests with, for example. Testcafe uses it to describe the test file, which other testing libraries like mocha and jest use the word `describe` for. I just wanted to propose either changing it, or allowing an alias so as not to confuse fixture with the other meaning.

**Comment by VasilyStrelyaev** [comment]
Hi @timwis,

Thank you for your observation.

When we just started working on TestCafe here at DevExpress, our first users were DevExpress teams that work on ASP.NET projects and run NUnit tests against them. So we borrowed the term `fixture` from NUnit meaning a set of tests.

I agree that most frameworks use the word `fixture` with a different meaning. However, the `describe` keyword is mainly used in BDD frameworks that support nested test sets. Note that we also have a suggestion to support BDD testing: https://github.com/DevExpress/testcafe/issues/792. And that's where we use `describe` instead of `fixture`.

As to our current test workflow, I feel like it is too late to make such a fundamental change switching from `fixture` to `describe`. This would be a major breaking change for all our users and we already have a number of them. After all, it is a matter of taste to rather prefer one or another keyword, isn't it?

**Comment by timwis** [comment]
Thanks for that background! Makes sense. I was suggesting perhaps allowing describe as an alias rather than replacing it, so it would be backwards compatible, but if that doesn't appeal to enough of your user base then it wouldn't be worth it I imagine.
