### ISSUE TITLE
TestCafe display a wrong callsite if error is occured in `t.eval` inside of async code

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#2306]
* testcafe version: 0.19.2-alpha3

Test code
```js
fixture `Fixture`;

test('test', async t => {
	await t.eval(() => {
		window.setTimeout(() => {
			throw new Error('I am an error');
		}, 0);
	});
	
	await t
		.wait(500)
		.click('body');
});
```
![image](https://user-images.githubusercontent.com/4133518/38609778-a7e007da-3d87-11e8-94cc-549d7e820395.png)

**Comment by AlexanderMoskovkin** [comment]
It's a behavior by design. 

If the error is raised during the `eval` command execution you will see a correct `An error occurred in eval code` error. In your example you raise the error inside the `setTimeout` callback. In this case `t.eval` is executed without errors. TestCafe finds the js-error in the browser when it tries to execute the `click` action.
