### ISSUE TITLE
Testcafe runs test cases that don't match a regexp

### ISSUE THREAD

**Issue by viraxslot** [DevExpress/testcafe#2337]
### Are you requesting a feature or reporting a bug?
Bug
### What is the current behavior?
I have test cases with titles like 
```
"#001 test case"
"#002 test case" 
"#003 test case" and so on
```
I want to run only the first one and tried commands:
```
testcafe firefox:headless src/tests -T "001*"
testcafe firefox:headless src/tests -T "#001*"
testcafe firefox:headless src/tests -T "\#001*"
```

But all test cases from test fixture with 001 test case are running.
I also tried "\*001\*" regexp, but it's not a valid regexp:
```
$ testcafe firefox:headless src/tests -T "*001*"
Using locally installed version of TestCafe.
ERROR The "--test-grep" option value is not a valid regular expression.
```

### What is the expected behavior?
Expected results: only the first test case is running.
Could you please add information about what regexp standard is used to documentation?

### Specify your
* operating system: Windows 10 Pro, version 1709, build 16299.309
* testcafe version: 0.19.2
* node.js version: 9.7.1

**Comment by inikulin** [comment]
The problem is that you've constructed incorrect regular expression. `*` is a quantifier that means 0 or more occurrences of the preceding character. In your case preceding character is `1` and all of the test names that you have are indeed contain 0 or more occurrences of character `1` at this position. The correct regular expression will be `#001.*` or just `#001`.

**Comment by viraxslot** [comment]
@inikulin thank you, I'll try.
