### ISSUE TITLE
Test waits for timeout before clicking input

### ISSUE THREAD

**Issue by tamlyn** [DevExpress/testcafe#2381]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?

When trying to click on an input which is hidden (for styling reasons), TestCafe waits for the element to appear then just as the wait times out, it clicks the input *successfully*.

### What is the expected behavior?

Either it times out then fails (what I would expect from the docs), or it succeeds straight away (what I would wish for as it simplifies my selectors 😀).

### How would you reproduce the current behavior (if this is a bug)?

```
import { Selector } from 'testcafe'

fixture('WTF Forms')

test('Click hidden input', async t => {
  await t.navigateTo('http://wtfforms.com/')
    .click(Selector('input').nth(0))
    .click(Selector('input').nth(1))
})
```

### Specify your

* operating system: OSX 10.11.6
* testcafe version: 0.19.1
* node.js version: 8.9

**Comment by hdorgeval** [comment]
Hi @tamlyn, I also encountered this issue on hidden inputs that are rendered as a YES/NO toggle. The work-around is to click on the parent container as a normal user will do.

**Comment by AndreyBelym** [comment]
Hi @tamlyn, @hdorgeval. Such behavior means that the target element is visible, but it's box is in background, hidden by some other element's box. E.g. on http://wtfforms.com the input's box is hidden behind the caption's box:
![image](https://user-images.githubusercontent.com/4479386/39867640-8a901f88-545e-11e8-8e8b-f23b8c23f23c.png)
![image](https://user-images.githubusercontent.com/4479386/39867669-ab1889b6-545e-11e8-8e93-8ff16b1a98c5.png)

Because a user can click only on foreground elements, it would be incorrect to click on the target element that is in background. In this case, TestCafe gives some time for the element to get into foreground, and if it isn't happen, TestCafe clicks on a foreground element that is placed over the target element's box. 

It's not a bug, it's designed behavior for complex JS-based animations. You should check that your selectors point to foreground elements, or just set [selector's timeout](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/selector-options.html#optionstimeout) to 0.

**Comment by tamlyn** [comment]
Thanks for the explanation. Would it be worth updating [the documentation](https://devexpress.github.io/testcafe/documentation/test-api/actions/#selecting-target-elements) to mention this? Currently it says

>Before executing an action, TestCafe waits for the target element to appear in the DOM and become visible. If this does not happen within the selector timeout, the test fails.

**Comment by AndreyBelym** [comment]
@tamlyn, I agree, we should make it clear in our docs. I've created an issue about it: https://github.com/DevExpress/testcafe/issues/2389
