### ISSUE TITLE
Accessing to the 'visible' property of the Selector shouldn't interrupt a test execution

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#2386]
See example to reproduce
```js
import { Selector } from 'testcafe';

fixture `Fixture`
	.page('https://devexpress.github.io/testcafe/example/');
	
test('i2383', async t => {
		const dummySelecotor = Selector('.dummy-class');
		
// Fails here
>		if (await dummySelecotor.visible) { 
			console.log('Wrong!! Dummy Selector is visible');
		} else {
			console.log('Executed `else` statement');
		}
});	
```

The test will interrupt with message 'Cannot obtain information about about the node because....'.
If I will change the `await dummySelecotor.visible` to `await dummySelecotor.exists` it works as expected.

* testcafe version: 0.20.0

**Comment by miherlosev** [comment]
Hi @noamaankhan 

We cannot provide you with precise time estimation. If this feature is important for you, the pull request would be appreciated. For more information, refer to the [Contribution guide](https://github.com/DevExpress/testcafe/blob/master/CONTRIBUTING.md#code-contribution) section in our documentation.

**Comment by SacredSkull** [comment]
I may be interested in providing a PR for this. I'm struggling with this issue due to a loader element disappearing after an `exists` check.

Basically the following:
```js
function waitForElementToDisappear(selector) {
    while (maxPollingChecksEtc && await selector.exists) {
        --- element disappears here ---
        let invisible = !await selector.visible; // test ends because visible depends on element existence (not sure why it does!)
        if (invisible) break;
        await t.sleep(pollDelay)
    }
}
```

In my opinion, an element that does not exist is not visible - and calling `visible` on an inexistant element should not throw an error.

If backwards compatibility is a concern, perhaps some `Selector {}` option that will make `visible` return false in this case (perhaps called `relaxedVisibilityChecks`)?

**Comment by AlexKamaev** [comment]
@SacredSkull 
I agree with you. If the element does not exist, this means that it is not visible and the error should not be thrown.
I think we do not need any additional options for this. 
Your PR will be appreciated.
