### ISSUE TITLE
Feature: Role snapshots need to include indexedDB

### ISSUE THREAD

**Issue by mwaldstein** [DevExpress/testcafe#2420]
### Are you requesting a feature or reporting a bug?

Feature

### What is the current behavior?

Currently, only cookies (I think?) get saved when Role snapshots are taken. In recent releases of firebase, user state information is stored in IndexDB. As a result, switching roles does not changed the authenticated user.

Similarly, switching to an anonymous Role stays logged in as the indexDB is not cleared.

### What is the expected behavior?

Creating a role and switching to a role changes the logged in user.

### References:

These issues refer to resetting, but need to apply to taking snapshots as well: 

 * #2240 
 * [testcafe-hammerhead/1429](https://github.com/DevExpress/testcafe-hammerhead/issues/1429)

**Comment by Juansasa** [comment]
I think exposing Role with a callback to enable devs to decide what to save and what not to the browser is a much better option. Or expose the Testcontroller in before hook so we Devs can do all of it ourselves is even better.

**Comment by viking2917** [comment]
Is this issue something that is likely to be fixed? It appears with this limitation that it's impossible to use Testcafe Roles with Firebase, Google's preferred user management toolset...

**Comment by AlexanderMoiseev** [comment]
Hello, yes we have this feature planned, continue to follow this thread to stay tuned

**Comment by viking2917** [comment]
@AlexanderMoiseev Awesome! Thanks. If you want a beta tester I'd be happy to help.

**Comment by viking2917** [comment]
Is there any suggestion for how to work around the incompatibility of Testcafe Roles & Firebase? I am on an ancient version of Firebase and need to upgrade, but my test suite is built with Roles as a key building block. Re-writing all my tests would be very unpleasant....thanks for any suggestions.

**Comment by wentwrong** [comment]
Hello, @viking2917,

IndexedDB proxying is a pretty big and complex feature. Right now team is busy with implementing [multi-window API](https://github.com/DevExpress/testcafe/issues/5034).

As a suggestion, you could try saving and restoring the IndexedDB state manually. In Role, use ClientFunction that fetches and returns serialized IndexedDB data and save the serialized state in a global variable in your test. Then use another ClientFunction before calling "t.useRole" to restore the saved IndexedDB state from a global variable.

Another possible workaround is replacing your Role with the following FallbackRole, that doesn't try to save and restore the page state but always executes authentication steps:

```js
import { Role } from 'testcafe';

function FallbackRole (url, body) {
    const role        = Role(url, body);
    const originPhase = role.phase;
    Object.defineProperty(role, 'phase', {
        get: () => originPhase,
        set: () => {}
    });
    return role;
}

fixture `1`;

const role = FallbackRole('example.com', () => console.log(123));

test('1', t => t.useRole(role));
test('2', t => t.useRole(role));
```

**Comment by viking2917** [comment]
@wentwrong Thanks for these suggestions. I'm relatively unfamiliar with IndexedDb, so I think I may try a variant of option 2. It may be that my tests don't really rely too much on app state other than authentication so just building my own FallbackRole to replace existing useRole (re)authentication, and tweaking the tests, may not be too bad.

I appreciate the suggestions!

**Comment by inferpse** [comment]
Just encountered the same issue with Firebase authentication 😞
I think I found another workaround that could be easily applied if your project does not rely on indexedDB:

> Simply kill global `indexedDB` factory and Firebase will have to fallback to `localStorage` in order to save data.

Here's how this could be done with the help of TestCafe configuration:
1) Create empty file `fix-client-env.js` with following content:
```
delete window.indexedDB;
```

2) Create or edit your `.testcaferc.json` so that it will inject this script in the test environment:
```
{
  "clientScripts": [
    "./fix-client-env.js"
  ]
}
```

This trick helped me to use TestCafe Roles with Firebase Authentication in Web.

**Comment by AdrienLemaire** [comment]
@inferpse I'm facing an error when trying to add your trick

```console
ERROR Cannot prepare tests due to the following error:

ReferenceError: window is not defined
    at Object.<anonymous> (/path/to/scripts/fix-firebase.js:1:1)
```
Did you not have this issue ?

**Comment by AdrienLemaire** [comment]
I'm failing to use @inferpse trick to delete indexedDB to authenticate with Firebase using roles, as reported in #6893

* When using the `signInWithPopup` method, I get a firebase error "auth/popup-closed-by-user".
* When testing with the `signInWithRedirection` method, firebase redirects the test user to my app upon signin, but the test user stays anonymous.

Looking at Chrome's console debugger Application tab, I can see the indexedDb data when signin in my app locally. But I cannot see any similar localStorage data when debugging the TestCafe chrome window.

What version of firebase could you get this working with ? Wondering if it's because I'm using `v8.6.5`.

**Comment by inferpse** [comment]
@AdrienLemaire that trick I've shared is working for me with both Firebase v8 and v9.

There might be a simple way to overcome your issue with popup:
You can create test account in Firebase Auth with predefined email/password and use `signInWithEmailAndPassword` method instead. It does not create any popups and works just fine with latest TestCafe for me at this moment.
