### ISSUE TITLE
Copy/paste functionality

### ISSUE THREAD

**Issue by Mihai0909** [DevExpress/testcafe#2514]
On the page I'm testing now, a new URL is generated and I need to select, copy the URL, open a new tab and continue to do more actions and assertions. My question is how can I make this thing work?                  I clicked and selected the new text (URL), but I'm stuck at this step. 
I'm aware that TestCafe can't handle multiple tabs. It's fine if the url is opened in the same tab.

**Comment by MarinaRukavitsyna** [comment]
Hello Mihai,
TestCafe cannot automate a browser's built-in behavior including the Copy & Paste functionality. We expect that this functionality works correctly as it is tested by browsers' developers. In addition, TestCafe does not support browser tabs: it is possible to run tests in a single window only.

Nevertheless, would you please describe your scenario in greater detail? Why do you wish to copy-paste URL instead of opening this URL directly?

**Comment by Mihai0909** [comment]
Hello, here is a screen shot of the page I'm automating: 
https://www.screencast.com/t/GsmiNpwK0k6

**Comment by MarinaRukavitsyna** [comment]
@Mihai0909,
In your scenario, I suggest you implement the following solution:
- Access the "Permalink" using [Selector](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/);
- Take the editor's [innerText](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/using-selectors.html#define-assertion-actual-value);
- Insert the obtained text into the [navigatoTo(innerText) ](https://devexpress.github.io/testcafe/documentation/test-api/actions/navigate.html)function.

**Comment by Mihai0909** [comment]
Thank you very much for your response. Works perfect now. We are going to migrate from Selenium Webdriver with Java to TestCafe. Keep up the good work and thanks for the prompt answers.
