### ISSUE TITLE
typeText() in WYSIWYG editor is different than a real user

### ISSUE THREAD

**Issue by alexschwantes** [DevExpress/testcafe#2675]
### Are you requesting a feature or reporting a bug?
Bug?

### What is the current behavior?
When using the typeText() method in a WYSIWYG editor, there are a couple unusual behaviours:
1. Spaces in the text are not actual spaces, they are instead \&nbsp; 
2. The resulting text is formatted differently than if you were to do it yourself. (see example below)

### What is the expected behavior?
With the test code below, if you perform the steps manually, the code in the editor appears as 
```
<p>The quick brown</p>
<p>fox jumps over</p>
<p>the lazy dog</p>
```

However with the script it actually appears as:
```
<p><br data-mce-bogus="1">The&nbsp;quick&nbsp;brown</p>
<p><br data-mce-bogus="1">fox&nbsp;jumps&nbsp;over</p>
<p><br data-mce-bogus="1">the&nbsp;lazy&nbsp;dog</p>
```
The ```<br data-mce-bogus="1">``` is something that tinymce appears to insert into blank paragraphs, eg. ```<p><br data-mce-bogus="1"></p>```, however as soon as a user starts typing something in the paragraph, it removes the ```<br data-mce-bogus="1">``` from the html. This is not happening when using the typeText() method in the test script below. 

### How would you reproduce the current behavior (if this is a bug)?
see test code below

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://www.tiny.cloud/

Test code

```js
test('type text into wysiwyg editor', async (t) => {
  await t.navigateTo('https://www.tiny.cloud/');
  await t.switchToIframe('#mce_0_ifr')
  await t.typeText('#tinymce', 'T');
  await t.pressKey('ctrl+a delete');

  await t.typeText('#tinymce', 'The quick brown');
  await t.pressKey('enter');
  await t.typeText('#tinymce', 'fox jumps over');
  await t.pressKey('enter');
  await t.typeText('#tinymce', 'the lazy dog');
  await t.debug();
});
```

### Specify your

* operating system: windows 10 & linux
* testcafe version: 0.20.5
* node.js version: v9.11.1

**Comment by RomeroDiver** [comment]
Hi,
is there any progress with this?

**Comment by AndreyBelym** [comment]
The problem is that browsers use sophisticated algorithms to determine how to represent space symbols typed in content editable elements in HTML code. E.g. a browser can use a non-breaking space or a regular space for a sequence of space symbols depending on its position in the line, the presence of hard-coded non-breaking spaces, the presence of empty lines and other factors. What's worse, different browsers use slightly different algorithms to solve this task.
 
It means we would need to invest a lot of time to solve it for different browsers and different platforms if we want to emulate browsers' behavior , or use browsers' automation protocols (Chrome debug protocol/Firefox Marionette protocol) to perform text typing.

**Comment by bartekmotyl** [comment]
As far as I can see in source code, all spaces are always (unconditionally) converted into non-breaking spaces when typing text into contenteditable: 
```
    text = text.replace(WHITE_SPACES_RE, String.fromCharCode(160));
```
Is this really still needed? I have checked three major browsers on macos (Chrome, Firefox and Safari) and none of them was inserting non-breaking spaces when typing text in [contenteditable container](https://jsfiddle.net/nvcmskdL/5/).

**Comment by joeldavuk** [comment]
Also experiencing this issue, would it be acceptable to have this as a configuration option? I could try raise a PR for that, assume we might need to keep this option for older browsers even if it no longer happens?

**Comment by AlexKamaev** [comment]
@joeldavuk

We would not like to add any additional option for this. We support only two latest browser versions. If the code above is unnecessary, it's better to just remove it. However, in order to do this, we really need to be sure that this change will not affect other users.

Could you please clarify if the issue occurs in Chrome v3.1.0?

**Comment by gorbeia** [comment]
Wildly replacing any white space by `nbsp` seems quite intrusive. In our case this makes our test fail for two reasons:

- we paste JSON code. Replacing normal spaces by `nbsp` makes the JSON invalid.
- we further check the inserted information. As the spaces are replaced, the output doesn't equal the inserted value.

I have removed the replacement from Testcafe and tested pasting or typing code in Codemirror on both Firefox and Chrome and both work fine without the replacement.

**Comment by PavelMor25** [comment]
Hello,

Unfortunately, we cannot take this enhancement into work, since currently we are fully focused on other tasks.
