### ISSUE TITLE
Timeout option does not work when expecting element to be .visible

### ISSUE THREAD

**Issue by dsayerjp** [DevExpress/testcafe#2682]
### Are you requesting a feature or reporting a bug?
Bug - We have an element that takes a long time to become visible. This has been deemed acceptable by the Business so we need to incorporate this into our automated tests and ensure there is no degredation. 

Currently, TestCafe doesn't respect the timeout set in the assertion option when asserting that the element is visible.

### Workaround

I have written a custom function that does both an exists and visible check:

```js
this.isVisible = async function(t, e, time = 3000) {
    await t
      .expect(e.exists)
      .ok(`${e} doesn't exist`, {timeout: time})
      .expect(element.visible)
      .ok(`${e} isn't visible`);
```

### What is the current behavior?

I have the following assertion in our code:

```js
        .expect(elements.availabilityIndicatorHeading.visible)
        .ok('availabilityIndicatorHeading not visible', {
          timeout: 10000
        })
```
Currently it waits for the default 3 seconds.

If I change the assertion to assert on whether the element exists, the timeout set in the option is honoured.

```js
        .expect(elements.availabilityIndicatorHeading.exists)
        .ok('availabilityIndicatorHeading not visible', {
          timeout: 10000
        })
```

### What is the expected behavior?

To wait for the time specified in the timeout option.

### How would you reproduce the current behavior (if this is a bug)?

- Set the overall test time out to 500ms
- Add the following assertion

```js
        .expect(elements.availabilityIndicatorHeading.visible)
        .ok('availabilityIndicatorHeading not visible', {
          timeout: 10000
        })
```
- Notice that it waits for the default timeout of 500ms

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: Backend administration page, unable to provide URL

Test code

```js
        .expect(elements.availabilityIndicatorHeading.visible)
        .ok('availabilityIndicatorHeading not visible', {
          timeout: 10000
        })
```

### Specify your

* operating system: MacOS v10.13.5
* testcafe version: 0.20.5
* node.js version: v8.11.1

**Comment by AndreyBelym** [comment]
Hi @dsayerjp! It happens likely due to https://github.com/DevExpress/testcafe/issues/2386.

It means when you try to assert the `visible` property of an element and the element doesn't appear on the page during the specified selector timeout, you'll get the `Cannot obtain information about the node because the specified selector does not match any node in the DOM tree` exception regardless of the configured assertion timeout, because assertion also will be interrupted by the exception.

You should try to configure  `availabilityIndicatorHeading`'s selector [timeout](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/selector-options.html#optionstimeout), or add an additional assertion that checks element's `exists` property, as in your workaround.
