### ISSUE TITLE
Screenshot is of the Windows 10 lockscreen and not the failed test

### ISSUE THREAD

**Issue by row1** [DevExpress/testcafe#2696]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
If the screenshot is taken while the PC is locked, then the screenshot will be of the Windows lockscreen.

### What is the expected behavior?
The screenshot should be of the failed test in the browser.

### How would you reproduce the current behavior (if this is a bug)?
1. Set Windows to lock the PC after 1 minute
2. Run a failing test that takes longer than a minute and that will take screenshots

### Specify your

* operating system: Windows 10
* testcafe version: 0.20.4
* node.js version: 8.9.4

**Comment by AndreyBelym** [comment]
Hi @row1! Because Windows doesn't provide a reliable API to take a screenshot of a specific window, so in general case TestCafe have to capture screenshot of the desktop and cut a image of the window from it. Of course if you lock you computer, you will get a screenshot of the lockscreen instead.

TestCafe uses this general approach for IE and Edge. Fortunately, Chrome and Firefox provide the possibility to capture screenshots of a browser window using their debug protocols, so the lockscreen shouldn't cause troubles with them.

**TL&DR**: If you experience this with IE and Edge, it's a Windows technical limitation, and I'm afraid you  have to disable your lockscreen. If it happens in Firefox or Chrome, it's a bug, so please provide me the TestCafe command that you used to run tests and the corresponding test report.

**Comment by row1** [comment]
Sorry, I should have mentioned that i have been using Chrome.

I see that v0.21.0 has just been released (thanks), so I will try upgrading to that first. I will also see if using headless Chrome makes a difference. Will report back next week.

Thanks

**Comment by row1** [comment]
You can close this. I have upgraded from 0.20.4 to 0.21.0 and it seems to be working fine now.

**Comment by AndreyBelym** [comment]
@row1, thanks for feedback!
