### ISSUE TITLE
Node shows warning 'Possible memory leak'  during run of few tests .

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe#271]
To reproduce this issue, run next steps:
1. Create TestCafe, a TestCafe runner instance and a browser connection.
2. Establish the browser connection (for example, open connection.url in the local browser or call method ``establish()`` )
3. Run chain 
```js
runner
    .src(...)
    .browsers(...)
    .run() 
 ```
at least 11 times (simultaneously or sequentially, it doesn't matter).

**Comment by inikulin** [comment]
This is because of default `EventEmitter` subscribers limit (see: https://nodejs.org/api/events.html#events_emitter_removelistener_event_listener). It's not a big deal to disable this warning. On the other hand, I wonder which emitter shows warning, because everything was designed to avoid big number of subscribers for the emitter. So this require investigation.

**Comment by georgiy-abbasov** [comment]
I'm working on this.

**Comment by AlexanderMoskovkin** [comment]
It seems the cause of the problem is [here](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-set.js#L35). We add a listener for both events (idle and closed) but just one is raised. So, maybe we should remove the second event listener when the first event is raised. @georgiy-abbasov is investigating this

**Comment by inikulin** [comment]
Need to `cancel` subscriptions once `race` is resolved (see: https://github.com/inikulin/promisify-event)

**Comment by AlexanderMoskovkin** [comment]
yes, we have a working solution yet. But we've found the same issue in the other place and will resolve it
