### ISSUE TITLE
Jumping button sometimes not Clickable

### ISSUE THREAD

**Issue by cor3000** [DevExpress/testcafe#2763]
### Are you requesting a feature or reporting a bug?

Bug (maybe Feature)

### What is the current behavior?

Clicking a button (which definitely exists on the page) fails when the button is moving or jumping.

(I could imagine that this could be an expected behavior correctly simulating human failure to click a button that jumps away exactly in that instant. However from a test case perspective it would be at least helpful to have an option to ensure the click if technically possible.)

### What is the expected behavior?

calling t.click(buttonThatExists) should generate an onClick event

### How would you reproduce the current behavior (if this is a bug)?

In practice that problem happened when trying to click a button on a page with dynamic content above the button (e.g. an image with a variable height displayed after a page update. Depending on the loading latency the height can jump at an upredictable time).
This causes non deterministic test failures even if the button exists in the DOM with a working onclick-event-listener.

#### Provide the test code and the tested page URL (if applicable)

To simulate/simplify this scenario I reduced it to a simple div, that changes height randomly based on setInterval(). The clickable buttons are placed below the div so that they visually jump around while always being present in the DOM.

Now when running a test trying to click either button it arbitrarily succeeds or fails. Of course this case is an exaggerated scenario hopefully isolating this from the real life case where network/render latency might cause such a problem only under rare circumstances, making it even harder to debug/fix test cases - eventually having to compensate every click that might fail due to a similar behavior.

Tested page URL:

https://jsfiddle.net/0pws3a9z/1/

Test code

```js
import {Selector} from 'testcafe';
fixture `click-test`.page `https://jsfiddle.net/0pws3a9z/1/`;

const switchToA = Selector('#switchToA');
const switchToB = Selector('#switchToB');
const pageTitle = Selector('h1');

const hasPageTitle = title => pageTitle.withText(title).exists;

test('problem clicking jumpy button', async t => {
    //just try often enough to cause the problem
    await t.switchToIframe('[name=result]');

    for(var i = 0; i < 10; i++) {
        await t
            .click(switchToA)
            .expect(hasPageTitle('Title A')).ok() //might fail here due to lost click in previous line
            .click(switchToB)
            .expect(hasPageTitle('Title B')).ok() //might fail here due to lost click in previous line
    }
});
```

### Specify your

* operating system: Windows 10 Home Edition (64bit)
* testcafe version: 0.21.1
* node.js version: v8.5.0
* browsers: Chrome( 68.0.3440.106)/Firefox(61.0.2 (64-bit)/IE11/edge(42.17134.1.0)

**Comment by AlexKamaev** [comment]
Please accept my apologies for the delayed response.
 
As you correctly noticed, it is difficult for a user to click a moving button. In the same manner, TestCafe can click only a visible and not moving element (i.e., when an element does not change its position) since it emulates user behavior.
 
In your example, the button is constantly moving and TestCafe cannot determine where and when the button is moving. As a workaround, you can determine the reason why the button (or any other element) is moving. For instance, if it is moving due to the preceding element appearance, you can wait until that element appears as follows:

```JS
await t.expect(Selector("#element").visible).ok())
```
If the preceding element changes its height (as in your example), you can use the [ClientFunctions](http://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client.html) function to fix its height by adding some CSS styles:

```JS
const fixHeight = ClientFunction(() => { document.getElementById('#el').className = 'fixedHeight' });
```
```CSS
#fixedHeight {
    height: 100px!important;
}
```
In addition, I'd like to mention that when the target element is moving, TestCafe will make another attempt to click it during the `selectorTimeout` period of time. If you increase this timeout value, there's a greater chance that TestCafe will click the moving element.

**Comment by AlexKamaev** [comment]
Thanks for your feedback. I understand that click behavior can be confusing so I've created a separate ticket with a sample example #2930. We'll consider how we can improve this behavior in the context of that issue.
