### ISSUE TITLE
Allow to use test and fixture names inside hooks and test bodies

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2826]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
You can't access current test and fixture name from the test code.

### What is the expected behavior?
Current test and fixture name can be retrieved by the code running in before/after hooks and the test body function.

**Comment by jiteshsojitra** [comment]
Reference: https://github.com/DevExpress/testcafe/issues/2823

**Comment by sophiecdd** [comment]
Just curious do we have a timeline for this feature?

**Comment by LavrovArtem** [comment]
Any personal estimate may be misleading, so I cannot currently tell you the precise date. Once we get any results, I assure you that we will notify you.

**Comment by icfantv** [comment]
Hi, any update on this?  We're doing image snapshot testing in TC and currently this is limiting us to one snapshot test per file since we're using the test file name to name the snapshot image files.  The workaround of using a wrapper function is just not going to scale effectively, though, we could create a utility function that does it implicitly...

At face value, this appears to be a trivial feature.  I'm happy to look into this and submit a PR if you guys can point me in the right direction.

**Comment by icfantv** [comment]
I should point out that I've seen the command line pattern option, `-p`, and I 1) I don't feel this is necessarily the right way to be doing this, but more importantly, 2) we're generating a baseline image (one that ends in `-baseline.png` if one doesn't yet exist and a snapshot image (one that ends in `-snapshot.png` if it does so we can compare/diff the two images.

Even if we used the `-p` flag, there's no way for us to test for the existence of the baseline image file without knowing the test name in the test.

If you can see a way around this, I'm open to suggestions.

**Comment by devmondo** [comment]
you can certainly get the fixture and test name in code, but it is not in the API typings

you can do it like this:

```js
fixture `Fixture 1`
    .page `https://google.com`;

test('Test 1', async t => {
    console.log(t.testRun.test.name);
    console.log(t.testRun.test.testFile.currentFixture.name);
  });
```

we do it to also use the name in logging, screenshots, etc...

also, you are not limited to the runner screenshot, you can use `t.takeScreenshot` to take a screenshot at any given time, we do that to use it with allure reporting.

hope this helps :)

**Comment by icfantv** [comment]
@devmondo we are using `t.takeScreenshot` and specifying the image path.  but your solution is perfect and should work accordingly.  thanks!

would you like me to update the typings or is this an "unpublished" API and thus, fragile?

**Comment by devmondo** [comment]
@icfantv, glad it helped :) 

i am not part of the testcafe team, and I think this is not intended for public API, which makes sense because it has soo much info about the whole process. 

but I think it is really a good idea if the testcafe team can expose a meta-object on the test and fixture api to get this sort of info, something like `t.info` or `t.metaInfo`.

**Comment by icfantv** [comment]
@devmondo did you happen to get your example working in typescript without jumping through all kinds of hoops?

**Comment by devmondo** [comment]
@icfantv 	

basically you have to add custom typing to your project, something like 
```js

declare global {
    interface TestController {
        testRun: {
            name: string;
        };
    }
}
```
https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by xorxero** [comment]
why is this not a thing? this is basic functionality. we can selectively run beforeEach logic or only a subet of the beforeEach logic based on test name...

the meta we assign to the test should also be available through the test controller in the before each hook.

**Comment by miherlosev** [comment]
Hi @xorxero

Thank you for sharing your test cases. We will take them into account when designing an API for this feature.

**Comment by jasongornall** [comment]
bumping could really use this
