### ISSUE TITLE
Make scrolling speed configurable by changing  the `speed` option

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2837]
### Are you requesting a feature or reporting a bug?
Feature

### What is the current behavior?
When a mouse action (`t.hover`, `t.click`, etc.) is executed, page is scrolled with the maximum possible speed, without taking in account the [Test Speed Option](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#setting-test-speed).

### What is the expected behavior?
Scrolling should have different speed for different `speed` values.

**Comment by andrzej-kodify** [comment]
Hi @AndreyBelym. Since AFAIK testcafe doesn't offer scroll method right now I see now way to simulate real user scroll to element (other than writing client function) and it is vital for my use case.

On the page I'm testing there are blurred placeholders and full size images (along with some client side behaviour like on hover) get loaded and enabled only when image gets shown in viewport (mostly to save bandwith and don't load images that are not presented to end user).

So in my test I want to make sure that when e.g. user scrolls to last image on page all the other images are loaded as well.

Also in my opinion the purpose of a framework like testcafe is to simulate user actions as close to real actions as possible. I never saw a user who can scroll through page without going through all elements in between start and end of scrolling. Unless we consider e.g. anchor or page reload when browser actually can jump directly to some place on page but that's different scenario.
