### ISSUE TITLE
Cannot save screenshots on mobile tests

### ISSUE THREAD

**Issue by hex0cter** [DevExpress/testcafe#2878]
### Are you requesting a feature or reporting a bug?

Bug

### What is the current behavior?
When testing on iPhone, `.takeElementScreenshot` doesn't not work. Here is the error:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/daniel.han/tmp/testcafe-boilerplate/duckduckgo-screenshots.png'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.oncomplete (fs.js:139:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What is the expected behavior?
Taking screenshots should work the same way as desktop browsers.

### How would you reproduce the current behavior (if this is a bug)?
Run any test on iPhone 7, iOS 12 with mobile safari.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://github.com/hex0cter/testcafe-boilerplate

Test code

https://github.com/hex0cter/testcafe-boilerplate/blob/master/tests/test-duckduckgo-search.js

### Specify your

* operating system:
iOS 12
* testcafe version:
0.21.1
* node.js version:
v10.8.0

**Comment by AndreyBelym** [comment]
Unfortunately I can't reproduce the issue, I've cloned the repository, and TestCafe has taken the screenshot. Could you please specify your OS version and provide me the full test report?

**Comment by AndreyBelym** [comment]
Thanks, I thought that the problem was in the BrowserStack configuration. I've reproduced the problem.

Unfortunately, you can't use window manipulation functionality (`t.takeScreenshot`, `t.takeElementScreenshot`, `t.resizeWindow`) in remote browsers. We should note this in documentation. 

But TestCafe must emit a warning in this case and terminate gracefully instead of completely crashing the process. So it's a bug, and I need some time to investigate its reason.

**Comment by hex0cter** [comment]
Hi,

The repo does have browserstack as one of its dependencies, but for this test it is not used at all. Why do you think the problem was in the browserstack configuration?

And what do you mean by `remote browsers`?

Best Regards,
Daniel Han

**Comment by AndreyBelym** [comment]
Never mind, I mean I tried to run tests using the BrowserStack configuration, because you've specified iPhone as the target, and configuration's name is `test:browserstack:iphone`. 

[Remote browsers](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#remote-browsers) are browsers that you connect using the `testcafe remote ...` command. TestCafe can't take screenshots in this case, because in this case it can use only HTML APIs, that don't have reliable methods for taking screenshots.

**Comment by hex0cter** [comment]
Thanks for the clarification Andrey!
