### ISSUE TITLE
Skip fixtures according to a service response

### ISSUE THREAD

**Issue by Lupiano** [DevExpress/testcafe#2903]
### Are you requesting a feature or reporting a bug?
I think is neither of both. Probably it is a language limitation.

### What is the current behavior?
I have the following configuration:

```
let fixtureFn= fixture('FixtureName').page('http://testPage');

(async () =>
await loadFixture(params,fixtureFn); )()

test('TestName', async t => {
		await t.click('body');
});
```

### What is the expected behavior?
Inside "loadFixture" function, there is a call to a service, which response is used to define whether the fixture is skipped or not. The problem is that the execution continues to read the "test" before the response is made, as if the "await" wasn't there. I know probably it is not a testcafe problem, but any ideas? Thanks!

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* operating system:
* testcafe version:
* node.js version:

**Comment by AlexKamaev** [comment]
I think the easiest way to solve the issue is to[ create testcafe](http://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/createtestcafe) instance in your code and set the [runner object](http://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html) in your own manner. I prepared a sample example to demonstrate this approach:
```JS
const createTestCafe = require('testcafe');
let testcafe         = null;

const fixtureFilter = fixturePath => {
    return fixturePath === 'test2.js';
}

const fixturePaths = ['test1.js', 'test2.js'];
const fixtures = fixturePaths.filter(fixtureFilter).map(path => `./tests/${path}`);


createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        testcafe     = tc;
        const runner = testcafe.createRunner();

        return runner
            .src(fixtures)
            .browsers(['chrome'])
            .run();
    })
    .then(() => {
        testcafe.close();
    });
```
Here I filter out all fixtures which do not have a path equal to 'test2'. You can modify this logic and make a request to your service.

**Comment by Lupiano** [comment]
@AlexKamaev, yes that opens us a lot of possibilities. We will have to think a big refactoring. Thanks a lot for your time!
