### ISSUE TITLE
t.takeElementScreenshots can't detect page area in some cases

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#2918]
### Are you requesting a feature or reporting a bug?
Bug

### What is the current behavior?
The `t.takeElementScreenshot` action fails to crop the taken screenshot to the specified element's dimensions, and displays the `Can't detect page area ...` warning.

It can happen because of

- non-integer ratio between physical and love pixel sizes on HighDPI

- screen color correction that leads to changes in intensities of black and white colors

- slow rendering on low-power machines and VMs

### What is the expected behavior?
Page area detection mechanism must be improved to get more reliable results.

**Comment by htho** [comment]
I have this problem with Firefox on Android where the screenshots are taken through adb.
See my stackoverflow post on this topic: https://stackoverflow.com/questions/55412931/testcafe-screenshot-browser-provider-for-android-crop-js-unable-to-locate-the/55456765#55456765

The black marks are rendered as #010101 instead of #000.

My first Idea was to accept a threshold in [crop.js:20](https://github.com/DevExpress/testcafe/blob/8ec5a8623c8222a943c850a4456d5062d089efca/src/screenshots/crop.js#L20). This would require a completely different implementation, where each pixel is checked if it is in a certain range. I think this might become slow and hard to read.

My second idea is to transform the screenshot instead. Each pixel in the screenshot is checked if its color is darker than - lets say #0f0f0f. Then the pixels color is set to #000 otherwise it is set to #fff.

I think I can implement that approach.

**Comment by htho** [comment]
I implemented this approach.
https://github.com/htho/testcafe/commit/26c83d582940fb6b0995a21b39dddcd9f0baf7bb

Please tell me how I can improve it. I will follow the contribution guidelines then.

**Comment by Farfurix** [comment]
@htho.

Hello.

Thank you for your implementation, the approach looks good. Please submit your changes as a Pull Request to this repository. We will review it.

**Comment by htho** [comment]
I added a [Pull-Request](https://github.com/DevExpress/testcafe/pull/3651). But I don't know how to write a Test for this specific case.
