### ISSUE TITLE
tests execution pauses when browser window is not visible

### ISSUE THREAD

**Issue by mkubrycz** [DevExpress/testcafe#2939]
### Are you requesting a feature or reporting a bug?

Reporting a bug.

### What is the current behavior?

when running multiple tests and window of the browser is behind any other window, tests execution pauses. When I move browser window with tests back to the front, tests execution resumes.

### What is the expected behavior?

Tests shouldn't pause once started

### How would you reproduce the current behavior (if this is a bug)?

run tests set with multiple cases, wait for the browser window to open, change to some other window so it's in front of browser with running testcafe, see that tests no longer pass in the terminal

### Specify your

* browser:  Chrome 69.0.3497
* operating system: Mac OS X 10.13.6
* testcafe version: v0.22.1-alpha.3
* node.js version: v6.9.5

**Comment by AlexKamaev** [comment]
I've reproduced the issue

**Comment by AndreyBelym** [comment]
It can be related to the [App Nap mode](https://apple.stackexchange.com/questions/153838/os-x-yosemite-suspends-inactive-windows).

**Comment by Juansasa** [comment]
This is most likely due how power management is handled by OSX.
By default it will freeze background apps from running so this is expected.
[https://enduranceapp.com/](OSX Endurance)

**Comment by AlexKamaev** [comment]
The issue is related to Сhrome background tab behavior optimization. Please refer to the following article: https://developers.google.com/web/updates/2017/03/background_tabs. You can use the `--disable-background-timer-throttling` command line argument to prevent this behavior. So, your CLI command will look like `testcafe "chrome:`--disable-background-timer-throttling" test.js`
