### ISSUE TITLE
[docs] Selectors - When they select many elements and when they return only one

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#3007]
Now, in most places, we say that selectors select **all** the matching elements. This is true, but there are many cases when only the first element is used. We need to highlight it better.

- [ ] Elevate info that if you perform an action with, or get a property value or a snapshot from a selector that matches multiple elements, only the first element will be used. Probably, copy this info to the `Selectors` root topic.
- [ ] Actions topic - say that actions are performed with the first element selected by the selector.
- [ ] Add a link from the `nth` section to the info mentioned above to show that it's not necessary to use `nth(0)` in actions.

More suggestions on this topic are welcome @kirovboris @helen-dikareva @AndreyBelym.

**Comment by helen-dikareva** [comment]
I could find information about using selectors in actions on `Using Selectors` page in section [`Define Action Targets`](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/using-selectors.html#define-action-targets) section on the last line.
Although there is no required info about getting selector property in [`Obtain Element State` ](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/using-selectors.html#obtain-element-state).  This info in [`Examples` on different page](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.html#examples).
Also our `Selector` has different type of properties: all of them will be executed for the first element in the set but `count` and `exists` (!) work different way. We have this info [here](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/using-selectors.html#check-if-an-element-exists).

So I think [`Using Selectors`](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/using-selectors.html) is a good place to describe how selectors could be used and how they will work in different case. After that we will be able to give a link to this section in all required sections (actions, assertions, `nth` filter, etc.).

And I'm not sure about `Selector Timeout` section here, because we have separate `Selector Options`, maybe we could give a link here and move all info there.

**Comment by titerman** [comment]
Closed because https://github.com/DevExpress/testcafe/issues/1760 is wider in scope.
