### ISSUE TITLE
Tests Passed Count vs Run Mismatch

### ISSUE THREAD

**Issue by austinrr** [DevExpress/testcafe#3010]
I'm trying to get a basic test navigates to a URL to run on multiple browsers in SauceLabs, which appears to be working, I can see two SauceLabs VMs start and navigate to the URL, but the output from TestCafe only reports 1 passing test and 0 failed, see output below.

```
browsers: [ 'saucelabs:chrome', 'saucelabs:firefox' ]
 Running tests in:
 - Chrome 69.0.3497 / Windows 7.0.0 (https://saucelabs.com/tests/<redacted>)
 - Firefox 62.0.0 / Windows 7.0.0 (https://saucelabs.com/tests/<redacted>)

 My Fixture
 √ Navigate to Login Page


 1 passed (10s)
Tests failed: 0
TypeError: Cannot read property 'close' of null
    at createTestCafe.then.then (C:\Repositories\TestCafe-Exp\packages\browser\src\index.ts:82:22)
    at <anonymous>
```

Here's the runner I'm using:
```
let testcafe: any = null;
console.log('browsers:', browsers)

    createTestCafe()
        .then((tc: any) => {
            let testcafe = tc;
            const runner = testcafe.createRunner();

            return runner
                .browsers(browsers)
                .src('./dist/tests/test.js')
                .run()
        })
        .then((failed: any) => {
            console.warn('Tests failed: ' + failed);
            testcafe.close();
        })
        .catch((error: any) => {
            console.error(error);
            process.exit(1);
        });
```

**Comment by AlexKamaev** [comment]
This behavior is expected. This means that the test is passed in both browsers.

**Comment by austinrr** [comment]
@AlexKamaev  maybe for an enhancement it would be nice to get a count of the number of times the single tests passed.  So for example if I ran it with a concurrency of 2 on 3 browsers I could see that my test passed 6 times.

**Comment by AlexKamaev** [comment]
We consider that the test is passed if it is passed in all browsers at once. If it fails in at least one browse,r then the test is considered as failed. In this case, you'll see a message that the test failed in a specific browser. I think it's enough for most cases. However, you can try to create your own reporter. Please refer the following article http://devexpress.github.io/testcafe/documentation/extending-testcafe/reporter-plugin/
 
In addition, I have to explain about concurrency. If we have 1 test, 3 browsers and -concurrency options equal to 2 that means that tests will execute 3 times, not 6, because concurrency is intended for parallel test execution, but not for increasing the test execution count.
