### ISSUE TITLE
TestCafe performance issues - Slow page loads, High CPU usage, Browser disconnect issues etc. 

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#3055]
### What is your Test Scenario?

Download the provided test repo and execute the tests. The test scripts basically checks the functionality of the given website.
 I'm currently in the process of migrating our projects Selenium tests into TestCafe and I'm halfway through the process. When I tried to execute the migrated tests in different browsers (both on Mac & Win), I noticed several issues as mentioned below.  

### What is the Current behavior?

 
Multiple Issues:
1 - The page is **very slow to load** when run via TestCafe. If I manually load the page in the browser (with cache & cookie cleared), the page loads reasonably fast. So I'm not sure what's causing the page to load slow inside the TestCafe server. Try to run the tests in Firefox (on Mac or Win) and you can easily observe this issue. We have longer test execution time because of this issue.
2 - The **CPU usage also goes 100%** ('Google Chrome Helper' & 'FirefoxCP Web Content' processes) when executing the test suite in Chrome & Firefox on Mac. You can hear loud fan noice  when this happens. (see screenshot below)
3 - Test scripts keep failing in Firefox (on Mac & Win) & Edge on Win. I'm unable to execute the test suite. I keep getting the **browser disconnected** error. (see screenshot below)
4 - Also test execution fails in Chrome on Windows. Getting '**write ECONNABORTED**' in console (see screenshot below)

### What is the Expected behavior?

None of the above issues should happen.
 
### What is your web application and your TestCafe test code?

 
Download this repo - https://github.com/sijosyn/testcafe-syntests and run the test suite.

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
Above provided repo contains all the test code.
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

-----
Firefox browser disconnect error:

<img width="1083" alt="screen shot 2018-10-30 at 10 13 14 am" src="https://user-images.githubusercontent.com/29459281/47756415-5086d500-dc78-11e8-8f75-11fdf78c6a91.png">

-----
Chrome disconnect error (on Win):

<img width="952" alt="screen shot 2018-10-30 at 8 08 00 pm" src="https://user-images.githubusercontent.com/29459281/47758126-030e6600-dc80-11e8-9d1f-5444e4ff6748.png">

-----
Edge browser disconnect error

<img width="986" alt="screen shot 2018-10-30 at 9 25 48 pm" src="https://user-images.githubusercontent.com/29459281/47760448-b3816780-dc8a-11e8-995b-faa081b258bb.png">

-----

<img width="792" alt="screen shot 2018-10-30 at 7 30 21 pm" src="https://user-images.githubusercontent.com/29459281/47756945-70b79380-dc7a-11e8-8d2b-2668d90e6926.png">

-----
<img width="783" alt="screen shot 2018-10-30 at 7 55 49 pm" src="https://user-images.githubusercontent.com/29459281/47757705-f721a480-dc7d-11e8-821b-f33245d7ca45.png">

</details>

### Steps to Reproduce:

Please read the README provided in the repo - https://github.com/sijosyn/testcafe-syntests
 
### Your Environment details:
 
* testcafe version:   0.23.0                
* node.js version:  8.9.4                  
* command-line arguments:  testcafe firefox desktop -e 
* browser name and version:  Firefox 63, Safari 12, Chrome 70, Edge 17 
* platform and version:    macOS 10.13, Win 10      
* other:

**Comment by miherlosev** [comment]
> The page is very slow to load when run via TestCafe. 

We will investigate it more deeply. I will notify you of our results later.

> The CPU usage also goes 100% 

I cannot reproduce this behavior. On my machine I have CPU usage about 60 %. Google Chrome takes about 20%. It's a normal behavior because TestCafe emulates user actions very fast.

> Test scripts keep failing in Firefox (on Mac & Win) & Edge on Win

I cannot reproduce it.
![image](https://user-images.githubusercontent.com/4133518/47775584-1b729500-dd01-11e8-9a09-6fcd393bf433.png)
![image](https://user-images.githubusercontent.com/4133518/47775593-2299a300-dd01-11e8-8fc1-5a62402b9221.png)

>Also test execution fails in Chrome on Windows. Getting 'write ECONNABORTED' in a console (see screenshot below)

There is a separate issue for this - https://github.com/DevExpress/testcafe-hammerhead/issues/1744.
We will fix it during the [current development sprint](https://github.com/DevExpress/testcafe-hammerhead/milestone/27).

**Comment by sijosyn** [comment]
@miherlosev Thanks for your prompt response and investigating this issue. 

> I cannot reproduce this behavior. On my machine I have CPU usage about 60 %. Google Chrome takes about 20%. It's a normal behavior because TestCafe emulates user actions very fast.

I've observed the CPU usage goes up while its waiting to finish loading the page and before it starts to interact on the page. This issue happens on Mac for me. Could you please check this issue on Mac if possible?. My system info is provided below. 

<img width="249" alt="screen shot 2018-10-31 at 9 36 11 am" src="https://user-images.githubusercontent.com/29459281/47791607-7223a300-dcf0-11e8-862c-b7328a3556b9.png">

> Test scripts keep failing in Firefox (on Mac & Win) & Edge on Win

If possible, could you please try to run the test suite in following browser & OS combination and see if you can reproduce the browser disconnect issue: 
Firefox 63.0.0 / Mac OS X 10.13.0
Firefox 63.0.0 / Win 10.0.0
Edge 16.16299 / Win 10.0.0

I would like to see the 'Browser disconnect' issue resolved as its one of the top annoying issue for me. Its been around for a while for now and haven't been addressed yet. I understand its hard to reproduce the browser disconnect issue but please see if the team can find the root cause of this issue and fix it.

**Comment by lukastaegert** [comment]
Did some more testing: I only observe this when testing on localhost where I used webpack dev server to serve my page. Remote pages seem to be fast.

**Comment by ZeddEn** [comment]
I started having this problem starting from version 0.22.0 (now using 0.23.1). Before it used to hang the build for hours but with a fix introduced on the 0.22.0 now, it just disconnects the browser(s). This may be strongly linked to running tests on multi-browsers (chrome & firefox).

I am using TeamCity to run the builds with the following configuration:

- UserAgents: Chrome 70.0.3538 / Windows 10.0.0,Firefox 61.0.0 / Windows 10.0.0
- Testcafe version: 0.23.1
- Node version: 8.11.3

There is the error message I get on my CI output:

`
[12:16:00][Step 4/6] Error: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
[12:16:00][Step 4/6]     at C:\BuildAgent\work\4a74606c58d6f60f\node_modules\testcafe\src\runner\browser-set.js:84:30
[12:16:00][Step 4/6]     at next (native)
[12:16:00][Step 4/6]     at step (C:\BuildAgent\work\4a74606c58d6f60f\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
[12:16:00][Step 4/6]     at C:\BuildAgent\work\4a74606c58d6f60f\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
[12:16:00][Step 4/6]     at Promise.F (C:\BuildAgent\work\4a74606c58d6f60f\node_modules\core-js\library\modules\_export.js:36:28)
[12:16:00][Step 4/6]     at C:\BuildAgent\work\4a74606c58d6f60f\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12
[12:16:00][Step 4/6]     at BrowserSet._waitConnectionsOpened (C:\BuildAgent\work\4a74606c58d6f60f\node_modules\testcafe\src\runner\browser-set.js:77:37)
[12:16:00][Step 4/6]     at _waitConnectionsOpened (C:\BuildAgent\work\4a74606c58d6f60f\node_modules\testcafe\src\runner\browser-set.js:107:35)
[12:16:00][Step 4/6]     at invokeCallback (C:\BuildAgent\work\4a74606c58d6f60f\node_modules\pinkie\index.js:60:12)
[12:16:00][Step 4/6]     at Array.forEach (native)
`
I am also using this on my runner:
`.then(failedCount => {
		console.log('Tests failed: ' + failedCount);
		testcafe.close();
		process.exit(failedCount ? 1 : 0);
	}
`

**Comment by miherlosev** [comment]
@sijosyn 
> Also test execution fails in Chrome on Windows. Getting 'write ECONNABORTED' in a console (see screenshot below)

We've fixed this problem in `testcafe@0.23.1`. Try to run your tests with this version and let us know if the other issues from your list above are reproduced. 

@lukastaegert 
> A simple hello world test took 1m 19s where most of this time was spent navigating to the initial page.

It's a very strange. Could you please provide a simple example so that we will reproduce it on our side?

**Comment by lukastaegert** [comment]
Admittedly only the test was "Hello World", the application under test was not. So I tried to create another repo using generic code but was not able to. In my original project I managed to track it down to my usage of @material-ui/icons. Once I removed the single used icon, Safari was immediately fast. So I set up a new project just using this icon but this was fast as well.
One difference was, though, that the new project was a create-react-app JavaScript project while the original one was a TypeScript project. Not sure how long I will try to find a simple reproduction. As for me, as I can live without those icons I am fine, so you may just take this as a hint that there may be something fishy going on. Especially considering that the slowness was 100% reproducible and 100% linked to the import (but usage! The component in question was never displayed in the initial view) of these icons at least in a TS setup and that it only occurred on Safari.

**Comment by sijosyn** [comment]
@miherlosev 

> We've fixed this problem in `testcafe@0.23.1`. Try to run your tests with this version and let us know if the other issues from your list above are reproduced.

The 'write ECONNABORTED' issue is resolved in testcafe@0.23.1. However, the other performance issues I reported (Slow page loads, High CPU usage, Browser disconnect issues) still exists in testcafe@0.23.1.

**Comment by sijosyn** [comment]
Issue is too old now and can't reproduce. Closing.
