### ISSUE TITLE
Cuncurrent test window stuck

### ISSUE THREAD

**Issue by Juansasa** [DevExpress/testcafe#3076]
### What is your Test Scenario?

 Run tests concurrently in 2 separate chrome browsers
### What is the Current behavior?

 Sometime when a test failed the browser stuck and wont continue
### What is the Expected behavior?

 Should fail and keep running the next test
### What is your web application and your TestCafe test code?
Chrome: v69.0.3497.100 (Official Build) (64-bit)
MacOs: 10.14
Testcafe: v0.23.0

**Comment by AlexKamaev** [comment]
Judging by your description, it is difficult to determine the cause of the issue. Could you please provide me with a simple project and your test files to demonstrate it?

**Comment by Juansasa** [comment]
This is not possible and it occurs randomly so its quite hard. But i suspect is somehow related to #3064 and #3070

**Comment by miherlosev** [comment]
Thank you for your clarification. However, the information you provided is insufficient for us to determine the cause of the issue and find a precise solution. Feel free to reactivate this issue when you get a chance to provide us with an example where we can see the issue in action and find a suitable solution, if any.

**Comment by anandbkrishnamohan** [comment]
I have the same issue. On concurrent or normal execution, some of the tests (passed/failed) are stuck in the browser and because of that, the execution is halted. Usually, it starts with one test and then all of the browsers get stuck. The issue is there for chrome, chrome: headless, firefox and safari browser. Replicated the issue in 0.23.0, 0.23.1. and 0.23.2 versions. All my tests work perfectly in 0.22.0 version. 

**Environment details**
Node:  8.11.3
Application use React and React native
OS: MacOS 10.14.2
Chrome: Version 71.0.3578.80 (Official Build) (64-bit)

My test suit has around 80 tests and usually I run against 4 concurrent browsers. All the tests pass in 0.22.0 version and take around 5 minutes.

I won't be able to share my application details and not exactly sure what triggers this issue.

**Comment by miherlosev** [comment]
#3064 and #3070 issues, mentioned by @Juansasa, were fixed in `testcafe@0.23.3-alpha.2`.

Try running your tests with this version.

If the problem persists, we won’t be able to do much until we reproduce it locally.

**Comment by anandbkrishnamohan** [comment]
> #3064 and #3070 issues, mentioned by @Juansasa, were fixed in `testcafe@0.23.3-alpha.2`.
> 
> Try running your tests with this version.
> 
> If the problem persists, we won’t be able to do much until we reproduce it locally.

Thanks, @miherlosev !! All my tests ran without any issues.

**Comment by anandbkrishnamohan** [comment]
Do you know by when 0.23.3 final will be released?
