### ISSUE TITLE
Browser hangs / disconnect when running testcafe with reporters on Team City

### ISSUE THREAD

**Issue by hconceicao** [DevExpress/testcafe#3102]
### What is your Test Scenario?

Running a smoke test on our web (react based) app 
 
### What is the Current behavior?

 If we attach a reporter to the test runner, it hangs/disconnects
 
### What is the Expected behavior?

To have the same behavior of when an report is not attached
  
### What is your web application and your TestCafe test code?
Can't disclose atm.

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 

[controllers.txt](https://github.com/DevExpress/testcafe/files/2567403/controllers.txt)
[smoke_test.txt](https://github.com/DevExpress/testcafe/files/2567404/smoke_test.txt)

```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

[17:23:06][Step 1/2] Using locally installed version of TestCafe.
[17:23:11][Step 1/2] The following message is send to slack: 
[17:23:11][Step 1/2]  Starting testcafe Fri Nov 09 2018 17:23:11 GMT+0000 (UTC). 
[17:23:11][Step 1/2]  Running tests in: Firefox 63.0.0 / Ubuntu 0.0.0
[17:25:30][Step 1/2] ERROR The Firefox 63.0.0 / Ubuntu 0.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
[17:25:30][Step 1/2] 
[17:25:30][Step 1/2] Type "testcafe -h" for help.
[17:25:32][Step 1/2] Process exited with code 1

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:  0.23.1                 
* node.js version:  v8.12.0                  
* command-line arguments:  
testcafe "firefox:headless" src/smoke_test.js --dev --env=staging --reporter xunit 
* browser name and version: Firefox 63.0.0 
* platform and version: Ubuntu 16.04.3 LTS          
* other: TeamCity Professional 2017.2.4        running on docker

**Comment by AndreyBelym** [comment]
Unfortunately, I can't reproduce the issue. Because you can't disclose your primary site, could you please provide an example with some other site that can be used to reproduce the problem?

The "Browser disconnected" error means that the browser can't send any request to the TestCafe server, and likely it's not related to the `--reporter` option. Likely it's an effect of the resource-limited Docker container environment.

Have you tried the steps described in the [Testing Heavy Websites](https://devexpress.github.io/testcafe/documentation/using-testcafe/using-testcafe-docker-image.html#testing-heavy-websites) topic? I also suggest you start the browser from the container and perform test actions manually. You may need to configure [X11](https://github.com/chanezon/docker-tips/tree/master/x11) in your container to use the browser's GUI from the container.

**Comment by machbohu** [comment]
Seems like I can reproduce similar problem by myself. For me a test run always hangs (see below).

TestCafe version 0.23.2

I have one fixture like this (in directory "bug2"):
```
require("nice-console")(console);

fixture('Fixture 1')
    .page(`${process.env.SUT_ADDRESS}/qm`)
    .beforeEach(async ctx => {
        console.log('BEFORE EACH');
    })
    .afterEach(async ctx => {
        console.log('AFTER EACH 1');
        await new Promise(resolve => setTimeout(resolve, 120000));
        console.log('AFTER EACH 2');
    })
    .after(async ctx => {
        console.log('AFTER');
    });

test('Test 1', async t => {
    console.log('TEST 1');
});

test('Test 2', async t => {
    console.log('TEST 2');
});

test('Test 3', async t => {
    console.log('TEST 3');
});
```
running TestCafe like
```
node node_modules/testcafe/bin/testcafe.js -e 'chrome' bug2 --selector-timeout 30000 --assertion-timeout 10000  -r spec,xunit:test_results/e2e-xunit.xml -s test_results
 Running tests in:
 - Chrome 70.0.3538 / Linux 0.0.0

 Fixture 1
2018-11-26T14:54:30.822Z BEFORE EACH
2018-11-26T14:54:30.824Z TEST 1
2018-11-26T14:54:30.825Z AFTER EACH 1
2018-11-26T14:56:30.826Z AFTER EACH 2
^C2018-11-26T14:58:36.800Z Stopping TestCafe...
```
Seems that I can't reproduce this problem with TestCafe version 0.22.0
```
node node_modules/testcafe/bin/testcafe.js -e 'chrome' bug2 --selector-timeout 30000 --assertion-timeout 10000  -r spec,xunit:test_results/e2e-xunit.xml -s test_results
 Running tests in:
 - Chrome 70.0.3538 / Linux 0.0.0

 Fixture 1
2018-11-26T15:01:39.497Z BEFORE EACH
2018-11-26T15:01:39.499Z TEST 1
2018-11-26T15:01:39.500Z AFTER EACH 1
2018-11-26T15:03:39.500Z AFTER EACH 2
 ✓ Test 1
2018-11-26T15:03:39.525Z BEFORE EACH
2018-11-26T15:03:39.526Z TEST 2
2018-11-26T15:03:39.527Z AFTER EACH 1
2018-11-26T15:05:39.529Z AFTER EACH 2
 ✓ Test 2
2018-11-26T15:05:42.815Z BEFORE EACH
2018-11-26T15:05:42.816Z TEST 3
2018-11-26T15:05:42.816Z AFTER EACH 1
2018-11-26T15:07:42.817Z AFTER EACH 2
2018-11-26T15:07:45.813Z AFTER
 ✓ Test 3


 3 passed (6m 06s)
```

Once I remove that wait it runs as expected even for 0.23.2 version.

**Comment by machbohu** [comment]
Srsly? No response? I provided easy to reproduce example. If it is not related (which I don't know) then you could let me know and I can create separate issue for it or you can just tell me that "you don't care".

**Comment by AndreyBelym** [comment]
@machbohu, it seems that the 'No Response` bot will prevent closing the issue only if the issue creator posts a message. 

It's always a good idea to start a new issue, especially if you see the `STATE: Need clarification` label. It means that there is not enough information to determine what caused the issue, so no one can be sure that the problem you want to report is covered by the issue with this label.

Your test works fine on my machine with `testcafe@0.23.3-alpha.4`. I guess the problem can be similar to  issue #3070 that has been fixed in this version. Please try to use `testcafe@0.23.3-alpha.4` on your machine and create a new issue if you still can reproduce the problem.
