### ISSUE TITLE
Cannot typeText in input with type=number if emulating userAgent

### ISSUE THREAD

**Issue by leahwhittaker** [DevExpress/testcafe#3109]
### What is your Test Scenario?
I am trying to run my test while emulating the Chrome userAgent according to the spec found here:
https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.html#emulator-parameters
 
### What is the Current behavior?
When trying to change the value of a number input
<input
    type="number"
    id="number-input"
    name="number-input"
    min="10"
    max="100"
  />

Using `await t.typeText(input, "12");`:
It will type the first number indefinitely.

Using `await t.typeText(input, "12", { replace: true });`:
the running will hang until the test crashes with the output:
 `1) Uncaught object "[object Object]" was thrown. Throw Error instead.`
 
### What is the Expected behavior?
The number input is able to be changed with or without `{replace: true}`
 
### What is your web application and your TestCafe test code?

<details>
<summary>Your complete app code:</summary>

```html
<head></head>
<body>
  <label for="tentacles">Number of whatever (10-100):</label>

  <input
    type="number"
    id="number-input"
    name="number-input"
    min="10"
    max="100"
  />
</body>
```

</details>

<details>
<summary>My complete test code:</summary>

 
```js
 import { Selector } from "testcafe";

fixture(`User agent - number input bug`).page(`http://127.0.0.1:8080`);

test("Number input is able to be changed", async t => {
  const input = Selector('input[name="number-input"]');

  await t.expect(input.exists).ok();
  await t.typeText(input, "12");
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
testcafe "chrome:emulation:userAgent='foo'" test.js
 Running tests in:
 - Chrome 70.0.3538 / Mac OS X 10.13.6

 User agent - number input bug
 ✖ Number input is able to be changed

   1) Uncaught object "[object Object]" was thrown. Throw Error instead.

      Browser: Chrome 70.0.3538 / Mac OS X 10.13.6



 1/1 failed (17s)
```
</details>

### Steps to Reproduce:

1. Save the html locally and start the saved html file in a local server using something like `http-server`
2. Save the test js locally in the same directory as test.js
3. testcafe "chrome:emulation:userAgent='foo'" test.js
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   0.23.2
* node.js version:                    11.1.0 (also tried 10.8.0 and 9.11.1)
* command-line arguments:  testcafe "chrome:emulation:userAgent='foo'" test.js
* browser name and version: chrome 70 (also tried chrome 63)
* platform and version:          "macOS 10.13.6"

**Comment by bdwain** [comment]
I am having the same issue.

**Comment by AndreyBelym** [comment]
Could you please provide me with the exact user agent string and command line parameters that you are using in the `testcafe` command?
 
TestCafe is a cross-browser application, so it uses user agent strings to detect the browser type to define a correct event simulation order and other browser-dependent details that can't be defined by the feature detection.
 
It means that TestCafe can't work properly if you specify an incorrect user agent string. It can be hard to pass a correct user agent using a command line because user agent strings include special characters that your shell or TestCafe argument parser can remove from the string and treat it in a special way. These modifications will invalidate the user agent string so you need to escape these characters in the way supported by your shell.
 
The list of special characters contains the following symbols:
 - `\` (backslash)
 - `'` (single quote)
 - `"` (double quote)
 - `,` (comma)
 - `;` (semicolon)
 - `:` (colon)

The rules of escaping special characters are complex and have minor differences in different shells, so I've created a separate ticket about adding these rules to our documentation: #3116.
 
Yet, I can give you an example of a properly escaped user agent string for the `bash` and `PowerShell` shells. I can't share an example for the `cmd` shell, because it's very hard to properly escape control characters there and all modern Windows systems (Windows 7+) have `PowerShell` preinstalled.

##### PowerShell
```
testcafe 'chrome:emulation:userAgent=''Mozilla/5.0 (Windows NT 10.0\; Win64\; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36''' test.js
```

##### bash
```
testcafe $'chrome:emulation:userAgent=\'Mozilla/5.0 (Windows NT 10.0\\; Win64\\; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36\'' test.js
```
The issue is not reproduced when I run these examples.

**Comment by leahwhittaker** [comment]
We figured out a workaround by adding an arbitrary string at the end of the legitimate userAgent you provided.

I'm still curious if userAgent is never meant to support arbitrary strings?
