### ISSUE TITLE
Anything in node_modules assumed to require compilation

### ISSUE THREAD

**Issue by Asher-** [DevExpress/testcafe#3128]
### What is your Test Scenario?
npm install mixwith
import { Mixin, mix } from "mixwith/src/mixwith.js";

 
### What is the Current behavior?

```
SyntaxError: Unexpected token export
``` 

### What is the Expected behavior?
No error should occur.

### How to fix it

Copy js file anywhere outside node_modules:
import { Mixin, mix } from "./mixwith.js";

**Comment by AlexKamaev** [comment]
This issue is not related to TestCafe. The `mixwith` module is an external library, which uses ES6 syntax, and of course, it needs to be compiled. However, TestCafe should not compile any external library by design.

In addition, the `mixwith` module is already compiled. You just need to import from the compiled `mixwith.js` file, as you mentioned, but not from the `src/mixwith` file.

I also need to mention that if you have a question about TestCafe, it's better to [ask it on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions

**Comment by Asher-** [comment]
Uh, false. Did you bother read the issue? Apparently not.

It is not “clearly” the case that compilation is required. It is ES6 code, which means exactly the opposite. No compilation should happen if testing is occurring in a modern browser. Transpilation should only occur if required. Testing ES6 code in an ES5 environment is profoundly stupid to say the least. 

The issue, which is Testcafe and has nothing whatsoever to do with mixwith (which was an arbitrary example).

You should read the content of the issue reports before being a dick.

**Comment by AlexKamaev** [comment]
TestCafe runs under node environment, and Nodejs but not a browser processes all the test code you have written.
Nodejs (and thus TestCafe) does not have full support for ES6 features. For example, async/await functions will not work in Node 6.  Please refer to the following links: https://nodejs.org/en/blog/release/v6.0.0/ and https://v8.dev/blog/v8-release-55
As you can see, support for async/await functions was introduced only in the V8-5.5 version while Node 6 uses the V8-5.0 version
As for your compilation question, the ES6 module support in Nodejs is currently limited and requires the `--experimental-modules` flag to be enabled. This is still an experimental functionality on which we cannot rely. Until these limitations are addressed, TestCafe requires compiled versions of modules.
