### ISSUE TITLE
Emulate 'code' property of the KeyboardEvent class

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3146]
#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example):

Your complete test code (or attach your test files)

```js

```
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by AlexKamaev** [comment]
I think we need to remove this ticket from the sprint. The `code` property depends on the physical placement of a button, but not on its keyCode. For example `code` property for `q` is `KeyQ` and for russian `й` is also `KeyQ`, because these symbols are on the same button. Even in the English language there are several types of keyboard layout:

> For example, the code returned is "KeyQ" is for the "q" key on a QWERTY layout keyboard, but the same code value also represents the "'" key on Dvorak keyboards and the "a" key on AZERTY keyboards. That makes it impossible to use the value of code to determine name of the key is to users if they're not using an anticipated keyboard layout.

Some useful links:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
https://www.w3.org/TR/uievents-code/
https://keycode.info/

**Comment by JSteunou** [comment]
As said in #4710 `code` is an important missing piece of the KeyboardEvent

`keyCode` was used and still used but `code` is replacing it on the developers side. Not being tight to the keyboard layout can only be achieved with `code` from the developers perspective.

Of course it is the opposite in order to emulate it.

Maybe `triggerKey` should emulate `code` using a default `en-US` keyboard layout en let testcafe user load or set different layout if needed.

**Comment by aleks-pro** [comment]
Hello @JSteunou ,

Thank you for sharing your idea with us. We will take it into account.

**Comment by JSteunou** [comment]
I'm sad to see this demand without activities so I am expressing my feeling to that bot :)

**Comment by akoskm** [comment]
I'm with you @JSteunou 👋  coming from https://github.com/DevExpress/testcafe-browser-provider-electron/issues/82.
