### ISSUE TITLE
How to read each span value when there are multiple selectors with same id in a single class

### ISSUE THREAD

**Issue by dineshpaduchuri** [DevExpress/testcafe#3175]
#### HEADS UP!
![image](https://user-images.githubusercontent.com/42802100/49331532-81825e80-f5c4-11e8-8ad7-fa61a9c153f6.png)

I have multiple dbmsubgroup with the same selector id and i have to read span value from each dbmsubgroup under main class .ng-star-inserted. And in that page i have many classes with .ng-star-inserted. 

Please help me in getting the code for above situation
You may also find answers in our up-to-date [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe) on StackOverflow. This may save your time.

If you have already looked there and have not found an appropriate answer, [file a new question on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).

**Comment by ljowen** [comment]
This is probably more appropriate to ask on StackOverflow.
Try something like:
```javascript 
for(let i = 0; i < (await Selector('#subGroupName').count); i++) {
        const spanText = await Selector('#subGroupName').nth(i).innerText;
        ...etc
}
```
Note it's technically invalid HTML to have multiple elements with the same id

**Comment by LavrovArtem** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

If you think that this issue is a bug, feel free to open a new issue, but please make sure to follow the bug template. Thank you in advance.
