### ISSUE TITLE
Feature request: function equivalent to setFilesToUpload to be able to upload folders

### ISSUE THREAD

**Issue by sebpalluel** [DevExpress/testcafe#3194]
### What are you suggesting?

It would be very useful for my project to be able to import folders in a way that preserve the relative path of the imported directory's content.

### What alternatives have you considered?

I haven't read any mention in your doc or in Stack Overflow of how to import folders in testcafe. I'm guessing you will need a recursive functions to import all the nested items but i guess it will be difficult to find a method that works across different browsers.

### Additional context

I'm aware that chrome have a safeguard when importing folders -which is not the case for firefox- (it triggers a confirm dialog which ask to confirm the upload), as you can see here ->

![screen shot 2018-12-06 at 18 54 02](https://user-images.githubusercontent.com/11297176/49602562-0a184a80-f989-11e8-9fe1-dd7e91adfb2c.png)

Obviously it would be an other issue when testing but I think there is some kind of way to de-activate this security feature when launching an instance of chrome, maybe with this flag -> `--allow-file-access-from-files` ?

**Comment by LavrovArtem** [comment]
It seems like you are trying to test your browser's behavior, but TestCafe is not supposed to do this. It does not matter for any application how the user will select files: by dragging multiple files or by dragging a folder - in fact, it is just multi-files selection. If you want to test a multi-upload scenario, you can pass an array of file paths as the second argument of `setFilesToUpload`.

https://devexpress.github.io/testcafe/documentation/test-api/actions/upload.html

**Comment by sebpalluel** [comment]
Thanks for the fast answer.

I'm aware that you can upload an array of files but the limitation is that it will upload a flat array of files without the nested paths.
For instance if i use the function such as described in the doc 
```javascript
test('Uploading', async t => {
    await t
        .setFilesToUpload('#upload-input', [
            './uploads/1.jpg',
            './uploads/folder_0/2.jpg',
            './uploads/folder_1/folder_0/3.jpg'
        ])
        .click('#upload-button');
});
```
The upload gives me this 
`['1.jpg', '2.jpg', '3.jpg']`
instead of this
`['1.jpg', 'folder_0/2.jpg', 'folder_1/folder_0/3.jpg']`

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/3194#issuecomment-446549913

Hi @sebpalluel 
Thank you for providing the additional details.

Due to security reasons, it's impossible to get a full path of the uploaded file.
After you selected a file using a native browser's 'Select File' dialog, the `value` attribute of the target `input` will contain a filename with this prefix: ` C:\fakepath\`.
As a browser passes only filenames during the file upload, there is no way to implement your suggestion.
TestCafe emulates the native browser behavior and stores uploaded files in the `<UPLOAD_ROOT>` folder using their names.

See these links for detailed information:
* https://html.spec.whatwg.org/multipage/forms.html#fakepath-srsly
* https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/file#Value
