### ISSUE TITLE
Allow to specify arrays as metadata values

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe#3267]
### What is your Test Scenario?

We have multiple client websites (with similar page layout) to test but certain preact components are disabled on certain client sites. I would like to store metadata values in array (one key with multiple values) and filter my fixture/test based on those metadata array values. For e.g 

```js
fixture (Array metadata fixture)
	.meta( { components: [ 'website1', 'website2', 'website5'] })
	.page(${config.pageURL})
```

When I try to run it from command line by passing metadata array values, I get no tests to run error.

```js
testcafe chrome desktop/ --config=website2 --fixture-meta components=website2

ERROR No tests to run. Either the test files contain no tests or the filter function is too restrictive.
```
### What are you suggesting?

As discussed in #2841 comments - https://github.com/DevExpress/testcafe/pull/2841#discussion_r225142260 (allow to specify arrays as metadata values), could TestCafe team or @NickCis support the option to be able to pass array of metadata values and filter them?

**Comment by NickCis** [comment]
As @AndreyBelym pointed out in the [comment](https://github.com/DevExpress/testcafe/pull/2841#discussion_r225142260) metadata should [(per documentation)](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#specifying-testing-metadata) be only string.

In addition, the particular case you are addressing is a bit tricky, what will be the user expected behaviour?, To match only when the array has all the passed values? or when the array is equal to that values (ie: don't have any extra one)?.

---

In order to do a workarround you could do the following:
```javascript
fixture (Array metadata fixture)
	.meta( { 
              componentWebsite1: 'true',
              componentWebsite2: 'true',
              componentWebsite5: 'true'
         })
	.page(${config.pageURL})
```

And the run:
```
testcafe chrome desktop/ --config=website2 --fixture-meta componentWebsite2=true
```

Another option is to use [testcafe's node api](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/), the [runner](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html) has a [`filter` method](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#filter) which you could use to implement your custom filtering logic.

**Comment by sijosyn** [comment]
Thanks @NickCis for providing the workaround.

> In addition, the particular case you are addressing is a bit tricky, what will be the user expected behaviour?, To match only when the array has all the passed values? or when the array is equal to that values (ie: don't have any extra one)?.

To answer the above question, what I needed was to store metadata values in array (one key with multiple values) and the user expected behavior is to filter if array key is equal to that value.

I'll close this ticket if the expectation is that the metadata has to be only string.
