### ISSUE TITLE
ECONNRESET error when using SauceLabs

### ISSUE THREAD

**Issue by cmbirk** [DevExpress/testcafe#3301]
### What is your Test Scenario?

I'm trying to run a simple login test with testcafe and Saucelabs using:
* `testcafe@^0.23.3`
* `testcafe-browser-provider-saucelabs@^1.6.0`

When I start the tests with `testcafe 'saucelabs:Chrome@59.0:OS X 10.11' test/e2e/**/*Test.js` I get the error:

```
ERROR Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
```
I've set my environment variables correctly, and my tests run with Chrome & Nightmare locally.

**I'm happy to help debug more and even look into fixing, but would need some guidance. Thanks!**

### What is the Current behavior?

No connection is made to Saucelabs and no useful error message is given. 

### What is the Expected behavior?

Connect to Saucelabs and run tests through the tunnel. On error provide useful error message.
 
### Your Environment details:
 
* testcafe version: 0.23.3                  
* node.js version: v10.15.0                   
* command-line arguments: `testcafe 'saucelabs:Chrome@59.0:OS X 10.11' test/e2e/**/*Test.js` 
* browser name and version: N/A
* platform and version:  macOS 10.14.2

**Comment by AndreyBelym** [comment]
I can't reproduce the issue. Could you provide an example project that can be used to reproduce the problem?

This error means that the Node.js framework (which TestCafe is built upon) encountered a fatally malformed request that can break TestCafe application state. It can be caused by your proxy or firewall, or even by the Sauce Connect tunneling software. Try to run your tests from a different machine, a different network and without the Sauce Connect tunnel.

**Comment by cmbirk** [comment]
@AndreyBelym you are absolutely correct. It seems my Eero router was blocking this. Tethering to my phone or using a different network has resolved this issue. I'm closing this, and thanks for the help!
