### ISSUE TITLE
Error: Cannot read property '__mouseflow_node_map_id__' of undefined

### ISSUE THREAD

**Issue by TerezaMihova** [DevExpress/testcafe#3344]
### What is your Test Scenario?
I am trying to open a static page, and from it to access a sign up modal form
 
### What is the Current behavior?
Test is failing after opening the page.
and I am getting the following error
`      Error: Cannot read property '__mouseflow_node_map_id__' of undefined
          at Function.t._error
      (http://192.168.1.100:50828/hammerhead.js:2:10524)
          at value (http://192.168.1.100:50828/hammerhead.js:2:11948)
          at NodeMap.nodeId

   (https://cdn.mouseflow.com/projects/c368f9a0-d3f8-4ce1-a38f-b41c97881cd3_eu.js:18:650)
          at NodeMap.has

   (https://cdn.mouseflow.com/projects/c368f9a0-d3f8-4ce1-a38f-b41c97881cd3_eu.js:18:1018)
          at MutationProjection.visitNode

   (https://cdn.mouseflow.com/projects/c368f9a0-d3f8-4ce1-a38f-b41c97881cd3_eu.js:18:7374)
          at MutationProjection.processMutations

   (https://cdn.mouseflow.com/projects/c368f9a0-d3f8-4ce1-a38f-b41c97881cd3_eu.js:18:7241)
          at new MutationProjection

   (https://cdn.mouseflow.com/projects/c368f9a0-d3f8-4ce1-a38f-b41c97881cd3_eu.js:18:6994)
          at MutationSummary.createSummaries

   (https://cdn.mouseflow.com/projects/c368f9a0-d3f8-4ce1-a38f-b41c97881cd3_eu.js:18:32299)
          at MutationSummary.observerCallback

   (https://cdn.mouseflow.com/projects/c368f9a0-d3f8-4ce1-a38f-b41c97881cd3_eu.js:18:33599)
          at
      MutationObserver.MutationSummary.observer.MutationObserverCtor.observe

   (https://cdn.mouseflow.com/projects/c368f9a0-d3f8-4ce1-a38f-b41c97881cd3_eu.js:18:29227)
`

Selector for element is: 
this.signUpButton = Selector('a[data-init = "initCharitySignUpForm"]').nth(2);

The form is actually open, but after that test fails, and following actions are not executed
 
testcafe version:                 0.23.3
node.js version:                  v6.9.1

**Comment by AlexKamaev** [comment]
Thank you for reaching out to us and submitting this issue.

This information is not sufficient to reproduce the problem. Since this error occurs on the client side, it can be related to your site. I recommend you use the `--skip-js-errors` flag to suppress the error. Please refer to the following article to get more information: https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors.
If it does not help, could you please provide your project or website url and your full test code?

**Comment by TerezaMihova** [comment]
Thank you! 

The --skip-js-errors option helped. Now it's all running fine.
