### ISSUE TITLE
Mistake in documentation for runner.filter in fixture meta

### ISSUE THREAD

**Issue by presha1** [DevExpress/testcafe#3373]
In documentation of runner.filter for meta, it gives 
runner.filter((testName, fixtureName, fixturePath, testMeta, fixtureMeta) => {
    return testMeta.mobile === 'true' &&
        fixtureMeta.env === 'staging';
});

But you need to access mobile and env as testMeta['mobile'] and fixtureMeta['env']  respectively.

**Comment by miherlosev** [comment]
Hi @presha1 
 
Thank you for bringing this to our attention. As I see, our documentation is correct because JavaScript allows you to use two notations for property accessing:
```js
object.property
object["property"]
``` 
So, these calls are equal and valid: `testMeta.mobile` and `testMeta['mobile']` as well as `fixtureMeta.env` and `fixtureMeta['env']`. 
 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors#Syntax
