### ISSUE TITLE
TestCafe hangs when asserting contents of a dialog in a Google Spreadsheet

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3422]
### What is your Test Scenario?
Assert contents of a modal dialog in a Google Docs, Spreadsheets, etc.
 
### What is the Current behavior?
TestCafe hangs when execution an assertion.
 
### What is the Expected behavior?
TestCafe should pass/fail according to an assertion results.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): https://docs.google.com/spreadsheets/d/1DicEdS0lBkPjXT19eadBeC13kct6mSR4_OQ3wJEskZU/edit?usp=sharing

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture`knockout`.page`https://docs.google.com/spreadsheets/d/1DicEdS0lBkPjXT19eadBeC13kct6mSR4_OQ3wJEskZU/edit?usp=sharing`;

const modaldialogFrame = Selector('.modal-dialog-content.script-app-contents iframe');
const sandboxFrame = Selector('#sandboxFrame');
const userHtmlFrame = Selector('#userHtmlFrame');
  
test('Check for email input', async browser => {
    // NOTE: unclock the page and perform these steps manually:
    // 1. Authenticate to Google
    // 2. Wait until the spreadsheet is loaded and the 'Custom Menu' item appears in the main menu
    // 3. Click 'Custom Menu' >> 'Custom Item' 
    // 4. Wait until the 'My custom dialog' opens and 'Hello, word' appears
    // 5. Resume test
    
    await browser.debug();
    
    await browser.switchToIframe(modaldialogFrame);
    await browser.switchToIframe(sandboxFrame);
    await browser.switchToIframe(userHtmlFrame);
  
    await browser.expect(Selector('#email').exists).ok();
})
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Your Environment details:
 
* testcafe version:                   1.0.0
* node.js version:                    10.15.0
* command-line arguments:  any
* browser name and version: Chrome 72
* platform and version:          any

**Comment by istvandesign** [comment]
How to reproduce easily : 
1. Install an addon which opens a login modal, e.g [Markets4Sheets](https://chrome.google.com/webstore/detail/markets4sheets/foefdijhpobeeelcpkfdaoiljdpemmdj) and open the login modal with Addons->Markets4Sheets->Login (this is just a random example, I am not associated with Markets4Sheets in any way)

2. Use the upper specified test code to assert something after switching inside #userHtmlFrame when the Login modal is open. e.g `await browser.expect(Selector('#username').exists).notOk();`
3.  Results : 
First the test hangs completely
Second inside the console I'll have a No log from hammerhead.js.2 :
> "There was an error during the transport or processing of this request. Error code = 10, Path = /wardeninit"

If I remove **.exists** from  `await browser.expect(Selector('#username').exists).notOk();`, then the test will fail with` expected [Function: __$$clientFunction$$] to be falsy`. or pass with .ok(), , which seems normal.
The same happens with **.innerText**, if I add .innerText instead of .exists, the test hangs, if I remove it, then it passes or fails. (same with getStyleProperty)

If I try await t.expect(Selector('#username').innerText).contains('') outside of #userHtmlFrame with only 
```
  await t.switchToIframe(modaldialogFrame);
  await t.switchToIframe(sandboxFrame);
```
then the test will fail without hanging. So the bug can be reproduced only inside #userHtmlFrame. 

My main concern is that Google is injecting some code for sandboxing in the 3rd iframe with a library called Google Caja, which maybe interferes with testcafe's proxy. (however clicking and typing still works with .click and .typeText, so the interference is only with .exists and other methods/properties on the selectors.

A related issue to this is that I cannot select anything inside #userHtmlFrame in TestCafe Studio.

**Comment by AndreyBelym** [comment]
Thank you for the provided information. I need some time to find the cause of the problem. For now, it looks very similar to https://github.com/DevExpress/testcafe-hammerhead/issues/1881.

**Comment by AndreyBelym** [comment]
This issue is really a duplicate of [DevExpress/testcafe-hammerhead#1881](https://github.com/DevExpress/testcafe-hammerhead/issues/1881), thanks to @LavrovArtem for confirming this.
