### ISSUE TITLE
Screenshots on fail are cropped and --window-width params are ignored with chrome:headless

### ISSUE THREAD

**Issue by infctr** [DevExpress/testcafe#3456]
### What is your Test Scenario?

Taking screenshots on failed tests with `chrome:headless --no-sandbox --window-size=1980,1080`. 
 
### What is the Current behavior?

Screenshots are cropped as if `--window-size` params are ignored. Works as expected with `chrome --headless --no-sandbox --window-size=1980,1080`. 
 
### What is the Expected behavior?

Taken screenshots match the size specified with `--window-size`
 
### What is your web application and your TestCafe test code?

Repro https://github.com/infctr/repro-testcafe-screenshot-error-reporting
 
And as a side note in what way does starting `chrome --headless` differs from `chrome:headless` in TestCafe? As they seem to work differently on my CI setup

**Comment by AlexKamaev** [comment]
I've checked the issue with this command `"chrome --headless --window-size='100,500'"` and it works as expected. The headless browser makes a screenshot with width=100 and height=500.
However, I was not able to resize the browser using the command you mentioned `chrome:headless --no-sandbox --window-size=1980,1080`
I need some additional time to research this issue.
 >And as a side note in what way does starting `chrome --headless` differs from `chrome:headless` in TestCafe?

There is a difference because `chrome:headless` is our syntax and it adds extra flags to Chrome, while `chrome --headless` does not do that.
For now, I recommend you use the following syntax: `"chrome:headless:emulation:width=100;height=100"`. It solves the problem and works well.

**Comment by infctr** [comment]
@AlexKamaev thanks for the tip, that works!
