### ISSUE TITLE
mock user media (camera / microphone)

### ISSUE THREAD

**Issue by nicgirault** [DevExpress/testcafe#3532]
Hello and thanks for this awesome project.

I would like to know what is the status of the reported bug here: https://testcafe-discuss.devexpress.com/t/allow-microphone-access/455

Passing the webrtc testing options on chrome (https://webrtc.org/testing/): `testcafe "chrome --use-fake-ui-for-media-stream --use-fake-device-for-media-stream"` does not seem to work. Chrome rejects the call to `navigator.mediaDevices.getUserMedia({
      audio: {
        sampleSize: 16,
        channelCount: 1,
        sampleRate: 16000,
      },
    })` with a `NotSupportedError` comming from the file `hammerhead.js`.

Any help would be welcome!

**Comment by nicgirault** [comment]
Continuing investigating, it seems that the chrome flags are working only on chromium. I still face issue testing a microphone recording but will share here any progress.

**Comment by AndreyBelym** [comment]
Chrome doesn't allow calling the `getUserMedia` API from insecure origins. Since Chrome considers any HTTP-based websites served from any host except `127.0.0.1` or `localhost` as insecure, you can:

1)  Specify `localhost` as the hostname when starting TestCafe:
```shell
testcafe --hostname localhost ...
```

2) Obtain a valid SSL certificate or register a self-signed certificate as a valid in your operating system and enable [HTTPS mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--ssl-options) in TestCafe:
```shell
testcafe --ssl pfx=/path/to/cert.pfx ...
```

I've tried the following example and it worked for me with `--hostname localhost`:
```js
fixture `WebRTC
   `.page`https://webrtc.github.io/samples/src/content/getusermedia/canvas/`;

test(`test`, async t => t.wait(30000));
```
