### ISSUE TITLE
Allow passing element to .ok() as a part of error message; it should print element's html source.

### ISSUE THREAD

**Issue by al3xand3r-K** [DevExpress/testcafe#3579]
### What is your Test Scenario?
Assert that each element in group of elements on the page has a specific attribute.

Test example:
```js
const imgs = Selector('img')
const imgsCount = await imgs.count;
for (let i = 0; i < imgsCount; i++) {
  await t.expect(imgs.nth(i).hasAttribute('alt')).ok();
}
```

### What are you suggesting?
Improve assertion error messaging by printing html element for which assertion has failed.

### What alternatives have you considered?
Allow passing actual element as a part of error message would be helpful too. E.g.:
```js
await t.expect(imgs.nth(i).hasAttribute('alt')).ok(imgs.nth(i));
```

Or alternatively, `.ok()` could somehow determine what kind of check it has been called on, and print a corresponding error message. I'm sure this is a lot harder to achieve, so just letting to pass an element as an error message is enough.

### Additional context
This specific test checks if all images on a given page have `alt` attribute. Manually looking for an image that has failed the test is not quite convenient. Seeing the element in html the way it was on the page in the moment of assertion could be a great help in finding that element (e.g. by its `class`, etc.)

**Comment by AlexKamaev** [comment]
I think that passing an element (it is Selector in your example) to the assertion function is not required since you already have a capability to pass a message to it.
Besides, it is unclear to me how to process an element (or Selector) in the assertion. An element is a complex object with a lot of properties and it will be very difficult to determine which property needs to be displayed.
So, I recommend you use the `message` argument (https://devexpress.github.io/testcafe/documentation/test-api/assertions/assertion-api.html#ok) since you can customize it. Please also see the following example:
```JS
import { Selector } from 'testcafe';
 
fixture`fixture`
    .page`../pages/index.html`;
 
test(`test`, async t => {
    const imgs = Selector('img');
 
    const imgsCount = await imgs.count;
 
    for (let i = 0; i < imgsCount; i++) {
        const src = await imgs.nth(i).getAttribute('src');
        const message = `Image with src attribute "${src}" should have the "alt" attribute`;
 
        await t.expect(imgs.nth(i).hasAttribute('alt')).ok(message);
    }
});
```

**Comment by AlexKamaev** [comment]
I've discussed the issue with the team and we decided to mark it as `enhancement` since it can be useful. As I mentioned before printing element properties or element HTML code (as you suggested) to the console can be too exhaustive. Anyway, we'll discuss how to solve it.
