### ISSUE TITLE
Sending custom data to reporter

### ISSUE THREAD

**Issue by oreporan** [DevExpress/testcafe#3584]
### What is your Test Scenario?
We are using testcafe to measure performance regressions. Our test case does some setup, tests something, and makes sure its under some X time. 
I would like to send the time it took (currently just a `console.log`)  to our custom reporter so we can track this in a graph and see how performance increases/decreases over time.

Currently this is not possible, the closest solution i saw was to use `meta` like [here](https://github.com/DevExpress/testcafe/issues/2242) but I need custom information after the test has passed, not before.

### What are you suggesting?
Some way to pass data, either by log or by the test object, into my reporter.
The time of the test is not good enough because it includes the setup/teardown of the test.

### What alternatives have you considered?
Right now I need to log the results to a file, and pick them up in another step of my CI disconnected completely from testcafe.

**Comment by sijosyn** [comment]
I would also like to send custom data to reporter. My use-case scenario is as follows:

I grouped bunch of test-scenarios together in one single test function (this is done in this way for test execution time saving purpose). Each test-scenario is considered to be a single test case and has associated testcase ID in TestRail test management system (https://www.gurock.com/testrail) and I use TestRail API in reporter plugin (https://www.npmjs.com/package/testcafe-reporter-html-testrail) to update the status of the test cases. Since I grouped the tests, I want to be able to capture the status during the test execution and make that info available in test reporter. For e.g

```javascript
test("My Test", async (t) => {
    // Test scenario for caseID_123
    await t.click(<DOM element found>);
    await t.report({caseID_123: "PASS"},/*  set the status of  caseID_123 as PASS*/);
  
    // Test scenario for caseID_234  
    await t.click(<DOM element found>);
    await t.report({caseID_234: "PASS"},/*  set the status of  caseID_234 as PASS*/);
   
    // Test scenario for caseID_456
     await t.click(<DOM element not found>);
     await t.report({caseID_456: "FAIL"},/*  set the status of  caseID_456 as FAIL or NOT TESTED */)
});
```

I don't think `meta` helps. So how can we send custom data to reporter?

**Comment by AlexKamaev** [comment]
Currently, TestCafe does not have such functionality. However, I think it'll be useful. 
I discussed the issue with the team and we decided that since we already have `meta` in reporters, we can add some API for modifying `meta` at runtime.
I marked this issue as `enhancement`, however, I cannot give you estimates as to when it will be implemented.
Of course, your PR will be welcomed.

**Comment by AlexKamaev** [comment]
Thank you for the detailed description. We already have a similar feature request: https://github.com/DevExpress/testcafe/issues/3584
We agree that this feature can be useful, however, we cannot give any estimates on this. If you want to create a PR with this feature, we will accept it and will help you.

**Comment by sivanisentinel** [comment]
Was this enhancement implemented?  I really need this feature

**Comment by Dmitry-Ostashev** [comment]
Currently, this feature is still not implemented, but we keep it in mind. You are welcome to submit your PR and contribute to our project.

**Comment by danlomantoSamsungNext** [comment]
I'd love to try and create a PR for this.  Are there any tips/things I should know before starting? Digging into a completely new codebase can get confusing sometimes. :)

**Comment by AndreyBelym** [comment]
@danlomantoSamsungNext, I think we need to discuss API extensions first. From what it seems to me, simply adding `t.log(...args)` that will handle its arguments similarly to `console.log` and append log lines to test reports will be enough. To implement such function, we need to introduce changes to [TestController](https://github.com/DevExpress/testcafe/blob/master/src/api/test-controller/index.js#L241) and [Reporter](https://github.com/DevExpress/testcafe/blob/master/src/reporter/index.js#L43) subsystems, plus implement support for this feature for in all reporter packages. I'm afraid this feature is too big to get started with contributing to the TestCafe codebase.

**Comment by danlomantoSamsungNext** [comment]
@AndreyBelym I think people are looking for more than just a `t.log(...args)` ability that's similar to `console.log()`.  I believe there were discussions for using `t.meta(key, value)` so that people could save different kinds of test information during a test run that would be accessible via a reporter. There are a couple of referenced tickets that demonstrate this.

I believe the thinking was to use the meta() functionality because it's already accessible when building a custom reporter as well.

**Comment by AndreyBelym** [comment]
@danlomantoSamsungNext yes, I've got your point. I discussed it in private with some other team members, and we agreed that it is easier to add metadata modification functions to the test controller.
What do you think about such API for this feature:
```ts 
type Meta = { [name: string]: string };

interface TestControllerMetaExtensions {
    /**
     * Returns the test metadata as an key-value object.
     * @example
     * test.meta('foo', 'bar')('test', async t => {
     *     console.log(t.meta);
     * });
     * // { 'foo': 'bar' }
     */
    readonly meta: Meta;

    /**
     * Adds an additional metadata entry to the test metadata.
     * If an entry with the specified name already exists, overrides its value.
     * @param name -  The name of the metadata entry to be added.
     * @param value - The value of the metadata entry to be added.
     * @example
     * test.meta('foo', 'bar')('test', async t => {
     *     await t.addMeta('ans', '42');
     *     console.log(t.meta);
     *     await t.addMeta('foo', 'foobar');
     *     console.log(t.meta);
     * });
     * // { 'foo': 'bar', 'ans': '42' }
     * // { 'foo': 'foobar', 'ans': '42' }
     */
    addMeta(name: string, value: string): TestController;

    /**
     * Adds an additional metadata entries to the test metadata.
     * If an entry with the specified name already exists, overrides its value.
     * @param meta -  A set of metadata entries to be added.
     * @example
     * test.meta('foo', 'bar')('test', async t => {
     *     await t.addMeta({ 'foo': 'foobar', 'ans': '42' });
     *     console.log(t.meta);
     * });
     * // { 'foo': 'foobar', 'ans': '42' }
     */
    addMeta(meta: Meta): TestController;

    /**
     * Removes metadata entries with the specified names from the test metadata;
     * @param names - A list of metadata names to be removed
     * @example
     * test.meta({ 'foo': 'bar', 'ans': '42' })('test', async t => {
     *     await t.removeMeta('foo');
     *     console.log(t.meta);
     * });
     * // { 'ans': '42' }
     * test.meta({ 'foo': 'bar', 'ans': '42' })('test', async t => {
     *     await t.removeMeta('foo', 'ans');
     *     console.log(t.meta);
     * });
     * // { }
     * test.meta({ 'foo': 'bar', 'ans': '42' })('test', async t => {
     *     await t.removeMeta(['foo', 'ans']);
     *     console.log(t.meta);
     * });
     * // { }
     */
    removeMeta(...names: (string | string[])[]): TestController;
}
```

**Comment by danlomantoSamsungNext** [comment]
@AndreyBelym That looks absolutely fantastic to me!!!! Thank you so much for digging into that!

**Comment by sivanisentinel** [comment]
It seems to me like this solution is “abusing” meta data. It is strange that this is the only way to send data to the report.
I feel like we need dedicated api for that.
I also thinks that we should have the option to send general data to the test and not only fixture or test related one. 
For example if I want to send environment details or username who triggered the run, do we really have to send it in all fixtures again and again?

**Comment by danlomantoSamsungNext** [comment]
@sivanisentinel I think I see your point, but I think your request is a bit different than the original intention of this ticket. 

I think it would be good to have some general way to associate data/info to an entire test run, so that you don't have to repeat yourself in all your `beforeEach()` and `afterEach()` methods (ie. Test Environment, User Info, etc.).  I think this would be a different enhancement though.

The reason why I think using the `meta()` capability is valid here is because the data/info I'd like to set it truly test-specific data/info that I'd like to have access to in a custom reporter.

**Comment by AndreyBelym** [comment]
@danlomantoSamsungNext thank you for warming words :)

@sivanisentinel I also thought about this way first, as you can see in [my comment](https://github.com/DevExpress/testcafe/issues/3584#issuecomment-515414619). I would like to see it implemented someday, but we need to invest a lot more time and powers into it.

**Comment by miherlosev** [comment]
The "Planned" milestone means that the TestCafe team has plans to implement this feature someday. At present, there is no precise time estimation for that. If the feature is very important for you, the pull request would be appreciated.

**Comment by Evilweed** [comment]
@AlexKamaev this feature is in Your best interest as having this functionality allows creating much powerful Test Reporters like the one that prints **Error Stack, URL of the website during error, and console errors from the browser**, which is currently impossible to do. Debugging errors that occured on CI on complicated websites, without this information is much harder.

**Comment by AndreyBelym** [comment]
@Evilweed error stacks should be printed with all built-in reporters for both server-side and client-side errors.

To properly integrate reporting current URLs and browser console logs in reports, we should also solve a problem with delivering this data consistently from a browser to the TestCafe. Otherwise, it will be not a big difference from using `console.log` and TestCafe APIs like `ClientFunction` and `getBrowserConsoleMessages` that can work unreliably in cases of fatal errors on a tested page.

**Comment by Evilweed** [comment]
My current solution which is rarely used by any developer because it is not presented in Allure report and it's not presented as a part of console error.

Forgot to wrap `getBrowserConsoleMessages` in try/catch. 
```
// Try catch was added as a precaution in order not to break Test Runner
// TODO(m) Create out of this proper Test Reporter plugin to Test Cafe
export async function printInformationFromBrowsersConsole(t: TestController): Promise<any> {
    const { log, warn, info, error } = await t.getBrowserConsoleMessages();
    let url = "";
    let testName = "";
    let fixtureName = "";
    try {
        url = await getUrl();
    } catch(e) {}

    try {
        // Do not remove - those objects are not defined in typings,
        // and can potentially break in future Test Cafe versions.
        // @ts-ignore
        testName = t.testRun.test.name;
        // @ts-ignore
        fixtureName = t.testRun.test.fixture.name;
    } catch(e) {}

    if ((log && log.length > 0) ||
        (warn && warn.length > 0) ||
        // (info && info.length > 0) ||
        (error && error.length > 0)) {
        console.log("\n");
        console.log("--------------------------------");
        console.log(`Test information:`);
        console.log("--------------------------------\n");
        console.log(`Fixture: ${fixtureName}`);
        console.log(`Test: ${testName}`);
        console.log(`🌍 Page URL: ${url}`);

        printEachIfExists(LogType.LOG, log);
        printEachIfExists(LogType.WARNING, warn);
        //printEachIfExists(LogType.INFO, info);
        printEachIfExists(LogType.ERROR, error);

        console.log("--------------------------------");
    }

}
```

**Comment by Farfurix** [comment]
One more request: https://github.com/DevExpress/testcafe/issues/4370.

**Comment by KouraiBee** [comment]
Hello !
I am also very interrested in adding personnalized info in my reporter.
The `addMeta` method would suit my needs I think.

So do you have any news on this functionnality ? Any (rought) idea on when it will be implement ?
(So I can choose whether to wait for it, or spend time to find a suitable workaround)

**Comment by miherlosev** [comment]
Hi @ilchenkoalexey

There is no update yet. As soon as we get any results, we will update this thread.

**Comment by Ogurecher** [comment]
@KouraiBee, We haven't yet started implementing this functionality, and we cannot give you any estimates as to when we start working on this. In the meantime, I suggest that you use one of the workarounds outlined in this thread.

**Comment by wentwrong** [comment]
https://stackoverflow.com/questions/65364252/testcafe-report-the-page-html-on-any-assertion-failure
One more feature request. Use case: provide the HTML code of a page when the assertion is failed.

**Comment by miherlosev** [comment]
https://stackoverflow.com/questions/65191797/testcafe-can-you-pass-ctx-context-variables-to-reporter

**Comment by AlexGrisin** [comment]
Hello! Do you have any updates on this issue ?

**Comment by kPepis** [comment]
👍  on this. This would be really helpful.

**Comment by Jgrabenbauer** [comment]
This would be very helpful with passing different errors to the reporter (without failing the tests) so that they can be reviewed locally and in CircleCI.

**Comment by miherlosev** [comment]
Hi @Jgrabenbauer,

> This would be very helpful with passing different errors to the reporter

Could you please clarify what kind of errors you want to pass on to the reporter? We have plans to collect browser console errors and request errors and notify customers about them. So, if you want to pass generic errors, we will consider adding them to the report.

**Comment by Jgrabenbauer** [comment]
Hey @miherlosev what we are mainly looking for is to enhance Testcafe’s reporter options to allow the user to implement an EventEmitter that will print a message of the failed request(Promise). This will allow TestCafe to finish running the tests while letting the users see other failures that happened during the run (400s and 500s). It would be nice if this was an option in the .testcaferc file as well as the fixture and test level.

**Comment by miherlosev** [comment]
@Jgrabenbauer 

Thank you for sharing the detailed information about your use case.

**Comment by JESii** [comment]
Given that this issue has been open since 2019 with many supporting comments, I have to assume that there really is no intent to implement it. In the hope that I am wrong, I'll add my use case: this is for an investment reporting app.
1. Clients are offered a view of their portfolios, with assets grouped into various categories.
2. The app offers a "current month" view, with the ability to switch to previous month's data -- called AsOfDates.
3. Within each monthly view, the data is organized into various periods; e.g., CYTD, FYTD, 1Year, 3Years... etc each of which offers a view of the portfolio over the respective time period.
4. There are numerous graphs throughout the app, with different display specs for the graph type (line, bar, ...): for example how many x-axis points there are for each period and how they are labelled.

I have a working TC regression test that: loops thru multiple clients; loops through the AsOfDates; loops through the available Periods; and examines the various graphs to ensure that the x-axis data is presented according to spec.

Obviously, there are many possible points of failure in this process, but in the event of a failure I want to simply write a message documenting the failure and continue to the end of the test. 

When the test completes, I want to collect any error information and report it to the TC reporter. There was a suggestion https://github.com/DevExpress/testcafe/issues/5563 made some time ago to provide a mechanism to explicity cancel a test and provide some information but that was closed last year.

I just have to say that, from our perspective, this is a huge omission and one that will count heavily against TestCafe when we are considering a testing framework for future client implementations.

**Comment by Aleksey28** [comment]
Hi @JE,

It's quite a complicated enhancement because a lot of users have different cases, and this enhancement should satisfy most of them. That is why implementation takes a long time. Thank you for sharing your use case.

**Comment by JESii** [comment]
Thanks!

**Comment by reinhartbuit** [comment]
Hi,

We are using TestCafe to do API Testing. We include the API Response body within the Report Output as proof the API did output a response body.
We are hoping that with this feature we can pass the Response body to the Reporter and therefore form part of the output.

If there is any workaround to the above scenario that will be appreciated.

Thanks for all the effort!

**Comment by Aleksey28** [comment]
Hi @reinhartbuit,

Thank you for sharing your case. There is no workaround. However, why can't you just check a response body with `expect`  in a test?

**Comment by Artem-Babich** [comment]
Hi @marinamarin91,

If I understand correctly, you execute all the code inside one test due to the need to re-authenticate on the test page.
You can prevent subsequent tests from being re-authenticated if you use the [Roles](https://testcafe.io/documentation/402845/guides/intermediate-guides/authentication#user-roles) mechanism, which allows you to log in only once (before the first test), and then use that authentication data for subsequent tests.

If Roles are not suitable for you, you can accomplish your task using [CustomActions](https://testcafe.io/documentation/404150/guides/advanced-guides/custom-test-actions). You need to put your custom methods' code into separate actions in the config file and return an object that contains a description field. After that, you will be able to access the result in the reporter's reportTestActionDone method. So, if you use Jenkins, you need to modify the [Jenkins reporter code](https://github.com/wentwrong/testcafe-reporter-jenkins) to display your custom information.
For example, your custom action in the config file can return an object with a description field:

```js
const { Selector } = require('testcafe');

module.exports     = {
    customActions: {
        async myFirstAction () {
            await this.typeText(Selector('#developer-name'), 'Peter Parker');

            return { description: 'first action description' }
        },
        async mySecondAction () {
            await this.pressKey('backspace').expect(Selector('#developer-name').value).eql('Pete Parker');

            return { description: 'second action description' }
        },
    },
}
```

In this case, you can modify the [jenkins](https://github.com/wentwrong/testcafe-reporter-jenkins) reporter in the following way:

```js
export default function () {
    return {
        ...
        customActions:      [],

        isCustomAction (type) {
            return type === 'run-custom-action';
        },

        reportTestActionDone (actionName, { command }) {
            if (this.isCustomAction(command.type)) {
                const { actionResult, name } = command;
                const description = actionResult?.description || '';

                this.customActions.push({ name, description });
            }
        },

        _renderCustomActionsInfo () {
            this.report += this.indentString('<system-out>\n', 4);
            this.customActions.forEach(({ name, description }) => {
                this.report += this.indentString(`${name}: ${description}\n`, 4);
            });

            this.report += this.indentString('</system-out>\n', 4);
        },
        async reportTestDone (name, testRunInfo) {
            ...

            if (hasScreenshots || hasVideos)
                this._renderAttachments(testRunInfo, hasScreenshots, hasVideos);

            if (this.customActions.length)
                this._renderCustomActionsInfo();

            this.report += this.indentString('</testcase>\n', 2);
        },

```

Using this code, I was able to run the following test:

```js
fixture`A set of examples that illustrate how to use TestCafe API`
    .page`https://devexpress.github.io/testcafe/example/`;

test('Dealing with text using keyboard', async t => {
    await t.customActions.myFirstAction();
     await t.customActions.mySecondAction();
});
```

And got the following report result:

```xml
<testsuite name="TestCafe Tests: Chrome 109.0.0.0 / Ubuntu 22.04" tests="1" failures="0" skipped="0" time="3.908" timestamp="Tue, 14 Feb 2023 06:15:29 GMT" id="9945521c-ac82-4024-8010-0d8b6a65309e">
  <testcase classname="A set of examples that illustrate how to use TestCafe API" name="Dealing with text using keyboard" time="1.779">
    <system-out>
    myFirstAction: first action description
    mySecondAction: second action description
    </system-out>
  </testcase>
</testsuite>
```

Please let me know if this helps.

**Comment by codambro** [comment]
tested with v2.5.0. not seeing it with default spec reporter. Also, what about `html` or `junit` reporters?

**Comment by codambro** [comment]
huh. manually updating `testcafe-report-spec` resolved it. Not sure why updating `testcafe` did not update the spec reporter version

**Comment by Artem-Babich** [comment]
Hi @codambro

TestCafe v2.5.0 uses the following dependency: `"testcafe-reporter-spec": "^2.1.1"`. So, according to semver logic, the spec reporter should also be updated to v2.2.0. I assume that you updated TestCafe with the following command: `npm i testcafe@latest`.
In this case, the spec reporter is not updated to the latest version. We fixed this behavior in [https://github.com/DevExpress/testcafe/pull/7620](https://github.com/DevExpress/testcafe/pull/7620).
As for html and junit reporters, they are supported by the community, not by the TestCafe team. You can ask their owners to update the reporters in order to display reported data or create a pull request manually.
The following information can be helpful:
All reported data can be accessed in the [reportTestDone](https://testcafe.io/documentation/402790/reference/plugin-api/reporter#reporttestdone) event handler. The [testRunInfo.reportData](https://testcafe.io/documentation/402790/reference/plugin-api/reporter?search#testruninfo-object) object contains key pairs of testRunId and reported data. Also, the t.report action immediately raises the reporter's reportData event with data passed from the action.
