### ISSUE TITLE
Inport Data

### ISSUE THREAD

**Issue by fariskur** [DevExpress/testcafe#3629]
### Inport Data?

how to simulate positive and negative cases with exp: data.js

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

If you think that this issue is a bug, feel free to open a new issue, but please make sure to follow the bug template. Thank you in advance.
