### ISSUE TITLE
Incorrect marker in Selector error

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#3639]
### What is your Test Scenario?
```js
import { Selector } from 'testcafe';

fixture `Fixture`.page `github.com`;

test('test', async t => {
   await t
        .typeText(Selector('#user[login]').withText('123').child(), 'test');
});
```
 
### What is the Current behavior?
```
1) The specified selector does not match any element in the DOM tree.

       > | Selector('#user[login]')
         |   .withText('123')
         |   .child()
```
 
### What is the Expected behavior?
```
1) The specified selector does not match any element in the DOM tree.

         | Selector('#user[login]')
       > |   .withText('123')
         |   .child()
```
 
### Your Environment details:
 
* testcafe version:                   1.1.0
* node.js version:                    8.12.0

**Comment by AndreyBelym** [comment]
https://github.com/DevExpress/testcafe/issues/2808 can also be related to this topic.

**Comment by AlexKamaev** [comment]
It is specifics of html attributes containing`'['` and `']'` symbols
 
The `#user[login]` selector is incorrect since `[smth]` means searching by attribute. In this case, the correct selector is `#user\[login\]`.
 
In addition, it is necessary to escape `\` symbols, so you should write it in the following manner: 
`#user\\[login\\]`
 
You can check this behavior in browser dev tools, it works in a similar way.
 
I also checked this type of selectors in Studio with recorder and converter. Everything works as expected.
