### ISSUE TITLE
TestCafe docker image 1.1.1 & 1.1.2 - ERROR Unable to establish one or more of the specified browser connections - Chromium on Docker

### ISSUE THREAD

**Issue by dthisner** [DevExpress/testcafe#3671]
### What is your Test Scenario?
The test failed to run in Chromium when executed in Docker testcafe/testcafe base image (1.1.1 or 1.1.2).

ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

Very similar to: https://github.com/DevExpress/testcafe/issues/3638. We are running with chromium:headless 

It works running with TestCafes image 1.1.0
 
### What is the Current behavior?
Test fails in the CI running with TestCafes docker image 1.1.1 and 1.1.2 and Chromium in headless mode
 
### What is the Expected behavior?
Test passes using chromium headless with TestCafe's docker image 1.1.1 and 1.1.2
 
### What is your web application and your TestCafe test code?
<details>
This is what we use to run our TestCafe scripts: 
More flexible when using `gherkin-testcafe` 

```js
 const createTestCafe = require('gherkin-testcafe');
const fs = require('fs');
let testcafe = null;

function readTestCafeConfig() {
  configData = fs.readFileSync('.testcaferc.json', 'utf8');
  const js = JSON.parse(configData);
  return getValues(js, 'src');
};

function getValues(obj, key) {
  var objects = [];

  for (var i in obj) {
    if (!obj.hasOwnProperty(i)) continue;
    if (i === key) {
      objects.push(obj[i]);
    }
  }
  return objects;
}

createTestCafe('localhost', 1337, 1338)
  .then(tc => {
    testcafe = tc;
    const runner = testcafe.createRunner();
    const src = readTestCafeConfig();

    return runner
      .src([src])
      .reporter(['spec', {
        name: 'json',
        output: 'reports/report.json'
      },
        {
          name: 'xunit',
          output: './test-reports/report.xml'
        }])
      .browsers('chromium:headless')
      .run();
  })
  .then(failedCount => {
    console.log('Tests failed: ' + failedCount);
    testcafe.close();
  });
```

</details>

### Pipeline Setup: 
<details>
<summary>Pipeline setup::</summary>

```js
pipelines:
  default:
    - step: *test
    - step: 
        name: Test the UI
        caches:
          - node
        image: testcafe/testcafe:1.1.1
        script:
          - cp .env.uiTest .env
          - npm ci
          - npm run ci-ui-tests
        artifacts:
          - reports/**
          - test-reports/**
```

Starts the test by running:
```
npm run ci-ui-tests
```
Which runs following commands:
```
    "test-ui": "gherkin-testcafe",
    "test-ui-ci": "node src/tests/testcafeCI.js",
    "ci-ui-tests": "gulp build && start-server-and-test start http://localhost:3000 test-ui-ci",
```

</details>

### Steps to Reproduce:
1. Using above files
2. Execute the pipeline 
3. ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

### Your Environment details:
 
* testcafe version:                   v1.1.0
* node.js version:                    v10.15.0
* command-line arguments:  
* platform and version:          Docker and bitbucket 
* other:                                   using `start-server-and-test` and `gherkin-testcafe`

**Comment by LavrovArtem** [comment]
This information is not sufficient to find the cause of the issue. Could you please start your test without a docker on the local browser and check the errors in console?

**Comment by herobix** [comment]
How does this make sense to run it without a docker when it is the docker image that is causing the issue?
The tests are running perfectly fine without a docker

**Comment by AlexKamaev** [comment]
@herobix
You mentioned that your tests fail in `chromium:headless`. Does it mean that it works in non-headless versions? Do the tests work in Firefox? Do the tests fail in Docker on your local machine or only in CI?

**Comment by herobix** [comment]
When I am running it locally (Without docker), headless for Chrome, Firefox and non-headless works

I am not able to run non-headless browsers on our CI 

Firefox-headless seems to work on 1.1.2

**Comment by benfjohnson** [comment]
My team is also experiencing errors with the latest `testcafe/testcafe` docker image (`d506a6d64866`). We can execute our tests fine using the older `998ab9fcca9f` but as soon as we pull the latest docker image we see the following:

```
+ XVFB_SCREEN_WIDTH=1280
+ XVFB_SCREEN_HEIGHT=720
+ dbus-daemon --session --fork
+ export 'DISPLAY=:1.0'
+ node /usr/lib/node_modules/testcafe/bin/testcafe.js --ports 1337,1338 chromium '/path/to/e2e/tests/*.js' --skip-js-errors
+ Xvfb :1 -screen 0 1280x720x24
+ fluxbox
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported high keycode 372 for name <I372> ignored
>                   X11 cannot support keycodes above 255.
>                   This warning only shows for the first high keycode.
> Internal error:   Could not resolve keysym XF86MonBrightnessCycle
```

**Comment by AlexKamaev** [comment]
@dthisner
Thank you for the additional information. We need time to reproduce and research the issue. Probably we have some problems with Chrome + CI, however, we are not ready to give any estimate right now.
 
@benfjohnson 
Looks like the issue is not related to the original one, so I recommend you create a separate ticket using this [form](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md). Please provide us as much information as possible (testcode, your project, command line arguments)

**Comment by mkubrycz** [comment]
I have a similar issue with testcafe 1.3.3 docker image (92b652e68640). Every time I run tests on docker I get the

`ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.`

I'm using docker-compose to run tests on my remote machine and I have found out that the first run after changing docker-compose configuration always passes, the following ones always fail with this error.

@dthisner 
My workaround, for now, is to use  `--force-recreate` flag with the `docker-compose` command. The equivalent for `docker run` command would be using `--rm` flag. I'm not sure how does docker images caching work on bitbucket pipelines but you could look for an option to enforce container recreation for every pipeline run.

my docker-compose.yml:
```yml
version: '3'

services:
  testcafe:
    container_name: testcafe_test
    image: testcafe/testcafe:latest
    volumes:
      - ./:/tests
    working_dir: /tests
    command: -e -c 2 'chromium:emulation:width=1920;height=1080' ./**/*.test.js -r slack,xunit:log/report.xml
```

my environment details:
testcafe version: v1.3.3
node.js version: v10.16.0
platform and version: docker v19.03.0, testcafe/testcafe image 92b652e68640

**Comment by Dmitry-Ostashev** [comment]
@mkubrycz Thank you for your report and workaround, I believe it will help us research the issue.

**Comment by josephmcasey** [comment]
see https://github.com/DevExpress/testcafe/issues/4306 for additional information

**Comment by hex0cter** [comment]
+1
