### ISSUE TITLE
Improve startup performance - skip the first worker idle page

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#3691]

**Comment by AndreyBelym** [comment]
Currently, we use the idle page to retrieve a native handle of the browser's window. In order to get rid of the idle page, we need to:
 - [ ] Override `document.title` and protect it from rewriting until a native handle is found
 - [ ] Provide a way to execute JS code on the client out of the driver's queue

**Comment by miherlosev** [comment]
'Idle page' waits until all tests were compiled. 
If we remove the 'Idle page' when we should wait for the finish of the test compilation before redirect to the first tested page.
Waiting for the compilation finish before redirect to the first tested page is a bad idea. Headless chrome hangs in this case. Chrome with GUI can abort redirection after 30 seconds. It's very bad, because, in the general case, we don't know the time of test compilation.

After discussing with the team we decided to not remove 'Idle page'.
