### ISSUE TITLE
How to wait until angular execute function

### ISSUE THREAD

**Issue by KaaamilZ** [DevExpress/testcafe#3692]
Hi I want to wait for angular stable state after some action in app. 
I found that angular has `window.getAllAngularTestabilities()` and `isStable` function()

I want to use Client Function to use this but this property is not recognized by TestCafe.

Do you have any idea?

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafeontributing)).

If you think that this issue is a bug, feel free to open a new issue, but please make sure to follow the bug template. Thank you in advance.
