### ISSUE TITLE
Http-server throws error 'events.js' and Error at EINVAL at TTY.onStreamRead

### ISSUE THREAD

**Issue by Prabukmca** [DevExpress/testcafe#3695]
I'm facing the below issue while i have tried to run Http-Server command.

![httpserverIssue](https://user-images.githubusercontent.com/20346782/56186370-d0450800-603c-11e9-971a-ccf0542bbc01.JPG)

I have tried with different port and cleared cache. What i'm missing? Need help.

Thanks

**Comment by AlexSkorkin** [comment]
Hi,

This issue does not seem to be related to testcafe. I assume that you were intended to submit it to the http-server repo at https://github.com/indexzero/http-server.
 
If you think that this issue is a testcafe bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template.

**Comment by Prabukmca** [comment]
Hi, Thanks for the response,
I don't know the testcafe, The same error happening for me while try to create new angular project using ng new command.

**Comment by AlexSkorkin** [comment]
This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask) - an amazing platform for users to ask and answer questions.
