### ISSUE TITLE
testcafe command not found

### ISSUE THREAD

**Issue by PonmaniAnnamalai** [DevExpress/testcafe#3696]
Description:
Testcafe is installed in  Mac OS X 10.14.4 globally, But when ran command testcafe -v, getting below error
-bash: testcafe: command not found
Steps:
In Mac root folder, have installed the testcafe using command "npm install -g testcafe"
Once done, when type the command "testcafe -v", getting error. 
Expected:
version to be displayed
Actual:
-bash: testcafe: command not found
Note : 
npm version is 6.4.1 and node version is v10.15.0. 
Also .npm_global is created as hidden file in system. node_modules folder is shown as Read only file in system.

Am not sure where I am going wrong, kindly help in sorting out, as I found it working  previous day.

**Comment by AlexKamaev** [comment]
I believe that the issue is not related to TestCafe. You can find possible recommendations on StackOverflow:
https://stackoverflow.com/questions/15054388/global-node-modules-not-installing-correctly-command-not-found
https://stackoverflow.com/questions/29955217/global-npm-package-installed-but-command-not-found/43473654
