### ISSUE TITLE
[TypeScript] Subsequent variable declarations must have the same type

### ISSUE THREAD

**Issue by screendriver** [DevExpress/testcafe#3710]
### What is your Test Scenario?

I just started with `testcafe` in one of my TypeScript projects. For my unit tests I use `Jest`. I tried to write a simple hello world test with `testcafe`.
 
### What is the Current behavior?

I get compile time errors because of clashing type definitions for `Jest`. Both, Jest and testcafe, define a global `test()` function:

```sh
node_modules/@types/jest/index.d.ts:36:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'test' must be of type 'TestFn', but here has type 'It'.

36 declare var test: jest.It;
```
 
### What is the Expected behavior?

It should be possible to compile my project with TypeScript as before.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```ts
import { Selector } from 'testcafe';

fixture('Getting Started').page('http://localhost:5000');

test('Page title', async t => {
  const title = 'Hello World';
  await t.expect(Selector('title').innerText).eql(title);
});

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Setup a TypeScript project
2. Add `jest` and `@types/jest` as dependency
3. Add `testcafe` as dependency
4. Write some unit and e2e tests
5. Try to compile your project
 
### Your Environment details:
 
* testcafe version: 1.1.2                  
* node.js version: 10.15.3                   
* command-line arguments: `testcafe chrome:headless 'test/e2e/**/*.ts' --app 'serve public'`  
* browser name and version: 
* platform and version: macOS 10.14.4         

I guess this is related to #1537 (which was closed long time ago)

**Comment by AndreyBelym** [comment]
I can only reproduce the issue when I precompile TypeScript tests instead of passing them to TestCafe directly. I've created an example to demonstrate it: AndreyBelym/typescript-example. When you run `npm run compile-all` that tries to compile TestCafe test files with default settings, TypeScript shows the `Subsequent variable declarations` error. But the error is not emitted if you run `npm run test-testcafe-ts` that runs TypeScript tests with TestCafe directly or `npm run compile-testcafe` that removes Jest globals during compilation.

I think it's a Jest issue actually. Definitions for Jest globals are added automatically in each file by default. In contrast, TestCafe globals are added only when you import something from the `testcafe` package. You can create a suggestion about allowing Jest global definitions to be loaded in the same way in the Jest repository: https://github.com/facebook/jest/issues/new?labels=%3Arocket%3A+Feature+Request&template=feature.md

Right now I see two solutions to this issue:

1. Pass TypeScript tests to TestCafe directly without precompiling and add them to the "exclude" property in your `tsconfig.json`.

2. If you can't pass TypeScript tests to TestCafe directly, use a separate `tsconfig.json` for compiling TestCafe tests. Add your TestCafe tests to the "include" property and explicitly define the "compilerOptions.types" property in this config file.

Both ways are implemented in the AndreyBelym/typescript-example repository with the `test-testcafe-ts` and `compile-testcafe` tasks respectively.

**Comment by screendriver** [comment]
Thank you for the detailed answer 👍
