### ISSUE TITLE
BrowserStack: Test without LocalTesting using application hostname

### ISSUE THREAD

**Issue by carolmirakove** [DevExpress/testcafe#3757]
### What is your Test Scenario?
I would like to send my tests to BrowserStack and NOT use [Local Testing](https://www.browserstack.com/local-testing).
 
### What is the Current behavior?
I was [advised on StackOverflow](https://stackoverflow.com/questions/54680360/testcafe-on-browserstack-without-localtesting) that in order to run TestCafe tests on BrowserStack without Local Testing, I need to deploy my application to a machine with a dedicated public IP address. This is not a viable solution for applications deployed to Cloudfront,  AWS, etc.
 
### What is the Expected behavior?
I can set an env var of `BROWSERSTACK_NO_LOCAL="TRUE"` and send my tests to a URL with an application hostname (e.g., https://github.com/), not an IP address (e.g., https://192.30.253.112/).

This is a real impediment for my team; we need to avoid the latency incurred by LocalTesting. Advice would be much appreciated!

### Steps to Reproduce:
1. set env var `export BROWSERSTACK_NO_LOCAL="TRUE"`
2. `testcafe "browserstack:chrome@73.0:OS X Mojave" myTest.js`
3. go to browserstack automate dashboard for results https://automate.browserstack.com/

expected: 
- Local testing value is False 
- Test completes without error

actual: 
- Local testing value is False 
- Test times out at the TestCafe initial proxy URL, e.g., `http://{host}:{port}/browser/connect/{session}`

```
Start   Duration Action
00:00 
4 Starting Browser
00:04 
76 Open URL http://{host}:{port}/browser/connect/{session}
url  http://{ip}:{port}/browser/connect/{session}
01:24
0 Get URL⇒http://{host}:{port}/browser/connect/{session}
02:44
0 Get URL⇒http://{host}:{port}/browser/connect/{session}
04:04
0 Get URL⇒http://{host}:{port}/browser/connect/{session}
05:24
0 Get URL⇒http://{host}:{port}/browser/connect/{session}
6:56
STOP SESSION
IDLE TIMEOUT
```

Console output:
```
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
```
BrowserStack dashboard output:
Timeout 

### Your Environment details:
* testcafe version: 1.1.3
* node.js version: v10.15.0
* command-line arguments:  `testcafe ie,chrome -e test.js`
* browser name and version: any
* platform and version: any

**Comment by AlexKamaev** [comment]
I agree with the StackOverflow version. Turning the Local Testing off means that there will not be a connection between your machine and BrowserStack servers. Thus your local addresses will not be available. This means that your website should have a public IP address.
Besides, I think that cloud platforms provide public IP addresses for applications.
Anyway, I think this question is related more to BrowserStack/Clould platforms settings than to TestCafe, so I'll close it.

**Comment by carolmirakove** [comment]
Thanks for the quick reply. I understand that you won't entertain this issue but just for clarification, many applications under test do not require the Local Testing tunnel in order to reach them (Selenium and Appium for example do not set a default config on Local Testing - this is an opinion asserted by TestCafe which for some users is a disservice). And cloud platforms do not provide *dedicated* IP addresses for applications, which TestCafe is requiring in order to not use Local Testing.

**Comment by AlexKamaev** [comment]
There is a difference between Selenium and TestCafe. TestCafe uses a built-in proxy server that runs on a local machine. All requests to the target site are processed by this server. If you run TestCafe on your machine, which is not public, this means that the proxy server starts on this local machine. So BrowserStack does not have access to this proxy server without a tunnel. That's why we need to enable LocalTesting - to have access to our proxy.

**Comment by carolmirakove** [comment]
Thank you for the explanation. I have another follow-up question :) 

I understand from your last comment that LocalTesting is necessary because the IP address of the machine running the TestCafe tests is not public. Does that mean that if I run my TestCafe tests on a machine with a public, dedicated IP address I will have success in using `export BROWSERSTACK_NO_LOCAL="TRUE"`?

I now understand the solution on StackOverflow to say that the application should be deployed to a machine with a public, dedicated IP address and that the tests should be run on this same machine. And with your explanation above I am now wondering if the application-under-test needs to be deployed to the same machine; it sounds like no - that as long as BrowserStack can communicate with the machine running the tests we can use Local Testing without a problem. Can you confirm?

**Comment by miherlosev** [comment]
The BrowserStack emulator is located on the cloud machine and doesn't know how to navigate to the tested website deployed on your machine. When you open the page `http://localhost:8080` in the emulator, it means the browser will try to find a website on the cloud machine on which the emulator is hosted. BrowserStack's 'LocalTesting' feature allows you to connect your 'localhost' with the emulator's 'localhost'. The 'LocalTesting' feature creates a tunnel between your and emulator computers. 
In most cases, you don't need to turn off 'Local testing'. It's easy to set up and use. Also, it's private because nobody can get access to your website.
 
If you turn off the 'Local testing' feature (export BROWSERSTACK_NO_LOCAL="TRUE"), the tunnel between your and emulator computers is aborted. In this case, the tested website should be reached from any place such as `https://google.com`, `https://facebook.com`.
Note, your tests can be executed on any machine. It matters only where the website is deployed.

**Comment by carolmirakove** [comment]
@miherlosev I'm familiar with Local Testing; my situation is as follows:
- my application CAN be reached from any place such as https://google.com, https://facebook.com
- I do not want to use Local Testing because it adds latency to my test runs with no added value

**Comment by carolmirakove** [comment]
My outstanding question on this issue is: 
I read @AlexKamaev 's last comment https://github.com/DevExpress/testcafe/issues/3757#issuecomment-487927579
to say that TestCafe defaults to Local Testing so that BrowserStack can communicate with the machine running the tests. Is that correct? If yes, is it also correct that if I run my tests on a machine with a dedicated, public IP address I can then use `BROWSERSTACK_NO_LOCAL="TRUE"`?

**Comment by AndreyBelym** [comment]
The comment from https://github.com/DevExpress/testcafe/issues/3757#issuecomment-487927579 is more correct. Your TestCafe machine should have a public IP address or domain name in order to run tests without establishing a BrowserStack Local tunnel. Since BrowserStack will access your site through the TestCafe proxy, there is no requirement of public IP/domain for your site. It just should be accessible from the machine that runs TestCafe.
