### ISSUE TITLE
File upload issue

### ISSUE THREAD

**Issue by MatiasPelemene** [DevExpress/testcafe#3820]
### What is your Test Scenario?
an input type file but is not visible
 
### What is the Current behavior?
the attribute file and the value are loaded with the data but the file is not being uploaded
 
### What is the Expected behavior?
Upload the file
 
### What is your web application and your TestCafe test code?
test cafe code:
.setFilesToUpload(myAccountPage.uploadFileInput, '../../mock-files/originalpicture.png')

the locator : this.uploadFileInput = Selector('#file-upload');

the html:
<input class="hidden" id="file-upload" type="file">
 

### Your Environment details:
 
* testcafe version:  0.22                 
* node.js version:  v8.11.4                  

* browser name and version: Chrome Version 74.0.3729.131 (Official Build) (64-bit)
* platform and version:          Windows 10

**Comment by helen-dikareva** [comment]
Please note that the `setFilesToUpload` and `clearUpload` actions only allow you to manage the list of files for upload. 
These files are uploaded to the server after you initiate an upload, for example, when you click the Upload or Submit button on a webpage. For example
```js
import { Selector, ClientFunction } from 'testcafe';

fixture`fixture`
    .page`http://localhost/site/`;

test('test', async t => {
    const fileInput = Selector('input[type=file]');

    const getUploadedFileName = ClientFunction(() => {
        const input = fileInput();

        if (!input.files.length)
            return;

        return input.files[0].name;
    }, { dependencies: { fileInput } });

    await t
        .expect(getUploadedFileName()).notOk()
        .setFilesToUpload(fileInput, './_uploads/image.png')
		
	//after using setFilesToUpload, you can check an input's file attribute
        .expect(getUploadedFileName()).eql('image.png')

	//but you can check the real file upload only after submitting a form
        .click('#submit');
});
```

**Comment by berrutti** [comment]
@helen-dikareva I'm working with Matias on this one. After some more research, we found that the input is being filled with the file list, the problem is that the front end is not responding in the same way with testcafé, as with manual testing.

Could it be that changing the value of the file input is not triggering some event that the front-end needs?
Are you aware of some limitation on testcafé regarding the file upload that we should be aware of?
I know that using the OS window is not possible because it is outside of the browser. I believe our issue has to be related to some event not being fired.

On a somewhat related question. Is there a way inside of testcafé to force / trigger some event?

Thanks for your help. It's much appreciated as usual

**Comment by miherlosev** [comment]
@berrutti 

> After some more research, we found that the input is being filled with the file list, the problem is that the front end is not responding in the same way with testcafé, as with manual testing.

The behavior should be the same.
I see that you are using a very old TestCafe version - `0.22`.
Try to update to the latest version - `1.1.4`. If the problem still persists, please provide us with a simple example. In this case, we can investigate the problem faster and find a precise solution.
