### ISSUE TITLE
Looking for a plugin for LambdaTest like SauceLab and BrowserStack

### ISSUE THREAD

**Issue by qarachit** [DevExpress/testcafe#3896]
Dear,
Testcafe is an amazing tool, I am part of LambdaTest product team and looking for testcafe selenium webdriver plugin for LambdaTest similar to SauceLab and BrowserStack you have provided. Let me know if you need anything from us and suggest the procedure to follow in order to achieve it.

Thanks,
LambdaTest Product Team

**Comment by miherlosev** [comment]
Hi @qarachit 
 
TestCafe doesn't use the WebDriver internally. Instead of the WebDriver, TestCafe uses a [URL-rewriting proxy](https://github.com/DevExpress/testcafe-hammerhead) to communicate with the browser. 
This proxy injects the driver script that emulates user actions into the tested page.
The TestCafe's browser providers for `SauceLabs` and `BrowserStack` use the public API of these platforms to communicate with browsers. 
To support running tests in LambdaTest platform you need to implement a custom browser provider. 
See the step-by-step instruction in the [browser-provider-plugin](https://devexpress.github.io/testcafe/documentation/extending-testcafe/browser-provider-plugin/) help topic.

**Comment by AndreyBelym** [comment]
I close this issue since the requested plugin is implemented in https://www.npmjs.com/package/testcafe-browser-provider-lambdatest by LambdaTest developers 🎉
