### ISSUE TITLE
Is there any way to run testcafe suite on Smart TVs or Android TVs?

### ISSUE THREAD

**Issue by rajat1986** [DevExpress/testcafe#3901]

**Comment by rajat1986** [comment]
I have test automation framework developed using TestCafe and working fine on browsers. However, I have new requirement to run test suite on the application installed on Smart TVs. So, I searched for the possible options to re-use my test cases. But I couldn't find any except using Suitest automation library in JS and write new test scripts using the new library that will run specifically on TVs.

I am still looking for an alternative solution which can save my effort by re-using test cafe scripts that use selector which works fine on browsers, but not apps on devices like Smart TVs. 
Below are the possible alternatives and please clarify if this can be achieved - 
1. Can we extend the existing Selector capability to identify elements on Apps?
2. If not, then how can we integrate Testcafe with Suitest automation library or Android Studio even?

Kindly suggest if there is any other alternative solution to the problem.

Thanks
Rajat

**Comment by AlexKamaev** [comment]
TestCafe is intended to test web applications based on web technologies like HTML and JS.
If your application is webview-based, it is technically possible to use TestCafe for testing WebView based apps (built with Cordova/PhoneGap/etc).
Please follow the https://github.com/DevExpress/testcafe/issues/2252 to see the progress.
However, we cannot give any estimate as to when this feature will be implemented, since it requires much time.
As a workaround, I can only recommend you run your application (if it is built with HTML + JS) in the browser of your Smart TV and connect it as [remote ](https://devexpress.github.io/testcafe/documentation/recipes/test-on-remote-computers-and-mobile-devices.html)
>Can we extend the existing Selector capability to identify elements on Apps?

 If your application is webview-based, you do not need to extend anything.
>If not, then how can we integrate Testcafe with Suitest automation library or Android Studio even?

You don't need any integration if your application is webview-based.
