### ISSUE TITLE
TestCafe proxy leaves control after working offline on firefox browser

### ISSUE THREAD

**Issue by jiteshsojitra** [DevExpress/testcafe#3907]
TestCafe proxy leaves control after working offline on firefox browser. Please note that, i'm using node-key-sender node package and even after coming online TestCafe proxy doesn't give control back.

**Error:**
ERROR The Firefox 67.0.0 / Windows 10.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

### What is your Test Scenario?
1. Login to client using TestCafe
2. Press keyboard key press (ALT+F + K)
3. Offline node is successful in Firefox
4. Tried by going online if TestCafe gives control back but no luck!
 
### What is the Current behavior?
- Firefox browser gets disconnected.
 
### What is the Expected behavior?
- Even after TestCafe proxy leaves control, control to browser should present so we can run tests further. We need to check application in offline mode.
 
Your website URL (or attach your complete example):
- Any

```
await common.sleep(5000);
let ks = require('node-key-sender');
ks.setOption('globalDelayPressMillisec', 1000);
ks.setOption('globalDelayBetweenMillisec', 1000);
ks.setOption('startDelayMillisec', 1000);
ks.setOption('caseCorrection', false);

ks.startBatch();
ks.batchTypeKey('alt')
	.batchTypeKey('f')
	.batchTypeKey('k');
ks.sendBatch();
await common.sleep(10000);
ks.startBatch();
ks.batchTypeKey('alt')
	.batchTypeKey('f')
	.batchTypeKey('k');
ks.sendBatch();
``` 

### Your Environment details:
 
* testcafe version: 1.2.0
* node.js version:  10.0
* browser name and version:  Firefox 67
* platform and version:  Windows 10

**Comment by Farfurix** [comment]
@jiteshsojitra 

Hello,

TestCafe has a [heartbeat timeout](https://github.com/DevExpress/testcafe/blob/49a38bc2b78cd24cfe17a137036f8eace3c01572/src/browser/connection/index.js#L22), and as a result you see the following error:
```
ERROR The Firefox 67.0.0 / Windows 10.0.0 browser disconnected.
This problem may appear when a browser hangs or is closed, or due to network issues.
```
Browser connection is necessary and in the case of `heartbeatTimeout` TestCafe attempts to [restart the browser](https://github.com/DevExpress/testcafe/blob/49a38bc2b78cd24cfe17a137036f8eace3c01572/src/browser/connection/index.js#L128). That's why the "offline" browser mode cannot guarantee a stable test result.

I suggest you intercept all requests with ["Mocking HTTP Responses"](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/#mocking-http-responses) or ["Creating a Custom HTTP Request Hook"](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/#creating-a-custom-http-request-hook) in your scenario.

If it doesn't help, please provide us with your project, a detailed scenario description and your test code. Our team will research your particular case.
