### ISSUE TITLE
Simplify handling special space symbols in elements

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#3937]
### What is your Test Scenario?
* Use `Selector.withText` for an element that has a `&nbsp;` in its `textContent`;
* Assert an element's text that contains `&nbsp`
### What are you suggesting?
`&nbsp;` is represented by the `\u00a0` char code, the regular space is the `\u0020` char code. We should allow `\u0020` to match all space symbols including `&nbsp` in selectors and assertions. Additionally, maybe we should perform HTML-escape sequences to Unicode conversions?

### What alternatives have you considered?
Use `\u00a0`?

### Additional context
https://stackoverflow.com/questions/56757405/is-there-any-way-to-click-the-sign-in-link-on-github-page-using-javascript-for

**Comment by fmancardi** [comment]
Hi, 
IMHO adding this feature at least on assertions is important. 
May be adding an option to indicate how to match on the eql() and nEql() can be a good approach (anySpaceCharIsOK =true/false). I do not see this as an overkill.
Please consider that when you start your 'journey' to test automation is very frustrating to see your assertions failed and you normally do not understand why the strings are different.
Yesterday , I've faced this situation again. :(

Adding the option (anySpaceCharIsOK) will allow people to check for specific space code if they need this check.

regards

**Comment by AlexKamaev** [comment]
We decided to close the issue since the withText option supports the RegEx argument:
[https://testcafe.io/documentation/402740/reference/test-api/selector/withtext#withtextre](https://testcafe.io/documentation/402740/reference/test-api/selector/withtext#withtextre)
You can use `match` in Assertions as well:
[https://testcafe.io/documentation/402723/reference/test-api/testcontroller/expect/match](https://testcafe.io/documentation/402723/reference/test-api/testcontroller/expect/match)
Thus, you can use \s for these purposes.
