### ISSUE TITLE
Support Chromium-based Edge

### ISSUE THREAD

**Issue by chhschou** [DevExpress/testcafe#3943]
### What is your Test Scenario?

Edge is now available on mac as a dev preview (https://www.microsoftedgeinsider.com/en-us/?form=MO12FS&OCID=MO12FS). I want to test on the edge browser on a mac.

### What are you suggesting?

Support calling edge browser on a mac (i.e. make `testcafe edge` work)

**Comment by AlexKamaev** [comment]
Thank you for pointing this out. Since Edge for Mac is based on Chromium, I think TestCafe should correctly work with it. However, at present, you can use Edge only as a remote browser. Please refer to the following article to get details: https://devexpress.github.io/testcafe/documentation/recipes/test-on-remote-computers-and-mobile-devices.html
I checked this approach on some tests and it seems to work correctly. Please try it as a workaround.
 
Meanwhile, we are going to officially support Edge for Mac, however, I cannot give you any estimates on this.

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe-browser-tools/issues/181

**Comment by AlexKamaev** [comment]
Implemented in https://www.npmjs.com/package/testcafe/v/1.8.0
