### ISSUE TITLE
Ability to disable page reload between tests in order to speed up test execution

### ISSUE THREAD

**Issue by Evilweed** [DevExpress/testcafe#3945]
Please add ability to disable page reload between tests in order to speed up test execution.

This would probably need disabling splitting `test` between browsers in spec file that need to be executed in this manner.

**Execution time of my fixture WITHOUT this feature:**
- 10 minutes;

**Execution time of my fixture WITH this feature:**
- 1 minute;

I am aware that sharing browser state sometimes can backfire but this is what I can live with - what I can't live with is **2 hours time execution** of all of my fixtures, and paying a lot of money on CI provider, **when instead it could be only 12 minutes**.

### What is your Test Scenario?
```
fixture(`User Area in Admin Panel after Checkout`)
    .beforeEach(async (t) => {
        const uniqueUserEmail = generateEmail();
        await goToProductPage();
        await designProductIn3D(); // <--- This takes a lot of time!
        await goToCheckout();
        await completePayment(uniqueUserEmail);
        await goToAdminPanelPage();
    });


test('has proper email value', async t => {
    expect(emailInput.value).eql('something');
});

test('allows changing email', async t => {
    await changeEmail();
    expect(emailInput.value).eql('something-else');
});

test('allows copying to clipboard', async t => {
    await clickCopyToClipboardButton();
    expect(await getClipboard()).eql('something-in-clipboard');
});

...
```

### What are you suggesting?
```
fixture(`User Area in Admin Panel after Checkout`)
    .doNotReloadBrowserBetweenTests
    .beforeAll(async (t) => {
        const uniqueUserEmail = generateEmail();
        await goToProductPage();
        await designProductIn3D(); // <--- This takes a lot of time!
        await goToCheckout();
        await completePayment(uniqueUserEmail);
        await goToAdminPanelPage();
    });

test('has proper email value', async t => {
    expect(emailInput.value).eql('something');
});

test('allows changing email', async t => {
    await changeEmail();
    expect(emailInput.value).eql('something-else');
});

test('allows copying to clipboard', async t => {
    await clickCopyToClipboardButton();
    expect(await getClipboard()).eql('something-in-clipboard');
});

...
```

### What alternatives have you considered?
None.

### Additional context
None.

**Comment by arubtsov** [comment]
Hi @Evilweed ,
 
Thank you for your inquiry. We already discussed this feature [here](https://github.com/DevExpress/testcafe/issues/1770), so I will close the current thread as a duplicate.
Here are the links to the key points of the discussion: 
1) [Current sate](https://github.com/DevExpress/testcafe/issues/1770#issuecomment-431854742)
2) [Restrictions](https://github.com/DevExpress/testcafe/issues/1770#issuecomment-387427159)
2) [The commit](https://github.com/DevExpress/testcafe/commit/29621ec7f8132f0d7b387a29c0c0bec5e304bcca) where this functionality was implemented.
3) [The PR](https://github.com/DevExpress/testcafe/pull/2643) with a draft of the documentation.

I would like to emphasize that if you are going to use this feature, you will do it **on your own risk** because it can be **extremely unstable** and we cannot guarantee that it won't be changed in the future.
