### ISSUE TITLE
How to make testcafe wait until a fixture is done executing before moving to the next fixture when using concurrency?

### ISSUE THREAD

**Issue by kiratjot** [DevExpress/testcafe#4004]
I want to run testcafe tests concurrently BUT only executing against 1 file at a time.
In other words, I want to wait for the all the tests of a specific fixture to be done executing before the tests from the next fixture start executing.
How do I do it?

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.
We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafeontributing)).
If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template. Thank you in advance.
