### ISSUE TITLE
Common Testcafe library

### ISSUE THREAD

**Issue by SagivCohen** [DevExpress/testcafe#4023]
Hi,
Im trying to create a node library that will use all of my UI projects.
The main purpose of this library is to have all the common logic to perform system tests for all of my F.E projects (Micro Frontend Architecture) like: Registration, Login, Navigation to pages, etc..
This common library depends on `testcafe/selectors` which causing problems in running the testcafe tests.

All of my tests (in the F.E projects) are written in es6, so as this common library. 
It seems to have troubles loading the logic from the library and i'll explain:

- If I do not perform the transpiling to the common library and try to import it:
-- Everything works fine as long as I use `npm link` to link the common package in my F.E project.
-- I failed to load the library due to: "Unexpected token import"

- When I use babel to transpile the common library, I get errors from testcafe:
```
An error occurred in Selector code:
ReferenceError: builder is not defined
```

My question:
Is it possible to have an external library that will contain testcafe code (such as page models that contains all the relevant selectors)?
If so, what is the right way to do so?

Thanks a lot!

**Comment by miherlosev** [comment]
Hi @SagivCohen 

> Is it possible to have an external library that will contain testcafe code (such as page models that contains all the relevant selectors)?
> If so, what is the right way to do so?

Yes, it's possible. You can find step by step instructions [here](https://devexpress.github.io/testcafe/documentation/recipes/extract-reusable-test-code/use-page-model.html).

**Comment by SagivCohen** [comment]
Hi, @miherlosev 
First, thanks for your time!
Second, I read this docs and there is no mention at all of an ׳external library׳.
My current common-library already contains these page model, it was not the problem.

The problem I'm trying to solve is:
How can I import this common-library (bunch of page models) in my UI project (in order to perform system tests)?

- Should I transpile the common-library?  Should not I?
- Is there a way to publish this common-library without any transpiling (in ES6 syntax)?

Thanks!!

**Comment by devmondo** [comment]
@SagivCohen , 
I have a similar setup, and I am developing custom tools around `testcafe` , so I thought I would share my experience if it helps :) 

what i advice:
1 -  you can keep es6 or TS code but make sure that the `main` property in `package.json` in your library point to correct entry file.
2 - if you want to transpile, use `webpack`, `fuse-box`, or any transpiler again follow advise 1 above.
3- use `npm ` link to link to that library, beware that sometimes you might need to install some lib in your target project even though they exist in your library. this is due to ` npm link` and how it works today.

`testcafe ` uses babel internally with typescript to transpile files, also the latest version has the ability to allow you to point to a custom `tsconfig.json` so that you can have control over your transpilation rules.

for small projects, I don't bother and use `testcafe ` directly and let it transpile typescript files, but for custom tools and big ones, i use `webpack ` or fuse box to have finer control. basically, I let the bundler transpile test files, and just point `testcafe ` to them.

the `builder is not defined` error you are getting is most probably due to some transpilation issues, typescript default imports, etc...

let me know if you want extra help, I always like to give back to the community and `testcafe ` is cool  :)
