### ISSUE TITLE
Duplicate HTML element when running test

### ISSUE THREAD

**Issue by smunoz-temperies** [DevExpress/testcafe#4027]
### What is your Test Scenario?

Open a pop up to upload a document with a form data
 
### What is the Current behavior?

 I open the pop-up window and get duplicated elements.
![dupplicateElemnt](https://user-images.githubusercontent.com/52670000/61150743-898b7080-a4ba-11e9-91ef-2b53fe5c7a96.png)

### What is the Expected behavior?

Should be only one element with Save, Cancel and Help button
 If i reproduce it manually I don't get duplicated elements.
![2019-07-12 15_56_58-Window](https://user-images.githubusercontent.com/52670000/61152055-d290f400-a4bd-11e9-8a93-11517ea0a97b.png)

### What is your web application and your TestCafe test code?

 -
Your website URL (or attach your complete example):
![2019-07-12 11_01_52-Window](https://user-images.githubusercontent.com/52670000/61151600-b476c400-a4bc-11e9-8039-416b0bb1117d.png)

### Your Environment details:
 
* testcafe version:                   1.2.0
* node.js version:                    v10.15.3
* command-line arguments:  
* browser name and version:  Chrome 75
* platform and version:           Windows
* other:

**Comment by AlexKamaev** [comment]
I apologize for the late response.
This issue is unclear since the TestCafe code should not duplicate any DOM elements. I see some error in your browser console. Probably, this error somehow affects the rendering.
I see the site url in your screenshots. However, I cannot get access to it since it requires authentication. Could you please create a user for testing purposes and share their credentials with us?
I would also appreciate it if you provide us with your testing code.
