### ISSUE TITLE
Add capability to reload the tested page

### ISSUE THREAD

**Issue by blanche-pinto** [DevExpress/testcafe#4049]
### What is your Test Scenario?
I'm currently writing tests which require me to reload a page quite frequently. I'm using ```location.reload(true)``` to do this.

### What are you suggesting?
TestCafe should add a feature such as ```testController.reloadPage()``` which would simplify reloading a page. 

### What alternatives have you considered?
My code uses ```testController.eval(() => location.reload(true))```. However, it is tedious to have this repeat in the code.

**Comment by miherlosev** [comment]
Hi @blanche-pinto 

Thank you for this suggestion. I think this will be a useful feature.

For TestCafe team: `Selenium Webdriver` has the same capability - [driver.refresh()](https://selenium-python.readthedocs.io/api.html)

**Comment by AlexKamaev** [comment]
We decided to close this issue since we have higher priority tasks. We recommend using the workaround with `t.eval` as described in the initial post. You can also create your custom action to reload a tested page and reuse it in your test. Please refer to the following help topic for details:
[https://testcafe.io/documentation/404150/guides/advanced-guides/custom-test-actions](https://testcafe.io/documentation/404150/guides/advanced-guides/custom-test-actions)
