### ISSUE TITLE
'The process not found' errors at the end of my test

### ISSUE THREAD

**Issue by KJHofstede** [DevExpress/testcafe#4081]
After my update to testcafe 1.3.3 I get a list of erros as you can see in the screenshot below:
![image](https://user-images.githubusercontent.com/46562822/62034617-9f08d600-b1ee-11e9-9301-44771e6bbd14.png)

I use npm X and I use puppeteer as my browser. I run my tests in quarantaine and in parallel.

![image](https://user-images.githubusercontent.com/46562822/62034834-fc9d2280-b1ee-11e9-9741-6322b9814b9c.png)

Does anyone know why the errors are there and how to get rid of them?

**Comment by miherlosev** [comment]
I am afraid this information is not sufficient to find the cause of the issue. Could you please provide a page or a small example so that we can reproduce it on our side?

**Comment by KJHofstede** [comment]
No, sorry, and I don't think the issue is with a specific page. 

It's puppeteer unfortunately. I don't have the issue when testing with chrome.

**Comment by AndreyBelym** [comment]
Could you please clarify why do use `puppeteer` with TestCafe? TestCafe supports headless Chrome [out-of-the-box](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/testing-in-headless-mode.html) and uses Chrome Debug Protocol under the hood for capturing browser screenshots and [enabling the device emulator](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.html) like `puppeteer`. 

If this issue is specific to `puppeteer`, it's better to address this issue in the https://www.npmjs.com/package/testcafe-browser-provider-puppeteer repository.

**Comment by KJHofstede** [comment]
Thanks, I will. Thanks for the other suggestions.
