### ISSUE TITLE
how can we handle javscriptexecutor in testcafe

### ISSUE THREAD

**Issue by shanthkumar043** [DevExpress/testcafe#4102]
how can we handle java script executor using test cafe.i have implemented using selenium .
same way i want to implement in test cafe.

snippet code.

((JavascriptExecutor) driverv)
		.executeScript("$('1F7D33D4CEF94105A967BC94031702CF_opt-in-checkbox').removeClass('hide')");
		((JavascriptExecutor) driverv)
		.executeScript("document.getElementById('1F7D33D4CEF94105A967BC94031702CF_opt-in-checkbox').click();");

**Comment by arubtsov** [comment]
Thank you for your inquiry. You can use [ClientFunction](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client/) to execute Javascript on the client side. If you face difficulties with the implementation, I would suggest you [ask them on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe/blob/master/CONTRIBUTING.md)).
 
If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template. Thank you in advance.
