### ISSUE TITLE
Automatically verify that the action target is not disabled/readonly

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#4106]
https://stackoverflow.com/questions/57331221/what-is-expected-behavior-when-testcafe-clicks-on-a-disabled-button-or-type-text

### What is your Test Scenario?

You click a button or type into an input, and you want to ensure that this button/input is not disabled/readonly.

### What are you suggesting?

The test automatically fails when you try to click/type into a disabled/readonly element.

### What alternatives have you considered?

You can add an assertion that verifies this fact:

```
await t.expect(input.hasAttribute('readonly').notOk().typeText(input,'text');
```

But you may want TestCafe to always perform this verification, without having to write an assertion every time.

### Additional context

On the other hand, actions with disabled/readonly elements might be intended.

**Comment by dskochubey** [comment]
Are there any updates?

**Comment by AndreyBelym** [comment]
Currently we have no updates about this feature. We keep the issue opened and consider discussing and implementing in the future.

**Comment by Artem-Babich** [comment]
After additional research, we decided not to implement this functionality. The official workaround is to write tests that will check the element's disabled state before interaction or/and confirm the corresponding action after clicking on this element. Note that you can also use [Custom Actions](https://testcafe.io/documentation/404150/guides/advanced-guides/custom-test-actions) in order to create a custom click action with confirmation and reuse it in your tests.
