### ISSUE TITLE
"Cannot find module './assets/content-types'" when using version 1.4.X in live mode 

### ISSUE THREAD

**Issue by rssfrncsrenishaw** [DevExpress/testcafe#4177]
#4012 # What is your Test Scenario?

 
### What is the Current behavior?

Live mode fails to start when using version 1.4.X. When I revert back to 1.3.X it works fine.

![image](https://user-images.githubusercontent.com/50481613/63328604-55606680-c328-11e9-970d-fedbd28b8234.png)
 
### What is the Expected behavior?

It behaves the same as 1.3.X.
 
### What is your web application and your TestCafe test code?

Private sorry.

**Comment by miherlosev** [comment]
Hi @rssfrncsrenishaw 

I cannot reproduce the problem by your description with `testcafe@1.4.1`.  Could you please provide an example so that I can reproduce the problem on my machine?

**Comment by rssfrncsrenishaw** [comment]
Just created a clean project and it is working fine.

I wonder if this is a typescript config (source project) issue.

**Comment by AndreyBelym** [comment]
Another possible reason is that `npm` failed to update TestCafe properly. Try to execute the following commands in your project:
```
npm i -D testcafe@latest
npm cache clean -f
npx del-cli node_modules/
npm i
```

**Comment by rssfrncsrenishaw** [comment]
I use Yarn with an offline mirror, I deleted the entire mirror, cleaned the cache and node modules re-installed and still having the same error.

**Comment by rssfrncsrenishaw** [comment]
The folder "assets" is physically missing 
![image](https://user-images.githubusercontent.com/50481613/63356152-316c4780-c35f-11e9-8fa9-99e0b748a819.png)

**Comment by AndreyBelym** [comment]
I've downloaded the TestCafe package from the NPM registry and it contains the `assets` directory:
![image](https://user-images.githubusercontent.com/4479386/63415811-f9b8da80-c406-11e9-809f-1ed2250bc9b8.png)

You can use `npm show testcafe dist.tarball` or `yarn info testcafe dist.tarball` to get the package URL (in my case it is `https://registry.npmjs.org/testcafe/-/testcafe-1.4.1.tgz`), download the package and check its content.

It seems that this issue is caused by `npm`, `yarn` or your package mirror. Please create bug reports in the corresponding projects.
