### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by belarba** [DevExpress/testcafe#4180]
I need to test an upload screen, but I'm having problem with the .setFilesToUpload. I can`t upload a file.

I tryed .setFilesToUpload(Selector('input').withAttribute('type','file'), '../src/assets/logo.png') and .setFilesToUpload(Selector("#customInputFile"), "../src/assets/icon.png")

But in both cases nothing is uploaded. The screen waits for it, but no file are uploaded

```
<template>
  <div>
    <div class="file-container" v-if="!image">
      <label>{{ label }}</label>
      <div class="input-group">
        <input
          type="text"
          @dragover="handleDragAndDrop"
          @dragenter="handleDragAndDrop"
          @dragleave="handleDragAndDrop($event, true)"
          @drop="onFileChange"
          v-bind:class="{ error: dataError }"
          :placeholder="dataPlaceholder"
          :value="dataFileName"
          readonly

        />
        <span class="input-group-btn">
          <button class="file-button" type="button" @click="launchFilePicker">
            SELECT A FILE
          </button>
        </span>
      </div>
      <input
        type="file"
        :value="filePayload"
        @input="onFileChange"
        ref="file"
        id="customInputFile"
        style="display: none"

      />
      <span v-if="dataError" class="errorMessage">{{ dataErrorMessage }}</span>
    </div>
    <div class="file-container" v-else>
      <img :src="image" />
      <button @click="removeImage">Remove image</button>
    </div>
  </div>
</template>
```

**Comment by LavrovArtem** [comment]
I see that you posted the same question on [StackOverflow](https://stackoverflow.com/questions/57582963/testcafe-upload-file). Let's continue discussing this problem there.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

If you think that this issue is a bug, feel free to open a new issue. Please make sure to follow the bug template. Thank you in advance.
