### ISSUE TITLE
How to run testcafe in docker with reporter option in Jenkins 

### ISSUE THREAD

**Issue by mishmaccas** [DevExpress/testcafe#4204]
Good afternoon Dev Express Friends

 If I want to run my tests from a Jenkins slave using a command such as this which includes a reporter it always fails.

(and definitely have installed the reporter dependencies we need using npm install)

this is the command in the Jenkins file

`sh 'docker run --shm-size=3g -v $(pwd):/web-ui-test -t testcafe/testcafe "chromium:headless --no-sandbox" project/tests/testfolder --skip-js-errors --reporter html'`
       
PS includes the option --reporter xxxx ( and tried html json allure)

Can you please explain why I get an error saying:

_The provided reporter "xxxx" does not exist. Check that you have specified the report format correctly?_

Much appreciated if someone could explain what I am doing incorrectly?

**Comment by alexey-lin** [comment]
Hi @mishmaccas,

The folder containing reporters (i.e., folder inside of which `npm install testcafe-reporter-html` was called) should be mounted and set as the working directory in order to TestCafe be able to find them.

For example, `sh 'docker run --shm-size=3g -v ${PATH_TO_TESTS}:/tests -v ${PATH_TO_REPORTERS}:/reporters -w /reporters -t testcafe/testcafe "chromium:headless --no-sandbox" /tests/**/*.js --skip-js-errors --reporter html'`

**Comment by mishmaccas** [comment]
THANK YOU @alexey-lin   Regarding the -w option,  I am assuming it either means WITH or WONDERFUL.  Much appreciated.
