### ISSUE TITLE
Make clearing sessionStorage and localStorage configurable for navigateTo

### ISSUE THREAD

**Issue by jordangarside** [DevExpress/testcafe#4376]
This is similar to:
https://github.com/DevExpress/testcafe/issues/2243

### What is your Test Scenario?
I'd like to do some stuff on a page and then navigate to a new page without going through the interface, while preserving localStorage.

### What are you suggesting?
I'd like `navigateTo` to have an additional `options` parameter that allows disabling the clearing of state.

### What alternatives have you considered?
Trying to re-work my tests to not use `navigateTo`.

**Comment by jordangarside** [comment]
Found somewhat of a solution for this:
```
const goTo = ClientFunction(url => {
  return (document.location.href = url)
})
```

Only issue is that I can't `await` this.

**Comment by miherlosev** [comment]
Hi @jordangarside 

Could you please provide an example that illustrates the problem?

**Comment by AndreyBelym** [comment]
TestCafe clears storages only when it starts a new test. If storages disappear after a call to `t.navigateTo`, it can be a problem caused by the page cache. Take a look at the [--disable-page-caching](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--disable-page-caching) switch, it can help you with problematic cache settings.

**Comment by jordangarside** [comment]
Hmmm, this may be the case. I'm not sure why storage was being cleared in my case. I ended up going with a solution that bypasses using local storage.
