### ISSUE TITLE
TypeScript can't compile tests using Testcafe version >1.6.0 if module @types/jest is in the project

### ISSUE THREAD

**Issue by LucasMaupin** [DevExpress/testcafe#4435]
TypeScript can't compile tests using Testcafe version >1.6.0 if module @types/jest is in the project.

When I compile the tests I get the following compilation errors:
- "Property 'expect' does not exist on type 'DoneCallback'."
- "Property 'click' does not exist on type 'DoneCallback'."
- "Property 'wait' does not exist on type 'DoneCallback'."
- "Property 'before' does not exist on type 'It'."

In this case _test_ is of type _jest.It_ instead of _TestFn_. There seems to be an issue in the declaration file _index.d.ts_ - "Cannot redeclare block-scoped variable 'test'.ts(2451)"

**Comment by vire** [comment]
@AndreyBelym I'd put a note on this into https://github.com/DevExpress/testcafe/blob/master/docs/articles/documentation/test-api/typescript-support.md

WDYT?

**Comment by AndreyBelym** [comment]
I think it isn't necessary since this problem is fixed in testcafe@1.6.1. For those people who like to precompile their tests, it's better to put a note in [@types/jest README](https://www.npmjs.com/package/@types/jest), since `jest`'s definitions actually cause the problem. It can be reproduced easily with other test frameworks like mocha, QUnit, etc. And we have to use workarounds to stay compatible with more popular test frameworks like `jest`.

**Comment by vire** [comment]
@AndreyBelym actually with

- `testcafe@1.6.1`
- `jest@24.9.0`
- `@types/jest@24.0.22`

I have types collision where my testcafe files work as expected because `fixture` and `test` resolve to

```
// node_modules/testcafe/ts-defs/index.d.ts
declare const fixture: FixtureFn;
declare const test: TestFn;
``` 

while unit test files written in jest `test(...)` resolve as well to  

```
// node_modules/testcafe/ts-defs/index.d.ts
declare const fixture: FixtureFn;
declare const test: TestFn;
``` 

there are multiple options

1) not using `test` in jest's files  😞 
2) creating typescript definition file `*.d.ts` workaround
3) modifying types on either `@types/jest` (what should be the desired definition?) or modifying `testcafe` definition files (that was done in `testcafe@1.6.1`

Do you have a suggestion how to resolve this problem?

**Comment by AndreyBelym** [comment]
You will get `testcafe`'s definitions for `test` only if you start `*.ts` files with the `testcafe` command or if you import the `testcafe` module in other `*.ts` files. Only definitions from the `node_modules/@types` directory are loaded automatically by default when compiling any TypeScript source file. Please, create a new bug report and provide an example that can be used to reproduce the problem, or at least provide your configuration files (`tsconfig,json`, `package.json`, `Gulpfile.js`, etc.) and your directory structure.
