### ISSUE TITLE
Documentation at your Test API doesn't talk about XPathSelector

### ISSUE THREAD

**Issue by stevenmchaves** [DevExpress/testcafe#4548]
### What is the Current behavior?
https://devexpress.github.io/testcafe/documentation/test-api/

Doesn't include XPathSelector information.
 
### What is the Expected behavior?
To Include XPathSelector information.

**Comment by miherlosev** [comment]
Hi @stevenmchaves 

At present, our documentation does not contain information about the use XPath selectors because we don't have built in support for them. We will add documentation once  the feature was implemented.

See example of using XPath selectors with TestCafe here: https://github.com/DevExpress/testcafe/issues/1178#issuecomment-350249305.
