### ISSUE TITLE
[Multi browser window] Refactor pageId to windowId

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#4586]
IMHO `pageId` naming is not very self-describing. Actually, it's not a page ID, but a window ID, In some context it can cause confusion. E.g. when handling `t.getBrowserConsoleMessages`, console messages are recorded not for a page, but for a window (which can host a number of different pages during a test session).

**Comment by miherlosev** [comment]
There is the following term conflict:
End-user opens a **page** in the browser tab. The **page** contains a few **windows** (top and in iframe). We open a **page** in a **window** instead of a tab. 

The `pageId` name is not ideal. But in my opinion, the `pageId` is better than `windowId`. Because it allows avoiding confusion between kind of windows (window is a detached browser tab, a window is a place where the HTML document is displayed).

That do you think about it? @helen-dikareva @kirovboris

**Comment by miherlosev** [comment]
After the discussion, we decided to change the parameter name to `windowId`.
