### ISSUE TITLE
on chrome After click on login button test remains on same url and gets 02 javascript errors

### ISSUE THREAD

**Issue by tabassumSpringernature** [DevExpress/testcafe#4594]
Issue: When i click on the login button on my application using correct user name and password, the chrome and safari browser in testcafe do not login to the page instead it clears the entered data and remains on the same login page.

Chrome version: 79
Safari version: 12.1
Testcafe version: 1.7.0

Note: it works well with firefox.
Attachment: error screenshot

Expected Behavior: The user should be able to login to the application and should be redirected to the next page.

test script: 
fixture`Getting Started: open browser`.page(
    "https://mytesturl"

test.only('login mac uat site', async t =>{
    await t.typeText(Selector('#LoginuserId'), 'n*****');
    await t.typeText(Selector('#LoginPassword'), 'A*****');
    await t.expect(Selector(".btn#LoginSubmit").exists).ok();
    await t.click(Selector('.btn#LoginSubmit'));
    await t.debug()
});

[testcafe error on chrome safari.docx](https://github.com/DevExpress/testcafe/files/3990445/testcafe.error.on.chrome.safari.docx)

**Comment by miherlosev** [comment]
Hi @tabassumSpringernature 

TestCafe tracks uncaught JavaScript errors that occur in a tested application. Try to perform the test action action manually and see the 'Console' tab in the browser developer tools.  If the 'Console' tab constants errors, run the TestCafe with the [--skip-js-error](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) flag. If the problem is reproduced only during test execution, please send us an example with which it's possible reproduce the problem locally. We are looking forward to your response.
