### ISSUE TITLE
Chrome : Testcafe browser connected after tests may not start.

### ISSUE THREAD

**Issue by minotier89** [DevExpress/testcafe#4620]
### What is your Test Scenario?
Run the same test several times in succession.
The reason why the same test is performed consecutively is that the test is performed while switching browsers in series.
 
### What is the Current behavior?
Testing may not start after the browser connects to TestCafe.
 
### What is the Expected behavior?
Testing begins after the browser connects to TestCafe.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):https://devexpress.github.io/testcafe/example/

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
- control_test.js
```js
 const Runner = require('testcafe');

let testcafe = null;

let runner;

const args = process.argv;
const browser = args[2];
const screenshot_dir = args[3];

Runner(null, '8000', '8001', null, true)
    .then(tc => {
        testcafe = tc;
        runner = testcafe.createRunner();
        return runner
            .src(`tests/example_pages.js`)
            .browsers(browser)
            .screenshots(screenshot_dir)
            .run();
    })
    .finally(() => {
        testcafe.close();
    });
```

- tests/example_pages.js
```js
import { Selector } from 'testcafe';

fixture`Getting Started`.page`http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    await t.takeScreenshot();
    await t.typeText('#developer-name', 'John Smith');
    const osName = t.browser.os.name.toLowerCase();
    if (osName === 'windows') {
        await t.click(Selector('#windows'));
    } else if (osName === 'macos') {
        await t.click(Selector('#macos'));
    } else {
        await t.click(Selector('#linux'));
    }
    await t.click('#submit-button');
    await t.takeScreenshot();
});
```

- examples codes: https://github.com/minotier89/testcafe-examples
</details>

### Steps to Reproduce:

Run the test.
Note:No error message is displayed when this event occurs.
You will also need to manually reload the page to begin testing.
 
### Your Environment details:
 
* testcafe version:                    1.7.1
* node.js version:                    12.13.1
* command-line arguments:  `node control_test.js chrome result` or `testcafe chrome tests/example_pages.js -s result`
* browser name and version: Chrome 79.0.3945.88
* platform and version:          macOS 10.15.2

**Comment by Farfurix** [comment]
@minotier89 

Hello,

I wasn't able to reproduce the issue (yes, there is some delay in concurrent mode, but all tests pass without any additional "manually reload" actions) in the following cases:
1. `testcafe chrome -c 10 -s result`

2. `node control_test.js`
I added the concurrnecy option to [your runner](https://github.com/minotier89/testcafe-examples/blob/master/control_test.js#L17):
```diff
const Runner = require('testcafe');

let testcafe = null;

let runner;

// const args = process.argv;
const browser = 'chrome';
const screenshot_dir = 'result';

Runner(null, '8000', '8001')
    .then(tc => {
        testcafe = tc;
        runner = testcafe.createRunner();
        return runner
            .src(`tests/example_pages.js`)
            .browsers(browser)
+           .concurrency(10)
            .screenshots(screenshot_dir)
            .run();
    })
    .finally(() => {
        testcafe.close();
    });
```

Could you please provide the correct project so that we can reproduce the issue in both these cases? We will examine it and check for a suitable solution.

**Comment by minotier89** [comment]
@Farfurix 

Indeed, the problem does not seem to be reproduced in the concurrency mode.
This makes it difficult to create a project that reproduces the problem in concurrent mode, but in a single browser instance:
![image](https://user-images.githubusercontent.com/19799243/71939372-c3cd9480-31f5-11ea-99ec-b2f68d7f7434.png)

**Comment by AndreyBelym** [comment]
[testcafe.close](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/testcafe.html#close) is an asynchronous function returning a Promise. It means that its return value should be returned from the `finally` handler to allow TestCafe to properly terminate browser processes. Otherwise, Node.js can terminate your runner script before browsers are closed.

Also please note that the `async/await` syntax can be easier to read and find inconsistencies like this one:
```js
const Runner = require('testcafe');

let testcafe = null;

let runner;

const args = process.argv;
const browser = args[2];
const screenshot_dir = args[3];

(async () => {
    const testcafe = await Runner(null, '8000', '8001', null, true);
    try {
        await testcafe
            .createRunner();
            .src(`tests/example_pages.js`)
            .browsers(browser)
            .screenshots(screenshot_dir)
            .run();
    }
    finally {
        await testcafe.close();
    }
})();
```
