### ISSUE TITLE
How to get only Text rather concerning about any internal tags

### ISSUE THREAD

**Issue by abhi2526** [DevExpress/testcafe#4648]
I need only the text **Gaps in Care**, 
Took selector as **div.patient-contact-popup li.nav-item a** , it results as **Gaps in Care1**.
How/What will be selector, for to get only the text portion not any numeric because it is dynamically changed.

![image](https://user-images.githubusercontent.com/33726616/72447560-8c557e00-37db-11ea-8eb6-b5bbfebd28eb.png)

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafeontributing)). If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template. Thank you in advance.
