### ISSUE TITLE
How to handle window in test cafe

### ISSUE THREAD

**Issue by sachin-funde** [DevExpress/testcafe#4653]
#### HEADS UP!

For TestCafe API, usage and configuration inquiries, we recommend [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

You may also find answers in our up-to-date [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe) on StackOverflow. This may save your time.

If you have already looked there and have not found an appropriate answer, [file a new question on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).

**Comment by AlexSkorkin** [comment]
This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafeontributing)). If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template. Thank you in advance.
