### ISSUE TITLE
Cucumber Integration with Testcafe removed from roadmap? (short question)

### ISSUE THREAD

**Issue by Nofit** [DevExpress/testcafe#4682]
I have noticed that the feature 'Cucumber Integration' is removed from the roadmap of Testcafe, which I was really rooting for.

Will this feature come back on the roadmap, or else on the roadmap of 2020?

What are your plans for this feature?

Thanks in advance!

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. Our team deeply discussed this topic and decided that it's better to provide a public Compiler API and integrate existing mature solutions like https://github.com/kiwigrid/gherkin-testcafe. But since it is a bigger feature and our yearly development cycle is about to end, we decided to remove it from the current roadmap and consider including it in the next roadmap.
