### ISSUE TITLE
Testcafe 1.8.1 doesn't recognize Edge as browser.

### ISSUE THREAD

**Issue by KimNikB** [DevExpress/testcafe#4702]
### What is the Current behavior?
Testcafe --browser-list finds safari, chrome and ff but not chromium based Edge
Testcafe all .... does the same

And even when giving the 'path:"/applications/Microsoft\ Edge.app"' it throws an Error "Was unable to open the browser due to error.

### What is the Expected behavior?
Testcafe should at version 1.8.1 find and run Edge
 

### Your Environment details:
 
* testcafe version:                   1.8.1
* node.js version:                    v13.1.0
* command-line arguments:  "testcafe --list-browsers" "testcafe all ...."
* browser name and version: Edge 79.0.309.71
* platform and version:         Mac OS 10.15.1 "Catalina"

**Comment by AlexKamaev** [comment]
I was not able to reproduce the issue. I installed Edge on Mac 10.15.2 and tried both commands:
```JS
testcafe -b
```
and
```
testcafe 'path:`/Applications/Microsoft Edge.app`'
```
Everything works as expected.
Please check your testcafe version using the `testcafe -v` command.
Try to run testcafe on another machine or reinstall Microsoft Edge.
Pay attention to command syntax on Mac; take a look at [this comment](https://github.com/DevExpress/testcafe/issues/1384#issuecomment-456315667) to get details.



I would also recommend the [following tread](https://github.com/DevExpress/testcafe/issues/4702) since it has some recommendations on a similar issue.

**Comment by KimNikB** [comment]
Ok the Problem was that my npm installed testcafe on version 1.7.1 for some reason so I had to reinstall npm. Thanks
