### ISSUE TITLE
Saucelab fails to identify browsers string when trying to run from concourse

### ISSUE THREAD

**Issue by aprabh001c** [DevExpress/testcafe#4715]
Run tests in saucelabs from Concourse testcafe/testcafe docker image

Current behavior:
testcafe -b saucelabs returns browser lists. But when tried to trigger execution for browser "browsers": "saucelabs:Chrome@79.0:OS X 10.10" getting below error back

ERROR Was unable to open the browser "saucelabs:Chrome@79.0:OS X 10.10" due to error.

Error: spawn /tmp/build/4ef0e317/automation-repo/node_modules/sauce-connect-launcher/sc/sc-4.5.4-linux/bin/sc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

Using "testcafe-browser-provider-saucelabs": "1.8.0" npm package.
Passing browser string in testcaferc.json

![Concourse](https://user-images.githubusercontent.com/58048733/73663929-86311f80-466c-11ea-8eb0-1d9badf5ac70.png)

Could you please help here

**Comment by aprabh001c** [comment]
Could someone help here please

**Comment by AndreyBelym** [comment]
I apologize for the delayed response. The `testcafe/testcafe` Docker image is based on Alpine Linux. It provides only the `musl` C standard library. The SauceLabs provider uses the proprietary [Sauce Connect]() software. It is available in the binary form only and requires the `glibc` C standard library. Since `musl` and `glibc` libraries are not fully compatible with each other, currently we cannot use the SauceLabs provider with the `testcafe/testcafe` Docker image.

We need to implement our image based on another Linux distribution in the context of #3100 or you can send a request to the [SauceLabs support services](https://support.saucelabs.com/hc/en-us/requests/new) and asks them if they can enable SauceConnect to run on Alpine Linux.

For housekeeping purposes, I mark this issue as a duplicate of https://github.com/DevExpress/testcafe-browser-provider-saucelabs/issues/17.
