### ISSUE TITLE
testcafe How to use Chrome or Chrmium browser in UI mode. It works fine in headless mode

### ISSUE THREAD

**Issue by sukhvinderb** [DevExpress/testcafe#4728]
I am planning to use Chrome browser using NON headless mode on Linux platform. 
I have also setup DISPLAY variable
Xvfb :1 -screen 0 "${XVFB_SCREEN_WIDTH}x${XVFB_SCREEN_HEIGHT}x24" >/dev/null 2>&1 &
export DISPLAY=:1.0

I am not sure what do I need to set to run my tests successfully in UI mode.

TESTRUNNER_ARGS=--script $TEST_SCRIPT --tracing --video --reporter spec,tma-reporter:/test_results --system-url $MY_URL
TESTRUNNER_BROWSER=chromium --no-sandbox --allow-insecure-localhost

This is how I run my test

npm run testrunner -- $TESTRUNNER_ARGS --browser "$TESTRUNNER_BROWSER"

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.
We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)). If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template. Thank you in advance.
