### ISSUE TITLE
Getting error message as 'There was an unexpected internal error. Please try again.' for login functionality with Chrome browser.

### ISSUE THREAD

**Issue by BhaskarVj** [DevExpress/testcafe#4735]
Hi Team,

While trying to login for our test application, getting issue for chrome browser.

**Configuration:**
Testcafe - 1.8.1v
Chrome - 79.0.39v
OS - Windows 10

**Below is the Code:**

// JavaScript source code
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `https://ourtestappURL/`;

test('My first test', async t => {
    var pass = "*********";
    var c = '"'+pass;
    console.log("value of pass is---"+pass);
    const password = '********';
    const pass77 = `"${password}`;
    await t
        .typeText('#okta-signin-username', 'user******')
        .typeText('#okta-signin-password',pass77)
        .click('#okta-signin-submit')
        .click("//span[normalize-space(text())='Filter']");
});

**Error message:**
There was an unexpected internal error. Please try again.

**Note:** Same script is working for IE browser, whereas Chrome is getting the above error. 

Could you please have a look on this.

**Comment by AlexSkorkin** [comment]
The information you provided is insufficient to determine the cause of the issue. Please provide your valid public URL (or a sample app) and the complete test code so that we can see the issue in action and research it.

If your web site URL is not public, please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) written confirmation. It must allow the DevExpress personnel to remotely access the website and its internal resources for research/testing and debugging purposes.

**Comment by BhaskarVj** [comment]
Hi Team,

Could you please consider the below application details and verify the issue.

App URL: https://okta-testcafe-poc.azurewebsites.net/home
Username: vijay.velugula@imaginea.com
Password: Test@testCafe2

Please let us know if additional information required.

**Comment by AlexSkorkin** [comment]
You seem to forget to send the written access confirmation, your complete and valid test case, and your environment details. I recommend that you create a new issue and fill all the requested fields from the template: [https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md). Thank you in advance.
