### ISSUE TITLE
why can't I see the window.alert()??

### ISSUE THREAD

**Issue by juuuuuuuuuuuuuu** [DevExpress/testcafe#4776]
### What is your Test Scenario?
In my code, when I press the button, the window.alert pops up.
but the testpage doesn't show the dialog.
I use window.alert() , but testpage is not working.
 
### What is the Current behavior?
I think window.alert() is blocking in testpage.
 
### What is the Expected behavior?
![image](https://user-images.githubusercontent.com/30399546/74635076-94bd2200-51a8-11ea-8877-99360f9c116b.png)

 
### What is your web application and your TestCafe test code?
```
await t
.setNativeDialogHandler(() => true)
.click(Selector('#button'))
});

```

### Your Environment details:
 
* browser name and version: 
* platform and version:

**Comment by AlexSkorkin** [comment]
The setNativeDialogHandler function prevents native dialogs from appearing and processes them in the specified manner, so they don't block the page during the test run. What do you mean by 'testpage is not working'? What behavior do you expect? What is your test code? What is your testcafe version?

**Comment by juuuuuuuuuuuuuu** [comment]
```
createTestCafe('localhost', 1340, 1341)
  .then((tc) => {
    testCafe = tc;
    if (isProduction) {
      runner = testCafe.createRunner();
    } else {
      runner = testCafe.createLiveModeRunner();
    }

    return runner
      .browsers(browsers)
      .src(join(__dirname, '..', 'pc/calc', '**', '*.spec.js'))
      .run();
  })
  .then((numFailed) => {
    testCafe.close();
    if (numFailed) {
      process.exit(1);
    }
  })
  .catch((failedCount) => {
    console.log('Test failed', failedCount);
    testCafe.close();
    process.exit(1);
  });
```
I mentioned testpage that the new window opens during running testcafe(url is localhost:1340/~~).
window.alert did not pop up even when not using setNativeDialogHandler.

I executed the 'window.alert('aaa')' into the testpage console window.
but is not working too.

**Comment by alexey-lin** [comment]
If a `window.alert` popup was shown, the page would require user interaction and would be blocked because of it. That's why TestCafe prevents native dialogs from being shown. If a native dialog handler is set, it is used; if it's not set, the test fails, but a dialog as it is can never be shown. It is expected behavior. You can learn more about native dialog handling from [test API documentation](https://devexpress.github.io/testcafe/documentation/test-api/handling-native-dialogs.html).

If you want to check if an alert dialog is opened, you can use dialog history, like this:

```js
await t
	.setNativeDialog(() => true)
	.click('#button');

const history = await t.getNativeDialogHistory();

await t
	.expect(history.length).eql(1)
	.expect(history[0].type).eql('alert')
	.expect(history[0].text).eql('alert message');
```
