### ISSUE TITLE
Questions about Non-determinism in TestCafé

### ISSUE THREAD

**Issue by Vicnovais** [DevExpress/testcafe#4880]
My team has been struggling with non-determinism when running end-to-end tests using TestCafé.
Based on this topic, can someone answer the following questions?

1. What is the recommended node version to use along TestCafé? We are using version 8.12.0, as this one is proven for us the most stable by now. When we use the most recent versions, TestCafé hangs when trying to connect to the browser.

2. We are using Jenkins as our test pipeline manager. As of now, we have tons of tests to run, and sometimes TestCafé hangs and stops answering. Is there anything we can do to research this problem? Could it be a memory issue?

3. When TestCafé loads the browser, several instances are started, although the concurrency mode is not enabled. Why TestCafé starts more than one instance? Is that really necessary?

4. Are there some tips to make element selectors more stable? Like visibility check, recommended timeout or some code tips? PS: our pages are almost entirely dynamic, so our selectors pop out on the screen on different times.

5. Finally, but not least, are there some general tips to handle flaky tests using TestCafé?

Thanks in advance!

**Comment by AlexKamaev** [comment]
Hello

1. TestCafe supports node versions starting from those versions which are in the `maintenance` state at this moment and newer. If TestCafe hangs for some reason with the latest nodejs version, we will investigate this behavior.
2. It's very difficult to say precisely what the cause of the issue is. In this situation, the best way is to reproduce the issue in the sample project without CI. The lack of memory can affect the test execution, so if you run your test concurrently or in multiple browsers, try to decrease the number of browsers.
3. This is incorrect. TestCafe should not start multiple instances if concurrency is not set. We were never reported about similar problems. We will really appreciate it if you prepare an example to demonstrate this behavior.
4. You can find some useful tips in the following article: [https://github.com/hdorgeval/testcafe-snippets/blob/master/say-goodbye-to-flakyness.md](https://github.com/hdorgeval/testcafe-snippets/blob/master/say-goodbye-to-flakyness.md)
In addition, you can take a look at[ Quarantine mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#quarantine-mode).
