### ISSUE TITLE
Using --ssl: how to properly get .pfx to work with TestCafe

### ISSUE THREAD

**Issue by Tall-KU-RideOn** [DevExpress/testcafe#4898]
I need to send a certificate to Safari to allow for an Apple Pay button to appear.  I personally generated a .pfx file from MacOS `Keychain Access`.  When I do the following command, I an error reported in the browser:

`testcafe --ssl path=path/to/file.pfx safari myfiletestname.js`

> Safari can't open a page <urlHere> because Safari can't establish a secure connection to the server "10.0.0.100"

How do I resolve this

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)). If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template. Thank you in advance.
