### ISSUE TITLE
Force a test to abort the execution of a test if it get stuck

### ISSUE THREAD

**Issue by vicentesaettone09** [DevExpress/testcafe#4917]
Hello guys.

I am working with TestCafé 1.8.1 and testcafe-browser-provider-electron 0.0.14. Let's say that an issue in the application force it to get stuck and hang one test execution, and for that reason, the rest of the test in my suite cannot continue executing. Is there a way to force TestCafé to abort the execution of that test after a timeout and continue running the rest of the test in the suite?

I have faced this issue several times and it's a problem because I am not able to see the results of the rest of the "good" tests, just because of one test that hanged the whole execution.

Thanks in advance.

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be better [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe), and I see that you already submitted your question there. Please await a response there.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)). If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) and please follow the bug template. Thank you in advance.
