### ISSUE TITLE
I am getting this error while executing in cmd  ERROR The specified glob pattern does not match any file or the default test directories are empty. Is there any issue with the npm installation

### ISSUE THREAD

**Issue by ashwini5gaikwad** [DevExpress/testcafe#4930]
I am getting this error while executing in cmd 
ERROR The specified glob pattern does not match any file or the default test directories are empty.

Is there any issue with the npm installation

**Comment by miherlosev** [comment]
Hi @ashwini5gaikwad

The error message informs you that the specified glob path pattern for the tests to execute is invalid.
Check that the specified path pattern value matches any available tests. For more information, see the [file-pathglob-pattern](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#file-pathglob-pattern) argument description.

For any further inquiries, I recommend that you post them [on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template. 
Thank you in advance.
