### ISSUE TITLE
Push 1.8.3 and 1.8.4 up to dockerhub

### ISSUE THREAD

**Issue by taylor-cedar** [DevExpress/testcafe#4964]
### What is your Test Scenario?
Running docker image from dockerhub
 
### What is the Current behavior?
Version 1.8.3 and 1.8.4 do not exist in dockerhub
 
### What is the Expected behavior?
Versions to exist in dockerhub
 
### What is your web application and your TestCafe test code?
N/A

**Comment by AlexKamaev** [comment]
Thank you for pointing this out. We'll publish these versions.

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. I was unable to build the `testcafe/testcafe:1.8.4` image yesterday due to a problem with Alpine repositories. It is published now. I also pushed the `testcafe/testcafe:1.8.3` image to the Docker Hub. It looks like there was an uploading problem last time. We will change our publish scripts to prevent this situation in future releases.
