### ISSUE TITLE
Improve 'noTestsToRun' error message

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5008]
Customer problems: 
* wrong filtering predicate
* test file is not well-formed
* error in dynamic test calling. 

https://github.com/DevExpress/testcafe/issues/2889
https://github.com/DevExpress/testcafe/issues/2524
https://stackoverflow.com/questions/57035057/testcafe-error-no-tests-to-run-either-the-test-files-contain-no-tests-or-the

**Comment by rob4629** [comment]
👋 Hey, I was wondering if this issue would resolve a problem we've been facing (nice to have, not a blocker).

What you meant be _"wrong filtering predicate"_?

The current behaviour is fine in our default scenarios, but causes false failures (in our build pipeline) if someone wants to kick off a build with a custom test path:

Command:
```sh
testcafe chrome:headless <test_path> --test-meta smoke=true
```

If there's no tests with `.meta(smoke: "true")`, then ideally we would just get a warning, rather than a failure. Is this something that can/will be implemented as part of this issue?

**Comment by miherlosev** [comment]
Hi @rob4629,

We discussed this use case with the team. We decided to raise a separate error with a clear message and steps to fix it if [test filtering by any option](https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html#filter) restricts all tests.

**Comment by rob4629** [comment]
Ok, thanks for clarifying

**Comment by miherlosev** [comment]
Implemented in https://github.com/DevExpress/testcafe/commit/e9fa4e0eff90c515603084dcfdef3aaef648b433
