### ISSUE TITLE
Support cloud browsers for the 'Testing in multiple windows' feature

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5024]
* [ ] BrowserStack
* [ ] Saucelabs

**Comment by rob4629** [comment]
Can we keep this issue open, please?

**Comment by AdrienLemaire** [comment]
What are the current recommendations to deal with this problem in cloud browsers ?
Are developers adding code logic to their authentication flow, to let a user signin via redirect instead of popup if some header is detected demonstrating that the page is run through browserstack ?

Being able to consistently verify that our auth process works on a number of devices was one of our main requirements for integration an e2e test suite with TestCafe & Browserstack. Too bad we missed out the "Multiple browser windows are not available in cloud browsers" note in the doc.
Hopefully this feature can be tackled on soon.

**Comment by alexphilin** [comment]
Hi @AdrienLemaire 
 
At present, the popup window will be opened in the same window in cloud browsers. If the client code of the tested website does not communicate with the opened window, the login process will work without any issues.
 
> Too bad we missed out the "Multiple browser windows are not available in cloud browsers" note in the doc.
 
For the list of supported browsers please refer to our [docs](https://testcafe.io/documentation/402841/guides/advanced-guides/multiple-browser-windows#supported-browsers).
 
At present, we are focused on our [roadmap](https://testcafe.io/402949/roadmap). Once it is finished, we will plan the next pool of features.
