### ISSUE TITLE
feature request: no redirect after useRole

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#5042]
### What is your Test Scenario?

I love the idea of `t.useRole` only problem is that it forces a redirect/reload even if i'm on the same page.

For example, we have a 'login' button on our home page.  if I want to test the home page with a role, the `t.useRole` works, but then when it's done it refreshes the home page, even though it's already there, and there's really no need to do that.  thus slowing the test down unnecessarily.

### What are you suggesting?

a new option to the `useRole` for `no-redirect` or `no-refresh` or something along those lines, that will not cause the page to fully reload/refresh the page, but rather just allow the test to resume from where the useRole action left off.

**Comment by miherlosev** [comment]
Hi @benmonro

TestCafe's Role is a snapshot of the cookie, localStorage, and sessionStorage.
The page refresh/redirect at the end of Role initialization is necessary to transfer the snapshot from the client to the server-side. Slowing of the test execution can't be an argument for changing the current mechanism of Role, because the page reload time is very small relatively the whole test execution time. If you have other ideas why this suggestion is necessary, please tell us about it.

**Comment by benmonro** [comment]
Yeah I'm not saying to change the current functionality but only to add an option to have it not redirect after the role is done.  Our login page does just what you said so it's really like doubling it

**Comment by benmonro** [comment]
Yeah I'm not saying to change the current functionality but only to add an option to have it not redirect after the role is done.  Our login page does just what you said so it's really like doubling it

**Comment by alexey-lin** [comment]
Hi @benmonro,

Only the first call of `t.useRole` executes steps from a Role definition. Once it's done, the state of cookie, localStorage and sessionStorage are saved. All subsequent calls of `t.useRole` just apply this saved state without actual interaction with the login page. So there is no doubling here, because your login page is not involved.

**Comment by benmonro** [comment]
hi @alexey-lin yeah that is very nice for tests in which you change roles within the test, but there are many tests in which I want to reuse the same role and it doesn't switch roles, so I still see this unnecessary reload take place.  I could of course just write a `login()` function that bypasses the role altogether to accomplish that, but I really feel it would be better to have it just use Role.

**Comment by AlexKamaev** [comment]
@benmonro
This reload is required. Every test in testcafe runs with clean cookies/storages. So when you run a new test and execute the `useRole` method, you initialize your cookies and storages with the snapshot saved in the role. This initialization requires page reload as @miherlosev mentioned. At the moment, we do not have plans to change this behavior.

>I could of course just write a login() function that bypasses the role altogether to accomplish that

Could you please clarify what you mean here? How can your custom login function avoid extra page reload?

If you do not plan to switch roles between tests, you can use the [preserveUrl](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html#optionspreserveurl) option without setting the page in your test:



```JS
import { Role } from 'testcafe';

const role = Role('http://example.com', () => {
    console.log('This function executes once');
}, {
    preserveUrl: true
});

fixture `f`

test(`test 1`, async t => {
    await t.useRole(role);

    await t.click('h1');
});

test(`test 2`, async t => {
    await t.useRole(role);

    await t.click('h1');
});

```
Here every test starts from a blank page and navigates to the URL to which the browser was redirected after the log-in.

**Comment by benmonro** [comment]
Hmm and what happens if the fixture is using `.page` to set it's own URL?

**Comment by AlexKamaev** [comment]
If a page is set, a test navigates to pageUrl; otherwise - to the 'about:blank' page.
After that, navigation is done again in the `useRole` method since it's a technical requirement.

**Comment by bartzielonka** [comment]
I am struggling with something similar. Here is my issue:
https://stackoverflow.com/questions/61954056/testcafe-tests-executed-before-userole-completely-finished
I have completely no idea how to solve it, this page load messes up my tests. 🤔

**Comment by AlexKamaev** [comment]
@bartzielonka
I answered on StackOverflow and I want to mention again that page reload is an essential part of TestCafe Roles, so it cannot be avoided. However, the situation when the next action is being executed while the page is not yet loaded is incorrect. We look forward for a sample where we can reproduce this.

Please feel free to ask additional questions here. I will be happy to follow up.

**Comment by bartzielonka** [comment]
@AlexKamaev 
Thank you for you input! I've added the example here #1191 
If you want to easily reproduce I can sent the URL I am testing on but over private message. Let me know where can I reach you.

**Comment by AlexKamaev** [comment]
@bartzielonka Thank you for cooperation. You can send this url to our email: [support@devexpress.com](mailto:support@devexpress.com)

Could you please create a separate issue with example instead of posting at #1191. It will help us to process your case more efficiently.

Please note that our policy prevents us from accessing internal resources without prior written approval from a site owner. If we need to access non-public parts of your website or pass through authorization pages, please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com))) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by bartzielonka** [comment]
Ticket created data sent over email. fyi @AlexKamaev 
Hopefully you will be able to reproduce and hopefully it is an easy fix. Thank you!

**Comment by miherlosev** [comment]
Hi @bartzielonka
 
TestCafe waits for 10 sec until the action element becomes available ([https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--selector-timeout-ms](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--selector-timeout-ms)). Usually, that time is enough to guarantee that the web page is ready for testing.
Your web site uses dynamic component creation and also there are two advertisement blocks with long-loading scripts. As a result, the target component doesn't have enough time to be loaded completely.
 
To fix the problem you can increase the timeout using the [selectorTimeout](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--selector-timeout-ms) option.
Also, I've created a separate issue for improving support for AMP-based web pages - [https://github.com/DevExpress/testcafe/issues/5132. ](https://github.com/DevExpress/testcafe/issues/5132.%C2%A0)
We will research this and possibly provide some enhancements in the future.

**Comment by bartzielonka** [comment]
Sounds good. Perfect. Thank you guys for quick response.

**Comment by Fashish** [comment]
Did the above solution work for you @bartzielonka? I have a similar issue with my roles where the credentials are submitted before the page has loaded properly and need to know if there's a better way to go about the problem other than using waits. I'm not sure how the selectorTimeout option would be relevant here since the issue is not elements being loaded in the DOM but rather the dynamic elements rendering properly. Besides, I've already set my selectorTimeout at 20000 at global level so I think it's fairly high enough!

**Comment by bartzielonka** [comment]
@Fashish I actually haven't use the solution they mentioned. However I might increase timeout if need in the future. 

Solution (more of a workaround to bypass waits) was to set starting url in my user role to `about:blank` and `preserveUrl: true`.
```
    this.regularUser = Role('about:blank', async t => {
      const time = await helpers.currentTime()
      await t
        .navigateTo(urls.authWall)
        .typeText(input, credentials.email, { paste: true })
        .click(continueBtn)
      // Fetch email and save it as .html.
      await email.fetchLatestEmail(time)
      // Extract verification URL from email.
      await t
        .navigateTo('file://' + path.resolve('gmail', 'sso-email.html'))
      const url = await email.verificationEl.textContent
      await helpers.goBack()
      // Perform GET request on fetched verification url.
      helpers.getRequest(url)
      // Wait until verification completed. Assertion based on url.
      await t
        .expect(helpers.getUrl()).eql('about:blank', { timeout: 10000 })
    }, { preserveUrl: true })
```
This way after the log in was done I was able to differentiate end url in use role and url provided in fixture.
How does this help? - TestCafe won't start you code on the other page especially when it is empty -about:blank).

If you still have problem with clicking before waiting please check ticket I created and my second comment #5127 Might help.

**Comment by Fashish** [comment]
@bartzielonka I'm not sure if this'll help you as well as your scenario is a little different than mine, but I managed to solve my problem by using the [testcafe react plugin](https://github.com/DevExpress/testcafe-react-selectors)'s `waitForReact()`. I simply added the line before my test actions and now everything seems to be working smoothly.

My scenario was more like this: I was trying to use Roles for a bunch of my tests, but I was having an issue with logging in the role where credentials were being submitted before the page was even fully loaded and therefore running into problems. If your page is also based on react then this might help!

sample of my code:
```
export const regUser = Role(`www.someurl.com/login`, async t => {
  await waitForReact();

  await t
    .typeText('name="username"', 'some_user', { replace: true })
    .typeText('name="password"', 'some_pass', { replace: true })
    .click(loginBtn);

  await t.expect(await getCookies()).contains('access_token');
});```
