### ISSUE TITLE
Not able launch the Test using Chrome Browser in TestCafe

### ISSUE THREAD

**Issue by NavinChikkaraddi** [DevExpress/testcafe#5056]
Hi,
When we try launching the test using chrome browser in TEST CAFE Automation tool, the script fails with below error: 
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

Im right clicking the testname in JS file & clicking the chrome browser option as shown in the screenshot.
This is happening only with Chrome browser. Have anybody encountered & resolved this issue?
![image](https://user-images.githubusercontent.com/64971376/81307279-22205c00-909e-11ea-9fcf-5e8e239e0ad9.png)

**Comment by SergeyShurygin** [comment]
As far as I can see in your screenshot, you are using the VSCode TestCafe Test Runner extension. Could you please clarify if this problem exists if you run tests via the TestCafe command line interface?
Please run `testcafe chrome <you-test-name>` from your console.
If the issue persists, it would help if you clarify the following information:
* your OS, node.js and TestCafe version;
* specify the Chrome version installed.

If the problem doesn't occur, run tests via the "Run Tests in Chrome" menu and share complete output from the VS Code terminal.

**Comment by thesrinu** [comment]
Hi.. I have the same issue and same message appears when I run from command line as well. Strangely, when I run on IE, the IE browser launches just fine.
Can anyone please advise?

**Comment by thesrinu** [comment]
Additional details requested on the thread:
OS - Win 10 
node.js - v12.16.0
TestCafe - v1.8.8
Chrome - v85

**Comment by wentwrong** [comment]
Hi @thesrinu,

We often resolve cases with this error. It's a general error that can be thrown for different reasons. The cause of the issue is the same thing: a browser doesn't send an establishing HTTP request to the TestCafe Proxy server. But what exactly prevented this request differs from case to case. We need more information to research your particular situation.
 
Please update TestCafe to the latest version (`1.9.2` now). Then, could you please clarify if you run tests concurrently? (using [Concurrency Mode](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/run-tests.html#run-tests-concurrently)). If so, try running them without this mode. If not, probably Chrome failed to launch for some reason. In order to check this, you need to collect Chrome debugging logs. Please follow steps from [this](https://github.com/DevExpress/testcafe/issues/3862#issuecomment-502710725) answer.
 
In addition, I think that it's a good idea to move our discussion in a separate thread. I recommend that you create [a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) with your logs and additional details.
