### ISSUE TITLE
unable to open website using Testcafe

### ISSUE THREAD

**Issue by shanthkumar043** [DevExpress/testcafe#5064]
Hi Team,

When i tried it manually below website open perfectly .but when i tried to open with test cafe its not opening .

same url work fine in IE 
url :https://prodcopy-prodcopy-apt.cs5.force.com/ATGConnect/s/TradeSiteRegistrationForm

**Comment by rob4629** [comment]
It's helpful if you add in a simple test, to highlight your issue:

```js
fixture('This is a demo fixture').page(
  'https://prodcopy-prodcopy-apt.cs5.force.com/ATGConnect/s/TradeSiteRegistrationForm'
);

test.only('This is a demo test', async t => {
  await t.expect(Selector('.contentRegion').visible).ok({ timeoutSeconds: 30 });
});
```

**Comment by shanthkumar043** [comment]
Hi Rob,

i am unable to open page  at all ..after certain time loading stop.
please find attached screenshot.
is thr any we need to fix on secure connection

![image](https://user-images.githubusercontent.com/52404918/81636043-690ca980-9430-11ea-894b-eaf0a134a1a4.png)

![image](https://user-images.githubusercontent.com/52404918/81636102-8c375900-9430-11ea-84eb-1eb0d98ae7b3.png)

**Comment by LavrovArtem** [comment]
The page is not rendered because an error occurs due to the Aura framework, which uses tricky code. We discussed this issue here: [DevExpress/testcafe-hammerhead#2056](https://github.com/DevExpress/testcafe-hammerhead/issues/2056); [DevExpress/testcafe-hammerhead#2003](https://github.com/DevExpress/testcafe-hammerhead/issues/2003).

I have an idea how to fix this. Please see the following issue to stay informed of our progress: [DevExpress/testcafe-hammerhead#2056](https://github.com/DevExpress/testcafe-hammerhead/issues/2056).

**Comment by felis2803** [comment]
Hi @pragmatictesters,

We've fixed it. Old testcafe-hammerhead issues are available again.
