### ISSUE TITLE
setFilesToUpload does not work

### ISSUE THREAD

**Issue by tlqiao** [DevExpress/testcafe#5093]
I use setFilesToUpload api to upload file, the case does not show error, but I can't see uploaded file in web page. below is my script. tested web page is public page. it is easy to reproduce the issue. 
```
import {t} from 'testcafe'
fixture('upload file demo');
test('should upload file successfully', async () => {
    await t.navigateTo("https://chercher.tech/practice/popups");
    await t.wait(3000);
    await t.setFilesToUpload('input[name="upload"]',['./test.jpeg']);
    await t.wait(8000);
});
```
![image](https://user-images.githubusercontent.com/16421412/82324100-a8785e80-9a0b-11ea-9d03-75a39af01757.png)

**Comment by LavrovArtem** [comment]
We emulate the upload action. For this reason, a native `input` of the `file` type doesn't show upload information. Usually, custom upload controls show uploaded files correctly because they hide the native input and display information via other elements. To make sure that your file is in fact uploaded, you can add an assertion that checks the `value`.



```js
import {t, Selector} from 'testcafe'
fixture('upload file demo');
test('should upload file successfully', async () => {
    await t.navigateTo("https://chercher.tech/practice/popups");
    await t.wait(3000);
    await t.setFilesToUpload('input[name="upload"]',['./test.jpeg']);
    await t.expect(Selector('input[name="upload"]').value).eql('C:\\fakepath\\test.jpeg');
    await t.wait(8000);
});
```
