### ISSUE TITLE
Unable to Run Tests one after another - once i run first tests which login  but  again for second going to login 

### ISSUE THREAD

**Issue by raghavendarraokulka** [DevExpress/testcafe#5097]
```js
import { Selector } from 'testcafe';

fixture `Mul Release Testing`
    .page `https://portalweb/p99ls9-val/configuration`
    

    test('login', async t => {
        


        await t
            .typeText(Selector('#_58_login'), 'me_portal')
            .pressKey('tab')
            .typeText(Selector('#_58_password'), 'Newuser005')
            .click(Selector('.aui-button-input.aui-button-input-submit'))
            .wait(1000)
            .click(Selector('#image-1021'))
    });

    test  
    ('Number Create', async t => {
    await t
        .click(Selector('#addToolbar-btnInnerEl'))
        .typeText(Selector('#number-inputEl'), 'AUTOMATION_CAFE_STD_001')
        .typeText(Selector('#projId-inputEl'), 'SQA')
        .click(Selector('.x-boundlist-item.x-boundlist-item-over'))
        .expect(Selector('#number-inputEl').value).eql("AUTOMATION_CAFE_STD_001")
       
        });
```

in the above code second test will not be not executed as it logges out and again goes back to login page.

any suggestion what needs to be done to solve this.

**Comment by LavrovArtem** [comment]
Please checkout the documentation:
https://devexpress.github.io/testcafe/documentation/how-it-works/#isolated-tests
> Each test starts with a clean browser state. Cookies and storages are reset, an empty user profile is used, and the tested page is reloaded.

You can use the [user roles API](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/authentication.html#user-roles) to log in to each test.

**Comment by yorkshireflatcap** [comment]
I'm experiencing the same issue with user roles - Initially it logs in, then when another test is executed it logs out and forces another login. It seems everything is cleared down - cache, tokens, etc.

In my userRoles.ts file, I have the following:

```
export const adminUser = Role(https://companyDomain.eu.auth0.com/login/', async t => {
    await t
        .typeText(**login**.username, 'UserName@domain.com')
        .typeText(**login**.password, 'password!!')
        .click(**login**.Submit)
        .expect(**login**.logo.hasAttribute("src")).ok("Unable to login")
        .wait(10000);
}, { preserveUrl: true });
```

Where **login** is a page object defining the locators.  
The following are my tests:
```

fixture(`Checking some logins`).page('https://https://companyDomain.eu.auth0.com')
                                        .beforeEach( async t=>
{

                                            await t.useRole(adminUser);
    t.ctx.workspace = await home.AddWorkspace();
                                          await t.ctx.workspace.ClickMenuItem()
                                          
})

test('Checking Layout', async t=>
{
 // Logic to do some checking
})

test('Running Filters', async t=>
{
 // Assumption is while preserveUrl: true, all cache, and tokens will be saved so no need to login again so that I can continue
// testing on the same page

})
```
I have the following currently installed:

"testcafe": "^1.9.0-alpha.2" (This version was recommended after a fix was made to UserRoles.)
testcafe-hammerhead@17.1.11
and our login page is handled by Auth0

**Comment by wentwrong** [comment]
Hi @yorkshireflatcap,

I cannot reproduce your authentication scenario using the `github.com` site. 

Please check the [Troubleshooting](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/authentication.html#troubleshooting) section in our docs.

> so no need to login again so that I can continue testing on the same page

I assume that you actually need to use the `disablePageReloads` feature. It will help you force your tests to stay on the same page and prevent its state from cleaning. Otherwise, each TestCafe test will start from a clean state by default.

To get more information about this experimental feature and an example of its usage, please navigate to the [answer](https://github.com/DevExpress/testcafe/issues/2850#issuecomment-420541150).

If this doesn't help, please share a reproducible example so that we can investigate it and fix the problem. Feel free to create a separate issue with an example illustrating it. Alternatively, you can use our support@devexpress.com mailbox to share private information with us.
