### ISSUE TITLE
wrong data in reports and no debug tools

### ISSUE THREAD

**Issue by sivanisentinel** [DevExpress/testcafe#5110]
hello,
we run every night about 800 tests with test cafe. lately it seems the data we get in the report is not correct.
i.e last night it showed that a skipped test took 1:30h.
if thats not a bug, how can I tell what is the problem with my tests?

thanks
![image (1)](https://user-images.githubusercontent.com/18511976/82546013-2483bb00-9b60-11ea-9aba-aa4dd2fe1068.png)

**Comment by Farfurix** [comment]
@sivanisentinel 

Hello,

This information is not sufficient to reproduce the issue. Could you please share a simple project with us? We'll examine it and check for a suitable solution.

**Comment by doronsever** [comment]
@Farfurix hi
I'm working with @sivanisentinel.
Unfortunately we cannot give you access to our codebase...  I don't think that any organization will...
We have a serious running issue and we have no way to properly debug it and understand if a test hangs or not. 
Can you please assist with how we can do better debugging?
We are running a nightly over Jenkins inside a headless chrome

**Comment by miherlosev** [comment]
Hi @doronsever

Your environment is very complex: Jenkins, a custom test reporter, etc. It's difficult to find the cause of the issue based on the provided test report.

I can recommend the following steps for debugging:

* Update to the latest stable TestCafe version (`1.8.5`);
* Run your test suite a few times. If the issue is stably reproduced, try to reproduce it on the local machine. Then, try to create a small reproducible example.
> Unfortunately we cannot give you access to our codebase


We don't need access to your code base. We need a simple example to run it locally. It will allow us to quickly reproduce the issue. If you can provide such an example, feel free to reopen this issue.

**Comment by doronsever** [comment]
@miherlosev What you are basically is saying is that your product is not designed to support big enterprise product. That’s a shame. Debugging tools is a minimum in order to find memory leaks. Even in our code while running inside your framework

**Comment by AlexKamaev** [comment]
@doronsever
It looks like we cannot suggest any tool to diagnose the exact cause of the problem in this situation. In a complex environment like yours, a problem can be connected to any part of the environment (e.g. it can be an issue with a test itself, a network issue, a Jenkins related issue, an issue in the custom Reporter plug-in you are using, and so on). In this case, we suggest you determine which part of your test setup leads to the problem.
If a test constantly fails, we suggest running it locally to determine whether or not this is a problem with the test itself, and not a network/Jenkins related issue. If the problem is indeed connected to a certain test, you may consider debugging this test as described in the [https://devexpress.github.io/testcafe/documentation/recipes/debugging/visual-studio-code.html](https://devexpress.github.io/testcafe/documentation/recipes/debugging/visual-studio-code.html) article.
