### ISSUE TITLE
How to remove hostname and port (added by testcafe) from URL?

### ISSUE THREAD

**Issue by AutomationTester143** [DevExpress/testcafe#5118]
What is the current behavior?
Failing to open an internal company page because testcafe adds "http://192.168.15.12:51713/8wtjCRmaq/" before the real URL.. http://192.168.15.12:51713/8wtjCRmaq/https://www.google.com/?gws_rd=ssl**

What is the expected behavior?
Testcafe should navigate to google.com  page

How would you reproduce the current behavior (if this is a bug)?
Test case not to write "http://hostname/port/xx" in the URL field along with google.com page.

Provide the test code and the tested page URL (if applicable)
Tested page URL:
Google.com

Test code
Basic code.

import {selector} from 'testcafe';

fixture `MyFixture`
.meta(`fixtureID`,`1`)
.meta({author:`Dev`, CreationDate:`20 May 2020`})
.meta({ severity: 'low', testedWebVersion: '1.0' })

.page `http://www.google.com/`;

test ('google description', async t=> {
    await t
    .navigateTo('`http://www.example.com/')
        .setNativeDialogHandler(() => true)
        .click('#populate')
        .click('#submit-button');

});
**Specify your**
operating system: Win 10
testcafe version: 1.8.5
node.js version: 13.13.0
Chrome:81

**Comment by AlexKamaev** [comment]
Rewriting url's is one of core TestCafe concepts. You cannot remove it. Please refer to the following article: [https://devexpress.github.io/testcafe/documentation/how-it-works/#reverse-proxy](https://devexpress.github.io/testcafe/documentation/how-it-works/#reverse-proxy)

Probably you cannot navigate to the target page because there is a proxy server in your local network. If so, please try the approach we described here: [https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--proxy-host](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--proxy-host)

Feel free to reopen this issue if you have further questions.

**Comment by AutomationTester143** [comment]
I am using wifi and the Proxy server is off on my machine.

**Comment by miherlosev** [comment]
> So you mean the application will have 2 URLs: Testcafe proxy URL+Application url and application will work as usual?

Yes, you are right. For the https://example.com the full URL will be http://proxy-url:port/example.com.

You need to add round brackets for the `getUrl` function. See the following fixed code example:
```js
import { ClientFunction } from 'testcafe';

fixture `Fixture`
	.page('https://example.com');
	
const getUrl = ClientFunction(() => window.location.href);	
	
test('test', async t => {
	await t.expect(getUrl()).eql('https://example.com/');
});	
```
