### ISSUE TITLE
I am facing issue while running my test cafe script

### ISSUE THREAD

**Issue by arvindarun** [DevExpress/testcafe#5171]
I am able to run my test cafe script locally, if I want to test on other environments like dev or stage then it takes URL after loading the URL it won't return any result it will be just blank

![image](https://user-images.githubusercontent.com/54062330/83795884-c1486b80-a6bd-11ea-9ce4-23c285d7bbbe.png)

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.
We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe/#contributing)). If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template. Thank you in advance.
