### ISSUE TITLE
WebRTC stream fails in Firefox

### ISSUE THREAD

**Issue by weineran** [DevExpress/testcafe#5272]
### What is your Test Scenario?

Subscribe to a WebRTC video stream and make various assertions about the video quality.

### What is the Current behavior?

 Using TestCafe to subscribe to the WebRTC video stream in Firefox fails. Specifically, the ICE connection fails. As a result, there is no video visible in the TestCafe session.

### What is the Expected behavior?

 The test should successfully subscribe to the video stream.

### What is your web application and your TestCafe test code?

 You can open this link in Firefox and see the video: https://phenixrts.com/channel/#phenixWebsiteDemo

 However, if you try to run this simple TestCafe file in Firefox, the video fails to load.
**testcafe-hello-world.js**:
```
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `https://phenixrts.com/channel/#phenixWebsiteDemo`;

test('My first test', async t => {
	await t
    .wait(20000)
    console.log("test Andrew test");
});
```
Command: `testcafe firefox testcafe-hello-world.js`

Additional info: In Firefox, WebRTC needs to run against a UDP ICE Candidate. It seems that UDP is being blocked or failing somehow when opening the page via TestCafe.

### Your Environment details:
 
* testcafe version:                   
1.8.7
* node.js version:                    
v10.19.0
* command-line arguments:  
testcafe firefox testcafe-hello-world.js
* browser name and version: 
Firefox 77.0.1 (64-bit)
* platform and version:          
macOS Catalina 10.15.3 (19D76)
* other:

**Comment by Farfurix** [comment]
Hello,

I reproduced the issue under Firefox 77.0 / Windows 10. Our team will examine it and check for a suitable solution.
Error:
`WebRTC: ICE failed, your TURN server appears to be broken, see about:webrtc for more details`
Result screen:
![Capture](https://user-images.githubusercontent.com/30019338/86224005-f8ad1980-bb90-11ea-87e8-01c0c345733f.PNG)

Could you please describe your test scenario that failed due to this issue? I mean what [actions](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/interact-with-the-page.html) and [assertions](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/assert.html) we should implement after the video stream is loaded.

**Comment by miherlosev** [comment]
For the team:

The provided test works successfully on my machine (testcafe - 0e87018 commit, Firefox - 77.0.1 ).
I guess we need to investigate the `media.peerconnection.enabled` Firefox's option.

**Comment by weineran** [comment]
> Could you please describe your test scenario that failed due to this issue? I mean what actions and assertions we should implement after the video stream is loaded.

Apologies for the delay. Regarding our test scenario, we are subscribing to a video for X minutes, then asserting on various statistics about the video such as mean bitrate, framerate, codec, and so on. If you want to see the ugly details, it is all here: https://github.com/PhenixRTS/PlatformTesting

Let me know if there is additional info I can provide that might be helpful.

**Comment by alexey-lin** [comment]
@weineran, thank you for this additional information! We will review it.
