### ISSUE TITLE
Improve the error message when browser takes a too long time to initialize

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#5307]
When multiple browsers (concurrency mode) are launched in CPU-restricted environments (CI-services, Docker containers), their performance can degrade drastically. The Chrome Debug Protocol initialization that normally takes 5-10 seconds can take over 2 minutes in such conditions and prevent tests from starting. Currently, we show a generic 'Unable to establish one or more browser connections` message in this case. We should improve it to note the following things:

* Browser takes too much time to initialize
* Likely there is a performance problem (CPU bottleneck)
* If TestCafe started in concurrency mode, we should suggest to disable it or reduce the number of concurrent browsers
* If it is possible, it's better to use a more powerful hardware

**Additional info**:
Chrome Debug Protocol seems the main CPU bottleneck for Chrome. In headless mode, browsers spend enormous time in `Emulation.setVisibleSize` (usually hangs here) and `Emulation.setDeviceMetricsOverride` (very slow, but passes through). In regular mode, browsers start experiencing problems during the `Page.enable` call.

**Comment by wentwrong** [comment]
To investigate possible improvements of connection stability when tests are being run in resource-restricted environments (CI, docker containers, etc), we've looked into a different way to start browsers in TestCafe. 

Currently, browsers are launched in parallel with one common timeout (2 minutes for local browsers and 6 minutes for remotes). Our assumption was that if the process of launching was implemented sequentially instead of in parallel, then operating system would be able to take advantage of caching and make fewer expensive context switches. That way it was supposed to speed up browser instance initialization. 

Although it does solve the problem of TestCafe [not being able to run tests in IE in concurrency mode](https://github.com/DevExpress/testcafe/issues/3910) by spawning IE instances in series, this still doesn't help with the issue at hand.

Despite the fact that each of browser instances has its own timeout, initialization of each subsequent instance takes more time than the previous. So when many browser instances are being launched (e.g. in concurrency mode) in a low resources environment, the last of them often still don't have enough time to establish connection. Even when they manage to do it, the connection remains unstable. Some of them randomly disconnect due to not having enough time to answer heartbeat request. 

JFI: patch with functionality described above (debug logging and sequential browser launching): [patch.txt](https://github.com/DevExpress/testcafe/files/5259590/patch.txt)
