### ISSUE TITLE
Content of the iframe in which the test is currently operating did not load

### ISSUE THREAD

**Issue by parostatkiem** [DevExpress/testcafe#5317]
### What is your Test Scenario?

It a kind of smoke-test that checks the integration of the iframe-based framework[ Luigi](https://luigi-project.io/), our apps displayed inside it and connection to our backend.
The scenario is simple: 
Click a link (outside an inframe), that should change the displayed iframe to another one. Then perform a basic check if the iframe loaded basically any data.
 
### What is the Current behavior?

The mentioned error appears **sometimes** inside a Docker container (run locally or on the CI). It never appears when tests are run on the native system. Even if the docker container has much more memory than it needs, the problem persists.
Also, it happens when Testcafe uses Chrome or Firefox.
 
### What is the Expected behavior?

Tests are stable.
 
### What is your web application and your TestCafe test code?

I'm afraid I can't share cluster access here but there's no problem to do this in PM.
Although you can start your own Kyma cluster (let's call it the _backend_) on your own, I honestly don't recommend it.

<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>
https://github.com/kyma-project/console/tree/master/tests
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>
One of many: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1282635972600664064  (line 964)

</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:            v1.8.5-alpha.1
* node.js version:                    12.13
* command-line arguments:  have a look at the package.json in the test code
* browser name and version: firefox:headless and chrome:headless
* platform and version:          `testcafe/testcafe:alpha` docker image
* other:

**Comment by Ogurecher** [comment]
Hello,

Thank you for your report. Unfortunately, we cannot accept your live debug session invitation due to it not being a part of our standard support procedure.

You mentioned that you could share access to your cluster in PM. You can use [support@devexpress.com](mailto:support@devexpress.com) to do so.

If that's not possible, please share a sample cluster that demonstrates the issue.

**Comment by AlexSkorkin** [comment]
We received your instructions and will look into them.

**Comment by AlexKamaev** [comment]
Hello @parostatkiem

I was not able to reproduce the issue.
I tried both of your scenarios:

* Run tests locally using the website hosted in the cluster.
* Run tests in the cluster.


In the first case, I have all tests passed except 'Docs view is rendered'. However, it failed with the selector error, not with the iframe error.

In the second case, I followed all steps you described in the email. I ran tests successfully twice and got the following log:


```
 Running tests in:
 - Chrome 83.0.4103.97 / Linux 0.0

 Console UI Smoke tests
One login method detected...
Trying to login using email...
 ✓ Luigi...
 ✓ Namespaces...
 - Deployments...
 ✓ Applications...
 ✓ Functions...
 - Logs...
 ✓ Catalog...
 ✓ Service...
 ✓ Instances...
 ✓ Docs...


 8 passed (4m 54s)
 2 skipped

> ui-tests@ test:cluster_firefox /usr/src/app
> testcafe firefox:headless --skip-js-errors tests/tests.js

 Running tests in:
 - Firefox 68.0 / Linux 0.0

 Console UI Smoke tests
One login method detected...
Trying to login using email...
 ✓ Luigi...
 ✓ Namespaces...
 - Deployments...
 ✓ Applications...
 ✓ Functions...
 - Logs...
 ✓ Catalog...
 ✓ Service...
 ✓ Instances...
 ✓ Docs...


 8 passed (6m 32s)
 2 skipped
code is 0
killing pilot-agent...
```
Did I miss anything? Do I need to follow any additional steps to reproduce the issue?

**Comment by parostatkiem** [comment]
Thank you @AlexKamaev for your time spent!
Actually I was afraid of such result. As I mentioned earlier, these tests **always** pass when run locally, **sometimes** fail (no difference if it's a normal cluster like you were using or created by the CI). [Here](https://github.com/kyma-project/console/issues/1853#issuecomment-661777074) are some logs of failed tests, most of them is caused by the error we're talking about. If you want to "experience" it personally, I'm afraid you have to run the tests few more times.

About the "Docs" test fail - this is another story, also very suspicious, random and I suspect on Testcafe side but let's leave it for now.

The cluster I gave you access for is still available and untouched so feel free to experiment with it 😄 
If you want, I can gather even more logs but believe me, the only thing you'll see there is the error popping up in random tests 😞

**Comment by alexey-lin** [comment]
Hi @parostatkiem,

I ran tests on the cluster again and could reproduce the issue. But we still need to debug it to understand the cause of the error. Could you try to take a screenshot when a test fails (please refer to [this topic](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/screenshots-and-videos.html#take-screenshots-when-a-test-fails) for details) and share it with us?

Errors that are reproducible only inside a Docker container are sometimes caused by a lack of memory or other resources. I see you've already tried to increase available memory. Could you also try to increase an [assertion timeout](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--assertion-timeout-ms)? This might help if the issue is caused by low performance.

**Comment by parostatkiem** [comment]
Hello again @alexey-lin 

I managed to take several fail screenshots in one run. 
[Here's the file](https://github.com/DevExpress/testcafe/files/4982050/2020-07-27_12-35-40.zip) with logs included.  
The result is quite unexpected even for me... 3 tests failed, 4 screenshots were taken, that's weird. Here are some guess theories from me:
- `Test 3` everything seems all right but the iframe was "not ready" anyway (Testcafe fault)
- `Test 7` our app inside iframe is not loaded yet, therefore it shouldn't be selected (there's no visible iframe in the DOM) (Testcafe fault)
- `Test 8` wrong view is rendered (Our app fault)
- `Test 10` definitely our app fault, this message shouldn't appear.

About the assertion time - it has already been set ot 30000. I believe that's more than enough so I decreased it to 10000, nothing changed.

**Comment by AlexKamaev** [comment]
@parostatkiem
Thank you for your cooperation. We checked your screenshots and log file, but the cause of the issue is still unclear and we are still not able to reproduce it locally.

I also took a more detailed look at your test code and found that you use the `retry` function. When you cannot switch to iframe you make additional attempts to switch. I think that if "iframe is not loaded", then additional attempts to switch will not work, since TestCafe processes iframes after the page is loaded. However, you can try to rewrite your `retry` function in a different manner. Please try to reload the page before additional switching. In this case, TestCafe will reload the page and will process it again.

Please refer to the [following StackOverflow question](https://stackoverflow.com/questions/56157048/testcafe-how-to-reload-actual-page) to check how to reload the page with TestCafe.

**Comment by parostatkiem** [comment]
Well, yeah the error cannot be reproduced locally. That's what I tried to keep clear since creating this issue :)

While waiting for your actions I made a desperate attempt to fix this error: https://github.com/kyma-project/console/pull/1903
I think I tried all the possible ideas (see the description), including reloading the whole page and artificial 3 second waits before further retries. The tests behave exactly the same, if not worse. 

And about the helpiness of the "retry" - it doesn't help in most cases but sometimes it does ![image.png](https://user-images.githubusercontent.com/22825433/88819826-cf4bd180-d1c0-11ea-8e2a-f4a9a0aa1861.png)

**Comment by Ogurecher** [comment]
Hello @parostatkiem,
I've reviewed your code and added comments that will hopefully help you fix the issue.

**Comment by parostatkiem** [comment]
@Ogurecher still no success after your advices 🤷‍♂️ 
We're out of ideas. Any help would be appreciated 🙏

**Comment by Ogurecher** [comment]
@parostatkiem, It looks like we forgot to await the `reloadPage` call. I apologize for not noticing it earlier. I'll suggest this change in your PR.
