### ISSUE TITLE
I want to run my testcafe testcases on browserstack for macOS ,iOS and Andriod . I need the list of browser alias for running on this OS.

### ISSUE THREAD

**Issue by vasantverma-LM** [DevExpress/testcafe#5321]
#### HEADS UP!

For TestCafe API, usage and configuration inquiries, we recommend [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

You may also find answers in our up-to-date [documentation](https://devexpress.github.io/testcafe/documentation/getting-started/) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe) on StackOverflow. This may save your time.

If you have already looked there and have not found an appropriate answer, [file a new question on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).

**Comment by vasantverma-LM** [comment]
I have tried executing the command - testcafe -b browserstack but got below error message: **'testcafe' is not recognized as an internal or external command, operable program or batch file.**
I have installed testcafe locally and globally. Also the testcafe-browser-provider-browserstack is installed locally and globally.
Also have added the path of npm folder present in C:\Users\AppData\Roaming\npm in Path env variable

**Comment by wentwrong** [comment]
Please show the output of the following command so that we can make sure that the TestCafe package is installed globally:

```
npm ls -g testcafe
```

The first line of the output will include a path to the location of global packages in your system:

![](https://user-images.githubusercontent.com/26363017/87655187-95aaad80-c760-11ea-9ab3-c92de8de898b.png)

Then, run this command to make sure that it's the same as in your PATH:

```
echo %PATH%
```

If you have local packages installed in the working directory, the use of npx can be an appropriate way to resolve the issue:

```
npx testcafe -b browserstack
```

As you stated in the text of your issue, you can [submit](https://stackoverflow.com/questions/ask?tags=testcafe)[ a new question](https://stackoverflow.com/questions/ask?tags=testcafe) to StackOverflow with a more detailed description of the issue.
