### ISSUE TITLE
Docs: example of running custom runner in github actions.

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe#5367]
### What is your Test Scenario?

Currently, the [documentation for the testcafe github action](https://devexpress.github.io/testcafe/documentation/guides/continuous-integration/github-actions.html) only shows how to run using the default CLI.  It would be useful if there was an example of how to run this using a custom runner.

### What are you suggesting?

Documentation on how to use the github action w/ a custom runner (i.e. the API, not the CLI)

**Comment by AlexKamaev** [comment]
We designed our GitHub action for simple scenarios when it's not required to use a custom runner. So the case you described is not supported.
For more complex scenarios with NodeJS/TestCafe, we would recommend installing TestCafe in your workflow files. The [Using Node.js with GitHub Actions](https://docs.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions) article describes how to create your own workflow, install npm modules, etc.

If you still want to use the custom runner with our Github Action (i.e. you want to install a specific TestCafe version), I suggest you try the following workaround:

The part of the `workflow` file:

```JS
steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - run: npm ci
      - name: Install TestCafe
        uses: DevExpress/testcafe-action@latest
        with:
          args: '-v'
      - name: Run custom runner
        run: node runner.js
```

And the runner code:

```JS
const createTestCafe = require('testcafe');

let testCafe = null;

createTestCafe('localhost', 1337, 1338)
    .then(tc => {
        testCafe = tc;

        return testCafe.createRunner()
            .browsers(['chrome:headless'])
            .run();
    })
    .then(() => {
        return testCafe.close();
    });
```

In the workaround I add the `-v` argument instead of passing browsers and a path to tests. So, in the `Install TestCafe` step, TestCafe will be installed correctly and will not execute tests (only show the TestCafe version).

Then, in the next step, you can run your own `js` file.

**Comment by benmonro** [comment]
@AlexKamaev this doesn't seem to work in conjunction with an `appCommand` that is using `yarn start` as it's command.  Note when i run this locally it works fine, but in github actions it does not work.  here's the example repo/PR:

https://github.com/benmonro/msw-server/runs/919655546?check_suite_focus=true

**Comment by AlexKamaev** [comment]
I made a fork from your repository. I tried to add the `yarn start` command without TestCafe. I expected that it would execute successfully. However, the command failed.
Please check my fork to see my results:
[https://github.com/AlexKamaev/msw-server/runs/922933941?check_suite_focus=true](https://github.com/AlexKamaev/msw-server/runs/922933941?check_suite_focus=true)

I cannot say it for sure, but it seems that the problem can be not related to TestCafe.
Could you please check it yourself if the `yarn start` command successfully starts on your project?
