### ISSUE TITLE
.exists ignores Selector timeout setting

### ISSUE THREAD

**Issue by chikunov** [DevExpress/testcafe#5368]
### What is your Test Scenario?
I have a page with dynamically loaded content
 
### What is the Current behavior?
```js
    // navigate to some page with dynamic content
    await t.navigateTo('http://localhost:8080');

    // this one is going to wait
    await t.expect(Selector('[data-test="myPage"]', { timeout: 10000 }).visible).ok();
    // this one is going to be executed immediately and fail
    await t.expect(Selector('[data-test="myPage"]', { timeout: 10000 }).exists).ok();
    // this one is going to wait
    await t.expect(Selector('[data-test="myPage"]').exists).ok({ timeout: 10000 });
   // this one is going to wait
    await t.expect(Selector('[data-test="myPage"]').visible).ok({ timeout: 10000 });
```
 
### What is the Expected behavior?
.exists should honor timeout of the selector and/or global timeout setting.
 
### Your Environment details:
 
* testcafe version:                   1.8.8

**Comment by Farfurix** [comment]
@chikunov

Hello,

We need to reproduce this issue locally. Could you please share a simple project with us? We'll examine it and check for a suitable solution.

**Comment by chikunov** [comment]
https://github.com/chikunov/testcafe_exists_issue

1. yarn/npm install
2. yarn start in one terminal
3. yarn test in another

**Comment by alexey-lin** [comment]
Hi @chikunov,

Thank you for the example. I reproduced the issue. We'll look into it and update this thread once we have any result.

**Comment by AndreyBelym** [comment]
This was a by-design behavior for `count` and `exists`, to allow checking page state manually. However, we can reconsider it.

**Comment by chikunov** [comment]
I thought about this, but it is not clear why there is a difference between those two timeouts
```js
await t.expect(Selector('[data-test="myPage"]', { timeout: 10000 }).exists).ok();
await t.expect(Selector('[data-test="myPage"]').exists).ok({ timeout: 10000 });
```

and api-wise it is not clear that ```visible``` and ```exists``` behave very differently
```js
await t.expect(Selector('[data-test="myPage"]', { timeout: 10000 }).visible).ok();
await t.expect(Selector('[data-test="myPage"]', { timeout: 10000 }).exists).ok();
```

**Comment by AndreyBelym** [comment]
We need to describe the difference between assertion and selector timeouts and between immediate and snapshot properties in the context of [https://github.com/DevExpress/testcafe/issues/5388](https://github.com/DevExpress/testcafe/issues/5388).

Selector timeouts allow you to retry obtaining an element's state (element properties) if the element doesn't exist. Since we don't need any element properties to execute `exists` and `count`, selector timeouts have no effect for `exists` and `count`. Assertion timeouts allow retrying an assertion when it doesn't satisfy specified constraints for any reason. Due to this, assertion timeouts can be used to retry constrains with the `exists` and `count` properties.

`visible` is a snapshot property because it needs access to element properties to check visibility conditions. Since `exists` and `count` don't need element properties, we can execute them immediately.

**Comment by ghost23** [comment]
@AndreyBelym May I ask one question to that? According to the documentation, the default assertion timeout is three seconds. So shouldn't these two lines be equivalent?

`await t.expect(Selector('[data-test="myPage"]').exists).ok({ timeout: 3000 });`
`await t.expect(Selector('[data-test="myPage"]').exists).ok();`

Because the second line fails immediately, which seems to indicate to me, the default assertion timeout is not respected? Or am I getting this wrong?

**Comment by wentwrong** [comment]
Hello, @ghost23,

These two lines - with the default timeout of 3 seconds specified manually and with the omitted one - are equivalent as long as you have not changed the [assertion timeout](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--assertion-timeout-ms) to another value. I assume that you placed lines one after another in a single test, so it failed due to the first failed assertion.

You can place them in two different tests:
```js
test('First test', async t => {
	await t.expect(Selector('[data-test="myPage"]').exists).ok({ timeout: 3000 });
});

test('Second test', async t => {
	await t.expect(Selector('[data-test="myPage"]').exists).ok();
});
```
and make sure that the amount of time during which an assertion allowed to pass before the test fails is identical in both of these assertions.
