### ISSUE TITLE
Link opens in new windows even though that behaviour should be blocked

### ISSUE THREAD

**Issue by malinjaworski** [DevExpress/testcafe#5434]
I have a scenario where, when a link is clicked, any default behaviour is blocked. Handling of the link is deferred and all I get is a console log that tells me a specific handler was called.
The test clicks the link and no window or tab is opened. The getBrowserConsoleMessages method  is used to get the console logs and an assertion is made to see that the console log I'm looking for is preset. 
After upgrading from TestCafé version 1.8.0 to 1.9.1 the default behaviour of clicking links is no longer blocked and clicking the link results in a new window being opened. I tried using the new closeWindow method on it but it seems to regard this new window as a parent window and not a child of the original window (which is still active in the background).
Since the original window is no longer active I can't assert that the console log I need is present.

### What is the Current behavior?
TestCafé clicks the link and a new window is opened. This does not happen when going through the manual steps in our test environment because that behaviour should be blocked.
 
### What is your web application and your TestCafe test code?
 
```js
 test('Logging of handler.', async (t) => {
  await testPage.init()
  await testPage.load()
  await testPage.switchToMainIframe()

  await testIframe.clickLink()
  await testPage.hasConsoleMessage('Handler X is called with: https://url.com')
})
```

### Your Environment details:
 
* testcafe version:                   1.9.1
* node.js version:                    10
* browser name and version: Chrome 84
* platform and version:          macOS 10.15.6

**Comment by Dmitry-Ostashev** [comment]
You can try to return to the main window using the [switchToParentWindow ](https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/switchtoparentwindow.html) method. Also, the multiple browser window support feature may be turned off by the `--disable-multiple-windows` flag.

If the problem persists, please share a simple project so that we can reproduce this behavior on our side. We'll try to research it and find a suitable solution.
