### ISSUE TITLE
Add capability to identify that TestCafe is running

### ISSUE THREAD

**Issue by julien51** [DevExpress/testcafe#5439]
Our front end code performs A/B tests experiments.
It is often not worth changing our e2e tests which are using testcafe for each of these experiements.
Is there a way to identify when the front end application is running thru testcafe? This would let us disable the experiements for testcafe.

**Comment by wentwrong** [comment]
Initially, we decided that our Proxy must be transparent so that a website doesn't determine whether it is opened by a real user or by TestCafe.

But there are multiple workarounds. One of them is to use [Client Scripts](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/inject-client-scripts.html) to inject the `window.TestCafe` flag explicitly into each page visited during tests:

```js
const setTestCafeFlag = () => {
    window.TestCafe = true;
}

fixture `Each page should contain the "window.TestCafe" flag`
    .clientScripts({ content: `(${setTestCafeFlag.toString()})()` });

test(`Google site should contain the "window.TestCafe" flag`, async t => {
    const getTestCafeFlag = t.eval(() => window.TestCafe);

    await t
        .navigateTo('https://google.com')
        .expect(getTestCafeFlag).eql(true);
});
```
Also, check the following thread on StackOverflow: [How can my application code know whether the app is being tested with testcafe?](https://stackoverflow.com/questions/55425982/how-can-my-application-code-know-whether-the-app-is-being-tested-with-testcafe)

I'm tagging this issue as enhancement to gain feedback regarding whether this feature should be implemented or not.
Feel free to share your scenarios where the `window.TestCafe` flag could come in handy.

**Comment by julien51** [comment]
Thanks! Yes we used the clientScript approach at first but we found that it runs "late" which means that our front end code might have already rendered on screen by the time the clientScript has run :(
