### ISSUE TITLE
Browser GUI is not displaying when we are running TestCafe Scripts in Jenkins

### ISSUE THREAD

**Issue by lakshminagandla2678** [DevExpress/testcafe#5452]
Hi,

Today we have created jenkins job to trigger TestCafe scripts, we triggered the TestCafe scripts. But Browser GUI not all displayed while scripts are running, but we can console messages.  

Note: Jenkins has permission to interact with my desktop. 

Hence could you please suggest what would be the solution here. Do we require any additional plugin to trigger TestCafe scripts in Jenkins?

Jenkins version is: 2.164.1

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. Also, refer to the [Enable Jenkins to Start the Browser UI](https://devexpress.github.io/testcafe/documentation/guides/continuous-integration/jenkins.html#enable-jenkins-to-start-the-browser-ui-macos-and-linux) article to find information on how to configure Jenkins.

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe/#contributing)). If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template. Thank you in advance.
