### ISSUE TITLE
switchWindow , swithctopreviouswindow is giving error "cannot find specified action parameter / previous window not found"

### ISSUE THREAD

**Issue by aprabh001c** [DevExpress/testcafe#5463]
Scenario:
1.	Launch URL1 and do some actions through pageobject model classes to get URL2 in UI
2.	Launch URL2 
3.	Switch to URL1 window
Using  await t.switchToWindow(firstWindow)
 
Getting ```1 Cannot find the window specified in the action parameters.
 
{
  code: 'E74',
  isTestCafeError: true,
  callsite: CallsiteRecord {
    filename: 'C:\\Users\\xxxx\\Desktop\\Tool\\xxxxx.js',
    lineNum: 76,
    callsiteFrameIdx: 6,
    stackFrames: [
      [CallSite], [CallSite],
      [CallSite], [CallSite],
      [CallSite], [CallSite],
      [CallSite], CallSite {},
      [CallSite], [CallSite],
      [CallSite], [CallSite]
    ],
    isV8Frames: true
  }
} 

Tried using switchToPreviousWindow as well
    
Environment details:
 
* testcafe version:                   1.9
* node.js version:                    12.18.3
* browser name and version: chrome
* platform and version:          windows 10

**Comment by alexey-lin** [comment]
Hi @aprabh001c,

Our attempts to replicate this issue based on your description were unsuccessful. Could you please share your test code so that we can reproduce and analyze the issue?

**Comment by aprabh001c** [comment]
Thanks for your response. I cannot share test code, but i am able to recreate this issue using a public website, please refer details below

    "testcafe": "1.9.0",
Node - v12.18.3


```
import { t, Selector } from 'testcafe'

fixture`Switch_Window`

test(`Switch_Window`, async tn => {
    await t.navigateTo("https://www.verizon.com/").maximizeWindow()
    const big = await t.getCurrentWindow()
    const small = await t.openWindow("https://www.verizon.com/")
    await t.switchToWindow(big)
    await t.click(Selector('[aria-label="Shop Menu List"]').nth(1))
    await t.click(Selector('[href="/deals/"]'))
    await t.switchToWindow(small)
    await t.click(Selector('[aria-label="Shop Menu List"]').nth(1))
    await t.click(Selector('[href="/deals/"]'))
    await t.switchToWindow(big)
})
```

**Comment by Farfurix** [comment]
@aprabh001c

Hello,

Thank you for the information. I reproduced the issue. Our team will examine it and check for a suitable solution.

For the team: if we remove all `click` actions, the test will pass.

**Comment by arunrajkuppusamy** [comment]
@Farfurix Any update on the above reported issue, i too face this same issue. I couldn't switch between windows.

**Comment by AlexSkorkin** [comment]
Once we get any results, we will share them here.

**Comment by rajeshmorla4** [comment]
Any update on this issue, even i am facing this issue when i try to switchwindows after performing click action.

**Comment by arubtsov** [comment]
@rajeshmorla4

Hello,

Thank you for reaching out to us. No updates yet. We will update this thread as soon as we have any results.

**Comment by iamle0pard** [comment]
I wanted to add that I'm also seeing this using TestCafe 1.9.3 and Chrome 85.0.4183.121 (Official Build) (64-bit).

It appears that we can "typeText" on either window and continue to switch between them, but the moment either of them are clicked (.click(...)) then the switching between windows fails, just as @Farfurix pointed out.

I feel like it's worth emphasizing that the ability to click within either window is quite critical functionality to be able to run any useful end-to-end test scenario.  I'm actually quite confused how some of the sample code provided in the advanced guide [here](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/multiple-browser-windows.html) and the sample blog [here ](https://devexpress.github.io/testcafe/media/team-blog/introducing-multi-window-tests-beta.html) both contain click events, yet this clearly doesn't work.  While I realize this is beta, it makes me wonder if this behavior used to work and broke shortly after being released or if it the click followed by switching windows ever did work at all.

@arubtsov Do you know if anyone is currently working on a fix for this?  I see the tag "STATE: Need response" and so that is why I am asking (even though I see your response saying you will post once you have updates)

**Comment by AlexKamaev** [comment]
@iamle0pard Thank you for your input. We agree that everything should work correctly in this case. We haven't yet researched this issue. We will discuss it when planning the next development sprint. Perhaps we will decide to research this behavior.

The `STATE: Need response` tag is set by the bot for every non-contributor comment. It helps us remember to process customer feedback.

**Comment by AlexKamaev** [comment]
https://github.com/DevExpress/testcafe/issues/5597
