### ISSUE TITLE
Relative path set in href directs to fixture.page `url` value

### ISSUE THREAD

**Issue by jburgs** [DevExpress/testcafe#5470]
### What is your Test Scenario?
setting fixture.page(url = `example.com`)
and href property on the link = '../testRun/testRunId
and current url = `https://example.com/projectId/testFolder`
click the link and verify navigation to `https://example.com/projectId/testRun/testRunId`
![image](https://user-images.githubusercontent.com/6913832/91456822-b7b04900-e851-11ea-9d91-99db5df9f923.png)

 
### What is the Current behavior?
Browser page navigates to to the url passed to fixture.page(url) + relative link `https://example.com/testRun/testRunId`
 
### What is the Expected behavior?
Browser page navigates to the proper page relative to current url
 
### What is your web application and your TestCafe test code?
web application is secure 
occurs on t.click(Selector('a').withAttribute('href', '../test/relative/url/path')
 
### Your Environment details:
 
* testcafe version:                  1.9.1
* node.js version:                    12.16.3
* command-line arguments:  testcafe chrome -s path=output,takeOnFails=true
* browser name and version: Chrome 84.0.4147.135
* platform and version:          macos 10.15.4

**Comment by miherlosev** [comment]
Hi @jburgs

When the browser location is `https://example.com/projectId/testfolder', the current `file` is `testFolder` and the current `directory` is `https://example.com/projectId`. Since the link `href` value starts with `..`, the browser's location will be switched to the parent of the current directory. So, the `testrunId/testId` URL will be appended to `https://example.com`.

This behavior can be reproduced without TestCafe. Run the following code in the browser's DevTools console:
![](https://user-images.githubusercontent.com/4133518/91531184-0c68c800-e915-11ea-86fd-b7d67b7799f6.png)

You can change the link's `href` value to `./testRunId/testid`, or navigate the browser to `https://example.com/projectId/testFolder/index.html` instead. If you still feel that there is some problem caused by TestCafe, please share an example page that can be used to reproduce the problem.
