### ISSUE TITLE
Expose browser client (CDP and Marionette) in test controller

### ISSUE THREAD

**Issue by nolanlawson** [DevExpress/testcafe#5476]
First off, I love TestCafé! Thank you for creating it! :heart: 

### What is your Test Scenario?

I would like to test for memory leaks as described [here](https://addyosmani.com/blog/puppeteer-recipes/#measuring-memory-leaks) and [here](https://media-codings.com/articles/automatically-detect-memory-leaks-with-puppeteer). Using either raw CDP or Puppeteer, this is possible via [`queryObjects()`](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-queryObjects).

### What are you suggesting?

It would be great to have an API in TestCafé to execute `queryObjects()` (or alternatively, a way to execute arbitrary CDP commands within TestCafé).

### What alternatives have you considered?

I checked to see if it's already possible to run arbitrary CDP commands in TestCafé, but it seems not.

### Additional context

Please see the blog post above for how it's already possible to write a memory leak test using `queryObjects()`. Alternatively, see [this test I wrote myself using Puppeteer](https://github.com/nolanlawson/emoji-picker-element/blob/b46278d299adb93abe7104d8957386fc75a042c6/test/leak/test.js) and which actually helped me find a leak. :slightly_smiling_face:

**Comment by miherlosev** [comment]
Hi @nolanlawson 

Thank you for sharing your use case and example. Since TestCafe adds its own styles and scripts to the tested web page, measurement results for memory leaks may be significantly different from results without TestCafe.
However, I believe we can think about exposing the native browser client (CDP for Chrome and Marionette for Firefox) in the test controller. The native browser client gives wide access to the browser and can be useful in some scenarios.
 
As a workaround, you can run TestCafe in emulation mode, attach to the browser in any known way (`chrome-remote-interface` is used for that in TestCafe) and execute any expression allowed by the 'Chrome debug protocol' specification.
`testcafe 'chrome:emulation:cdpPort=<free_port_value>' tests`.
