### ISSUE TITLE
Method `scrollIntoView` missing from TypeScript definitions

### ISSUE THREAD

**Issue by nweber-gh** [DevExpress/testcafe#5488]
### What is your Test Scenario?
We have JavaScript code that uses `scrollIntoView`. We would like to migrate this code to TypeScript.
 
### What is the Current behavior?
After migration, we get an error that the method `scrollIntoView` does not exist. The text `scrollIntoView` does not exist anywhere in the `ts-defs` directory.
 
### What is the Expected behavior?
This method should exist (on SelectorAPI and NodeSnapshot, I believe).
 
### What is your web application and your TestCafe test code?
Unable to provide - however this is a compilation issue and not a runtime issue so it's moot.
 
```js
const bottomOfPage = Selector('#bottomOfPage');
await t.eval(
  async () => {
    const container = await bottomOfPage();
    container.scrollIntoView(); // error - Property 'scrollIntoView' does not exist on type 'NodeSnapshot'.
  },
  {
    dependencies: { bottomOfPage },
  }
);
```

### Steps to Reproduce:

1. Author a TypeScript test that uses `scrollIntoView`
3. Observe compilation error
 
### Your Environment details:
 
* testcafe version:                   1.3.0 (I also checked the types in 1.9.0 and did not see the method)
* node.js version:                     10.14.2
* typescript:                              4.0.2

**Comment by miherlosev** [comment]
Hi @nweber-gh 
 
You need to cast the bottomOfPage() function result to the HTMLElement interface and remove the async/await keywords from the t.eval declaration because it isn't supported.
 
The fixed code example is:
```js
const bottomOfPage = Selector('#bottomOfPage');

await t.eval(() => {
    const container = bottomOfPage() as unknown as HTMLElement;

    container.scrollIntoView(); // error - Property 'scrollIntoView' does not exist on type 'NodeSnapshot'.
  },
  {
    dependencies: { bottomOfPage },
  }
);
```

**Comment by nweber-gh** [comment]
Thanks for the quick reply! I'll do that. Is this documented somewhere and I missed it? I didn't see anything on the TypeScript page itself for Testcafe (https://devexpress.github.io/testcafe/documentation/guides/concepts/typescript-and-coffeescript.html).

Out of curiosity, why are the types authored in this way? Does a `Selector` conditionally return an `HTMLElement` which can't be statically analyzed? If so, shouldn't that be part oft he union return of `Selector` (which already returns several different shapes)?

**Comment by miherlosev** [comment]
> Is this documented somewhere and I missed it? I didn't see anything on the TypeScript page itself for Testcafe (https://devexpress.github.io/testcafe/documentation/guides/concepts/typescript-and-coffeescript.html).

The fact that you need cast the `Selector` call result in to the type differ than `NodeSnapshot` in `t.eval` action and in the `ClientFunction` is not documented.

>  Does a Selector conditionally return an HTMLElement which can't be statically analyzed?
In your case, you can cast to more strict type (for example to `HTMLDivElement`) if you know the type of the returned element.

> If so, shouldn't that be part oft he union return of Selector (which already returns several different shapes)?
Selector returns the html element only if the code is executed in the browser. It occurs if you use the t.eval action and ClientFunction.
Theoretically, we can extend the result of selector but,
* we don't know the returned type. This is why we are forced to return the base type - HTMLElement. Finally, it will require using the casting to the more strict type.
* on the browser side, the `Selector` result has a different signature - just `HTMLElement` instead of `Promise<NodeSnapshot`. It will confuse the customers.

* As I see, the best solution here is to describe the type using in the code executed on the browser side.
