### ISSUE TITLE
Files not getting downloaded on Chrome browser

### ISSUE THREAD

**Issue by SainiRenuka** [DevExpress/testcafe#5546]
### What is your Test Scenario?
I logged-in to the application and try to download the excel from ' download excel' icon from the Page. It showed "Failed-Network Error". Manually it is working fine
 
### What is the Current behavior?
File is not downloaded for Chrome. For Firefox it is working
 
### What is the Expected behavior?
File should be downloaded for any browser
 
### What is your web application and your TestCafe test code? 
<details>
<summary>Your website URL (or attach your complete example):</summary>
</details>
https://www.hpsalescentral.com/
<details>
<summary>Your complete test code (or attach your test files):</summary>
```Code: 
fixture('Verify dowload scenarios')
    .page(config.url);

    test('Verify awards and recognition details are download as excel', async t => {
        const loginPage: LoginPage = new LoginPage();
        const homePage: HomePage = await loginPage.loginAsPublicUser(config.publicUser.name, config.publicUser.password);
        const awardsAndRecognitionToolPage: AwardsAndRecognitionToolPage = await homePage.openAwardsAndRecognitionTool();
    
        await t .click(this.awardsAndRecognitionToolPageSelector.excelLinkIcon)
                   .expect(this.awardsAndRecognitionToolPageSelector.toastMessagePopup.exists)
                   .ok('Open toast message did not appear to download excel', { timeout: 40000})
                   .click(this.awardsAndRecognitionToolPageSelector.openToastMessagePopup);
    })
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>

<summary>Screenshots:</summary>

```
![Screenshot from 2020-09-15 09-31-46](https://user-images.githubusercontent.com/55740465/93205963-47bd2080-f776-11ea-8837-d2c42b96aadf.png)

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.8.8
* node.js version:                    v12.18.3
* command-line arguments:    "testcafe chrome downloadtest.ts" -->
* browser name and version:  Chrome 84.0.4147
* platform and version:           Ubuntu 18.04.5
* other:

**Comment by AlexanderMoiseev** [comment]
Hello

We would love to assist you and diagnose this issue. However, our policy prevents us from accessing customers' internal resources without prior written approval from a site owner. If you want us to further research the problem directly on your side, please ask the website owner to send us (mailto:support@devexpress.com) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

Please also provide us with your credentials since your website requires authentication. And, if possible, send us full test code.
