### ISSUE TITLE
Abort test execution from Test API 

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#5563]
https://testcafe-discuss.devexpress.com/t/how-to-stop-test-or-teardown/1106
https://stackoverflow.com/questions/63967477/error-handling-how-do-i-stop-the-script-if-theres-an-error-in-a-before-each-h

**Comment by prudhvidandamudi** [comment]
@miherlosev I have created an issue (https://github.com/DevExpress/testcafe/issues/5047) and by mistake, I have uploaded some private information in the screenshots uploaded in the issue, the issue is the auto-locked state as I cannot edit or delete the content. Could you please delete the screenshots uploaded in the above-mentioned issue. thanks in advance.

**Comment by JESii** [comment]
Still a good feature to have... any plans to implement something like this? A work-around?

**Comment by Aleksey28** [comment]
Hi @JESii,

We don't have this enhancement in plans, because it didn't gather enough attention from users. If we see more demand from users, we will think about this improvement again. However, a workaround exists. Share [`runner`](https://testcafe.io/documentation/402641/reference/testcafe-api/runner) in the global scope and use the `global.runner.stop()` stop method.

**Comment by JESii** [comment]
Thanks, @Aleksey28 I will definitely check that out!

**Comment by JESii** [comment]
Hi, @Aleksey28 Is there a way to grab the runner when running TestCafe from the command-line, or do I have to create my own object with the `testcafe.createRunner()` function?

**Comment by Aleksey28** [comment]
There is no way. You need to create a separate file where `runner` is created and run this file using `node`.

**Comment by Artem-Babich** [comment]
We decided not to implement this functionality. The official solution is to throw an error in the test code and use the [-stop-on-first-fail](https://testcafe.io/documentation/402639/reference/command-line-interface#--sf---stop-on-first-fail) flag.
