### ISSUE TITLE
TestCafe Stops After Redirction

### ISSUE THREAD

**Issue by rehanmomin** [DevExpress/testcafe#5626]
Tescafe just hangs/ stops execution once the redirection happens.

### What is your Test Scenario?
I would like to continue after redirection
 
### What is the Current behavior?
Testcafe just stops , no error is displayed also no code is executed once redirection happens.
 
### What is the Expected behavior?
Testcafe should continue execution
 
### What is your web application and your TestCafe test code?
```js
import { Selector, t } from 'testcafe';

fixture `Services Flow`
  .page `https://www.getjarvis.com.au/` 

test
(': Validate All services on Landing Page', async t =>{

  await t.maximizeWindow();
  await t.click(Selector('a').withExactText('Services'))
  await t.click(Selector('a').withExactText('Disinfection Cleaning'))
  await t.typeText(Selector('#findName'),"test")  
  await t.typeText(Selector('#findNumber'), "23432334")
  await t.click(Selector('#findButton'))
  await t.typeText(Selector('#addressInput'),"123")
  await t.expect(Selector('h3').withExactText('Your Booking Summary').exists).ok('Booking page is not loaded')
  console.log("test passed ")
  
});
```

 
### Your Environment details:
 Tescafe version 1.8.6
Node version : v12.19.0
OS : Mac 10.15.7

**Comment by AlexanderMoiseev** [comment]
Hello, 

Thank you for your sample project. We have reproduced the issue and need some time to investigate it. Please stay tuned.

**Comment by rehanmomin** [comment]
@AlexanderMoiseev  Please update if there is any workaround for this issue.

thanks

**Comment by samwill** [comment]
Hi! I'm seeing a very similar-looking issue in my own testcafe tests, but hadn't been able to create a small repro case to report with. I attempted to repro with the case provided above, but although it did freeze for several minutes after the redirect, it did eventually restart from the beginning. It still got stuck at the same spot upon retry, and after 3 attempts, it crashed with `ERROR The Chrome 86.0.4240.75 / Linux 0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.`

My version info since it is slightly different than OP's:
Testcafe : v1.9.4
Node : v10.22.1
OS : Linux 18.04

And the command I used was `testcafe chrome testcafe-test.js`

With some well-placed console logs, I was able to figure out that it freezes after the `await t.click(Selector('#findButton'))` line, so I inspected the button and noted it seems to be using a click handler for the redirect. Then after a few more reruns I noticed that it redirects from `http://192.168.1.72:38341/B9o6fULrN*tX1CAUriK/https://www.getjarvis.com.au/disinfection-clean` to `https://app.getjarvis.com.au/sign-up`, _without_ the testcafe proxy. So it seems to be that the method used by the button to redirect is causing the test to escape the proxy, leaving the test unable to proceed. 

@rehanmomin, if you could provide the method being used for the redirect on that page, it would be helpful for further debugging I think.

**Comment by AlexanderMoiseev** [comment]
Hello @samwill,

Thank you for sharing this information and your willingness to help. Please stay tuned to our announcements in this thread.

**Comment by rehanmomin** [comment]
@AlexanderMoiseev any update on the above

**Comment by satyadipon** [comment]
this is working for me
try updating the testcafe version to "1.9.4"
