### ISSUE TITLE
Set the correct test status in cloud browser dashboards when cloud browsers get restarted

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe#5643]
### What is your Test Scenario?
Test a heavy web app with a cloud browser (e.g. BrowserStack).

When TestCafe loses connection to a browser, it terminates the current remote session and restarts the current test in a new remote session, but doesn't set the status (passed/failed) of the terminated session.

### What are you suggesting?
TestCafe should calculate the status of the tests completed in the terminated remote session and use the browser provider API to set this status as a status of the terminated session. If all tests passed, the terminated session should have the "passed" status. If some test failed, the session status must be "failed". To preserve consistency across different browser providers, the status should be calculated in the TestCafe code. A browser provider should only use the remote API to set the status specified by TestCafe.

### Additional context
#5535, DevExpress/testcafe-browser-provider-browserstack#132

**Comment by yashLadha** [comment]
Aligned with the approach as it is a much more neat way to handle the situation, but isn't we are already doing this thing with like we send the browserJobStatus to the provider but the provider didn't have the logic for sending the status.

**Comment by AndreyBelym** [comment]
Currently the specific "restart" status is used in #5535 and DevExpress/testcafe-browser-provider-browserstack#135. I propose to still use only explicit "passed"/"failed" statuses, altering only the status message when needed.

**Comment by yashLadha** [comment]
Aligned with you on the proposal. I am suggesting that we should mark the session appropriately if there are no failures in the test run before the moment of restarting we should mark it as passed. If there is even a single failure then that session should be marked as failed and also appended with the appropriate message like restarted or aborted based on the action. 
For e.g, if 10 test functions were supposed to run in 1 BrowserStack session but after 5 functions, the session was restarted. Currently the user has no way to know how many functions ran in that session and whether they passed or failed.
The restarted session should be marked appropriately i.e. if all 5 had passed, then mark as “passed” with the reason “5 tests passed. Session restarted”. If 1/5 has failed, then “1/5 failed. Session restarted” should be the reason and status should be “failed”

**Comment by miherlosev** [comment]
We'll discuss it at our next sprint planning meeting and share detailed information on how it should work.

**Comment by yashLadha** [comment]
@miherlosev Any updates on this?

**Comment by miherlosev** [comment]
We discussed this issue at our sprint planning meeting. At present, we need to work out some technical details. Once we do it, we will update this thread.

**Comment by yashLadha** [comment]
Hey @miherlosev any update on this?

**Comment by miherlosev** [comment]
No updates at the moment. Once we have any results, we will share them here.

**Comment by wentwrong** [comment]
@yashLadha, sorry for the delayed response.

After checking this issue and discussing it with the team, we came to the conclusion that neither marking all restarted sessions as "passed" nor calculating the status of each restarted session individually is an ideal way. In the first case, even a session with a failed test could be marked as "passed", and in the second case, a user would have to deal with multiple restarted sessions, some of which could be marked as "passed" and others as "failed", even though they all originate from a single test run.

Considering this, our current approach - to leave all restarted sessions unmarked - is better because it's less confusing for the user. A terminated session is the only one that's relevant: it contains information about the number of failed tests (if any) and the final status of the whole test run. It's easy to distinguish restarted sessions from terminated in the BrowserStack dashboard. If it was possible to [set the test status](https://www.browserstack.com/docs/automate/api-reference/selenium/session#set-test-status) for a session to a value other than "passed" or "failed", a currently unmarked session could be marked as "restarted", although we don't think that it's the best possible solution.

Ideally, restarting a browser should not create a new session at all. We were wondering if it's possible to achieve this using the BrowserStack Automate API. There is a way to [create a new browser window](https://www.selenium.dev/documentation/en/webdriver/browser_manipulation/#create-new-window-or-new-tab-and-switch) using Selenium WebDriver. Maybe we could call this functionality using some BrowserStack Automate API endpoint (like [this](https://github.com/DevExpress/testcafe-browser-provider-browserstack/blob/0bc262ba01efdec43fc3e69e470267b4bae5a695/src/backends/automate.js#L28) one) and make the browser restart within a single session. If we could do this with BrowserStack Automate, we could even set this API as default ([currently](https://github.com/DevExpress/testcafe-browser-provider-browserstack#browserstack-js-testing-and-browserstack-automate), the TestCafe BrowserStack provider uses the JS Testing API by default).

It would be great to hear your thoughts on this.

**Comment by wentwrong** [comment]
Based on the reasons explained above, we decided to leave the current approach unchanged (keep restarted sessions as unmarked). I'll close the thread. However, if you've ideas about a better way to restart browsers on BrowserStack - feel free to comment.
