### ISSUE TITLE
Emit an error when the `eval` action is placed in a chain

### ISSUE THREAD

**Issue by wentwrong** [DevExpress/testcafe#5649]
See #5648

Related: #1859

**Comment by AndreyBelym** [comment]
We should do the same for other `getXXX` methods that are currently chainable. We also have some getters that are not chainable, but they are even worse since they do not take into account all previous commands residing before them in the test controller chain.

**Comment by AlexKamaev** [comment]
We decided to close the issue because we have a note in the documentation that the `eval` call should not be chained. Please refer to the following help topic for details:
[https://testcafe.io/documentation/402703/reference/test-api/testcontroller/eval](https://testcafe.io/documentation/402703/reference/test-api/testcontroller/eval)
