### ISSUE TITLE
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure

### ISSUE THREAD

**Issue by suchitrak** [DevExpress/testcafe#5662]
Unable to execute the tests on Safari.

Node version: v10.19.0
Testcafe version:  "testcafe": "^1.9.4",

Tried to execute safari tests using the below script in package.json
    "test:safari": "testcafe safari test1.js --hostname localhost"

Testcase: Any simple test to just check testcafe connection to safari browser.
I did enable Safari under Testcafe Browser Tools in MAC Privacy settings.

**Comment by AlexanderMoiseev** [comment]
Hello,

I’ve tried to reproduce the problem but failed. Would you please clarify if it is reproduced with browsers other than Safari? In addition, can you send me a video illustrating how you reproduce the problem by running the command with sudo privileges. Make sure that the callstack with the problem is visible there.
