### ISSUE TITLE
TestCafe on WSL1

### ISSUE THREAD

**Issue by httpete** [DevExpress/testcafe#5669]
I have looked through all the suggestions on previous bug reports but it won't fire up. WSL2 is out, but we are stuck on wsl1 for a while. I understand that this isn't a testcafe "bug" perse but it prevents us from using it. Really looking for a configuration  / suggestion or even a call that it's impossible on WSL1 and may work on 2. 

The dream result is to launch windows chrome from the wsl, which works great. After some alias fiddling I can launch chrome.exe easily from the cmd, but no combination of /mnt/ paths, backticks, or single quotes with path: seems to work.

**Comment by AndreyBelym** [comment]
Thank you for your report. Currently, WSL1 and WSL2 are not officially supported. You can subscribe to issue #1640 to track and discuss our progress.

If you do not wish to install and use Chrome Linux to run tests, you can start the Chrome Windows executable from the command line and connect is as a [remote browser](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#remote-browsers):

```sh
/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe http://localhost:1337/browser/connect
npx testcafe --hostname localhost --ports 1337,1338 remote test.js
```

**Comment by httpete** [comment]
I get the same error I had before: ERROR The number of remote browsers should be divisible by the factor of concurrency.

**Comment by miherlosev** [comment]
It looks like you specify the `concurrency` parameter value that isn't compatible with the number of remote browsers:

See an explanation [here](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/run-tests.html#run-tests-concurrently).

> On a remote device, invoke all the required instances manually. The total number of instances should divide by the concurrency parameter n. Otherwise, an exception will be thrown.

Could you please describe how you run TestCafe?

**Comment by arubtsov** [comment]
@httpete, Could you please share the CLI arguments you use when launching TestCafe?

**Comment by httpete** [comment]
so I have aliased in my .bashrc like

alias chrome="\"/mnt/c/Users/myusername/AppData/Local/Google/Chrome/Application/chrome.exe\""

When I go$ chrome it launches windows chrome great.

then
chrome http://localhost:1337/browser/connect
npx testcafe --hostname localhost --ports 1337,1338 remote test.js

**Comment by AndreyBelym** [comment]
If you want to connect only one type of a remote browser, the number of remote browsers should be equal to the number of concurrent browsers:
```
chrome http://localhost:1337/browser/connect

chrome http://localhost:1337/browser/connect

chrome http://localhost:1337/browser/connect

npx testcafe --hostname localhost --ports 1337,1338 --concurrency 3 remote:3 test.js
```

**Comment by httpete** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)::1337/browser/heartbeat/hy3gc1C:1 

I don't understand the 3 thing. I just want one browser to open.

**Comment by wentwrong** [comment]
I think @AndreyBelym assumed that you are using the concurrency mode, because initially you [reported](https://github.com/DevExpress/testcafe/issues/5669#issuecomment-719713800) about the error that only appears when this mode is used (pay attention to the ".testcaferc.json" [configuration file](https://devexpress.github.io/testcafe/documentation/reference/configuration-file.html) in the directory where you run the above script - it should not have the `concurrency` option).

If you want just to start a single browser, you can run this script:
```bash
#!/bin/sh

export CI=1
alias chrome="/mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe"
npx testcafe --hostname localhost --ports 1337,1338 remote test.js &
chrome http://localhost:1337/browser/connect
```

This script performs the following actions:

1. Set a CI environment variable to disable loading spin animation in stdout
2. Use your alias to specify a path to a Windows Chrome executable
3. Run TestCafe tests in remote mode in the background (via an ampersand (&) symbol).
4. Run the Chrome browser

It works for me with the latest TestCafe version ("v1.9.4"). If it doesn't work for you, please send a video demonstrating it (you can use a screen recording tool like [Jing](https://www.techsmith.com/jing-tool.html)).


Also consider the possibility of using a Linux browser executable inside WSL, because it will help you avoid such workarounds.

**Comment by httpete** [comment]
This works for me - by adding it to my scripts in package.json:

    "testcafe:local": "testcafe --hostname localhost --concurrency 1 --ports 1337,1338 remote live"

executable like this:
npm run testcafe:local -- browser-tests/src/tests/pages/alerts/monitors/list-smoke-tests.js

**Comment by wentwrong** [comment]
Thank you for the update. Happy to hear that this workaround works for you.
