### ISSUE TITLE
Create 'Decreasing the test execution time' article

### ISSUE THREAD

**Issue by AcademyOfF** [DevExpress/testcafe#5686]
I'm looking for some documentation on best practices for faster test speed. I think there's some information sprinkled in the documentation already, like running headless or concurrently, but I'd like one page to go to so I can learn all the options of improving test speed. A page to learn where I'm doing things inefficiently. Maybe I could structure my HTML differently to improve test performance? Etc.

**Comment by alexmi256** [comment]
Some random tips:
- Don't use ReactSelectors from `testcafe-react-selectors`, each `.find` chain you perform increases the time it takes for the selector to execute. ReactSelectors are 3x slower in a best case scenario. Any chaining you perform doubles that.
- If the app you're testing is fast, Congratulations! If not, make sure you have an appropriate loading strategy to figure out when you can start testing against components/areas. 
  - For certain tests you may only care about a certain area being loaded and not the whole page.
- Defining multiple Selectors/Promises and trying to use `Promise.all()` gives you no benefit, basically you can't do stuff in a true parallel way unless you're running ClientFunctions and at that point it's the browser that's doing it for you. For parsing large data tables this might matter.
- Use XPath selector (it's not an official thing but some dev posted code here) if you find them useful. Speed is about the same as the native Selector.
- Avoid excessive sticky/floating headers/footers. These are a pain to deal with and TestCafe has poor support to detect when one element is covering another. In my experience, element visibility is just really poor in TestCafe, this will vary on how your app was built.
- Headless vs windowed, it's best that you benchmark this out yourself, there may be no performance gains at all.
- Increasing the number of parallel test being run will decrease test stability and weird things may happen.
- Using a service like BrowserStack will be slower than running things on a local box unless it's something underpowered.
- And finally, use a different framework. At my org, TestCafe was initially evaluated and seems like a good choice, however after actually using it, it's become clear that it does not scale and is plague by gremlins.

**Comment by AcademyOfF** [comment]
That's useful. Thanks for sharing.

I'm hoping some other things could be answered:

- [ ] If tests are slow, how would I go about troubleshooting why? There's a lot of talk about how to debug tests, but not how to performance test them.
- [ ] I'd like to know about selector performance:
  - [ ] Is it better to define specific selectors? e.g., is `selector("body").innerText` slower than `selector(".some-class").innerText`?
  - [ ] Is `withText` slower than searching by class/id? e.g., is `selector("button").withText("button text")` slower than `selector("button.some-class")`?
  - [ ] etc. 
- [ ] If I'm running concurrently, would the suite run faster if the tests were a long and few, or short and many?
  - [ ] If the answer is, "it depends," what does it depend on? This knowledge would be very useful to know.
- [ ] I'd like more details about how concurrency works. Specifically, how does it distribute the work? Does it break up each test and distribute them? Each fixture? Each file?

**Comment by alexmi256** [comment]
- For logging performance I use Node's [process.hrtime](https://nodejs.org/api/process.html) with logging in a bunch of places. The HTML report will also tell you how many minutes/seconds a whole test took but that is not so granular.
- The type of CSS selector you use doesn't matter too much in real life scenarios, see https://ecss.io/appendix1.html
- No idea, I suggest you try out `Selector('button').withText('foo')` vs `Selector('.specific-button-class')` 
- I would assume the tests would complete faster if you did log+few, this is based on the assumption that you perform fewer test setups/teardowns. The downside to this is if the test fails early then you won't know the status of test scenarios that happened later on in that single test.
- I've had TestCafe concurrency explained to me before and all I remember is that it's not like pytest. Semi-related: It has the concept of Roles, so you can perform certain functions like login (which will create auth cookies) in the test `.beforeEach`. The way this works at a high level is that it will save all added cookies/other stuff and pass them on to another test using the same Role instead of running the whole Role function again.

**Comment by miherlosev** [comment]
@alexmi256
Thank you for mentioning the 'Improve testing speed' tips and for sharing your feedback on TestCafe.
>it's become clear that it does not scale and is plague by gremlins

Could you please tell us why you came to this conclusion?

@AcademyOfF
At present, there is no separate documentation topic about decreasing the test execution time. We will consider it in the future.

**Comment by AcademyOfF** [comment]
@miherlosev may I ask if I've missed anything in the existing documentation? All I know of is headless and concurrency.

**Comment by Farfurix** [comment]
@AcademyOfF 

Hello,

I don't see any additional information on this in the existing documentation. We will update this thread once we have any results.

**Comment by AcademyOfF** [comment]
Thank you for creating that article, but it didn't answer any of the questions here: https://github.com/DevExpress/testcafe/issues/5686#issuecomment-723283050

Because all of those who remain unanswered, can this issue be reopened?

**Comment by arubtsov** [comment]
Hi @AcademyOfF,

The most common reason for slow or flaky tests is the lack of resources. This could be checked easily by increasing them one by one to find the bottleneck. If it is not the case, you have three options. First, follow the tips from the article. If that does not help the cause is either in the site itself or somewhere in testcafe and this is a good reason to open an issue here.

Concerning the performance of selectors: there should not be a difference in speed for specific selectors; generally, the more operations you use the slower the selector becomes.

You can find the information about work distribution in concurrency mode in the [documentation](https://devexpress.github.io/testcafe/documentation/reference/configuration-file.html#concurrency): "Tests are run concurrently against this pool, that is, each test is run in the first free instance." Speaking of the tests length to tests count ratio, I would say there are two main factors. On the one hand, each test causes the browser to reload the page. On the other, really long tests may result in one of the instances being idle. I would avoid extremes and tend to write longer tests if your application loads really slowly. However, in that case, the best would be to deal with application load time or to open an issue in the testcafe repository if problems originate here. The best practice is still to write independent tests and not to adapt them to anything.

If you think these topics deserve a more detailed explanation, feel free to create a new issue.
