### ISSUE TITLE
Very slow, 100% CPU usage for 9s when signing in with AWS Cognito

### ISSUE THREAD

**Issue by russelldavis** [DevExpress/testcafe#5798]
When signing in to my site outside of testcafe, it runs in about 1s. Inside testcafe, it takes about 9s. It looks like testcafe is injecting some javascript that is causing the Cognito library to run significantly slower.
 
Possibly related: #3055

### What is your web application and your TestCafe test code?
I'll send the link to support@devexpress.com. It's a standard Cognito signin flow (calling `let user = new AmazonCognitoIdentity.CognitoUser(...)` then `user.authenticateUser(...);`).

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
fixture `repro`
  .page `<url sent in email>`;

test('signin', async t => {
  await t
      .typeText('#emailInputSignin', "rdavis")
      .typeText('#passwordInputSignin', "badpassword")
      .click('input[type="submit"]');
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>
None
</details>

<details>
<summary>Your complete test report:</summary>

```
 Running tests in:
 - Chrome 87.0.4280.88 / macOS 10.15.7

 apdata
 ✓ signin


 1 passed (11s)
```
</details>

### Your Environment details:
 
* testcafe version: 1.9.4
* node.js version: v12.20.0
* command-line arguments:  testcafe --dev chrome tests/repro.js
* browser name and version: Chrome 87.0.4280.88
* platform and version: macOS 10.15.7

**Comment by AlexSkorkin** [comment]
We received additional information. However, we need your written approval to access your internal resources. Is this possible? I look forward to your response.

**Comment by russelldavis** [comment]
You don't actually need to access anything internal, you can reproduce the issue by trying to log in with an invalid password (as given in the test code above). You have my permission to do that.

**Comment by aleks-pro** [comment]
Hello @russelldavis,

Please try to run tests without the [`--dev`](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--dev) flag: `testcafe chrome tests/repro.js`. Unminimized TestCafe scripts may significantly slow tests' execution.

**Comment by russelldavis** [comment]
Hi @aleks-pro. The issue is still there even without the `--dev` flag.

**Comment by aleks-pro** [comment]
Hello @russelldavis ,

Yes, you are right. TestCafe injects some javascript code that is necessary for the built-in [waiting mechanisms](https://devexpress.github.io/testcafe/documentation/guides/concepts/built-in-wait-mechanisms.html). This code causes slows down execution of site scripts. To improve this behavior, we need to rewrite some TestCafe subsystems. So, the fix is a very complex and possibly may take a considerable amount of time.
 
If necessary, increase appropriate timeouts ([selector](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--selector-timeout-ms), [assertion](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--assertion-timeout-ms), and [pageload](https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#--page-load-timeout-ms)).
