### ISSUE TITLE
1000 console.logs slow tests down to a crawl

### ISSUE THREAD

**Issue by AcademyOfF** [DevExpress/testcafe#5820]
I'm running testcafe through node: 

"testcafe": "^1.10.0",
"testcafe-reporter-spec-time": "^4.0.0",

I'm using Windows 10 and checked the OS through sfc and dsim, there are no OS errors.

Here is how I am starting the tests:

`testcafe chrome --reporter spec-time -s takeOnFails=true -c 3 'tsc/endtoendtests/maingameplay/**.ts'`

The same issue happens in headless mode and it also happens in Firefox (didn't check headless mode for that).

Here is a GIF of it happening. https://i.imgur.com/CnFbZv4.gif This is only 10 frames per second, but it is real time. Notice how slow each click is going. I can click faster than this as a human.

There is one test it keeps getting stuck on. This is the URL for it, at least during one run: 

http://192.168.1.2:56049/Aikt1KOcK*wSNx9Unx7/file:///C:/IdeaProjects/monstergirlfarmer-text/dist/index.html?passageName=TestMacros&end_to_end_test_mode=true

if I go to that same URL in my browser while the test is running, I experienced the same thing. The test is constantly spinning without proceeding. But if I go to the actual file in my browser ( file:///C:/IdeaProjects/monstergirlfarmer-text/dist/index.html?passageName=TestMacros&end_to_end_test_mode=true ), it loads fine as always. 

I actually figured out how to solve this problem: You see, I had left a log statement on a javascript function call. When I removed this, the tests return to their typical speed--faster than I can click as a human. This log statement created 1000 lines on the test that hung, here's a sample of what the logs look like:

> title Sophie-Touch2 index.html:17430:21
> title Sophie-Touch3 index.html:17430:21
> title Sophie-Chores index.html:17430:21
> title Sophie-Chores2 index.html:17430:21
> title Sophie-Chores3 index.html:17430:21
> title Sophie-welcome index.html:17430:21
> title Sophie-welcome2 index.html:17430:21

for what it's worth, here's the code that generated these logs: `    console.log("title", passage.title)`

The interesting thing to me is how this slowed down every test that was running and how drastic it did so. I think what this means is, whatever http://192.168.1.2:56049 is, it gets bogged down by a bunch of log statements in a way that affects all tests, not just the one with the extra logs. To me, 1000 log statements doesn't seem like a huge deal. And if you look at the task manager, you'll see that the CPU and RAM was never pegged.

Anyway, I know I haven't provided a sample project, but I hope this is enough to reproduce the issue on your end. I've seen a lot of mentions of problems that reproduce my symptoms, maybe this can help you resolve it once and for all.
 
### Your Environment details:
 
* testcafe version:                   1.10.0
* node.js version:                    v12.18.2
* command-line arguments:  testcafe chrome --reporter spec-time -s takeOnFails=true -c 3 'tsc/endtoendtests/maingameplay/**.ts'
* browser name and version: Chrome 87.0.4280.88
* platform and version:          Windows 10
* other:  my test files are typescript

**Comment by AndreyBelym** [comment]
[https://github.com/DevExpress/testcafe/issues/5820](https://github.com/DevExpress/testcafe/issues/5820)

Thank you for your inquiry. While `console.log` is not a CPU-intensive function, it is still a synchronous (blocking) function - prevents any other code in the same thread from running and is known for causing performance degradation, e.g., [https://stackoverflow.com/a/26754011/5114901](https://stackoverflow.com/a/26754011/5114901). Since TestCafe uses regular JS injected into your test pages to emulate user actions, the use of blocking functions like `console.log` in the UI thread also impacts its performance.

From my point of view, we can overcome this only by using native browser debug protocols to emulate user actions (like Chrome Debug Protocol, a.k.a. CDP, or WebDriver, which uses CDP internally). However, this is an epic task, and our current researches shows that this change may lead to many other problems. So, it is very unlikely that it will be implemented in a short-term period.

In the meantime, you can modify your logging mechanism to store your log data in memory and output it to the browser console on demand. You can even use an NPM module like [debug](https://www.npmjs.com/package/debug) or [winston](https://www.npmjs.com/package/winston) that does not only offer a more performance-efficient logging subsystem but also comes with additional useful features.

Also, it's possible that there is some other issue that is masked by frequent `console.log` calls in your app. But we can say this for sure only if I or some other TestCafe developer takes a look at your project and tests. Sharing them is the most helpful and effective move to research and solve issues like this one.
[https://github.com/DevExpress/testcafe/issues/5820](https://github.com/DevExpress/testcafe/issues/5820)

Thank you for your inquiry. While `console.log` is not a CPU-intensive function, it is still a synchronous (blocking) function - prevents any other code in the same thread from running and is known for causing performance degradation, e.g., [https://stackoverflow.com/a/26754011/5114901](https://stackoverflow.com/a/26754011/5114901). Since TestCafe uses regular JS injected into your test pages to emulate user actions, the use of blocking functions like `console.log` in the UI thread also impacts its performance.

From my point of view, we can overcome this only by using native browser debug protocols to emulate user actions (like Chrome Debug Protocol, a.k.a. CDP, or WebDriver, which uses CDP internally). However, this is an epic task, and our current researches shows that this change may lead to many other problems. So, it is very unlikely that it will be implemented in a short-term period.

In the meantime, you can modify your logging mechanism to store your log data in memory and output it to the browser console on demand. You can even use an NPM module like [debug](https://www.npmjs.com/package/debug) or [winston](https://www.npmjs.com/package/winston) that does not only offer a more performance-efficient logging subsystem but also comes with additional useful features.

Also, it's possible that there is some other issue that is masked by frequent `console.log` calls in your app. But we can say this for sure only if I or some other TestCafe developer takes a look at your project and tests. Sharing them is the most helpful and effective move to research and solve issues like this one.
