### ISSUE TITLE
${RUN_ID} breaks the screenshotPath in quarantine mode

### ISSUE THREAD

**Issue by bradleybensmith** [DevExpress/testcafe#5846]
### What is your Test Scenario?
Verifying production application availability.
 
### What is the Current behavior?
The screenshotPath is incomplete when there is a failure and quarantine mode is enabled:

```json
          "screenshotPath": "/Users/smithb/Code/testcafe/data/screenshots",
```
 
### What is the Expected behavior?
A complete screenshotPath:

```json
          "screenshotPath": "/Users/smithb/Code/testcafe/data/screenshots/2021-01-06-02-23-47-run-3-test-1.png",
```
 
### What is your web application and your TestCafe test code?
Application can not be made public, but the issue is reproduced on your example site:
https://devexpress.github.io/testcafe/example

Test case repository:
https://github.com/bradleybensmith/testcafe-screenshot

### Steps to Reproduce:
1. Clone the above repository.
2. Run: `node index.js`
3. Review `screenshotPath` in output.
4. Remove `${RUN_ID}` from `pathPattern` and re-run the test.
 
### Your Environment details:
 
* testcafe version:                   1.10.1
* node.js version:                    v12.20.1
* command-line arguments:  (none)
* browser name and version: Safari and Chromium Edge
* platform and version:          macOS 11.0.1 and Windows 10

**Comment by AlexSkorkin** [comment]
Thank you for submitting this issue.

When I run the test case with ${RUN_ID}, I get the following three screenshots:

2021-01-08-11-38-28-run-1-test-1.png
2021-01-08-11-38-28-run-2-test-1.png
2021-01-08-11-38-28-run-3-test-1.png

![image](https://user-images.githubusercontent.com/995726/103999921-99b70580-51ae-11eb-9969-185f6ef158c2.png)

I used Edge Chromium Version 87.0.664.75 (Official build) (64-bit) on Windows 10 Build 1083, TestCafe v1.10.1 and Node.js v14.15.4.

I also used Safari 13 on MacOS 10.15 and got a similar result:

![image](https://user-images.githubusercontent.com/995726/103999836-78561980-51ae-11eb-977a-8b6d5fb14caf.png)

If I remove ${RUN_ID}, I get the following warning, which is also expected:

`The file at "testcafe-screenshot\data\screenshots\2021-01-08-12-19-38-test-1.png" already exists. It has just been rewritten with a recent screenshot. This situation can possibly cause issues. To avoid them, make sure that each screenshot has a unique path. If a test runs in multiple browsers, consider including the user agent in the screenshot path or generate a unique identifier in another way.
`

To replicate the issue, I cloned your repo, installed all packages, and executed "node index.js". Would you please clarify what you mean by "The screenshotPath is incomplete when there is a failure and quarantine mode is enabled"? What happens on your side?

**Comment by bradleybensmith** [comment]
Yes, the file is generated correctly, but the `screnshotPath` in the JSON output is missing the filename:

```json
{
  "startTime": "2021-01-08T09:59:21.619Z",
  "endTime": "2021-01-08T09:59:40.248Z",
  "userAgents": [
    "Safari 14.0.1 / macOS 10.15.6"
  ],
  "passed": 0,
  "total": 1,
  "skipped": 0,
  "fixtures": [
    {
      "name": "Getting Started",
      "path": "/Users/smithb/Code/testcafe/test.js",
      "meta": {},
      "tests": [
        {
          "name": "My first test",
          "meta": {},
          "errs": [
            "AssertionError: expected 'Thank you, John Smith!' to deeply equal 'Thank you, Johnny Smith!'\n\n+ expected - actual\n\n-'Thank you, John Smith!'\n+'Thank you, Johnny Smith!'\n\n\nBrowser: Safari 14.0.1 / macOS 10.15.6\nScreenshot: /Users/smithb/Code/testcafe/data/screenshots/2021-01-08-04-59-20-run-3-test-1.png\n\n    8 |    await t\n    9 |        .typeText('#developer-name', 'John Smith')\n   10 |        .click('#submit-button')\n   11 |\n   12 |        // Force an error...\n > 13 |        .expect(Selector('#article-header').innerText).eql('Thank you, Johnny Smith!')\n   14 |});\n   15 |\n\n   at <anonymous> (/Users/smithb/Code/testcafe/test.js:13:56)\n   at asyncGeneratorStep (/Users/smithb/Code/testcafe/test.js:1:219)\n   at _next (/Users/smithb/Code/testcafe/test.js:1:557)\n   at <anonymous> (/Users/smithb/Code/testcafe/test.js:1:722)\n   at <anonymous> (/Users/smithb/Code/testcafe/test.js:1:463)\n   at <anonymous> (/Users/smithb/Code/testcafe/test.js:7:5)"
          ],
          "durationMs": 18606,
          "unstable": false,
**        "screenshotPath": "/Users/smithb/Code/testcafe/data/screenshots",**
          "skipped": false
        }
      ]
    }
  ],
  "warnings": []
}
```

The screenshot path shown in the `errs` array is correct, but not the `screenshotPath` property.

**Comment by AlexSkorkin** [comment]
Thank you for your clarification. When you use `${RUN_ID}, the test run will generate three screenshots. When you don't use ${RUN_ID}, only one screenshot will be generated.

The `screenshotPath` property value is generated as a full path to a single screenshot, or a common path in case of multiple screenshots. Here are the corresponding source code lines:

[https://github.com/DevExpress/testcafe-reporter-json/blob/master/src/index.js#L41](https://github.com/DevExpress/testcafe-reporter-json/blob/master/src/index.js#L41)
[https://github.com/DevExpress/testcafe/blob/master/src/reporter/index.js#L138](https://github.com/DevExpress/testcafe/blob/master/src/reporter/index.js#L138)
[https://github.com/DevExpress/testcafe/blob/master/src/screenshots/index.js#L52](https://github.com/DevExpress/testcafe/blob/master/src/screenshots/index.js#L52)
[https://github.com/DevExpress/testcafe/blob/master/src/utils/get-common-path.js#L28](https://github.com/DevExpress/testcafe/blob/master/src/utils/get-common-path.js#L28)

This behavior is by design. If the screenshotPath property value contains a single file only while there are several screenshot files, other screenshots may be missed.
