### ISSUE TITLE
could you pls provider required depe required in docker?

### ISSUE THREAD

**Issue by luckhpy** [DevExpress/testcafe#5890]
could you pls provider required dependencies required in docker? because i have to "yarn start" my application in the docker and then run e2e test, i need base docker image provider by my company which contains some environment that need to start my application。so beg for something like cypress provide（https://docs.cypress.io/guides/getting-started/installing-cypress.html#System-requirements）

![37581611558754_ pic_hd](https://user-images.githubusercontent.com/19641484/105672814-099fec80-5f20-11eb-978e-028853606e09.jpg)

**Comment by wentwrong** [comment]
TestCafe has an official Docker image: [Use TestCafe Docker Image Guide](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/use-testcafe-docker-image.html). It comes with two browsers (Chromium and Firefox) and all the required dependencies for work (nodejs, tools for managing virtual display for running non-headless browsers and more). You can examine them yourself: [Dockerfile](https://github.com/DevExpress/testcafe/blob/master/docker/Dockerfile).

However, since it can be difficult to determine which dependencies you need to install for a custom image, we've created the following issue: [Document how to setup Testcafe on custom docker image](https://github.com/DevExpress/testcafe/issues/5894). Thank you for your suggestion.
