### ISSUE TITLE
Inconsistent results with the use of a `+` character at the end of a keypress

### ISSUE THREAD

**Issue by mohlsen** [DevExpress/testcafe#5940]
### What is your Test Scenario?
I am seeing inconsistent results with the use of a `+` character at the end of a keypress. I know in the [docs](https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/presskey.html) that `ctrl+` (zoom) is not passed, but in some cases you can pass the string `plus` and in others escape with `\+`.
 
### What is the Current behavior?
The following table illustrates what I am seeing. The rors are the beginning of the keystroke, and the columns insicate the end of the keystroke. and the table contents indicate if the `t.pressKey` call was seen by the browser. i.e. the first row of the table would be the following keystrokes: 

- `ctrl+shift++`
- `ctrl+shift+\+`
- `ctrl+shift+plus`

| key press    | `+` | `\+` | `'plus'` |
| ------------ | --- | ---- | -------- |
| ctrl+shift   | ✅  | ✅  |   ✅     |
| ctrl         | ❌  | ✅  |   ❌     |
| shift        | ✅  | ✅  |   ✅     |
| alt (option) | ❌  | ✅  |   ❌     |
| [char only]  | ❌  | ✅  |   ❌     |
 
### What is the Expected behavior?
The desired state is not all green here per se, but consistent results across all 5 test cases.
 
### What is your web application and your TestCafe test code?
I have written a functional test for this, and it can be found in [this fork's commit](https://github.com/mohlsen/testcafe/commit/6cd1b608248deb743a30c44e370088bcba7a473d) and in https://github.com/DevExpress/testcafe/pull/5941.  Perhaps this is all working as intended, I am not sure but wanted to post the inconsistencies I found. 
 
### Steps to Reproduce:
run `testcafe chrome ./test/functional/fixtures/regression/gh-xxx/testcafe-fixtures/index.test.js`
 
### Your Environment details:
 
* testcafe version: 1.8.8
* node.js version: 12.17.0
* command-line arguments:  `testcafe chrome ./test/functional/fixtures/regression/gh-5940/testcafe-fixtures/index.test.js`
* browser name and version: chrome 88.0.4324.150
* platform and version:          macOS 10.15.7
* other:

**Comment by arubtsov** [comment]
Hi @mohlsen, thank you for your input.

There is no need to escape the `keys` argument of `pressKey` (you can find the corresponding `eslint` error [here](https://travis-ci.com/github/testcafe-build-bot/testcafe/jobs/481603792#L403)). TestCafe does not support the `plus` keyword. You can see the list of supported keys and keywords [here](https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/presskey.html).

Actually, the code you wrote for the test page does not work. You can open this page in Chrome and check for yourself - checkboxes won't change their state no matter which key combination you press. To make it work you need to use the `keydown` event instead of `keypress`. The reason your tests still pass is that you forgot to insert the `await` keyword into the `uncheckIfNecessary` function: `if (await selector.checked)`.

I believe I can close both the issue and the PR you created. Let me know if you have any questions.

**Comment by mohlsen** [comment]
Thank you for pointing out the issue in the test.  The have been updated on my fork's branch.  The updated results are as follows:

| key press    | `+` | `\+` | `'plus'` |
| ------------ | --- | ---- | -------- |
| ctrl+shift   | ✅  | ✅  |   ✅     |
| ctrl         | ❌  | ❌  |   ❌     |
| shift        | ✅  | ✅  |   ✅     |
| alt (option) | ❌  | ❌  |   ❌     |
| [char only]  | ❌  | ❌ |   ❌     |

So, this shows `ctrl+`, `alt+` and `+` do not work (and not listed as supported as you mentioned.)  However, `shift+` and ctrl shift+` do work, as seen in the test.  So the `+` key does work under certain conditions.  

So I guess this issue now, would just be providing documentation regarding using the `+` char in combination with the other modifiers (shift, etc).  Or does this just happen to work, and it is not really supported?  Thoughts?

**Comment by arubtsov** [comment]
Hi @mohlsen,

When I open the page you created for the test in the Chrome browser without `testcafe`, I see the same behavior as in the test for the `ctrl+` and `alt+` key combinations. That is, if I press one of them in Chrome, the corresponding event will not be caught by the `keypress` event handler (corresponding checkboxes do not change the state). If you want to handle them, you need to use the `keydown` event. I do not see any issue here.

I would like to draw your attention one more time to the `eslint` errors that occur in the commit you shared with us. The escaping of characters is unnecessary in `pressKey` and does not affect its behavior. If the `eslint` integration is not configured in your editor, you can see them by running `npx gulp lint` at the root of the repository.

As you can see in the [documentation](https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/presskey.html), testcafe supports alphanumeric keys (A-Z a-z 0-9), modifier keys, and a number of navigation and action keys, their combinations, and sequential key presses. This includes neither `+` nor the `plus` keyword. The `plus` keyword just happens to work because `testcafe` uses it internally. One should not rely on it because it is an implementation detail and could be changed in the future.

**Comment by mohlsen** [comment]
Thank you for you reply.  There are several topics your reply, I will comment on them individually.

**manually running in chrome** - This behavior work for me in chrome using the existing test page. I can press `ctrl+` and `alt+` and the check boxes check.  I am pressing the `+` key on the extended keyboard (numpad).  It does not work in the keyboard layout with the `+` over the `=` sign since that requires a shift (perhaps that is what you tried?).  See the attached gif.  

![plus test](https://user-images.githubusercontent.com/3265497/108096784-5f634280-704f-11eb-8f0b-1d5610e50133.gif)

**escape characters** - I understand this is not needed and shows up in lint. They were in the tests from experimentation, and no follow up is necessary. I am not proposing anything to change here.

**plus keyword**  I understand this is also not needed.  Other frameworks use this and they were in the tests from experimentation, and no follow up is necessary. I am not proposing anything to change here.

**testcafe run with `ctrlshift+` and `shift+`** these continue to work for me with the referenced tests using testcafe.  See attached gif.

My only ask with this issue is to understand why the `+` character after some modifiers are working (`ctrlshift+` and `shift+`).  As you stated the `+` is not supported per the documentation, but they ARE working with these modifiers.  So either there is a bug that is allowing the `+` to work sometimes, or the documentation is incorrect and `+` does work for some conditions.

![ctrlshift+](https://user-images.githubusercontent.com/3265497/108098850-df8aa780-7051-11eb-99e7-fd34a7c61ff5.gif)

I hope this is clear now. thank you!

**Comment by AlexSkorkin** [comment]
Thank you for your clarification. Please give us additional time to review and discuss them.

**Comment by arubtsov** [comment]
@mohlsen, Thank you once again for the clarification.
The `ctrl+` and `alt+` key combinations do behave as you stated (I missed the Mac platform).
Concerning the `+` character, our position is the same as with the `plus` keyword. It just happens to work. This behavior was not intended and is inconsistent, so one should not rely on it. Based on that, the documentation is correct. Feel free to open a new issue if the `pressKey` action does not perform the functions described in the documentation.
