### ISSUE TITLE
Slow performance with custom radio buttons and ids

### ISSUE THREAD

**Issue by gemal** [DevExpress/testcafe#5970]
I have a test where testcafe says "Waiting for element to appear" and I dont understand why.
I use a ID selector

My test is fairly simple and I made a slow version using a ID and a fast one using a non ID

Is this a bug in testcafe?

Using Testcafe v1.11.0 on Chrome 88.0.4324.182 / Windows 10

Test output says:
```
 Book
 √ slow  (17s)
 √ fast  (3.69s)
```

Why is selecting using ID so much slower? Shouldn't it be faster?

This is my test:
```
import { Selector } from 'testcafe';

fixture('Book').page('https://book.dinnerbooking.com/dk/en-US/book/table/pax/458/2');

test('slow', async t => {
    'use strict';
    await t
        .maximizeWindow()
        .click('button.ui-spinner-up')
        .click('button.black-button')
        .click('#RestaurantAreaConfigAreaId6');
});

test('fast', async t => {
    'use strict';
    await t
        .maximizeWindow()
        .click('button.ui-spinner-up')
        .click('button.black-button')
        .click(new Selector('.restaurant-area-label').nth(1));
});

```

**Comment by gemal** [comment]
Is there way for me to debug this?

**Comment by aleks-pro** [comment]
Hello @gemal,

Thank you for reaching out to us.
This issue looks like a question and we try to keep the GitHub issue tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).
 
So, let's continue discussing this issue in the StackOverflow thread you've created: https://stackoverflow.com/questions/66246885/slow-performance-with-testcafe-and-ids-and-custom-radio-buttons

PS: If you think that this issue is a bug, feel free to open a new issue, but please make sure to follow the bug template.
