### ISSUE TITLE
setFilesToUpload does not work 

### ISSUE THREAD

**Issue by RafikaBenneji** [DevExpress/testcafe#5976]
**### Issue Description** : I use **setFilesToUpload** method to upload file, the case does not show error, but I can't see uploaded file in web page. 
Below is my script.
**### Script**
//*********************************************************************************************
`import {Selector, t} from 'testcafe'
import {LastFly_URL} from '../../configuration/config';

fixture (`Uplad file`)
    .page (LastFly_URL);

test('Upload file', async t => {
    .setFilesToUpload(Selector('input[type="file"]'), ['./toto.pdf'])
});`
//*********************************************************************************************
[](url)
![image](https://user-images.githubusercontent.com/79314322/108507968-62fb0180-72bb-11eb-800d-e527acdb34bd.png)
![image](https://user-images.githubusercontent.com/79314322/108508438-1bc14080-72bc-11eb-8667-41c2ab51db1e.png)

**### Result**
The input file is not populated with file path
### 
**Environment details**:
 
* testcafe version:                  1.10.1
* node.js version:                    6.14.10
* command-line arguments:  npx testcafe chrome createFile\sc2.js 
* browser name and version: chrome 85
* platform and version:        windows 10

**Comment by Farfurix** [comment]
@RafikaBenneji 

Hello,

TestCafe's file upload emulation is different from what a real user would do to upload files. More details: https://devexpress.github.io/testcafe/documentation/recipes/basics/test-file-upload.html.

Could you please share an example where the issue is reproduced (or a public URL and your test file)?

Please note that the [minimal supported Node.js version is 10](https://github.com/DevExpress/testcafe/blob/master/package.json#L19):
```json
"engines": {
  "node": ">=10.0.0"
},
```

Also, I recommend you update TestCafe to the latest v1.11.0 version.

**Comment by RafikaBenneji** [comment]
Hello
Unfortunately i m not able to give you the url  acciording to a confidentiality agreement.
I have upgraded testcafé and node js but setFilesToUpload method still not working 

> node js version :v14.15.4

> testcafe version v1.11

Can i have a private  call to troubleshoot this issue? 

Thanks in adavance for your help.

Kind Regards,
Rafika Benneji

**Comment by AlexSkorkin** [comment]
Hello,

We don't do private calls. I recommend that you create a simple sample that we can run and research on our side to find a solution if any.
