### ISSUE TITLE
Add REPL Feature 

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#5985]
Having the chance to execute the script till a certain action and the enter in a console mode, (REPL) that allow you to add and test steps will be a MUST.

**Comment by wentwrong** [comment]
Thank you for your suggestion. With the current design of TestCafe (compiling your tests before starting) in mind, I think it's not so easy to implement the ability to add test steps "on the fly". Please take a look at our docs about [Live Mode](https://devexpress.github.io/testcafe/documentation/guides/basic-guides/run-tests.html#live-mode). Perhaps, this feature will serve your needs.

**Comment by fmancardi** [comment]
Thanks for your answer. The live mode is not the answer. 
Best option will be to have a REPL mode, that means that test script can not be compiled before starting.
I love how taiko do this, and think this feature addition will make TestCafe fantastic for the developers, while they I drafting the test case script

**Comment by AlexSkorkin** [comment]
I see your point, Francisco. However, we don't have plans to add this functionality, and it's unlikely we will have such plans in the future because the current product architecture does not allow implementing test steps "on the fly".

Our features planned for the upcoming year are listed in our [RoadMap](https://devexpress.github.io/testcafe/roadmap/).
