### ISSUE TITLE
Add headers to response via RequestHook?

### ISSUE THREAD

**Issue by ZebraFlesh** [DevExpress/testcafe#6021]
How do I add headers to the response in Testcafe? So far I've tried using the `onResponse` function of the `RequestHook` class. Using a `RequestLogger`, I can validate that the headers were added, but they don't actually make it to the browser (not visible in the list of response headers in Chrome's network tab).

Here's what I'm using:
```js
import { RequestLogger, RequestHook } from 'testcafe';

class HeadersHook extends RequestHook {
  constructor(requestFilterRules) {
    super(requestFilterRules, { includeBody: false, includeHeaders: true });
  }

  async onRequest(event) { }

  async onResponse(event) {
    event.headers['bar'] = 'foo';
    event.headers.foo = 'bar';
    console.log('hook: ', event.headers);
  }
}

fixture('My Fixture');

test('Example internal-sdk usage', async (t) => {
  const headerLogger = RequestLogger(process.env.TEST_URL, {
    logResponseHeaders: true
  });

  // This order is significant: adding the logger first causes it to miss the additional headers.
  // Not sure why.
  await t.addRequestHooks(new HeadersHook(process.env.TEST_URL));
  await t.addRequestHooks(headerLogger);

  await t.navigateTo(process.env.TEST_URL);
  console.log('logger: ', headerLogger.requests.length, headerLogger.requests[0].response.headers);

  t.debug();
});
```

This gives the following console output which seems to indicate that the headers were successfully added:
```text
hook:  {
  'content-type': 'text/html;charset=utf-8',
  vary: 'origin,accept-encoding',
  'access-control-allow-credentials': 'true',
  'access-control-expose-headers': 'WWW-Authenticate,Server-Authorization',
  'cache-control': 'no-cache',
  'content-encoding': 'gzip',
  date: 'Fri, 05 Mar 2021 16:43:06 GMT',
  connection: 'keep-alive',
  'keep-alive': 'timeout=5',
  'transfer-encoding': 'chunked',
  bar: 'foo',
  foo: 'bar'
}
logger:  1 {
  'content-type': 'text/html;charset=utf-8',
  vary: 'origin,accept-encoding',
  'access-control-allow-credentials': 'true',
  'access-control-expose-headers': 'WWW-Authenticate,Server-Authorization',
  'cache-control': 'no-cache',
  'content-encoding': 'gzip',
  date: 'Fri, 05 Mar 2021 16:43:06 GMT',
  connection: 'keep-alive',
  'keep-alive': 'timeout=5',
  'transfer-encoding': 'chunked',
  bar: 'foo',
  foo: 'bar'
}
```

But in the browser network tab, all I see is this (additional headers missing):
```text
access-control-allow-credentials: true
access-control-expose-headers: WWW-Authenticate,Server-Authorization
cache-control: no-cache
connection: keep-alive
content-encoding: gzip
content-type: text/html;charset=utf-8
date: Fri, 05 Mar 2021 16:45:51 GMT
keep-alive: timeout=5
transfer-encoding: chunked
vary: origin,accept-encoding
```

**Comment by AlexSkorkin** [comment]
Please await a response in the StackOverflow thread:

[https://stackoverflow.com/questions/66496441/add-response-headers-via-requesthook](https://stackoverflow.com/questions/66496441/add-response-headers-via-requesthook)

We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe/#contributing)). 

If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template. Thank you in advance.

**Comment by wentwrong** [comment]
I confirm that modifying the `body` or `headers` properties of the `event` object, which is passed to the `onResponse` method, doesn't affect the real response in the browser (although the [`responseEventConfigureOpts`](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/intercept-http-requests.html#create-a-custom-request-hook) object is configured). We'll see if there's a better way to modify the response, and update this thread.

In the meantime, please use the following workaround to set additional headers to the response:

```js
class HeadersHook extends RequestHook {
  constructor(requestFilterRules) {
    super(requestFilterRules, { includeBody: false, includeHeaders: true });
  }

  async onRequest () { }

  async onResponse () { }

  _onConfigureResponse (event) {
    super._onConfigureResponse(event);

    event.setHeader('foo', 'bar');
    event.setHeader('bar', 'foo');
  }
}
```

Please note that this workaround uses a private API – the `_onConfigureResponse` method.

**Comment by ZebraFlesh** [comment]
Thanks, the work around definitely works!

**Comment by wentwrong** [comment]
@ZebraFlesh, I'm happy to hear that the workaround resolved your issue. We'll reflect this in our docs and discuss the possibility of making this API public. Use #2991 to track our progress.

**Comment by ZebraFlesh** [comment]
@wentwrong I’m confused about this issue is closed. It looks like a bug, and the behavior definitely doesn’t match the documentation. #2991 is a feature request from 2018.

**Comment by wentwrong** [comment]
@ZebraFlesh It appears that this is not a bug, but rather an initial design decision - that the response should be either read-only or mocked entirely using `RequestMock`. However, later, some of our users came up with different use cases in which they needed to change only a part of the response (a body or headers) - #2991. Then, the `_onCongifureResponse` method was introduced to cover the case with modifying the headers of the response.

We decided to close this issue because essentially it is a part of the feature "[Add ability to mock only part of a response](https://github.com/DevExpress/testcafe/issues/2991)". However, I agree with you that the docs can be misleading. We'll clarify that the response can't be modified in the `RequestHook.onResponse` method and add the workaround mentioned above.
