### ISSUE TITLE
Testcafe tests don't support "User-Agent Client-Hints" headers introduced with latest Chrome v89 so certain API calls fail

### ISSUE THREAD

**Issue by estebanbalvin** [DevExpress/testcafe#6141]
### What is your Test Scenario?
I'm running a basic automated testcafe test that clicks a button (which triggers an API)on a webpage  , then it should wait for a response back from that API call to display some customer's information.
 
### What is the Current behavior?
The get call to the API fails with 500 Internal server error, as some headers are not sent from the browser.  I have detected that Chrome v89 on Windows 10 doesn't set the new "**User-Agent Client-Hints" headers `sec-ch-ua` and `sec-ch-ua-mobile`** when the test is driven automatically by testcase. This only happens when the test is automatic, when we run the test manually on Chrome it works fine. Ref: https://www.chromium.org/updates/ua-ch

I have downgraded Chrome to v87 and the automated tests run fine. It only happens on latest version of Chrome

### What is the Expected behavior?
Chrome v89 should set all the headers to the API calls when the test is triggered from Testcage  same as if the test is executed manually. 
 
### What is your web application and your TestCafe test code?
 
<details>
<summary>https://www.ami.co.nz/dashboard/</summary>))

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 

    async incidentDatefromCalendar(time){
        await t
        .expect(this.mrj_question.innerText).contains('When did the incident happen?')
        .typeText(incident_date.date_incident,time)
        .typeText(incident_date.incident_time,"1015")
        .click(incident_date.incident_am)
        .debug()
        .click(this.mrj_nextbutton)
        .wait(config.general.shortTimeout)
        .expect(this.mrj_nextbutton.hasAttribute('disabled')).notOk('Error retrieving info from Policy system- incident date', { timeout: config.general.shortTimeout });
    }

```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

</details>

<details>
<summary>Your complete test report:</summary>

<!-- Paste your complete result test report here (even if it is huge): -->
The test fails as the page shows a generic error after the API fails to retrieve the information.

</details>

<details>
<summary>Screenshots:</summary>
<!-- If applicable, add screenshots to help explain the issue. -->

done 
</details>

### Steps to Reproduce:
<!-- Describe what we should do to reproduce the behavior you encountered. -->

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:    "^1.14.0",           
* node.js version:     v14.15.5           
* command-line arguments:  testcafe chrome -c 1  ./src/tests/motorTests.js  --env=prod --live 
* browser name and version: Version 89.0.4389.72 (Official Build) (64-bit)
* platform and version:         Windows 10 64bits
* other:

**Comment by estebanbalvin** [comment]
This is the screenshot of the same test but executed manually, see that Chrome sets 2 headers that are not visible when the same scenario is run from BrowserStack
![Test result manually](https://user-images.githubusercontent.com/22824929/114810909-2520e200-9e01-11eb-82d4-50d77f3281f6.PNG)

**Comment by wentwrong** [comment]
Hello, @estebanbalvin,
I wasn't able to reproduce the issue using the information you shared. We'll need some reproducible example in order to fix it.

It looks like that the site you shared requires the login procedure. We need written confirmation and all required authentication data (login, password). Since your website ([https://www.ami.co.nz/dashboard/](https://www.ami.co.nz/dashboard/)) requires authentication, I will not be able to access it. Our policy prevents us from accessing a customer’s internal resources without prior written approval from the entity that owns the server/web resource.

If you want us to research the problem further, we’ll need access to the server/web resource. Please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.
