### ISSUE TITLE
TestCafe CLI is not returning exit code 1 on test failures

### ISSUE THREAD

**Issue by lprajus2007** [DevExpress/testcafe#6158]
### What is your Test Scenario?
REACT_APP_HOST=`echo ${ENV_HOST:-'0.0.0.0:3000'}` testcafe -c 2 --hostname localhost "$BROWSER --allow-insecure-localhost" "path-to-test-files"
 
### What is the Current behavior?
The above command doesn't return failure status code when tests are failing
 
### What is the Expected behavior?
TestCafe CLI should return the correct exit code when tests fail

The TestCafe CLI command is being run from a shell script and it exits with a code 0 no matter if tests pass or fail
Ex: `./test-script.sh; echo "$?"` always returns 0

**Comment by thelazurite-cell** [comment]
Hello @lprajus2007 ,

This may be of use to you:
```typescript
          createInstance('localhost', port, alternatePort, this.sslOptions)
                .then(async (tc: TestCafeInstance) => {
                    this.runner = this.createRunner(tc);
                    const browserStr = await this.getBrowser(thisBrowser);
                    const tagConfig = this.determineTags();
                    this.logConfiguration();
                    this.completeInit(thisBrowser);
                    return this.configureRunner(tagConfig, browserStr, thisBrowser);
                })
                .then((failedCount: number) => {
                    console.log('Tests failed: ' + failedCount.toString());
                    console.log(`Started at: ${this.startedAt} Completed at: ${moment().format('YYYY-MM-DD_HH:mm:ss')}`);
                    resolve(process.exit(failedCount > 0 ? 1 : 0));
                });
```
The first then, is configuring the testcafe runner, the second then is after testcafe has finished running

**Comment by wentwrong** [comment]
TestCafe [does](https://github.com/DevExpress/testcafe/blob/57aa1d303ffbe820e5711361ec5c3707899116ed/src/cli/cli.js#L128) set the exit code. I tried the following shell script:
```sh
#!/bin/bash
testcafe -c 2 --hostname localhost "chromium:headless --allow-insecure-localhost" test.js
```
With the `./test-script.sh ; echo "$?"` command, the exit code was shown correctly for me (0 if all tests passed and >0 if there were failed tests). Make sure that the command that runs TestCafe CLI is the last command in your script because bash returns the exit code of the last command after script execution.

If this doesn't help, please share the full content of your script or use the workaround with a custom [TestCafe Runner](https://testcafe.io/documentation/402641/reference/testcafe-api/runner) posted above by @thelazurite-cell.
