### ISSUE TITLE
[docs] Highlight info about TestCafe not being usable for performance testing

### ISSUE THREAD

**Issue by DIRECTcut** [DevExpress/testcafe#6160]
Our customers ask whether testcafe can be used for types of testing other than functional (performance, load testing). We have this mentioned in the [Best Practices Guide](https://testcafe.io/documentation/402836/guides/basic-guides/best-practices#e2e-test-scope), but it's not searchable. We need to optimize the topic for search engines (for example, rewrite the title to something like `Can I use TestCafe for Performance Testing?`

**Comment by fmancardi** [comment]
I would like again discuss a little bit regarding these topics.
Here my opinions, I will be great if you can provide more details in the documentation (Best Practices Guide)

**LOAD Testing**  
can testcafe be used for load testing?  
IMHO in order to generate load on your system you need some kind of automation, then testcafe scripts can be used to generate the load.  @DIRECTcut: do you disagree? Would you mind explain why? Would you mind to provide more details?

**PERFORMANCE testing (Browser Side / User Experience)**  
can testcafe be used to measure performance on the BROWSER side? 
Due to the way testcafe is implemented (the proxy hammerhed) is clear that the figures you can get can be higher/worse of the figures that can be collected using Chrome Development Console -> network.    
Then measurements **can NOT be used as absolute times**, but may be you can create some kind of conversion factor in this way: 
- you access the system and collect times from Developer Console. (TDC)   
- Then run your testcafe scripts adding some code that will get the execution time. (TTC)  
- Create the conversion factor: TDC/TTC.

I've working on collecting TTC, and the issues on measuring/getting TTC is how you can be sure the page has changed and page loading has finished, and anyway async things like AJAX can be difficult to measure  
I can provide you a system where you can see the problems I've mention.  

I'm very interesting on your opinions, and IMHO more details need to be added on official documentation

**Comment by miherlosev** [comment]
Hi @fmancardi

> can testcafe be used for load testing?
IMHO in order to generate load on your system, you need some kind of automation, then testcafe scripts can be used to generate the load.

You can simulate the load for the tested website. However, you'll have to do the rest yourself – run the TestCafe script on multiple machines, measure and display the results. Since TestCafe is not designed for that, it can be quite difficult. So, I do not recommend you use TestCafe for load testing.

> can testcafe be used to measure performance on the BROWSER side?
Due to the way testcafe is implemented (the proxy hammerhed) is clear that the figures you can get can be higher/worse of the figures that can be collected using Chrome Development Console -> network.

TestCafe proxies most of the DOM methods and properties to provide information about the execution state of the tested page to the tested engine (first of all, it's necessary for [Built-in wait mechanisms](https://testcafe.io/documentation/402827/guides/concepts/built-in-wait-mechanisms)). So, you're checking the performance of the TestCafe [url-rewrittern proxy](https://github.com/devexpress/testcafe-hammerhead), not the performance of the tested web site. TestCafe is not suitable for website performance testing.

We will add this information to our documentation.











https://github.com/DevExpress/testcafe/issues/6160

Hi @fmancardi 

> can testcafe be used for load testing?
IMHO in order to generate load on your system you need some kind of automation, then testcafe scripts can be used to generate the load. 

You can simulate the load for the tested website. The rest of the feature (capability to parallel the TestCafe script for few machines, measure logic, result presentation, etc.) you need to implement yourself. Since the TestCafe is not designed for that, it can be difficult. So, at that time, TestCafe is not useful for load testing purposes.

> can testcafe be used to measure performance on the BROWSER side?
Due to the way testcafe is implemented (the proxy hammerhed) is clear that the figures you can get can be higher/worse of the figures that can be collected using Chrome Development Console -> network.

TestCafe proxies the most DOM methods and properties to provide the tested engine the information about the tested page execution state. First of all, it's necessary for the [Built-in wait mechanisms](https://testcafe.io/documentation/402827/guides/concepts/built-in-wait-mechanisms). So, if you will measure the performance of the browser side, you check the performance of the TestCafe [url-rewrittern proxy](https://github.com/devexpress/testcafe-hammerhead) not the tested web site. So, the TestCafe is not useful for website performance testing.

We will add this into documentation.

**Comment by fmancardi** [comment]
Thanks for your explanations.
There is just a question about the following sentence:
_So, you're checking the performance of the TestCafe url-rewrittern proxy, not the performance of the tested web site._ 
But you are checking (and distorting) the site performance, because there is an additional 'layer' the proxy. do you agree?

best regards

**Comment by wentwrong** [comment]
Hello @fmancardi,

Yes, just as @miherlosev said, TestCafe is not suitable for website performance testing because the code of our proxy creates an additional load on your page's performance, making metric scores (such as timings) not very representative.

**Comment by fmancardi** [comment]
@wentwrong, ok thanks for the confirmation
