### ISSUE TITLE
feature request --test-meta-grep

### ISSUE THREAD

**Issue by fmancardi** [DevExpress/testcafe#6177]
### What is your Test Scenario?
the test test1 covers multiple tickets: 10101,2222,666
the test test2 covers multiple tickets: 9999,2222,333
the test test3 covers multiple tickets: 666,888

for each test a separated js file is created (design choice) with meta ISSUES with the values defined in this way:
for test1 test .meta({"ISSUES": "10101,2222,666"})
for test2 test .meta({"ISSUES": "9999,2222,333"})
for test3 test .meta({"ISSUES": "666,888"})

I would like to run test cases that cover issue 2222 OR 666, and AFAIK today it's not possible.

### What are you suggesting?
add **--test-meta-grep** keyword

then I will be able to launch testcafe in this way
testcafe ... **--test-meta-grep ISSUE='2222|666'**

the format to specify the pattern will be the same used by grep ([pattern multiple strings](https://phoenixnap.com/kb/grep-multiple-strings))

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/6177

Hi @fmancardi 

Thank you for sharing this idea.

**Comment by fmancardi** [comment]
HI
do you plan to consider this request? this issue has been closed automatically

best regards

**Comment by miherlosev** [comment]
Hi @lastzero,

This thread is about adding the command-line option `--test-meta-grep`. Due to low demand we keep it closed.
However, you can filter tests by `meta` using the [Runner.filter](https://testcafe.io/documentation/402657/reference/testcafe-api/runner/filter#header) method. In this case, you need to use a [programmatic way](https://testcafe.io/documentation/402655/reference/testcafe-api/runner/run) to run your tests.

**Comment by lastzero** [comment]
Thank you! I understood that. It was feedback on the requested `--test-meta-grep` parameter, because it seems to be ONE WAY for non-developers to implement a blacklist (without developing their own filtering function, which not all users can do flawlessly even if they find it in the docs).

This is a common use case for test tools that IMHO you should consider. Should I have a little time, I will try to contribute.

**Comment by miherlosev** [comment]
Thank you for the feedback. Your contribution is greatly appreciated.
