### ISSUE TITLE
Uncaught object "[object Object]" was thrown. Throw Error instead.

### ISSUE THREAD

**Issue by Tall-KU-RideOn** [DevExpress/testcafe#6197]
### What is your Test Scenario?
Starting TestCafe always hangs on first page
 
### What is the Current behavior?
When loading Chrome/Safari/FireFox, the page always hangs.  The page is 100% clickable and the user can manually navigate away from the page (this shouldn't happen).  Eventually the test fails with this error: `Uncaught object "[object Object]" was thrown. Throw Error instead.`
 
### What is the Expected behavior?
TestCafe continues without any error
 
### What is your web application and your TestCafe test code?
This can be reproduced on any page, any test file.
 
### Your Environment details:
 
* testcafe version:                  v1.14.0
* node.js version:                   v14.16.1
* command-line arguments:  `testcafe chrome <testfilename>`
* browser name and version: Chrome Version 90.0.4430.93, Safari Version 14.1 (16611.1.21.161.3)
* platform and version:           macOS 11.3 (20E232)

**Comment by AlexSkorkin** [comment]
When I run a test, the page is locked and I cannot interact with it. Please clarify how you "manually navigate away from the page". And why you do this.

**Comment by Tall-KU-RideOn** [comment]
@AlexSkorkin - For me, this doesn't require a sample test file.  I can replicate it anytime that I start TestCafe up locally on my machine.  Regardless of what example page I go to, TestCafe always hangs on the first page and then throws that `[object][object]` error.

**Comment by diegovf** [comment]
@Tall-KU-RideOn I ran into the same problem, everything was working ok and from one moment to another - just out of the blue - TestCafé stopped working.  
I found out that the issue is that the tested webpage was using self-signed certs, and fixed it by using [--hostname localhost](https://testcafe.io/documentation/402639/reference/command-line-interface#--hostname-name).  
If that's the case, you can check [this](https://testcafe.io/documentation/402839/guides/advanced-guides/test-https-features-and-http2-websites) out for more info.
