### ISSUE TITLE
Testcafe browser window launches to 'about:blank' with console errors

### ISSUE THREAD

**Issue by GibDot** [DevExpress/testcafe#6241]
### What is your Test Scenario?

Every test is unable to start as expected in Chrome or Firefox (functional when running tests via docker).

### What is the Current behavior?

Browser launches to a Testcafe page w/ 'about:blank' and various JS errors in console, doesn't move from this page.
 
### What is the Expected behavior?

Getting past initial page load and continuing to run the tests.
 
### What is your web application and your TestCafe test code?
<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { t } from 'testcafe'

fixture('About Blank')

test('Go to URL', async () => {
  await t.navigateTo('https://www.github.com')
})
```
</details>

### Steps to Reproduce:

1. Run any TestCafe test
2. See page load to `http://192.168.1.167:53023/do7j2zBCU*c1hyXyWs7/about:blank`
3. Inspect console for following logs

Chrome:
```
Failed to load resource: net::ERR_INVALID_HTTP_RESPONSE // :60901/ testcafe-automation.js:1
Failed to load resource: net::ERR_INVALID_HTTP_RESPONSE // testcafe-driver.js:1
Uncaught TypeError: ClientDriver is not a constructor   // task.js:48
    at task.js:48
    at task.js:69
    at task.js:71
```

 Firefox:
```
Uncaught SyntaxError: expected expression, got '}'     // testcafe-automation.js:1:37
Uncaught SyntaxError: expected expression, got ')'     // testcafe-driver.js:1
Uncaught TypeError: ClientDriver is not a constructor  // task.js:48:24
    <anonymous> http://192.168.1.167:53023/task.js:48
    <anonymous> http://192.168.1.167:53023/task.js:69
    <anonymous> http://192.168.1.167:53023/task.js:71
```

### Your Environment details:
 
* testcafe version:                  1.14.2
* node.js version:                    v14.17.0
* command-line arguments:  testcafe chrome test.js OR testcafe firefox test.js
* browser name and version: Chrome - 90.0.4430.212, Firefox - 88.0
* platform and version:          macOS 11.3.1
* other:                                     If left idle for two minutes the window will close and re-open to the same 'about:blank' URL.
                                                  Testcafe logging states it is running in {Browser} / macOS 10.15, but I am on macOS 11.3.1

**Comment by sebiglesias** [comment]
I've been having the same issue, it's been driving me crazy. It started happening right after the last macOS Big Sur update and I've been using the same Testcafe version and code for over several months.

**Comment by agustinlg** [comment]
+1

**Comment by AndreyBelym** [comment]
Unfortunately, I cannot reproduce it after updating my Mac. 

@GibDot you mentioned that you use docker to run TestCafe, have you tried to install and TestCafe directly from the host OS?

@sebiglesias @agustinlg do you use docker too?

**Comment by ajc24** [comment]
+1 here too.

I had no trouble running TestCafe from my NodeJs project on MacOS until I updated to Big Sur version 11.3.1.
At that point I can't run TestCafe tests locally anymore using `testcafe chrome my-test.js`, it will boot the browser up, register multiple errors in the console and then fail to progress any further.

MacOS Big Sur 11.3.1
TestCafe version 1.4.2
Node version 14.17.0
NPM version 6.14.13
Chrome version 90.0.4430.212 (Official Build) (x86_64)

The really strange thing is that **sometimes** the tests will run fine locally (to the point where I think the problem is resolved) but then just stop working and hit the same reported errors again.

Further info:

Similar to what @GibDot has mentioned, I am also executing TestCafe tests using Chrome via a Docker container. The tests run fine every single time via Docker (my Docker container uses a Linux environment). Yet they won't launch locally in MacOS.

I have tried running Firefox version 88 and Safari version 14.1 (16611.1.21.161.6) locally too and all browsers hit the same problem: browser launches, hit the same errors as reported in the initial post (hammerhead and TestCafe API errors) and then the tests do not progress any further.

---

So here's my test script `test.e2e.test.js` (for reference):
```
fixture('Test Script');

test.page('https://www.google.ie')(
  'Verifies something...',
  async t => {
    console.log('***** WAIT');
    await t.wait(5000);
    console.log('***** VERIFICATION');
    await t.expect(true).ok();
  }
);
```

And my NPM script to launch it:
```
"test:chrome": "testcafe chrome test.e2e.test.js"
```

Just now I've run this test **four** times
**Three** times it passed as normal (note the incorrect MacOS version reported:
![Screenshot 2021-05-20 at 13 01 57](https://user-images.githubusercontent.com/11652950/118975370-dc15fd80-b96b-11eb-8b6f-70e3557134d3.png)

Then on the fourth run it just hung there and wouldn't progress with errors shown in the console:
![Screenshot 2021-05-20 at 13 02 21](https://user-images.githubusercontent.com/11652950/118975567-09fb4200-b96c-11eb-96fa-21e3a8b93e7b.png)

<img width="1201" alt="Screenshot 2021-05-20 at 13 02 46" src="https://user-images.githubusercontent.com/11652950/118975583-0ff12300-b96c-11eb-9ea3-0944e216bc2f.png">

**Comment by AndreyBelym** [comment]
The OS version displayed by TestCafe is detected by the browser's user agent. For security reasons, modern browsers do not provide any very detailed information about the user's environment. You can open a DevTools console and check that `navigator.userAgent` contains `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)` even without TestCafe. It should have no impact on test execution.

Unfortunately, I cannot reproduce the problem even after starting TestCafe more than 20 times. What processer type does your Mac have, Intel or ARM?

**Comment by ajc24** [comment]
@AndreyBelym my Mac has an Intel processor.

**Comment by AndreyBelym** [comment]
Could you please try to install a different Node.js version? E.g. 12.22.1 and 16.2.0

**Comment by GibDot** [comment]
> @GibDot you mentioned that you use docker to run TestCafe, have you tried to install and TestCafe directly from the host OS?
This is running TestCafe directly from my host machine, running via Docker doesn't appear to have problems.

These errors arise when running TestCafe in my local environment, but run without error in Docker.

> Could you please try to install a different Node.js version? E.g. 12.22.1 and 16.2.0

Same error occurs when running the latest version of Node.js (v16.2.0)

> Also, could you please try to open the Network tab in the Chrome Developer tools, hit the reload button in the browser, and if it throws an error again, [collect and share a HAR report]?

Using reload on the second or third attempt will get the test working as expected.  Attached HAR report from the initial failure on reload.

[HAR Report (Google Drive)](https://drive.google.com/file/d/1QdCPzKEP-BFTXCym7hs3MeUyuqwXDygY/view?usp=sharing)

**Comment by ajc24** [comment]
@AndreyBelym 

> Also, could you please try to open the Network tab in the Chrome Developer tools, hit the reload button in the browser, and if it throws an error again, [collect and share a HAR report](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)?

This is interesting. Whenever I reload the page after hitting the error, the errors do not show up on page reload.
Seems this is only an intermittent issue on first launching the browser. Manual refresh / reload clears it.

> Could you please try to install a different Node.js version? E.g. 12.22.1 and 16.2.0

Working on this as we speak.

**Comment by ajc24** [comment]
NodeJs version 16.2.0: Seeing the same test intermittently hanging on first load with errors logged in the console. Errors clear and test progresses normally after page refresh.

![Screenshot 2021-05-20 at 14 46 43](https://user-images.githubusercontent.com/11652950/118989915-53eb2480-b97a-11eb-925e-d13a2773f4ed.png)

<img width="1204" alt="Screenshot 2021-05-20 at 14 46 32" src="https://user-images.githubusercontent.com/11652950/118989935-59486f00-b97a-11eb-8dfb-50b802064893.png">

**Comment by kyle-johnson** [comment]
Adding `--hostname localhost` on Big Sur seems to fix this issue for me.

**Comment by ajc24** [comment]
Just want to second the fix suggested by @kyle-johnson 
I've run around 30 tests this morning since updating the `createTestCafe` API to use a `localhost` value for its `hostname`.
```
const testcafe = await createTestCafe({
  hostname: 'localhost',
});
```
I've run tests across Chrome and Firefox mainly (same versions as quoted earlier in this ticket) and everything is running perfectly now. Thanks for the tip Kyle!

Continuing to test this over the course of the day but this looks to have completely resolved it.

**Comment by AndreyBelym** [comment]
It seems that the issue can be caused by some Node.js issue: https://github.com/nodejs/node/issues/38709

The issue poster mentions that the "Network Monitor" component should be removed to fix broken systems: https://github.com/nodejs/node/issues/38709#issuecomment-845493173

As for now, it seems that's all we can do. Thanks @kyle-johnson for discovering the workaround, I'll add it to the original post.

**Comment by ArmandoAmador** [comment]
Hi, I was having the same issue `Failed to load resource: net::ERR_INVALID_HTTP_RESPONSE until I saw the --hostname workaround. 🥇

Is there a workaround for the case when you use `testcafe remote` command? The Browser starts but nothing happens on the page. 😢

**Comment by VasilyStrelyaev** [comment]
We have not tested any workaround for remote testing yet. However, I can recommend the following approach for you to try:

1. Set up request rerouting on a remote machine from `localhost` to your computer (the machine where you run TestCafe)
2. Run tests on your computer: `testcafe remote tests/ --hostname localhost`
3. Open the generated URL on the remote machine as you would normally do.

Please let us know of your results.
