### ISSUE TITLE
Can't use role  with a "post login redirect" strategy

### ISSUE THREAD

**Issue by htulipe** [DevExpress/testcafe#6269]
### What is your Test Scenario?
This is a bug reported per suggestion of @AlexKamaev on [my SO question](https://stackoverflow.com/questions/67718794/post-login-redirect-logic-does-not-work-with-testcafe-roles). 
 
You can read the SO question for further details but here is a recap:

My app catches any unauthenticated access, save the requested route in localStorage and redirect user to login page. When login is done, the app check for the saved route in localStorage and redirects the user to it. Fallback is redirecting the user to homepage ("/").

I want to test that on a given route ("/some-route") I have the expected content (some listing of stuff or whatever). To factorize the auth process, I'm using a Role in a beforeEach hook but it does not work as expected with my app

### What is the Current behavior?

When the test is ran (cf reproduction app):
1. testcafe goes to "/some-route"
2. My app redirects it to "/login". 
3. testcafe initialize the Role, navigating to "/login"
4. testcafe execute the role code successfully 
5. My app redirects testcafe to "/" instead of "/some-route"
 
### What is the Expected behavior?
I'd expect testcafe to access "/some-route" after the role initialization. 

My understanding is that testcafe memorize "/login" as the route to redirect to because it's the current location before Role initialization (due to step 2 above).

### Steps to Reproduce:

I created a sample project demonstrating my usecase here [https://github.com/htulipe/testcafe_bug](https://github.com/htulipe/testcafe_bug)
 
### Your Environment details:
 
* testcafe version:                   1.14.2
* node.js version:                    v14.15.1
* command-line arguments:  `testcafe chrome e2e/`
* browser name and version:  Chrome 90.0.4430.212 
* platform and version:          MacOS 11.2.1

**Comment by AlexKamaev** [comment]
Thank you for the example. I was able to reproduce the issue. At this moment, it's difficult to determine its cause. I can only say that initial redirect in the Role(`$/login') constructor affects storage processing.

I tried to modify role settings and found the following workaround:


```JS
import { Role, Selector } from "testcafe";

const URL = "http://localhost:8080";

// NOTE: /some-route in initializer
const adminUser = Role(`${URL}/some-route`, async (t) => {
  console.log('role initializer');

  await t.click("button");
// NOTE: use the `preserveUrl` option
}, { preserveUrl: true });

fixture`Sample tests`.beforeEach(async (t) => {
  await t.useRole(adminUser);
});

test("test1", async (t) => {
  await t.expect(Selector("div").withText("This is some route").exists).ok();
});

test("test2", async (t) => {
  await t.expect(Selector("div").withText("This is some route").exists).ok();
});
```
Please try this approach in your real application.

**Comment by htulipe** [comment]
Hi, thanks for the follow up.

Creating a role with "/some-route" as URL surely will work but then I can't share the role with all my others tests (which are ran on other routes).

**Comment by AlexKamaev** [comment]
I understand. I just wanted to check if this workaround works in your real application. Otherwise, the cause of you real issue can be different. Anyway, thank you for the detailed information.

**Comment by AlexKamaev** [comment]
I researched the issue and found that the Roles mechanism works as expected. The cause of the issue you encountered is that you write `redirectUrl` to the local storage before the Role is initialized. However, the Role's initialization function starts with empty cookies and storages. This means that Roles do not preserve the cookies/local storage state that were set before the role was initialized.

Thus, the workaround that I described above is correct in this usage scenario.

Since this workaround is not quite suitable for you, please modify your example to demonstrate the issue with multiple routes. We'll try to find a more suitable solution.

**Comment by htulipe** [comment]
Hi Alex and thanks again for the follow up,

What puzzles me is why the test access the webpage before the role is initialized. For what I see it goes like this:

1. go to the URL specified at fixture level 
2. initialize the role

I would expected the execution order to be flipped: initialize the role, then access my page. Maybe beforeEach is not the right place to define my role ?

On a more general note, maybe I'm mistaken but I don't see my use case as particularly exotic: it's a "catch and redirect to login page" strategy which looks quite common. Has nobody ever encountered such a use case ? Maybe my implementation is flawed. 

I'm currently working around this issue by specify home as my tests URL, then in my tests, navigate to the URL I want. It takes longer to execute tests (go to home, getting redirected to login, initializing role, getting redirected to home, navigating to the desired URL) but it does work.

Thanks again

**Comment by AlexKamaev** [comment]
> What puzzles me is why the test access the webpage before the role is initialized. For what I see it goes like this:
> 
> 1. go to the URL specified at fixture level
> 2. initialize the role
> 
> I would expected the execution order to be flipped: initialize the role, then access my page. Maybe beforeEach is not the right place to define my role ?

It is default behavior that the test accesses the web page before the role is initialized. The `useRole` method requires the web page, because it's an ordinary TestController (the `t` variable) method like `t.click` and others.

You can start your test from the `blank` page as I described in the workaround. To do this, you can omit the `.page` declaration for the fixture/test.
In this case, if you start the test from the blank page, the Role will preserve the redirectUrl.

> On a more general note, maybe I'm mistaken but I don't see my use case as particularly exotic: it's a "catch and redirect to ?> login page" strategy which looks quite common. Has nobody ever encountered such a use case ? Maybe my implementation is flawed.

I agree that your usage scenario is not unusual. However, the implementation of your case depends on `localStorage`, so the Role url should contain the `/some-route` url and the `preserveUrl` option. I do not think that your implementation is incorrect. It just needs to be more specific in role setup.



>I'm currently working around this issue by specifying "home" as my tests URL, then in my tests, navigate to the URL I want. It takes longer to execute tests (go to home, getting redirected to login, initializing role, getting redirected to home, navigating to the desired URL) but it does work.

What if you use the role from the workaround and add some additional `t.navigate` calls after the `t.useRole` in your test?

**Comment by htulipe** [comment]
Sorry for the delay, I've moved away from e2e right now since my team is not fully convinced of their benefit in our case. 

If I got time I'll try starting on a blank page but anyhow, my work around is "working" since I can run my tests. Thanks for your time!

**Comment by codambro** [comment]
I think this should be reopened. I am also experiencing this. Obviously the workaround is to have `t.navigateTo` as part of every fixtures `beforeEach` instead of defining in `fixture.page`. But this significantly slows down testing time as we are continuously waiting for the initial login redirect page to load despite not testing  it.

**Comment by codambro** [comment]
I did end up using the workaround suggested. It's a little clunky, and more frustratingly is I can't use relative URLs in page objects without specifying `.page` in the fixture. So I had to update all URLs to absolute paths. But it works...

Previous code:
```
const role = Role(baseUrl, async () => { /* login */ }, { preserveUrl: true });

fixture.page(testPageUrl).beforeEach(async t => { await t.useRole(role); });
```

New code:
```
const role = Role("about:blank", async () => { await t.navigateTo(loginPage); /* login */ });

fixture.beforeEach(async t => { await t.useRole(role); await t.navigateTo(testPageUrl); });
```
