### ISSUE TITLE
Testcafe test not working on MacOS - BigSur

### ISSUE THREAD

**Issue by Aishmaheshwari** [DevExpress/testcafe#6298]
I created a basic testcafe test and tried to execute it for a POC.

```js
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `http://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    await t
        .typeText('#developer-name', 'John Smith')
        .click('#submit-button');
});
```

After I give command to execute the test, it launches the browser with the given URL and get's stuck there only, nothing gets typed on the screen.

The below can be seen in the terminal:

` Running tests in:
 - Chrome 91.0.4472.77 / macOS 10.15.7

 Getting Started`
 
 
* testcafe version:                   1.14.2
* node.js version:                    v16.0.0
* command-line arguments:  testcafe chrome -e test.js
* browser name and version: Chrome 69, Firefox 100, Safari
* platform and version:          macOS 11.4 BigSur

**Comment by PaulMEdwards** [comment]
Worked fine for me...

```javascript
import { Selector } from 'testcafe';

fixture(`Getting Started`).page(`http://devexpress.github.io/testcafe/example`);

test('My first test', async (t) => {
    await t.typeText('#developer-name', 'John Smith').click('#submit-button');
});
```

```
➜  e2e git:(master) # nvm use v16
Now using node v16.0.0 (npm v7.10.0)
➜  e2e git:(master) # npx testcafe --version
1.14.2
➜  e2e git:(master) # npx testcafe chrome -e test.spec.js      
 Running tests in:
 - Chrome 91.0.4472.77 / macOS 10.15.7

 Getting Started
 ✓ My first test


 1 passed (2s)
```

![Screen Shot 2021-06-10 at 11 04 35 AM](https://user-images.githubusercontent.com/153847/121575158-e4e27800-c9db-11eb-85c0-d22f35788bff.png)


However, you might want to explicitly use the Selector, like one of these examples:

```javascript
    await t.typeText(Selector('#developer-name'), 'John Smith').click('#submit-button');
```
```javascript
    const devName = Selector(`#developer-name`);
    await t.typeText(devName, 'John Smith').click('#submit-button');
```

**Comment by VasilyStrelyaev** [comment]
@PaulMEdwards  thank you for testing this!
 
I cannot reproduce this issue either. @Aishmaheshwari please clarify if you see an empty page or the target page is loaded. If it is the former, try the tips from the [Troubleshooting](https://testcafe.io/402636/faq#i-have-installed-testcafe-but-i-cannot-run-it-what-should-i-do) document. You can also try setting the [--hostname flag](https://testcafe.io/documentation/402639/reference/command-line-interface#--hostname-name) to `localhost` because this bug looks similar to https://github.com/DevExpress/testcafe/issues/6241
 
```sh
testcafe chrome -e test.js --hostname localhost
```

**Comment by PaulMEdwards** [comment]
Interestingly, I do have the hostname set to `localhost` in my config file in the existing project I used to quickly test this...
However, when I removed that setting, it still worked fine.

**Comment by Aishmaheshwari** [comment]
@VasilyStrelyaev @PaulMEdwards Thank you for your help!

It worked fine with this command
`testcafe chrome -e test.js --hostname localhost`

Can you also help me understand what adding a hostname to localhost for http://devexpress.github.io/testcafe/example fixes the issue and also am I supposed to keep the command same for production environments as well.

**Comment by miherlosev** [comment]
Hi @Aishmaheshwari

Thank you for confirming that the workaround helps. We will investigate this behavior. We will update this thread as soon as we have any results.

**Comment by miherlosev** [comment]
Windows 10

https://github.com/DevExpress/testcafe/issues/6274

**Comment by Farfurix** [comment]
@Aishmaheshwari @ssg127 @pubkey @GibDot @ajc24

Hello,

The possible reason is pointed out in related threads ([1](https://github.com/DevExpress/testcafe/issues/6241#issuecomment-846858750), [2](https://github.com/nodejs/node/issues/38709#issuecomment-845493173)) as a third-party software issue.
Let's check it on your side. Run the simple Node.js HTTP server (see example [here](https://nodejs.org/en/knowledge/HTTP/servers/how-to-create-a-HTTP-server/)) and request the `<your IP>:<used port for TestCafe>/index.html` page. If the page does not open, then the issue is not related to TestCafe.
After that, you can investigate why your machine doesn't allow access by IP address. This may occur because of third party software, firewall settings, and so on.
