### ISSUE TITLE
Save native dialog is shown when running tests in firefox via 'path:'

### ISSUE THREAD

**Issue by wombatka** [DevExpress/testcafe#6326]
Files are not automatically saved when running testcafe on firefox-esr . Save native dialog is shown instead which is impossible to interact with .
 Firefox version: 78.11.0esr

**Comment by AlexKamaev** [comment]
I could not reproduce the issue. Please share a simple example to demonstrate it. Please also specify the OS you use and the command in the terminal that you use to run the tests.

**Comment by wombatka** [comment]
The issue occurs to me when trying to export a file that has a .par extension (an archive of special type). WHen exporting manually In firefox (both esr and canonical) a dialog is then shown because the  browser does not know
![image](https://user-images.githubusercontent.com/25752375/123072639-fed97d00-d415-11eb-82ee-d6c7a0dee8ae.png)

When running tests on canonical firefox or chrome the dialog is not shown and file is saved
When running test on firefox-esr the dialog is shown and cannot be handled so the file is not saved and test fails

I am running tests on Linux Ubuntu 18.04 LTS. I run the test with the following command : testcafe path:/path/to/firefoxEsrBinary tests

**Comment by miherlosev** [comment]
Hi @wombatka
It looks like TestCafe doesn't properly handle the process of downloading `par` files. This occurs because TestCafe uses the `mime-db` library to handle file downloading and its library doesn't contain the definition for the `par` file format. Also, I can't find information about the `par` file format [here](https://www.iana.org/assignments/media-types/media-types.xhtml).
As I see in the previous comment, the `par` file is downloaded using the `blob` scheme.
E.g. `<a download="file.par" href="blob:http://localhost:8080/54f4141c-9ec6-4f9e-a125-abcb16a0593a" id="link">Download .par</a>`
Could you please inspect the application code, find the place where URL is set up, and share this code part?
It can look like this:

```js
let blob = new Blob(["data"], { type: 'mime-type-of-par' });
document.querySelector('#link').href = URL.createObjectURL(blob);
```

**Comment by wombatka** [comment]
It works on firefox canonical and chrome- the file is correclty downloaded ,  so I guess it is not the problem with downloading itself

**Comment by miherlosev** [comment]
Ok, I understand. Then, we still need an example that we can reproduce locally without any additional setup.

**Comment by wombatka** [comment]
there you go. I found this page with download blob button : https://gojs.net/latest/samples/minimalBlob.html . I wrote a simple test:

import {Selector, t} from "testcafe"
fixture `example`
    .page `https://gojs.net/latest/samples/minimalBlob.html`;

test('Submit a form', async t => {
    await t.click(Selector("#blobButton"));
});

When running on firefox esr with :  testcafe path:/pathToFirefoxEsr/firefox-esr example.js
I get this dialog after button click:
![image](https://user-images.githubusercontent.com/25752375/123602110-b72d6980-d7f8-11eb-84e7-d997cf91fb23.png)

I am not getting the dialog neither on canocical firefox nor chrome

**Comment by VasilyStrelyaev** [comment]
Thank you for your example. I have managed to reproduce this behavior.
 
This issue does not seem to be related to the ESR version in particular, but rather to running Firefox via the `path` keyword. I also reproduced it with the latest Firefox version if I specify the executable path instead of the alias. In the same way, I *did not* reproduce it when I left only the ESR version on my computer and used the alias `firefox` to run it.
 
We will update this thread once we have any news.
