### ISSUE TITLE
Improve video frame rate by using the Chrome DevTools Screencasting API

### ISSUE THREAD

**Issue by HanmingWu-TW** [DevExpress/testcafe#6422]
### What is your Test Scenario?
I want to record my test scenarios

### What is the Current behavior?
Video frame is very low even I set r higher
 
### What is the Expected behavior?
Video frame can be set or just higher
 
### What is your web application and your TestCafe test code?
Runner setting:
            .video('videos', {
                pathPattern: '${FIXTURE}-${TEST}-${BROWSER}.mp4'
            },{
                r: 30,
                s: '1366*768',
                aspect: '1366:768'
            })
 
### Your Environment details:
 
* testcafe version:                   1.15.0
* node.js version:                   16.5.0
* command-line arguments:  
* browser name and version: chrome and firefox
* platform and version:          macOS
* other:                                   

And I think it is similar with https://github.com/DevExpress/testcafe/issues/3685

**Comment by AndreyBelym** [comment]
Currently, the framerate is limited by Chrome APIs. Please see this comment for a detailed explanation: https://github.com/DevExpress/testcafe/issues/3685#issuecomment-511730325

**Comment by HanmingWu-TW** [comment]
> Currently, the framerate is limited by Chrome APIs. Please check this comment for a detailed explanation: [#3685 (comment)](https://github.com/DevExpress/testcafe/issues/3685#issuecomment-511730325)

I find this message and change to use firefox but the frame still very low. Is there any way to set firefox then I can have high frame video?

Runner setting:
.browsers('firefox')
.video('videos', {
pathPattern: '${FIXTURE}-${TEST}-${BROWSER}.mp4'
},{
r: 30,
s: '1366*768',
aspect: '1366:768'
})

**Comment by aleks-pro** [comment]
The problem is in the browser performance. Firefox can record a video with a higher frame rate than Chrome, but it's still insufficient to meet the requirements. The issue got complicated because Firefox has no alternative screencasting API with which this behavior might be avoided.

PS: We keep the GitHub issues tracker only for bugs and feature requests (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)). So, this looks like a question that is best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. If you think that this is a bug, feel free to open a new issue. In this case, please make sure that you follow the bug template.

**Comment by AndreyBelym** [comment]
The research is complete. 

We should call `Page.startScreencast` and receive screenshots via the `Page.screencastFrame` event. The `sessionId` event argument should be passed to the `Page.screencastFrameAck` method for each received frame, otherwise, the browser will stop the screencast after sending a few frames. 

The resulting video is astonishingly smooth. However, there are a few caveats with FFMPEG.

First - the browser won't send a frame if it doesn't render something new since the last frame. So especially when we should finish recording, we have to duplicate the previously received frame, otherwise, a part of the video could be lost. If we implement a buffer that contains screencast frames, it should be easy to overcome this.

Second - sometimes things in the video run faster than real actions. Likely it happens because I didn't use the original timestamps provided by the browser, and relied on timestamps generated by FFMPEG internally when it receives each frame (that's how it works right now). There are two approaches to overcome this issue: we can use the [`concat` input demuxer](https://trac.ffmpeg.org/wiki/Slideshow#Concatdemuxer)(actually it is not practical since it requires saving each frame as a separate file) or add delays before passing frames to FFMPEG.

**Comment by AndreyBelym** [comment]
Also maybe we should limit the framerate that the browser outputs like https://github.com/cypress-io/cypress/pull/18392
