### ISSUE TITLE
How to force TestCafe to use VPN

### ISSUE THREAD

**Issue by IsabelAntonia** [DevExpress/testcafe#6447]
I want to test a comment section on a webpage. This comment section is only visible if the webpage is accessed through a vpn. If there is no vpn connection pressing the button to open the comments will do nothing. If it is connected the comment section will open below the button.
 
If the page is opened via running the script I can't access the comment section even though I am connected to the vpn. 
I am checking this by clicking the openComment button and scrolling down to see if the comment section is showing up.

I would like to force testcafe to use the vpn. 

i am not allowed to share the url of the webpage. 

This is my script:

```js
import { Selector } from 'testcafe';
// Node.js modules.
import fs from "fs";
import path from "path";
import { ClientFunction } from 'testcafe';

const scrollBy = ClientFunction((x, y) => {
   window.scrollBy(x, y);
});

const openComments = Selector('button').withAttribute('title', 'Kommentare öffnen');

fixture `Getting Started`
    .page `https://...`;


test('My first test', async t => {
        await t
        .click(openComments)
        
     // scroll down to check if correct content is shown 
        await t
        .scrollBy(0,400);
        
});
```
 
* testcafe version:                   1.14.0
* node.js version:                    v11.2.0
* command-line arguments:  testcafe chrome testcafe.js --speed 0.8
* browser name and version: Chrome 92
* platform and version:          macOS 10.15.6

**Comment by AlexKamaev** [comment]
There is no difference between testing with or without VPN connection. You can connect to your VPN network with your VPN client and start testing. Please note that sometimes TestCafe can't automatically detect an IP address that should be used to serve a tested website when your machine is connected to multiple networks. In this case, try specifying the --hostname localhost option when starting TestCafe.

**Comment by IsabelAntonia** [comment]
Thank you! I am still struggling. What you are suggesting is running my script like this: testcafe chrome test.js --hostname localhost? I tried that and that did not make a difference. Is there something else I can do?

**Comment by Farfurix** [comment]
@IsabelAntonia 

Hello,

Are you able to go through test scenario steps manually, with your VPN connection, but without TestCafe? Please update TestCafe to the latest version (v1.15.3) and try to run a simple test (using your VPN connection) and share the result with us.
**test.js**:
```js
import { Selector } from 'testcafe';

fixture `Fixture`
    .page('https://github.com/');

test('test', async t => {
    const h2 = Selector('body > div.application-main > main > div.overflow-hidden > div.home-hero-container.position-relative.js-webgl-globe-data > div.home-hero.position-absolute.z-1.top-0.right-0.bottom-0.left-0.overflow-hidden > div > div > div.ml-md-n3.mr-md-3.col-12.col-lg-6.text-center.text-md-left > h1');

    await t.expect(h2.innerText).eql('Where the world builds software');
});
```
**Commands to run**:
1. `testcafe chrome test.js`
2. `testcafe chrome test.js --hostnname localhost`

**Comment by IsabelAntonia** [comment]
@Farfurix 

Hey, going through the test scenario steps manually without TestCafe works. It also works when I use Browserstack Live (after enabling local testing + force local). I updated to version 1.16.0 and ran the test above. Both commands resulted in passed tests. VPN was switched on.

**Comment by Farfurix** [comment]
@IsabelAntonia 

Hello,

Since the issue can be reproduced with your application and your specific VPN connection only and it cannot be reproduced with some other external resource, we are not able to debug this scenario on our side. I can only assume that this issue may relate to some network routing settings that are used to access your internal testing application by VPN. In this case, you can send us the access data (VPN connection settings, internal application URL, and the test code) by email (support@devexpress.com).

Since your website sits behind a proxy and requires authentication, I will not be able to access it. Our policy prevents us from accessing a customer’s internal resources without prior written approval from the entity that owns the server/web resource. If you want us to research the problem further, we’ll need access to the server/web resource. Please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.
