### ISSUE TITLE
Connect remotely to Android device > testcafe remote tests --qr-code > FAILS

### ISSUE THREAD

**Issue by mariushorvat** [DevExpress/testcafe#6539]
### What is your Test Scenario?
Connect remotely to Android device > testcafe remote tests --qr-code
 
### What is the Current behavior?
After running the above command - I'm getting this error: _There are no available _connections to establish._
![Samsung Internet](https://user-images.githubusercontent.com/52577229/133153346-003f7a53-be5a-4628-ae88-e9fb7b3084a1.jpg)
 
### What is the Expected behavior?
I should have get the Connected TestCafe screen - same as in IOS - which works
 
### What is your web application and your TestCafe test code?

> import { Selector } from "testcafe";
> // fixture("authentication suite").page("https://qa-automation-practice.netlify.app/login.html");
> ​
> // prettier-ignore
> fixture `authentication suite`.page `https://qa-automation-practice.netlify.app/login.html`
> test("login scenario - bad creds", async (t) => {
>   const emailField = Selector("#email");
>   const pswField = Selector("#password");
>   const loginBtn = Selector("#submitLoginBtn");
>   const responseMsgElement = Selector("#message");
>   const responseSuccessMessage =
>     "Bad credentials! Please try again! Make sure that you've registered.";
> ​
>   await t
>     .typeText(emailField, "admin@admin.com")
>     .typeText(pswField, "admin123")
>     .click(loginBtn)
>     .expect(responseMsgElement.innerText)
>     .contains(responseSuccessMessage);
> });

 
<details>
https://qa-automation-practice.netlify.app/login.html - It works fine with IOS device

</details>

### Steps to Reproduce:

1. run testcafe remote tests --qr-code
2. Scan the QRCODE with any Android device (mine was Samsung S10, S21 + OnePlus 8)
3. This is the terminal error : _CONNECTED Android Browser 0.0 / Android 0.0
ERROR The Android Browser 0.0 / Android 0.0 browser disconnected. If you did not close the browser yourself, browser performance or network issues may be at fault._
4. Phone error show before the terminal error:
![Samsung Internet](https://user-images.githubusercontent.com/52577229/133153346-003f7a53-be5a-4628-ae88-e9fb7b3084a1.jpg)
 
### Your Environment details:
 
* testcafe version:                   Using locally installed version of TestCafe. > 1.16.0
* node.js version:                    v14.17.5
* command-line arguments:  testcafe remote tests --qr-code
* browser name and version: Mobile Chrome
* platform and version:          Android V11 
* other:                                    Tested few devices Galaxy S10, S21 and OnePlus8

**Comment by VasilyStrelyaev** [comment]
I ran the test you shared on my old Xperia XZ3 (Android 9), and it completes without issues.
 
The error you received indicates that the phone visits the link in the QR code twice. The first time it connects successfully, but soon closes the browser window/tab. On the second visit, TestCafe rejects the connection because you requested only one remote runner in the CLI.
 
To check if this is the case, you can try to manually enter the `Connect URL` that TestCafe prints in the console and see if the test runs as expected.
 
Since you are testing on different phones, the issue may be caused by the QR code reader you are using. It looks like it first opens the link in the system WebView, and then it sends it to a stand-alone browser (or you do this manually). You can try to configure the QR code reader to avoid multiple page visits or use a different reader application.
 
We have a suggestion for making corresponding changes on our side: https://github.com/DevExpress/testcafe/issues/2318. You can track this issue to be notified once we have any news.
