### ISSUE TITLE
Document state doesn't update when using TestCafe with Concurrency

### ISSUE THREAD

**Issue by jbradenclickfunnels** [DevExpress/testcafe#6551]
### Are you requesting a feature or reporting a bug?

Bug

### What is your Test Scenario?

Our users can either log in via a 'magic email link' or by entering their password. In order to see the password field, we have the user click a link that will show/hide the respected fields.

### What is the Current behavior?

When running the tests with TestCafe and concurrency, the page states do not update and clicking the link does not update the page state either.

### What is the Expected behavior?

- Default login view displays
- User clicks link
- Password field displays
- User enters information
- User clicks Sign In

### How would you reproduce the current behavior (if this is a bug)?

Run the test with concurrency (We have a default value of 7)

#### Provide the test code and the tested page URL (if applicable)

 
Your website URL (or attach your complete example): https://accounts.reborncf.com/users/sign_in

- I can't provide you usernames or passwords, but the focus is on the page state, not the functionality.

Your complete test code (or attach your test files)

```js
import { Selector, t } from 'testcafe'

class LoginPageObjects {
    constructor() {
        this.txt_user_email = Selector('#user_email')
        this.txt_user_password = Selector('#user_password')
        this.btn_sign_in = Selector('input').withAttribute('value', 'Sign in')
        this.link_login_with_password = Selector('a').withText('Or Login with Password')

    async login_with_password(user_email, user_password){
        // Purpose: Populates the username and clicks the login link to enter password.
        // Param: user_email
        // Param: user_password

        await t
            .click(this.link_login_with_password)
            .typeText(this.txt_user_email, user_email, { replace: true, paste: true } )
            .typeText(this.txt_user_password, user_password, { replace: true, paste: true } )
            .click(this.btn_sign_in)
    }

export default new LoginPageObjects()




fixture `login`
    .page `reborncf.com/users/sign_in`

test('user_can_log_in', async t => {
     await LoginPageObjects.login_with_password(data.users.account_owner.user_email, 
          data.users.account_owner.user_password)
```
### Your Environment details:
 
* testcafe version:                   1.15.2
* node.js version:                    v16.5.0
* command-line arguments:  testcafe chrome -t "user_can_log_in" -c 7
* browser name and version: chrome 93.0.4577.82
* platform and version:          macOS Big Sur Version 11.6
* other:

**Comment by felis2803** [comment]
Hello,

While researching the issue, I noticed that immediately after loading, the login form is in a state that is apparently not normal:
![image](https://user-images.githubusercontent.com/34184692/134146812-bf3b1386-94c4-4ce6-9bee-bbde4b1d4d99.png)
In this video, I reload the page you are testing:
![gif](https://user-images.githubusercontent.com/34184692/134147277-c3ed7300-ca82-4351-9da6-47460e487f6a.gif)

This behavior becomes even more noticeable during testing, because the scripts responsible for changing the shape take longer than usual to process. Thus, this is not a TestCafe issue. It is a peculiarity of your site that TestCafe demonstrates more explicitly than with manual testing.

The easiest workaround to test your page in the current state is to add a delay to the `login_with_password` function before the 'Or Login with Password' link is clicked:
```js
async login_with_password(user_email, user_password){
    await t
        .wait(2000)     // this delay will allow you to wait for the form to be redrawn
        .click(this.link_login_with_password)
        .typeText(this.txt_user_email, user_email, { replace: true, paste: true } )
        .typeText(this.txt_user_password, user_password, { replace: true, paste: true } )
        .click(this.btn_sign_in);
}
```

**Comment by felis2803** [comment]
You're right, redrawing a form in concurrency mode takes a very long time. We will research this issue to see if we can fix this on the side of TestCafe.
Stay tuned for our updates on this issue.
