### ISSUE TITLE
Uncaught ReferenceError: __get$ is not defined

### ISSUE THREAD

**Issue by suyog-wani** [DevExpress/testcafe#6655]
### What is your Test Scenario?
A simple login to our application.
 
### What is the Current behavior?
Login to application is successful but above JS ReferenceError is reported at the end. This is not reproducible by hand or by our existing framework and only seen when running test with TestCafe.
 
### What is the Expected behavior?
Reference Error should not be reported.
 
<details>
<summary>Your website URL (or attach your complete example):</summary>

https://testcafe.latest.stage.c8y.io/apps/cockpit/index.html#/
`testuser:Test@123`

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
#####################################
test.js

const { userVariables, Selector } = require('testcafe');
const page = require('../../config/pageCollection');
const TestPage = page.TestPage;

fixture `First test`
    .page(userVariables.url);

test('The first login test', async t => {
    let header = Selector('c8y-navigator-outlet span');
    let data = { userName: "testuser", password: "Test@123"};
    await TestPage.login(data);
    await t.expect(header.innerText).eql('COCKPIT');
});

######################################
testPage.js

const { Selector, t } = require('testcafe');
function TestPage() {
    let loginInput = Selector('[name="user"]'),
        passwordInput = Selector('[name="password"]'),
        loginBtn = Selector('[title="Log in"]');

    this.login = async(data) => {
        await t
            .maximizeWindow()
            .typeText(loginInput, data.userName)
            .typeText(passwordInput, data.password)
            .click(loginBtn)
            .wait(3000);
    }
}

module.exports = TestPage;

######################################
pageCollection.js

'use strict';

let pageCollection = (function () {
   let TestPage = require('../tests/pageobjects/testPage');

   return {
      TestPage : new TestPage()
   };
}());

module.exports = pageCollection;
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
.testcaferc.json

{
  "userVariables" : {
    "url" : "https://testcafe.latest.stage.c8y.io"
  },
  "browsers": [
    {
      "path": "chrome"
    }
  ],
  "src" : "./tests/fixtures/**/*.js",
  "reporter" : {
    "name" : "json",
    "output" : "./reports/test.json"
  },
  "screenshots" : {
    "path" : "./screenshots/",
    "takeOnFails" : true
  }
}

```
</details>

<details>
<summary>Run Test:</summary>

```
testcafe --config-file .testcaferc.json
```
</details>

### Steps to Reproduce:

Please create appropriate files and run the test as mentioned above.
 
### Your Environment details:
 
* testcafe version:                   1.16.1
* node.js version:                     v14.17.1
* command-line arguments:   testcafe --config-file .testcaferc.json
* browser name and version:  Chrome 95.0.4638.54
* platform and version:            macOS 10.15.7

**Comment by suyog-wani** [comment]
Hi,

Would be good if someone can take a look into this and give us workaround or feedback. All the information is already provided in the ticket.

Regards,
Suyog

**Comment by AlexKamaev** [comment]
Thank you for reporting this. I managed to reproduce the issue. At this moment, there is no workaround for this. We need more time to research it in detail.

**Comment by tuna-rootnet** [comment]
I'm getting the same errors when I update TestCafe to 1.18.6. Everything runs fine on any version lower than that. I've also noticed that it does seem to onlu occur whenever some code is trying to access a private property. Making the property public 'fixes' that specific error, until it gets to the next private property.

Has there been any more research done into the issue? I'm fine using 1.18.5 for now and ignoring some vulnerability errors since the application is still very much in development, but some perspective would be nice.

**Comment by AlexKamaev** [comment]
@tuna-rootnet
This issue looks like regression if you say that there are no errors in previous versions. It is unlikely that the issue is related to the original one. Please prepare a simple sample to demonstrate the problem, and we will research it in detail. Please create a separate github issue using the following link: [https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml)
