### ISSUE TITLE
Docker image testcafe/testcafe Errors with pref not defined in a Firefox file

### ISSUE THREAD

**Issue by jbradenclickfunnels** [DevExpress/testcafe#6770]
### What is your Scenario?

We are trying to set up usage with Docker using the testcafe/testcafe image to allow for localhost executions. Based on TestCafe documentation: https://testcafe.io/documentation/402838/guides/advanced-guides/use-testcafe-docker-image 

### What is the Current behavior?

We've not been able to get past: 

'ReferenceError: pref is not defined
    at Object.<anonymous> (/usr/lib/firefox/browser/defaults/preferences/firefox-branding.js:2:1)'. 

We are using this command (sudo code): 

docker run --rm -v /Users/<username>/<project-directory>:/tests -it testcafe/testcafe chromium:headless /**

### What is the Expected behavior?

Our TestCafe execution to work within a Docker container.

### What is your public website URL? (or attach your complete example)

Since we are trying to run locally, we do not have a public website URL.

### What is your TestCafe test code?

The tests aren't the problem, it's the Docker command/image provided that isn't working.

### Steps to Reproduce

1. Install Docker on your machine
2. In a terminal, run docker command
3. See error right after trying to run the docker command

### TestCafe version

1.17.1

### Node.js version

16.13.0

### Command-line arguments

docker run --rm -v /Users/<path>:/tests -it testcafe/testcafe chromium:headless  /**

### Browser name(s) and version(s)

chrome 96, firefox 95

### Platform(s) and version(s)

macOS 11.6.1

**Comment by pavsenin** [comment]
Hello,
It looks like this issue may be related to the way you run the docker command.
Would you please try using '/tests' instead of '/**' to run tests only from this folder?
Also, please try putting all your tests in some subfolder, for example, 'tests'.
After that, replace '-v /Users:/tests' with '-v /tests:/tests' to mount only this subfolder to the docker container.

**Comment by jbradenclickfunnels** [comment]
@pavsenin 
Thanks for the reply,

SO you're saying in order to run our project in a Docker file, we'd have to refactor our entire repo to have everything under a 'test' folder? Something we don't have to do when running any other way?

Is this a Docker thing or a TestCafe thing?

**Comment by pavsenin** [comment]
@jbradenclickfunnels,
When you use '/\*\*', TestCafe tries to find and run .js files from all folders in the root directory, for example, from /lib.
You need to use '/tests' instead of '/**' to run tests only from the tests subfolder.
If you mount the whole /Users directory to /tests and it contains a lot of files without TestCafe tests, this can still lead to issues.
