### ISSUE TITLE
Show failed test script line in report

### ISSUE THREAD

**Issue by future-mine** [DevExpress/testcafe#6825]
### What is your Scenario?

I want you to add failed code line in the report.
So a user can easily know where an issue occurred.

### What are you suggesting?

![image](https://user-images.githubusercontent.com/59634187/150302512-1c3bd62e-1d13-4f63-a3af-17342fa139d4.png)
Here you can add which line was failed(In my case, which code line of `security-policy.test.js`)

**Comment by AlexKamaev** [comment]
As far as I understand it, you are using a JSON reporter. The code line with the error is highlighted, but error formatting is missing since we cannot format an error in a JSON reporter. Please see the screenshot:

![image](https://user-images.githubusercontent.com/1678902/150487233-a94f967d-43d5-4c4c-a3c5-3cf40b402d11.png)

**Comment by future-mine** [comment]
Maybe I didn't explain clearly.

**Comment by future-mine** [comment]
I don't care about the formatting now.
In the report, there is no code line of the test script from which other errors start.

**Comment by AlexKamaev** [comment]
I understand your idea now. It looks like the error stack in the report does not mention the code file with the error. Thank you for reporting this. We received a similar issue: https://github.com/DevExpress/testcafe/issues/6251
We will take your suggestion into account, however, we cannot give any estimate.

**Comment by future-mine** [comment]
Thank you for your response
