### ISSUE TITLE
Taking a screenshot of an element that is bigger than the window width (horizontal scrolling)

### ISSUE THREAD

**Issue by hossammourad** [DevExpress/testcafe#6849]
### What is your Scenario?

I want to take a screenshot of an element using the `takeElementScreenshot` API. My element is bigger in width than the window size. Think of the cards layout of Trello, it spans horizontally indefinitely.

I tried using the other `takeScreenshot` method and provided the `fullPage: true` option, but it didn't work too.

### What is the Current behavior?

The screenshot is limited to the window size. TestCafe doesn't produce a screenshot where the whole element is visible.

### What is the Expected behavior?

The screenshot should include the whole element.

### What is your public website URL? (or attach your complete example)

Any Trello board would be sufficient, let's take this one as an example: https://trello.com/b/AwYSWOyt/ultimate-to-do-list

### What is your TestCafe test code?

```
test("Generate screenshot", async (t) => {
  await t.takeElementScreenshot(
    Selector("#board"),
    "preview.png"
  );
});
```

OR

```
test("Generate screenshot", async (t) => {
  await t.takeScreenshot({
    path: "preview.png",
    fullPage: true,
  });
});
```

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.14.0

### Command-line arguments

none

**Comment by VasilyStrelyaev** [comment]
The `takeElementScreenshot` method does not currently have a full-page mode, so it can only capture elements that can fit on the screen entirely. Note that `takeElementScreenshot` scrolls the page to show the center of the target element if it's not visible due to overflow.

I will mark this issue as a feature request for full-page mode support in `takeElementScreenshot`. We will take it into account during our future planning.
