### ISSUE TITLE
Javascript error is not caught and test passes

### ISSUE THREAD

**Issue by gemal** [DevExpress/testcafe#6869]
### What is your Scenario?

I have a test which produces a javascript error

### What is the Current behavior?

test passes

### What is the Expected behavior?

show the javascript and not pass the test

### What is your public website URL? (or attach your complete example)

see test cafe

### What is your TestCafe test code?

```
test('test', async t => {
    'use strict';
    await t
        .maximizeWindow()
        .navigateTo('https://dinnerbooking.com/dk/da-DK/f1/soegning')
        .click('.rest-map-init')
        .wait(10000)
    ;
});
```

### Screenshots

![image](https://user-images.githubusercontent.com/69105/153606378-e7796bbd-de01-4d7b-8387-5745d9568860.png)

### Steps to Reproduce

1. run the test
2.
3.

### TestCafe version

1.18.3

### Node.js version

v16.14.0

### Command-line arguments

testcafe chrome

### Browser name(s) and version(s)

Chrome 98.0.4758.82 / Windows 10

### Platform(s) and version(s)

windows 10

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I reproduced the issue. We will research it and update this thread once we have news.

**Comment by gemal** [comment]
Any update on this one?

**Comment by Aleksey28** [comment]
Thank you for coming back. Earlier Dmitry wrote that he reproduced this issue, but at the moment this client-side error does not occur by the URL address that you specified. I also tried to reproduce a similar issue locally, but without success. Could you please clarify if you can reproduce this issue now? If yes, please share the updated steps to reproduce. Otherwise, we'll need an updated example where we can reproduce the issue.
