### ISSUE TITLE
How to acces page with Proxy in testcafe. I need to set Automatic proxy configuration URL = http://wpad/wpad.dat and No proxy for 138.3.96.89.

### ISSUE THREAD

**Issue by UdaiSingh163** [DevExpress/testcafe#6882]
### File a new question on StackOverflow

https://stackoverflow.com/questions/ask?tags=testcafe

**Comment by UdaiSingh163** [comment]
I am able to access URL using selenium - below code but not sure how to use that in testcafe.


		Proxy proxy = new Proxy();

		proxy.setProxyAutoconfigUrl("http://wpad/wpad.dat");

		FirefoxOptions options = new FirefoxOptions();
		options.setCapability("proxy", proxy);
		options.addArguments("--headless");

		options.addPreference("network.proxy.no_proxies_on", "138.3.96.89");

		// Calling new Firefox profile for test
		driver = new FirefoxDriver(options);

**Comment by AlexSkorkin** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions. We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)). If you think that this issue is a bug, feel free to [open a new issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md), but please make sure to follow the bug template
