### ISSUE TITLE
Configuration errors are swallowed

### ISSUE THREAD

**Issue by nijk** [DevExpress/testcafe#6925]
### What is your Scenario?

Setup testcafe configuration with errors such as missing dependencies or incorrect commonJS require paths.

### What is the Current behavior?

Testcafe reports an error relating to the config:

```
An error has occurred while reading the ".testcaferc.js" configuration file.
ERROR You have not specified a browser.
```

### What is the Expected behavior?

Testcafe should report the underlying error thrown in the `readJsConfigurationFileContent` method of `configuration-base.ts`

```
ERROR Error: Cannot find module 'axe.config.js'
```

### What is your public website URL? (or attach your complete example)

N/A

### What is your TestCafe test code?

N/A

### Steps to Reproduce

See current behaviour

### TestCafe version

1.18.4

### Command-line arguments

none

**Comment by AlexKamaev** [comment]
I researched the issue and found that you can use the internal TestCafe log to show the error message.
To enable the TestCafe log, you need to set the `DEBUG` environment variable as follows:

```
DEBUG=testcafe:*
```

As for the `ERROR You have not specified a browser.` error message, it looks like expected behavior, because the configuration file was not loaded properly.
