### ISSUE TITLE
Getting undefined/Other 0.0 in browser due to browserAgent

### ISSUE THREAD

**Issue by dubesar** [DevExpress/testcafe#6934]
### What is your Scenario?

We are running test on different browser and getting issue in versions using testcafe.

### What is the Current behavior?

Current behaviour is getting undefined or Other 0.0

### What is the Expected behavior?

Expected it should give the correct browser environment agent.

### What is your public website URL? (or attach your complete example)

https://gap.com

### What is your TestCafe test code?

https://github.com/LambdaTest/testcafe-browser-provider-lambdatest

### Steps to Reproduce

1. Go to lambdatest.com and create an account
2. Get the username and access key
3. Set the environment variables as given in the testcafe-browser-provider-lambdatest repository
4. Run the test

### TestCafe version

1.18.4

### Node.js version

14

### Command-line arguments

testcafe "lambdatest:Galaxy S8@9:android:isReal" "path/to/test/file.js"

**Comment by Aleksey28** [comment]
I will be happy to assist you and diagnose this issue. However, since the lambda test requires a paid subscription, I will not be able to access it.

Please send your access data for the lambda test to [support@devexpress.com](mailto:support@devexpress.com). I'll continue researching the issue.

Also, you can run this test and share the result from the console:

```js
fixture`Getting Started`
    .page`https://devexpress.github.io/testcafe/example`;

test('My first test', async t => {
    const ua = await t.eval(() => navigator.userAgent);

    console.log('UserAgent', ua);
});
```
