### ISSUE TITLE
Browser Process is not belonging to calling node process

### ISSUE THREAD

**Issue by pschmolke** [DevExpress/testcafe#7060]
### What is your Scenario?

Sometime there is a test controller that hung up or got killed from i.e. a Jenkins timeout which resolves in orphan browser instances.
To workaround this I wanted to wrap the `npm run test -- [..]` with a timeout, like `timeout -k "15s" -s 15 "20m" npm run test -- [..]`. With this I expected the browser to close on terminating the testcafe command but it turns out the headless browser instances have a PPID of 1 which resolves to `/sbin/init`

### What is the Current behavior?

The Browser stays open and continues with its actions

### What is the Expected behavior?

When the corresponding testcafe node process is gone the open browser windows should shutdown as well.

### What is your public website URL? (or attach your complete example)

Does not exists and is also not relevant

### What is your TestCafe test code?

// Test code does not matter here but w/e
Test( 'DEBUG', async () => {
   // do login here
  
   await t.debug();
} );

### Your complete configuration file

{
   "browsers": [
      "chrome:emulation:width=1800;height=1000"
   ],
   "selectorTimeout": 10000,
   "assertionTimeout": 5000,
   "pageLoadTimeout": 15000,
   "runExecutionTimeout": 360000,
   "testExecutionTimeout": 300000,
   "disableMultipleWindows": true,
   "disablePageCaching": true,
   "pageRequestTimeout": 30000,
   "browserInitTimeout": 120000,
   "retryTestPages": false,
   "hostname": "localhost",
   "screenshots": {
      "path": "out/screenshots/",
      "pathPattern": "${FIXTURE}_${DATE}_${TIME}/${TEST_ID}_${TEST}_${RUN_ID}.png",
      "takeOnFails": true,
      "fullPage": true
   },
   "videoPath": "out/videos/",
   "videoOptions": {
      "pathPattern": "${FIXTURE}_${DATE}_${TIME}/${TEST_ID}_${TEST}.mp4"
   },
   "compilerOptions": {
      "typescript": {
         "configPath": "./tsconfig.json"
      }
   }
}

### Steps to Reproduce

1. Fire a test with long lasting actions or `t.debug()`
2. Get process ID of node process, i.e. `ps -ef | grep "npx"
3. Run `kill -9 ${nodeProcessId}
4. See that browser is still open and even continuing executing tests

### TestCafe version

1.18.6

### Node.js version

14.17.6

### Command-line arguments

--no-color 'chrome:headless:width=1800;height=1000' -c 5 -q attemptLimit=3,successThreshold=1

### Browser name(s) and version(s)

Chrome 102

### Platform(s) and version(s)

Linux Debian 5.10.103-1

**Comment by Dmitry-Ostashev** [comment]
Thank you for the report. I reproduced the issue on Debian and Windows.

**Comment by Artem-Babich** [comment]
Hello @pschmolke,

We researched this issue and came to the conclusion that the behavior you are experiencing is expected. We have complex logic that closes browsers when the main process is about to be killed. However, you are calling the kill command with a "-9" flag, which means "force" termination. In this case, our process.on('exit') handler is not raised and this browser closing logic does not work. Although browser processes are running as child processes, only one browser process is terminated by the system in this case. This is the standard behavior for the Unix system. If the parent process is terminated first, then the init job (PID 1) will inherit all such orphaned processes. So, we recommend terminating the TestCafe process without the "force" flag so that our on("exit") handler logic could close all child processes.
