### ISSUE TITLE
CLI command to set quarantine mode to false

### ISSUE THREAD

**Issue by jbradenclickfunnels** [DevExpress/testcafe#7077]
### What is your Scenario?

In our .testcaferc file, we have quarantine mode enabled and use it for all of our runs, but we've implemented a feature that we don't want to use quarantine mode for (visual testing using Applitools).

### What are you suggesting?

Allow us to disable (set quarantine mode to false) in the CLI so we can write a script to kick off our visual tests without having to alter the .testcaferc file or have to write a separate config file just to have quarantine mode disabled for this one run.

**Comment by Aleksey28** [comment]
Hi @jbradenclickfunnels,

Thank you for the suggestion. We will take it into account and update the thread once we have any news. As a workaround, you also can delete the quarantine option from the config and assign it with CLI only for the required tests.

**Comment by Aleksey28** [comment]
Hi, you can enhance this behavior yourself, if necessary. You need to change the condition in [this method](https://github.com/DevExpress/testcafe/blob/67507bc91c840c2f4cab3b456558195e44dee164/src/cli/argument-parser/index.ts#L341) so that it will be fulfilled when the value is defined. Then, return the value as is in [this method](https://github.com/DevExpress/testcafe/blob/67507bc91c840c2f4cab3b456558195e44dee164/src/utils/get-options/quarantine.ts#L34) when it has the `boolean` type.
