### ISSUE TITLE
Browser Multi-Tab automated tests are not working due to limitations of TestCafé automation tool 

### ISSUE THREAD

**Issue by sahithikuncham** [DevExpress/testcafe#7085]
### File a new question on StackOverflow

https://stackoverflow.com/questions/ask?tags=testcafe

**Comment by sahithikuncham** [comment]
Unable to complete test automation scripts which need end to end processing due to TestCafe (test automation tool) limitation as detailed below.

In our application one of the integrations open a new tab within the same window on the application to complete the call.
But, Test Café is unable to automate this functionality where a blank page is getting displayed and unable to perform any action.

**Comment by AlexKamaev** [comment]
It is expected that TestCafe opens a new window instead of opening a tab. This should not lead to the problem you described:

> In our application one of the integrations open a new tab within the same window on the application to complete the call.
But, Test Café is unable to automate this functionality where a blank page is getting displayed and unable to perform any action.

To find the cause of the issue and fix it, we need a sample which would help us reproduce the issue on our side.

**Comment by sahithikuncham** [comment]
Hi Team,
Thanks for the response. 
But the requirement in our AUT is to open in a new tab instead of new window.
Could you please help us if there is any possibility to open the page in a new tab using TestCafe?
