### ISSUE TITLE
A non-informative report is generated for a failed assertion when running the *.testcafe fixture file using the CLI

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe#7089]
### What is your Scenario?

Need to find out which assertion of the recorded (*.testcafe) test fails.

### What is the Current behavior?

If some action fails, the report shows an incorrect selector:
![image](https://user-images.githubusercontent.com/24777868/173788578-4154f458-37d7-4c1d-ace4-de7a458f50c5.png)

However, when an assertion fails, no selector info is shown:
![image](https://user-images.githubusercontent.com/24777868/173788791-1b9ee5dd-033b-4cdd-b7f5-a68a6766b141.png)

### What is the Expected behavior?

It should show verbose info of the failed assertion.

### What is your public website URL? (or attach your complete example)

See the attachment

### What is your TestCafe test code?

[recorded-examples.zip](https://github.com/DevExpress/testcafe/files/8907776/recorded-examples.zip)

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.19.0

### Node.js version

16.14.2

### Command-line arguments

npx testcafe chrome recorded-examples.testcafe

**Comment by aleks-pro** [comment]
The problem is still reproducible for actions in hooks. You can use the following recorded test:
[recorded-test-be.testcafe.zip](https://github.com/DevExpress/testcafe/files/9316665/recorded-test-be.testcafe.zip)

The problem is that the `callsite` property value for actions from hooks is an action number with a hook as a prefix (e.g. `beforeEachHook_0`). But the `testcafe` code expects a number like string: https://github.com/DevExpress/testcafe/blob/master/src/compiler/test-file/formats/raw.js#L20
