### ISSUE TITLE
Assertion takes longer than necessary

### ISSUE THREAD

**Issue by felis2803** [DevExpress/testcafe#7129]
### What is your Scenario?

Assertion that the download icon is no longer visible when the download is complete.

### What is the Current behavior?

Assertion continues to wait for the element to disappear for ~10 seconds after the element is no longer visible.

### What is the Expected behavior?

Assertion shouldn't wait that long.

### What is your public website URL? (or attach your complete example)

Details in [T1100414](https://supportcenter.devexpress.com/internal/ticket/details/T1100414).

### What is your TestCafe test code?

[T1100414](https://supportcenter.devexpress.com/internal/ticket/details/T1100414).

### Steps to Reproduce

1. Take the test from [T1100414](https://supportcenter.devexpress.com/internal/ticket/details/T1100414).
2. Run it: `testcafe chrome test.js -e`.

### TestCafe version

1.19.0

### Node.js version

16.14.2

### Command-line arguments

testcafe chrome test.js -e

### Browser name(s) and version(s)

Chome 103

### Platform(s) and version(s)

Windows 10

**Comment by Aleksey28** [comment]
I researched this issue deeper and came to the conclusion that this behavior was expected. To check the visibility of an element we need to find this element in the DOM. In this case, the element being checked isn't just hidden; it is removed from the DOM. It means that it's impossible to find the element in the DOM, however, `testcafe` tries to find one and that is why it takes longer than necessary. The time is taken not by the assertion but by the `Selector`. To resolve this you can check Selector for `exists` instead of `visible`. For a smarter decision, you can check for `exists` at first and then for `visible`.

```js
const selector = Selector("selector");
await t.expect(selector.exists || selector.visible).notOk();
```
