### ISSUE TITLE
Hammerhead hangs when proxying a web page

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#7169]
### What is your Scenario?

Original issue: https://supportcenter.devexpress.com/internal/ticket/details/T1094906

### What is the Current behavior?

Hammerhead hangs when opening the webpage from the example in https://supportcenter.devexpress.com/internal/ticket/details/T1094906. Reproduced with `http-playground` and actual tests. The page opens in the browser normally.

### What is the Expected behavior?

Hammerhead proxies the page

### What is your public website URL? (or attach your complete example)

See https://supportcenter.devexpress.com/internal/ticket/details/T1094906

### What is your TestCafe test code?

See https://supportcenter.devexpress.com/internal/ticket/details/T1094906

### Steps to Reproduce

Run a test from https://supportcenter.devexpress.com/internal/ticket/details/T1094906

OR

Visit the test's start page with `http-playground`

### TestCafe version

1.19.0

### Command-line arguments

testcafe chrome test.js

**Comment by miherlosev** [comment]
We dropped the 'Support Center' label due to customer doesn't have an active product license.

**Comment by Artem-Babich** [comment]
We will close this issue since it is fixed in the [Native Automation mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode). Please try the native automation mode in your tests.
Feel free to reopen the issue if you need a fix for the other browsers or you cannot use Native Automation for some reason.
