### ISSUE TITLE
Hammerhead crashes when opening a web page because of web sockets

### ISSUE THREAD

**Issue by VasilyStrelyaev** [DevExpress/testcafe#7171]
### Original Message

https://stackoverflow.com/questions/71632158/how-can-i-debug-a-websocket-connection

### What is your Scenario?

Just opening my web app via TestCafe (or Hammerhead Playground)

### What is the Current behavior?

1) A WebSocket error in the console:
  
    <img width="640" alt="image" src="https://user-images.githubusercontent.com/11459924/160792609-c6ab2570-a446-47f8-b90a-1d7b4f0c01ac.png">

2) The web page is automatically refreshed
3) If I use Hammerhead Playground instead of TestCafe, it crashes after refresh:

    <img width="873" alt="image" src="https://user-images.githubusercontent.com/11459924/160793011-c55a212d-dafc-4a45-a6fd-d43f80d6aacc.png">

4) If I use TestCafe, refreshes go on and on

### What is the Expected behavior?

The web page is proxied correctly

### What is your public website URL? (or attach your complete example)

https://torus.qa.argos.education/session/new

### What is your TestCafe test code?

```js
import { ClientFunction, Selector } from "testcafe";

fixture`Getting Started`.page("https://torus.qa.argos.education/session/new");

test("Example error", async (t) => {
  await t.debug();
});
```

### Steps to Reproduce

1. Run the attached test or open the specified URL in hammerhead playground

### TestCafe version

1.18.4, hammerhead-playground: `master` on `4a9cd8f`

### Node.js version

16.14.2

### Command-line arguments

testcafe chrome test.js

**Comment by Artem-Babich** [comment]
Hello,

We released a new TestCafe version (v2.3.0), which includes [experimental proxyless mode](https://testcafe.io/documentation/404237/guides/experimental-capabilities/proxyless-mode). This mode uses native browser automation. In Proxyless mode, a few issues are already fixed. This issue should also be fixed in Proxyless mode.

Unfortunately, I was not able to test your web site since the URL you shared is no longer available. Would you please check if your sample is working correctly in v2.3.0 with experimental proxyless mode enabled?
This option is available in all interfaces:

```js
// Command-line
testcafe chrome tests --experimental-proxyless

 

// Programmatic
const testcafe = await createTestCafe({ experimentalProxyless: true });
    
// Configuration file
{
   "experimentalProxyless": "true"
}    
```

Please keep in mind that this mode is still experimental and is implemented only in Google Chrome. It will not work correctly if you run tests in a non-Chrome browser or in a combination of other browsers.
