### ISSUE TITLE
Console keeps showing an error  Uncaught DOMException: Blocked a frame with origin  from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by s-syam** [DevExpress/testcafe#7177]
### What is your Test Scenario?
The user is trying to log in 
 
### What is the current behavior?
When a user tries to login from an iframe popup which has a redirect after successfully logging,user is stuck on the login popup and the user is not logged in

### What is the Expected behavior?
User is allowed to be logged in
 
### What is your web application and your TestCafe test code?
```js
fixture `MyFixture`
   .page('https://www.hoefenhaag.nl/');
test('Test1', async t => {
   await t
      .maximizeWindow()
      .click('button.module-cookies-close')
      .click('a.button-full')
      .click('div.js-navigation-login-heart-bg')
      .switchToIframe('#login-iframe')
      .typeText('input[name*="account_email"]', 'test08@mailinator.com')
      .typeText('input[name*="account_password"]', 'Qwerty123$')
      .click('#button-submit')
      .switchToMainWindow();
  
});
```

### Steps to Reproduce:
Steps described above,
Error : `Uncaught DOMException: Blocked a frame with origin "xxxxxxx" from accessing a cross-origin frame.`

### Your Environment details:
* testcafe version:  1.9.1 also 1.9.4
* node.js version:    12.18.2

**Comment by miherlosev** [comment]
Hi @s-syam,

TestCafe runs tests using the [URL-rewritten](https://github.com/devexpress/testcafe-hammerhead) proxy.
This approach is good. However, there is a way to improve the stability and speed of test execution - the native browser automation API.
We have a test execution mode uses native browser automation - we call it the `Proxyless` mode.
In `Proxyless` mode, a few issues are already fixed.
By the way, this issue was also fixed in `Proxyless` mode.
This option is available in all interfaces:

```js
// Command-line
testcafe chrome tests --experimental-proxyless

// Programmatic
testcafe
    .createRunner
	.src('tests')
	.browsers('chrome')
	.run({ experimentalProxyless: true });
	
// Configuration file
{
   "experimentalProxyless": "true"
}	

```

Setup the `testcafe@2.1.1-alpha.3` version and try running your tests in `Proxyless` mode. I look forward to your results.
Note that at present it is an experimental mode.
Also, the `Proxyless` mode is implemented only in Google Chrome. It will not work correctly if you run tests in a non-Chrome browser or in a combination of other browsers.

**Comment by miherlosev** [comment]
[https://github.com/DevExpress/testcafe/issues/7177](https://github.com/DevExpress/testcafe/issues/7177)

Hi @kerrijackson,

> --disable-web-security did solve the problem.

I am happy to hear that. Note that `experimental-proxyless` mode has become a regular option, and was renamed to [native-automation](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode). You can try to use it one more time.

**Comment by miherlosev** [comment]
Hi @s-syam,

This issue is not reproduced with combination of `testcafe@3.0.1` and the Google Chrome browser. Feel free to reopen this issue if you encounter it in other browsers.

**Comment by patrickathompson** [comment]
This error was observed in SUT when using TestCafe 2.6.0 in proxy mode. The chrome arg _--disable-web-security_ was already configured for chrome. The iframe CORS error was observed in both desktop+osx+chrome, android+pixel7+chrome, and android+samsungS22+samsunginternet. The fix that worked in this case was to unchain the _await t._ lines and edit them to be separate lines with their own awaits.

**Comment by patrickathompson** [comment]
The offending code in our use case was this visible check on a modal div embedded in an iframe:

`await t.expect(zipCodeModalDiv.visible).ok()`

Once replaced with another suitable check on another div not using .visible and the issue was resolved.

It was almost consistently reproducible on 'browserstack:Samsung Galaxy S22@12.0', which uses Samsung Internet, but we also observed the error intermittently on 'browserstack:Google Pixel 7 Pro@13.0' and 'browserstack:chrome@112.0:OS X Ventura' and possibly some other chromium based desktop browsers.
