### ISSUE TITLE
Support resize window feature for remote devices

### ISSUE THREAD

**Issue by PierreRott** [DevExpress/testcafe#7258]
### What is your Scenario?

The `resizeWindow()` method is currently not supported for remote computers and mobile devices.
This is a request to enable resizing of the browser viewport on remote computers and mobile devices using the TestCafé method `resizeWindow`.

### What are you suggesting?

Explore the possibility of changing the viewport size on remote computers and mobile devices.

We have TestCafé installed on Windows 10, but our test matrix includes testing on other platforms as well, e.g. Mac.
Some test scenarios must be tested manually as this feature is not currently supported.

### What alternatives have you considered?

Use TestCafé locally, or not to use TestCafé for the given test scenarios.

**Comment by felis2803** [comment]
Hi @PierreRott,

Window resizing cannot be called from the browser client's code. TestCafe has the ability to resize a browser window that runs locally, because it has access to the browser process using the `testcafe-browser-tools` library. In the case of remote browsers, TestCafe cannot implement `resizeWindow()`.

To work around this limitation, you can install TestCafe on your Mac (for example). An even better solution is to install the GitHub Actions runner on your Mac. This will automatically run tests on it as happens on our side (even though we use Ubuntu). Here is an example: [https://github.com/DevExpress/testcafe/blob/master/.github/workflows/test-functional-local-firefox.yml](https://github.com/DevExpress/testcafe/blob/master/.github/workflows/test-functional-local-firefox.yml).

Also, please clarify what you mean by viewport resizing on mobile devices. As a rule, the browser size on these devices is always the same, so this usage scenario is unclear.

**Comment by PierreRott** [comment]
Hi, @felis2803,

you are right, it is not possible to resize browser viewport on mobile devices, this scenario is out of the question.

Now I understand that you don't have access to the instance of remote browsers.
We will discuss your proposed solutions within our team.
Thank you for your time and effort.
