### ISSUE TITLE
Selector Timeout Between Steps

### ISSUE THREAD

**Issue by felis2803** [DevExpress/testcafe#7305]
For some unknown reason, TestCafe waits for a timeout to expire before clicking on an element.
The user example uses an element whose center is overlapped by another element. However, even if you change the selector to one that is not overlapped by any others, the behavior will not change.

More information in [T1116871](https://supportcenter.devexpress.com/internal/ticket/details/T1116871).

**Comment by Aleksey28** [comment]
This behavior is correct. There are two clicks at the end and the delay occurs in the last one. It may seem that it occurs in the previous one, because nothing happens. The reason why nothing happens is that the button's event in this action doesn't have sufficient time to be bound to this button. To resolve this issue, you need to add a timeout of approximately 300ms before this action.
