### ISSUE TITLE
The status bar does not disappear

### ISSUE THREAD

**Issue by felis2803** [DevExpress/testcafe#7384]
### What is your Scenario?

I'm running a test in live mode, and I'm trying to access the elements at the bottom of the page.

### What is the Current behavior?

The status bar does not disappear when hovering over it.

### What is the Expected behavior?

The status bar should disappear.

### What is your public website URL? (or attach your complete example)

See private ticket [T1127746](https://supportcenter.devexpress.com/internal/ticket/details/T1127746).

### What is your TestCafe test code?

Any empty test on the page specified in private ticket [T1127746](https://supportcenter.devexpress.com/internal/ticket/details/T1127746).

### Steps to Reproduce

1. Run an empty test in live mode.
2. Hover over the status bar.

### TestCafe version

2.1.0

### Node.js version

16.18.0

### Command-line arguments

testcafe chrome test.js -L

### Browser name(s) and version(s)

Chrome@107.0.5304.107

### Platform(s) and version(s)

Windows 10

**Comment by AndreyBelym** [comment]
It happens because the target page sets `display: none` on `document.body` in CSS during loading. This hides our status bar during initialization and we cannot correctly calculate the status bar height (it is 0 in this case) and use it in the `mousemove` event handler to determine if we should hide the panel or not.

https://github.com/DevExpress/testcafe/blob/1818967525b0aef4f89dddf63116c30b2329a698/src/client/ui/status-bar/index.js#L303

https://github.com/DevExpress/testcafe/blob/1818967525b0aef4f89dddf63116c30b2329a698/src/client/ui/status-bar/index.js#L309
