### ISSUE TITLE
Add ability to repeat the test specified number of times

### ISSUE THREAD

**Issue by Klaster1** [DevExpress/testcafe#7445]
### What is your Scenario?

Unstable tests are an unfortunate truth about E2E testing. During my experience with TestCafe, I discovered a technique to reliably check the test stability and reproduce a decent amount of rare failures: wrap the test in a for-loop, `only` the test, run the parent fixture with medium to high concurrency.

What this helps to uncover:
1. Application race conditions. Actual bugs to fix, the tests did their job.
2. Rate limiting issues (for example, Stripe).
3. Suboptimal lazy content loading assertions in tests.

### What are you suggesting?

The ability to run a specific test an arbitrary number of times in order to sample the test stability seems like a good fit for any test runner. Add a new runner option `repeat` (or something like that). Since TestCafe comes with its own test runner, it would be really handy to have such a feature.

### What alternatives have you considered?

- Manually modify the test suite. Pros: can be done with the current TestCafe. Cons: not suitable for CI; limited discoverability by other developers, resulting in an overall more unstable suite.
- Modify the test suite at the AST level. Pros: can be automated; can be done with the current TestCafe. Cons: requires custom instrumentation.
- Run the test suite multiple times with shell scripting. Pros: can be automated; can be done with the current TestCafe. Cons: significant overhead, increasing overall run time; reduced CPU utilization.

**Comment by Aleksey28** [comment]
Hi @Klaster1,

TestCafe has the [Quarantine Mode](https://testcafe.io/documentation/403841/guides/intermediate-guides/quarantine-mode) option, which allows using unstable tests in production.

**Comment by Klaster1** [comment]
@Aleksey28 the quarantine mode repeats the test only upon the first failure. It can not run the test _regardless of the result_ a specified number of times. And it does not run the test concurrently. You can use the quarantine mode to cover up _occasional_ failures, the change I propose allows to _check if the test is stable_ at the given sample rate.

**Comment by Aleksey28** [comment]
Yes, it has been done on purpose because test execution would take a lot of time if all of them are repeated by `n` times. In most cases, there is no reason to repeat stable tests. As for the [concurrency mode](https://testcafe.io/documentation/403626/guides/intermediate-guides/run-tests-concurrently), it runs different tests in different windows simultaneously. We don't execute the same test in quarantine mode in different browsers because it's important to finish the execution if the number of successful attempts was reached. In case we run it simultaneously, some attempts would be still made. I reopened your suggestion and if it is popular among other users, we'll consider implementing your suggestion.

As a workaround, you can implement your own test function:

```js
import { Selector } from 'testcafe';

const arr = ['', '1', '2', '3'];

function testWrapper(name, cb, repeat = 5) {
  for (let index = 0; index < repeat; index++) {
    test(name, cb);
  }
}

fixture('Getting Started')
    .page('https://devexpress.github.io/testcafe/example');

testWrapper('My first test', async t => {
    const index = arr[Math.floor(Math.random() * 3)];

    console.log(`file: test.js -> line 10 -> index`, index);

    await t
        .typeText('#developer-name', 'John Smith' + index)
        .click('#submit-button')
        .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});
```

**Comment by Klaster1** [comment]
> As a workaround, you can implement your own test function
That's exactly what I practice, but after some time manual wrapping gets old, so I figured it would hurt to inquire about making this a TestCafe feature. It's up to you guys to decide if you'd like to implement it, but me and my team found the approach extremely helpful when fixing unstable tests. Would be a shame for other not to know about such a gem.

**Comment by Aleksey28** [comment]
I didn't find similar requests from other users. It seems that the capabilities of the quarantine mode are sufficient for them. However, we will keep your suggestion in mind and we will consider implementing it when we will see that this feature is in demand.

**Comment by pschmolke** [comment]
To specify repeatable tests would be a nice feature. For example when running smoke tests for a given software feature.
You can now say: test this feature, but I want to know if it still remains functional when I test it <n> times.
Yes one can provide a loop for that, but  in my opinion that should be doable without changing the test code itself. This in return would keep individual tests more compact and more readable.

**Comment by AlexKamaev** [comment]
We decided to close the issue. We don't have to implement it out of the box in the near future since we have tasks with higher priority. We recommend using the workaround from the following comment: [https://github.com/DevExpress/testcafe/issues/7445#issuecomment-1369556927](https://github.com/DevExpress/testcafe/issues/7445#issuecomment-1369556927).

**Comment by Klaster1** [comment]
Here's a package I made exactly for this purpose, enjoy.
https://www.npmjs.com/package/@klaster_1/testcafe-repeat-test
