### ISSUE TITLE
fix 'Should provide node snapshots for non-element nodes' test in the master branch

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe#7571]
Run the `Should provide node snapshots for non-element nodes` test in the proxyless mode (`test-functional-local-proxyless` task).

**Comment by AlexKamaev** [comment]
I fixed the test in the https://github.com/DevExpress/testcafe/pull/7564/files#diff-489b6074ac8eda0a0c3ce8511ee10f6d35cfcdee98afefaa74a06c7647bdcfc2R196

However, the issue still exists.
The cause of the issue is in that the `document.body.childNodes[0]` call returns hammerhead shadowUI root.
However, for some reason, if we check the `document.body.childNodes` before taking the element, everything works.
