### ISSUE TITLE
Cursor is not visible when testcafe run with proxyless

### ISSUE THREAD

**Issue by FlorinCio** [DevExpress/testcafe#7581]
### What is your Scenario?

cursor is not visible when proxyless mode is running. Because of this the hover function in nested dropdown isn't working.

### What is the Current behavior?

cursor not visible

### What is the Expected behavior?

cursor to be visible

### What is your public website URL? (or attach your complete example)

Not relevant--

### What is your TestCafe test code?

test('Check', async t => {
    'use strict';
    await t
        .maximizeWindow()
        .navigateTo('https://mdbootstrap.com/docs/standard/extended/dropdown-multilevel/')
        .click('#dropdownMenuButton')
        .hover(new Selector('main .dropdown-item').nth(2))
        .click(new Selector('main .dropdown-item').nth(3));
    ;
});

### Your complete configuration file

Not relevant--

### Your complete test report

Not relevant--

### Screenshots

![image](https://user-images.githubusercontent.com/42927945/227162814-c113d21b-2da8-4b58-8e40-2d09d521f53c.png)
![image](https://user-images.githubusercontent.com/42927945/227162864-40a03f7e-40b2-4066-a64b-421873d00094.png)

### Steps to Reproduce

1.Run the test I just added or on a nested dropdown

### TestCafe version

2.4.0

### Node.js version

16.15.1

### Command-line arguments

testcafe -- -t 'Check' --experimental-proxyless

### Browser name(s) and version(s)

chrome  111.0.5563.65

### Platform(s) and version(s)

Windows 10

**Comment by AlexKamaev** [comment]
You are right. The Cursor is invisible right now. It's an implementation feature of the `--experimental-proxyless` mode. We are aware of this.

Regarding the issue, I did not manage to reproduce the described behavior. The test passes. I do not think that the issue can be related to the missing pointer because the arrow pointer is made for convenience. It is not involved in the event emulation process.
