### ISSUE TITLE
Remove deprecated and outdated modules

### ISSUE THREAD

**Issue by Shanejp** [DevExpress/testcafe#7611]
### What is your Scenario?

Testcafe references many deprecated packages which result in errors when executing via cli.
![image](https://user-images.githubusercontent.com/36070355/230012549-9e247b5d-bc5a-4daa-91f5-38bdc5cfe290.png)

### What are you suggesting?

update dependencies  or remove dependencies that I no longer needed

### What alternatives have you considered?

n/w

**Comment by miherlosev** [comment]
Hi @Shanejp,

Thank you for pointing this out.
I install the latest Testcafe version (`2.5.0`) and get significantly fewer warnings.
![](https://user-images.githubusercontent.com/4133518/230532787-71651db3-05d0-4306-8242-7b9f3d2e0d0f.png)
We constantly update outdated and deprecated packages. Sometimes, we cannot do this fast due to some reasons (dependency on an unsupported module, no alternatives, and so on).
If you want to update some dependencies right now, a PR is greatly appreciated.

**Comment by Shanejp** [comment]
Thanks, I'll check it out.
I raised this when I was on version 2.4.0 - and which was the latest
available

Shane Pillay
quality test specialist

mobile: 076 037 1540 <+27760371540>

phone: 087 2310 230 <0872310230>

website: www.codeo.co.za

codeo_
