### ISSUE TITLE
Pinning alpine version in Dockerfile

### ISSUE THREAD

**Issue by stickperson** [DevExpress/testcafe#7714]
### What is your Scenario?

Using `alpine:edge` in the `Dockerfile` is very unstable and leads to frequent issues when installing specific versions of packages.

### What are you suggesting?

Rather than using `alpine:edge`, specific versions of alpine should be used e.g. `alpine:3.18`.

**Comment by AlexKamaev** [comment]
Hello.
We understand that using the `alpine:edge` version can sometimes cause issues when installing certain packages. However, it looks like these issues are usually fixed quickly. Most of our users don't need extra packages, so it's easier for us to stick with the edge version instead of a specific one. As a workaround, you can use our Dockerfile to build your own TestCafe image with the required Alpine version.
