### ISSUE TITLE
js error in testcafe but not manually 

### ISSUE THREAD

**Issue by marinamarin91** [DevExpress/testcafe#7814]
### What is your Scenario?

In the scenario that I run, I have to click on some links which open a new window with a list of elements. 

### What is the Current behavior?

Test is failing due to a js error which manually cannot be seen in the console. 

### What is the Expected behavior?

no error is expected

### What is your public website URL? (or attach your complete example)

website is not public. Attached is a printscreen on the page where the error occurs

![image](https://github.com/DevExpress/testcafe/assets/97027602/db8d7b02-46d8-46c2-a9f8-ffb2d3e28c52)

### What is your TestCafe test code?

|//Click on <Ansvar> under <Konteringslinjer>
       > 511 |.click(PageOkonomi.FakturaerMenu.AnsvarLink)
         512 |//A searchbox and list of Ansvars shows
         513 |.expect(PageOkonomi.FakturaerMenu.LinkSearchBox.exists).ok()

test fails at click on the Ansvar Link. It can be seen in the screenshow above that error is not present 

### Your complete test report

![image](https://github.com/DevExpress/testcafe/assets/97027602/13b602cc-3c84-4178-a3c0-80ac75671df6)

### Steps to Reproduce

1. Click on link
2. Search window should appear

### TestCafe version

Using locally installed version of TestCafe. 2.5.0

### Node.js version

node -v   v16.20.0

### Command-line arguments

testcafe chrome:headless *.js

**Comment by marinamarin91** [comment]
Can we have a short meeting to show you the example? the webpage is not public, neither the user/password , so I cannot send you the files :). Thanks

**Comment by AlexKamaev** [comment]
Please try updating your TestCafe version to the latest one. You can also try using the `--native-automation` flag to resolve the issue. If this does not help, we need to reproduce the issue on our side.

>Can we have a short meeting to show you the example? the webpage is not public, neither the user/password , so I cannot send you the files :). Thanks

We cannot have an online meeting since we do not offer such a service. The best way is to send us a sample via email at support@devexpress.com.

Note that our policy prevents us from accessing a customer's internal resources without prior written approval from the entity that owns the server/web resource.

If you want us to research the problem further, we'll need access to the server/web resource. Please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing and debugging purposes.
