### ISSUE TITLE
`--proxy` command line option stopped working in 3.0.0

### ISSUE THREAD

**Issue by tuxofil** [DevExpress/testcafe#7838]
### What is your Scenario?

Launch testcafe as:
```
testcafe "chrome:/usr/bin/google-chrome-stable:headless --disable-dev-shm-usage" \
    --reporter=json \
    --proxy 127.0.0.1:8888 \
    script.testcafe
```

### What is the Current behavior?

Script succeeds, but the traffic isn't sent through the `127.0.0.1:8888` HTTP proxy (it used to work up to TestCafe v2.6.2).

### What is the Expected behavior?

TestCafe sets up the browser to use `127.0.0.1:8888` HTTP proxy server, as it was prior to TestCafe v3.0.0.

### What is your public website URL? (or attach your complete example)

https://github.com/tuxofil/testcafe-bugreport

### What is your TestCafe test code?

```json
{
  "fixtures": [
    {
      "name": "Test",
      "pageUrl": "http://archive.ubuntu.com/ubuntu/",
      "tests": [
        {
          "name": "main",
          "commands": [
            {
              "type": "assertion",
              "assertionType": "contains",
              "expected": {
                "type": "js-expr",
                "value": "\"Index of /ubuntu\""
              },
              "actual": {
                "type": "js-expr",
                "value": "Selector('h1').nth(0).innerText"
              }
            }
          ]
        }
      ]
    }
  ]
}
```

### Your complete configuration file

no config file used

### Your complete test report

```json
{
  "startTime": "2023-06-28T13:32:45.583Z",
  "endTime": "2023-06-28T13:32:48.183Z",
  "userAgents": [
    "Chrome 114.0.5735.198 / Ubuntu 23.04"
  ],
  "passed": 1,
  "total": 1,
  "skipped": 0,
  "fixtures": [
    {
      "name": "Test",
      "path": "/home/user/script.testcafe",
      "meta": {},
      "tests": [
        {
          "name": "main",
          "meta": {},
          "errs": [],
          "durationMs": 476,
          "unstable": false,
          "screenshotPath": null,
          "skipped": false
        }
      ]
    }
  ],
  "warnings": []
}
```

### Steps to Reproduce

1. Install HTTP proxy server, Google Chrome and TestCafe;
2. Launch HTTP proxy server in background;
3. Launch TestCafe with `--proxy` command line option, pointing to the proxy server
4. Check the proxy server logs.

Implemented and described here: https://github.com/tuxofil/testcafe-bugreport

### TestCafe version

3.0.0

### Node.js version

20.3.1

### Command-line arguments

"chrome:/usr/bin/google-chrome-stable:headless --disable-dev-shm-usage" --reporter=json --proxy 127.0.0.1:8888 script.testcafe

### Browser name(s) and version(s)

Google Chrome 114.0.5735.198

### Platform(s) and version(s)

Ubuntu 23.04

**Comment by tuxofil** [comment]
@Makavelic ,
Yep, it worked with `--disable-native-automation` command line switch. According to https://testcafe.io/documentation/402830/guides/basic-guides/run-tests#use-a-proxy ,

> When TestCafe uses [native automation](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode), it cannot route HTTP requests through a proxy. Use the built-in capabilities of your operating system to configure a proxy connection.

I wonder what are these capabilities I can take advantage of? Could you please name a few? Asking because setting `http_proxy` environment variable or passing `--proxy-server` cmd arg directly to the Chrome didn't help.

**Comment by AlexKamaev** [comment]
It is correct. TestCafe cannot use the `--proxy` option in Native Automation.
Since TestCafe has no underlying proxy server, we cannot use the `--proxy` option anymore in Native Automation mode.
You can try the following steps to set Proxy settings using Chrome: [How to Use Chrome Browser Proxy Settings](https://oxylabs.io/resources/integrations/chrome).
Please note that Chrome settings just redirect you to the OS Proxy settings page.


In case you use Windows OS, you can change your proxy settings directly using the following link:
[https://support.microsoft.com/en-us/windows/use-a-proxy-server-in-windows-03096c53-0554-4ffe-b6ab-8b1deee8dae1#:~:text=server%20connection%20manually-,Select%20the%20Start%20button%2C%20then%20select%20Settings%20%3E%20Network%20%26%20internet,on%20Use%20a%20proxy%20server](https://support.microsoft.com/en-us/windows/use-a-proxy-server-in-windows-03096c53-0554-4ffe-b6ab-8b1deee8dae1#:%7E:text=server%20connection%20manually-,Select%20the%20Start%20button%2C%20then%20select%20Settings%20%3E%20Network%20%26%20internet,on%20Use%20a%20proxy%20server).
