### ISSUE TITLE
Test user agent differs when run localy and remotely

### ISSUE THREAD

**Issue by pavelmrazek** [DevExpress/testcafe#7885]
### What is your Scenario?

Run test on local and remote machine

### What is the Current behavior?

1) When test is run in headed mode on Chrome Mac as local machine '- Chrome 114.0.0.0 / Ventura 13' is logged as user agent
2) When test is run in headless mode on Chrome Mac as local machine '- Chrome 114.0.5735.198 / Ventura 13' is logged as user agent
3) When test is run on Chrome Mac as remote 'CONNECTED Chrome 114.0.0.0 / macOS 10.15.7' is logged as user agent.

Notes:
All of these were run on the same machine.
The actual Mac OS: Ventura 13.14.1
The actual Chrome version: 114.0.5735.198

### What is the Expected behavior?

User agent in is the same, no matter if run remote/local

### What is your public website URL? (or attach your complete example)

n/a

### What is your TestCafe test code?

n/a

### Steps to Reproduce

1) Write in terminal on local Mac 'testcafe chrome tests.js'
2) Write in terminal on local Mac 'testcafe chrome:headless tests.js'
3) Write in terminal on different machine 'testcafe remote tests.js --hostname 1.1.1.1
4) Connect testcafe on remote Mac in chrome (from previous step)
5) Compare logged user agents

### TestCafe version

2.0.0

### Command-line arguments

Described in 'Steps to reproduce'

**Comment by Aleksey28** [comment]
Hi @pavelmrazek,

It's expected behavior. TestCafe retrieves the user agent from the browser.

As for the browser version, the latest versions of Chrome no longer include information about the minor versions. You can refer to this blog post by the Chrome team for details: [https://developer.chrome.com/blog/user-agent-reduction-android-model-and-version/#user-agent-reduction-so-far](https://developer.chrome.com/blog/user-agent-reduction-android-model-and-version/#user-agent-reduction-so-far). The fact that it is still shown in `headless` mode is a Chrome bug.

Regarding different MacOS versions - if you try to do it manually in DevTools, you'll see the wrong OS version. But when you run tests locally, TestCafe can get information about OS directly, which is why you can see the correct version. When you run `remote` tests, TestCafe has access only to the user agent from the browser.
