### ISSUE TITLE
CLI argument to skip tests based on metadata

### ISSUE THREAD

**Issue by RInverid** [DevExpress/testcafe#7915]
### What is your Scenario?

When running a subset of tests, I would like to be able to run all tests *except* those with certain metadata. This would allow me to test a product with certain features disabled, by skipping all the tests for the disabled feature.

### What are you suggesting?

Currently meta tests can be run by using the `--test-meta` cli argument. I would like to propose a new ali argument: `--test-meta-skip`, that is the inverse of the existing argument.

### What alternatives have you considered?

Filtering by name with RegExp would allow us to use negative matching, to skip certain tests. This would require defining all required features for the test in the test name, which makes test results more complex by having unneccesarily long test names.

**Comment by AlexKamaev** [comment]
Thank you for your suggestion. We discussed it with the team and decided not to implement such a functionality in the CLI, since you can implement this approach programmatically.

Please refer to the following help topic for details:
[https://testcafe.io/documentation/403436/guides/intermediate-guides/metadata-and-filtering#runner-2](https://testcafe.io/documentation/403436/guides/intermediate-guides/metadata-and-filtering#runner-2)
