### ISSUE TITLE
t.click incorrectly applies :focus-visible class in Firefox

### ISSUE THREAD

**Issue by tomasVizdal** [DevExpress/testcafe#7969]
### What is your Scenario?

When `t.click(divElement)` executes in Firefox v106.0.3 browser on windows 10, `:focus-visible` pseudo class is applied on the div. This is not happening when the test is done manualy.

### What is the Current behavior?

When `t.click(divElement)` in Firefox v106.0.3 browser on windows 10, `:focus-visible` pseudo class is applied on the div. This is not happening when the test is done manualy.

### What is the Expected behavior?

Clicking on an element should not apply `:focus-visible`. Observe that other browsers like Chrome or Edge do not apply the `:focus-visible` pseudo class.

### What is your public website URL? (or attach your complete example)

````html
<html>
<head>
    <style>
        #divWithFocusVisible {
            border: 1px solid red;
        }

        #divWithFocusVisible:focus-visible {
            border: 10px solid #00D6FF;
        }
    </style>
    <title>:focu-visible in Firefox</title>
</head>
<body>
<div id="divWithFocusVisible" tabindex="0">
    Should not have focus ring.
</div>
</body>
</html>
````

### What is your TestCafe test code?

```
fixture`focus-visible`
    .page('index.html');
test('Should not have applied :focus-visible after click', async () => {
    const divWithFocusVisible = Selector('#divWithFocusVisible');
    const redColor = 'rgb(255, 0, 0)';

    await t
        .expect(divWithFocusVisible.getStyleProperty('border-top-color')).eql(redColor)
        // click on the div element should not apply :focus-visible
        .click(divWithFocusVisible)
        .expect(divWithFocusVisible.getStyleProperty('border-top-color')).eql(redColor);
});
```

### Steps to Reproduce

1. Execute the enclosed testcafe test in Firefox

### TestCafe version

3.2.0

### Node.js version

18.17.1

### Command-line arguments

testcafe firefox test-file.ts

### Browser name(s) and version(s)

Firefox 106.0.3

### Platform(s) and version(s)

Windows 10

**Comment by Aleksey28** [comment]
Thank you for reporting the issue.

I managed to reproduce it. The issue is not in Firefox. It's a specificity of our proxy driver. Since the TestCafe version 3.0.0, we run tests in [Native Automation](%5Bhttps://testcafe.io/404431/resources/blog/2023-6-21-testcafe-goes-native%5D(https://testcafe.io/404431/resources/blog/2023-6-21-testcafe-goes-native)) mode by default for Chromium-based browser. This mode reduces the use of our proxy driver. That's why your usage scenario works fine in Chrome. At present, we do not support this mode for Firefox. As a workaround, you can execute this type of test only with Chromium-based browsers (e.g. Chrome, MS Edge) and don't turn off the Native Automation mode.

Since the usage scenario is very rare and the issue has a workaround, I'll close it. Please let us know if the suggested workaround doesn't meet your needs.

**Comment by tomasVizdal** [comment]
Hello @Aleksey28,
Unfortunately, we have to run this test on Firefox and Safari. Coudly ouplease consider to reopen the issue?

**Comment by AlexKamaev** [comment]
We can reopen the issue. However, we cannot give you any time estimates for our research or the fix.
