### ISSUE TITLE
soft asserts feature

### ISSUE THREAD

**Issue by razvanvancea** [DevExpress/testcafe#8023]
### What is your Scenario?

I have a test that contains multiple assertions. Would be great a method like .softExpect that instead of stopping the test execution at the first failed assert, to continue the execution with the remaining steps. In the end I would like to see all the failed asserts at once, instead of fixing the first assert, rerun the test, fix the second assert, rerun the test and so on.

### What are you suggesting?

To have a new method like .softExpect() that handles soft assertions as described above

### What alternatives have you considered?

the not so elegant workaround is having fewer asserts per tests, fingers crossed they pass
If you mean by alternative solution other tools, this feature exists in selenium for years and on pw as well (e.g. https://playwright.dev/docs/test-assertions#soft-assertions for reference)

**Comment by Aleksey28** [comment]
Hi @razvanvancea,

Thank you for your interest in TestCafe. Currently, we do not see it reasonable to execute the next assertion if the previous failed because the test has already failed and the application doesn't behave as expected. There was a discussion about it already: [https://github.com/DevExpress/testcafe/issues/80](https://github.com/DevExpress/testcafe/issues/80).

As a workaround, you can use the `try...catch` JS construction for this purpose. I'll close this issue for now. We'll reopen it once there's a high demand for this feature.
