### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Fetch') 

### ISSUE THREAD

**Issue by alice-ep** [DevExpress/testcafe#8076]
### What is your Scenario?

We have a pipeline running several TestCafe fixtures, usually without issue.

### What is the Current behavior?

Every once in a while, one of the fixtures (completely randomly) fails with the following error:
```
> @spectre-tests/e2e@0.1.0 test-all
> testcafe -q attemptLimit=3,successThreshold=1 -s path=D:\data\CHT\44a9602d\UserLogs\TestResults\TestCafe -f Alerts -c 2

The "concurrency" option from the configuration file will be ignored.
ERROR Unable to open the "edge:emulation:width=1920;height=1080; --lang=en-US" browser due to the following error:

TypeError: Cannot read properties of undefined (reading 'Fetch')
    at NativeAutomationRequestPipeline.start (D:\ct\44a9602d\[BuildRoot]\Applications\spectre\tests\e2e-build\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:390:28)
    at NativeAutomation.start (D:\ct\44a9602d\[BuildRoot]\Applications\spectre\tests\e2e-build\node_modules\testcafe\src\native-automation\index.ts:46:29)
    at BrowserProviderPluginHost._setupNativeAutomation (D:\ct\44a9602d\[BuildRoot]\Applications\spectre\tests\e2e-build\node_modules\testcafe\src\browser\provider\built-in\dedicated\chrome\index.js:63:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BrowserProviderPluginHost.openBrowser (D:\ct\44a9602d\[BuildRoot]\Applications\spectre\tests\e2e-build\node_modules\testcafe\src\browser\provider\built-in\dedicated\chrome\index.js:109:13)
    at BrowserProvider.openBrowser (D:\ct\44a9602d\[BuildRoot]\Applications\spectre\tests\e2e-build\node_modules\testcafe\src\browser\provider\index.ts:326:9)
    at BrowserConnection._runBrowser (D:\ct\44a9602d\[BuildRoot]\Applications\spectre\tests\e2e-build\node_modules\testcafe\src\browser\connection\index.ts:279:13)
```

I assume turning off native automation will make this go away but we haven't tried that.

### What is the Expected behavior?

Browser should start up

### What is the public URL of the test page? (attach your complete example)

Cannot provide a link to our tests unfortunately, and I'm frankly not sure how to provide an example that will reproduce this. It has never happened in a local run, and it's impossible to predict when it will happen in our CI either - the fixture that fails is completely random, some of them were written 2+ years ago, some of them recent. It doesn't happen in every run, and when it does happen a re-run works.

### What is your TestCafe test code?

n/a

### Your complete configuration file

{
    "browsers": ["edge:emulation:width=1920;height=1080; --lang=en-US"],
    "cache": true,
    "concurrency": 8,
    "reporter": [
        { "name": "spec" },
        { "name": "spec", "output": "./results/reports/report.txt" },
        { "name": "json", "output": "./results/reports/report.json" },
        { "name": "trx", "output": "./results/reports/report.trx" }
    ],
    "screenshots": {
        "pathPattern": "${FIXTURE}--${TEST}--${DATE}_${TIME}_${BROWSER}/${FILE_INDEX}_trial_#${QUARANTINE_ATTEMPT}.png",
        "takeOnFails": true
    },
    "src": "./dist/",
    "selectorTimeout": 90000,
    "assertionTimeout": 90000,
    "pageLoadTimeout": 90000
}

### Your complete test report

```
> testcafe -q attemptLimit=3,successThreshold=1 -s path=D:\data\CHT\44a9602d\UserLogs\TestResults\TestCafe -f Alerts -c 2

The "concurrency" option from the configuration file will be ignored.
ERROR Unable to open the "edge:emulation:width=1920;height=1080; --lang=en-US" browser due to the following error:

TypeError: Cannot read properties of undefined (reading 'Fetch')
    at NativeAutomationRequestPipeline.start (D:\ct\44a9602d\[BuildRoot]\Applications\spectre\tests\e2e-build\node_modules\testcafe\src\native-automation\request-pipeline\index.ts:390:28)
    at NativeAutomation.start (D:\ct\44a9602d\[BuildRoot]\Applications\spectre\tests\e2e-build\node_modules\testcafe\src\native-automation\index.ts:46:29)
    at BrowserProviderPluginHost._setupNativeAutomation (D:\ct\44a9602d\[BuildRoot]\Applications\spectre\tests\e2e-build\node_modules\testcafe\src\browser\provider\built-in\dedicated\chrome\index.js:63:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BrowserProviderPluginHost.openBrowser (D:\ct\44a9602d\[BuildRoot]\Applications\spectre\tests\e2e-build\node_modules\testcafe\src\browser\provider\built-in\dedicated\chrome\index.js:109:13)
    at BrowserProvider.openBrowser (D:\ct\44a9602d\[BuildRoot]\Applications\spectre\tests\e2e-build\node_modules\testcafe\src\browser\provider\index.ts:326:9)
    at BrowserConnection._runBrowser (D:\ct\44a9602d\[BuildRoot]\Applications\spectre\tests\e2e-build\node_modules\testcafe\src\browser\connection\index.ts:279:13)
```

### Steps to Reproduce

N/A

### TestCafe version

3.3.0

### Node.js version

18.17.0

### Command-line arguments

-q attemptLimit=3,successThreshold=1 -s path=D:\data\CHT\44a9602d\UserLogs\TestResults\TestCafe -f {fixtureName} -c 2

### Browser name(s) and version(s)

Edge 119

### Platform(s) and version(s)

Windows

**Comment by aleks-pro** [comment]
Hello @alice-ep ,

Please try enabling testcafe logs on your CI - `set DEBUG=testcafe:*,hammerhead:*` and capture the results when the problematic behaviour takes place. Send the results to us, The logs might help us find the cause of the issue.

**Comment by Lyian** [comment]
Hi, I have pretty much the same issue. We run a container on a kubernetes cluster with testcafe v3.3.0:

The logs when setting `DEBUG=testcafe:*,hammerhead:*` are

`testcafe -u "chromium:headless '--window-size=1920,1080 --lang=de --no-sandbox --disable-dev-shm-usage'" --hostname localhost tests/testcafe/support/enable-dotenv.js tests/testcafe/spec/legal/impressum.test.js
  testcafe:cli
  testcafe:cli     [
  testcafe:cli       '/usr/bin/node',
  testcafe:cli       '/e2e/node_modules/testcafe/lib/cli',
  testcafe:cli       '-u',
  testcafe:cli       "chromium:headless '--window-size=1920,1080 --lang=de --no-sandbox --disable-dev-shm-usage'",
  testcafe:cli       '--hostname',
  testcafe:cli       'localhost',
  testcafe:cli       'tests/testcafe/support/enable-dotenv.js',
  testcafe:cli       'tests/testcafe/spec/legal/impressum.test.js'
  testcafe:cli     ]
  testcafe:cli  +0ms
  testcafe:cli
  testcafe:cli     {
  testcafe:cli       clientScripts: [],
  testcafe:cli       skipUncaughtErrors: true,
  testcafe:cli       hostname: 'localhost',
  testcafe:cli       v8Flags: undefined,
  testcafe:cli       listBrowsers: false,
  testcafe:cli       browsers: [
  testcafe:cli         'chromium:headless --window-size=1920,1080 --lang=de --no-sandbox --disable-dev-shm-usage'
  testcafe:cli       ],
  testcafe:cli       src: [
  testcafe:cli         'tests/testcafe/support/enable-dotenv.js',
  testcafe:cli         'tests/testcafe/spec/legal/impressum.test.js'
  testcafe:cli       ],
  testcafe:cli       filter: undefined,
  testcafe:cli       screenshots: {},
  testcafe:cli       reporter: []
  testcafe:cli     }
  testcafe:cli  +5ms
  testcafe:version 3.3.0 +0ms
  testcafe:configuration Unable to find the "/e2e/.testcaferc.js" configuration file. Error details:
  testcafe:configuration
  testcafe:configuration Error: ENOENT: no such file or directory, stat '/e2e/.testcaferc.js' +0ms
  testcafe:configuration Unable to find the "/e2e/.testcaferc.cjs" configuration file. Error details:
  testcafe:configuration
  testcafe:configuration Error: ENOENT: no such file or directory, stat '/e2e/.testcaferc.cjs' +0ms
  testcafe:reporter begin dispatchToPlugin method: init
  testcafe:reporter [ '3.3.0' ] +0ms
  testcafe:reporter end dispatchToPlugin method: init +0ms
  testcafe:runner
  testcafe:runner     TestCafeConfiguration {
  testcafe:runner       _options: {
  testcafe:runner         disablePageCaching: Option {
  testcafe:runner           name: 'disablePageCaching',
  testcafe:runner           value: true,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         screenshots: Option {
  testcafe:runner           name: 'screenshots',
  testcafe:runner           value: [Object],
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         developmentMode: Option {
  testcafe:runner           name: 'developmentMode',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Default'
  testcafe:runner         },
  testcafe:runner         retryTestPages: Option {
  testcafe:runner           name: 'retryTestPages',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Default'
  testcafe:runner         },
  testcafe:runner         cache: Option {
  testcafe:runner           name: 'cache',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Default'
  testcafe:runner         },
  testcafe:runner         disableHttp2: Option {
  testcafe:runner           name: 'disableHttp2',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Default'
  testcafe:runner         },
  testcafe:runner         disableNativeAutomation: Option {
  testcafe:runner           name: 'disableNativeAutomation',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Default'
  testcafe:runner         },
  testcafe:runner         disableCrossDomain: Option {
  testcafe:runner           name: 'disableCrossDomain',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Default'
  testcafe:runner         },
  testcafe:runner         filter: Option {
  testcafe:runner           name: 'filter',
  testcafe:runner           value: null,
  testcafe:runner           source: 'Default'
  testcafe:runner         },
  testcafe:runner         isCli: Option {
  testcafe:runner           name: 'isCli',
  testcafe:runner           value: true,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         hostname: Option {
  testcafe:runner           name: 'hostname',
  testcafe:runner           value: 'localhost',
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         port1: Option {
  testcafe:runner           name: 'port1',
  testcafe:runner           value: 43413,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         port2: Option {
  testcafe:runner           name: 'port2',
  testcafe:runner           value: 33573,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         ssl: Option {
  testcafe:runner           name: 'ssl',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         configFile: Option {
  testcafe:runner           name: 'configFile',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         v8Flags: Option {
  testcafe:runner           name: 'v8Flags',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         esm: Option {
  testcafe:runner           name: 'esm',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         proxy: Option {
  testcafe:runner           name: 'proxy',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         proxyBypass: Option {
  testcafe:runner           name: 'proxyBypass',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         src: Option {
  testcafe:runner           name: 'src',
  testcafe:runner           value: [Array],
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         tsConfigPath: Option {
  testcafe:runner           name: 'tsConfigPath',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         browsers: Option {
  testcafe:runner           name: 'browsers',
  testcafe:runner           value: [Array],
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         reporter: Option {
  testcafe:runner           name: 'reporter',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         concurrency: Option {
  testcafe:runner           name: 'concurrency',
  testcafe:runner           value: 1,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         videoPath: Option {
  testcafe:runner           name: 'videoPath',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         videoOptions: Option {
  testcafe:runner           name: 'videoOptions',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         videoEncodingOptions: Option {
  testcafe:runner           name: 'videoEncodingOptions',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         appCommand: Option {
  testcafe:runner           name: 'appCommand',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         appInitDelay: Option {
  testcafe:runner           name: 'appInitDelay',
  testcafe:runner           value: 1000,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         clientScripts: Option {
  testcafe:runner           name: 'clientScripts',
  testcafe:runner           value: undefined,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         compilerOptions: Option {
  testcafe:runner           name: 'compilerOptions',
  testcafe:runner           value: [Object],
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         skipUncaughtErrors: Option {
  testcafe:runner           name: 'skipUncaughtErrors',
  testcafe:runner           value: true,
  testcafe:runner           source: 'Input'
  testcafe:runner         },
  testcafe:runner         debugMode: Option {
  testcafe:runner           name: 'debugMode',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         debugOnFail: Option {
  testcafe:runner           name: 'debugOnFail',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         stopOnFirstFail: Option {
  testcafe:runner           name: 'stopOnFirstFail',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         takeScreenshotsOnFails: Option {
  testcafe:runner           name: 'takeScreenshotsOnFails',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         disablePageReloads: Option {
  testcafe:runner           name: 'disablePageReloads',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         disableScreenshots: Option {
  testcafe:runner           name: 'disableScreenshots',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         disableMultipleWindows: Option {
  testcafe:runner           name: 'disableMultipleWindows',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         selectorTimeout: Option {
  testcafe:runner           name: 'selectorTimeout',
  testcafe:runner           value: 10000,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         assertionTimeout: Option {
  testcafe:runner           name: 'assertionTimeout',
  testcafe:runner           value: 3000,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         pageLoadTimeout: Option {
  testcafe:runner           name: 'pageLoadTimeout',
  testcafe:runner           value: 3000,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         speed: Option {
  testcafe:runner           name: 'speed',
  testcafe:runner           value: 1,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         },
  testcafe:runner         skipJsErrors: Option {
  testcafe:runner           name: 'skipJsErrors',
  testcafe:runner           value: false,
  testcafe:runner           source: 'Configuration'
  testcafe:runner         }
  testcafe:runner       },
  testcafe:runner       _defaultPaths: [
  testcafe:runner         '/e2e/.testcaferc.js',
  testcafe:runner         '/e2e/.testcaferc.json',
  testcafe:runner         '/e2e/.testcaferc.cjs'
  testcafe:runner       ],
  testcafe:runner       _filePath: '/e2e/.testcaferc.json',
  testcafe:runner       _overriddenOptions: [],
  testcafe:runner       _isExplicitConfig: false
  testcafe:runner     }
  testcafe:runner  +0ms
  testcafe:hammerhead:proxy:router register route GET /hammerhead.js +0ms
  testcafe:hammerhead:proxy:router register route GET /transport-worker.js +7ms
  testcafe:hammerhead:proxy:router register route GET /worker-hammerhead.js +0ms
  testcafe:hammerhead:proxy:router register route GET /messaging +1ms
  testcafe:hammerhead:proxy:router register route POST /messaging +0ms
  testcafe:hammerhead:proxy:router register route OPTIONS /messaging +0ms
  testcafe:hammerhead:proxy:router register route GET /task.js +0ms
  testcafe:hammerhead:proxy:router register route GET /iframe-task.js +0ms
  testcafe:hammerhead:proxy:router register route GET /browser/connect/{id} +4ms
  testcafe:hammerhead:proxy:router register route GET /browser/heartbeat/{id} +0ms
  testcafe:hammerhead:proxy:router register route GET /browser/idle/{id} +0ms
  testcafe:hammerhead:proxy:router register route GET /browser/idle-forced/{id} +0ms
  testcafe:hammerhead:proxy:router register route GET /browser/status/{id} +0ms
  testcafe:hammerhead:proxy:router register route GET /browser/status-done/{id} +0ms
  testcafe:hammerhead:proxy:router register route GET /browser/init-script/{id} +0ms
  testcafe:hammerhead:proxy:router register route POST /browser/init-script/{id} +0ms
  testcafe:hammerhead:proxy:router register route GET /browser/active-window-id/{id} +0ms
  testcafe:hammerhead:proxy:router register route POST /browser/active-window-id/{id} +1ms
  testcafe:hammerhead:proxy:router register route POST /browser/close-window/{id} +0ms
  testcafe:hammerhead:proxy:router register route POST /browser/open-file-protocol/{id} +0ms
  testcafe:hammerhead:proxy:router register route POST /browser/dispatch-native-automation-event/{id} +0ms
  testcafe:hammerhead:proxy:router register route POST /parse-selector/{id} +0ms
  testcafe:hammerhead:proxy:router register route POST /browser/dispatch-native-automation-event-sequence/{id} +0ms
  testcafe:hammerhead:proxy:router register route GET /browser/connect +0ms
  testcafe:hammerhead:proxy:router register route GET /browser/connect/ +0ms
  testcafe:hammerhead:proxy:router register route GET /service-worker.js +0ms
  testcafe:hammerhead:proxy:router register route GET /browser/assets/index.js +0ms
  testcafe:hammerhead:proxy:router register route GET /browser/assets/styles.css +0ms
  testcafe:hammerhead:proxy:router register route GET /browser/assets/logo.svg +0ms
  testcafe:hammerhead:proxy:router register route GET /about:error +0ms
  testcafe:hammerhead:proxy:router register route GET /testcafe-core.js +1ms
  testcafe:hammerhead:proxy:router register route GET /testcafe-driver.js +0ms
  testcafe:hammerhead:proxy:router register route GET /testcafe-legacy-runner.js +1ms
  testcafe:hammerhead:proxy:router register route GET /testcafe-automation.js +1ms
  testcafe:hammerhead:proxy:router register route GET /testcafe-ui.js +1ms
  testcafe:hammerhead:proxy:router register route GET /testcafe-ui-sprite.png +1ms
  testcafe:hammerhead:proxy:router register route GET /testcafe-ui-sprite.svg +0ms
  testcafe:hammerhead:proxy:router register route GET /favicon.ico +0ms
  testcafe:hammerhead:proxy:router register route GET /testcafe-ui-styles.css +0ms
  testcafe:utils:temp-directory Found temp directories: [ 'chrome-profile-62ezCbjyAa28ua' ] +0ms
  testcafe:utils:temp-directory Temp directory path:  /tmp/testcafe/chrome-profile-62ezCbjyAa28ua +1ms
  testcafe:bootstrapper tests compilation took 640 ms +0ms
  testcafe:browser-tools:open '"/usr/bin/chromium" --remote-debugging-port=45985 --user-data-dir=/tmp/testcafe/chrome-profile-62ezCbjyAa28ua --headless --window-size=1920,1080 --lang=de --no-sandbox --disable-dev-shm-usage --disable-infobars --disable-session-crashed-bubble --no-first-run --new-window --disable-background-networking --disable-ipc-flooding-protection --disable-background-timer-throttling --disable-backgrounding-occluded-windows --autoplay-policy=no-user-gesture-required "http://localhost:43413/browser/connect/9vd9U-2" 0<&- >/dev/null 2>&1 &' +0ms
  testcafe:browser:connection:9vd9U-2 status changed to 'ready' +0ms
  testcafe:browser:provider:built-in:dedicated:chrome Error: connect ECONNREFUSED ::1:45985
  testcafe:browser:provider:built-in:dedicated:chrome     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
  testcafe:browser:provider:built-in:dedicated:chrome     at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) +0ms
  testcafe:native-automation starting +0ms
  testcafe:browser:connection:9vd9U-2 Error: Unable to open the "chromium:headless --window-size=1920,1080 --lang=de --no-sandbox --disable-dev-shm-usage" browser due to the following error:
  testcafe:browser:connection:9vd9U-2
  testcafe:browser:connection:9vd9U-2 TypeError: Cannot read properties of undefined (reading 'Fetch')
  testcafe:browser:connection:9vd9U-2     at NativeAutomationRequestPipeline.start (/e2e/node_modules/testcafe/src/native-automation/request-pipeline/index.ts:390:28)
  testcafe:browser:connection:9vd9U-2     at NativeAutomation.start (/e2e/node_modules/testcafe/src/native-automation/index.ts:46:29)
  testcafe:browser:connection:9vd9U-2     at BrowserProviderPluginHost._setupNativeAutomation (/e2e/node_modules/testcafe/src/browser/provider/built-in/dedicated/chrome/index.js:63:32)
  testcafe:browser:connection:9vd9U-2     at processTicksAndRejections (node:internal/process/task_queues:95:5)
  testcafe:browser:connection:9vd9U-2     at BrowserProviderPluginHost.openBrowser (/e2e/node_modules/testcafe/src/browser/provider/built-in/dedicated/chrome/index.js:109:13)
  testcafe:browser:connection:9vd9U-2     at BrowserProvider.openBrowser (/e2e/node_modules/testcafe/src/browser/provider/index.ts:326:9)
  testcafe:browser:connection:9vd9U-2     at BrowserConnection._runBrowser (/e2e/node_modules/testcafe/src/browser/connection/index.ts:279:13)
  testcafe:browser:connection:9vd9U-2     at BrowserConnection._runBrowser (/e2e/node_modules/testcafe/src/browser/connection/index.ts:288:32)
  testcafe:browser:connection:9vd9U-2     at processTicksAndRejections (node:internal/process/task_queues:95:5) +54ms
  testcafe:browser:connection:9vd9U-2 status changed to 'closing' +0ms
ERROR Unable to open the "chromium:headless --window-size=1920,1080 --lang=de --no-sandbox --disable-dev-shm-usage" browser due to the following error:

TypeError: Cannot read properties of undefined (reading 'Fetch')
    at NativeAutomationRequestPipeline.start (/e2e/node_modules/testcafe/src/native-automation/request-pipeline/index.ts:390:28)
    at NativeAutomation.start (/e2e/node_modules/testcafe/src/native-automation/index.ts:46:29)
    at BrowserProviderPluginHost._setupNativeAutomation (/e2e/node_modules/testcafe/src/browser/provider/built-in/dedicated/chrome/index.js:63:32)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at BrowserProviderPluginHost.openBrowser (/e2e/node_modules/testcafe/src/browser/provider/built-in/dedicated/chrome/index.js:109:13)
    at BrowserProvider.openBrowser (/e2e/node_modules/testcafe/src/browser/provider/index.ts:326:9)
    at BrowserConnection._runBrowser (/e2e/node_modules/testcafe/src/browser/connection/index.ts:279:13)`

**Comment by Bayheck** [comment]
Hello, thank you for reaching out to us.
Unfortunately, it's difficult to determine the cause of the issue without a sample.

Could you please create a minimal working example so that our team can take a closer look at the issue?

 

Please refer to the following help topic for additional information: [how to create a minimal working example](%5Bhttps://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue)]([https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue](https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue)))
