### ISSUE TITLE
Add `ignore-ssl-certs` option in TestRunner methods for TestCafe

### ISSUE THREAD

**Issue by ash8454** [DevExpress/testcafe#8111]
### What is your Scenario?

We are currently using TestRunner API  methods to define the browser, concurrency etc for our tests using TestRunner API. Currently all our tests are failing when we use native automation of TestCafe due to ssl certificate error.

### What are you suggesting?

We would like to have method to ignore ssl certs using TestRunner API like other methods to define concurrency, proxy, browser etc.

### What alternatives have you considered?

Tried using HammerHead but we are getting issues where we are seeing errors while clicking elements hidden inside the main element.

**Comment by Bayheck** [comment]
Hello, 
thank you for reaching out to us.
Try using the 

```
--ignore-certificate-errors
```

flag when you define your browser.
Please note that this flag is applicable only in Chrome and Chromium-based browsers.
 
If using the

```
--ignore-certificate-errors
```

flag doesn't resolve the issue, another approach you can consider is using a [self-signed certificate](https://testcafe.io/documentation/402839/guides/advanced-guides/test-https-features-and-http2-websites#generate-a-certificate-in-your-code) generated by the

```
openssl-self-signed-certificate
```

module.

Feel free to implement these solutions and let us know if you encounter any issues.

**Comment by ash8454** [comment]
Thank you for your response @Bayheck 
However, like i said before, we would like to get them methods in testrunner api so we can use it in cucumber. Currently, adding that flag doesn't work for us.

Thanks,
Ash

**Comment by Bayheck** [comment]
As far as I understood, you are using something like:

```
const testcafe = await createTestCafe(testCafeOptions);
 
    await testcafe.createRunner()
        .src('test.js')
        .browsers('chrome')
         //other methods
```

If so, you can still use ‘[--ignore-certificate-errors](https://testcafe.io/documentation/403937/faq/working-with-testcafe?search#my-tests-fail-in-native-automation-mode-because-the-website-uses-an-invalid-ssl-certificate-what-should-i-do)’ flag like this:

```
const testcafe = await createTestCafe(testCafeOptions);
 
    await testcafe.createRunner()
        .src('test.js')
        .browsers('chrome --ignore-certificate-errors)')
         //other methods
```
 
In addition, did you try to use a [self-signed certificate](https://testcafe.io/documentation/402839/guides/advanced-guides/test-https-features-and-http2-websites#generate-a-certificate-in-your-code) approach?

If this does not help, could you please provide a [minimal working example](https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue) or a screencast illustrating the issue?
