### ISSUE TITLE
add parameter to take fullPage screenshot on failure

### ISSUE THREAD

**Issue by vasilyevi** [DevExpress/testcafe#8116]
### What is your Scenario?

I would like to have a fullpage screenshot on any fail, but do not have fullpage by default for all takeScreenshot actions

### What are you suggesting?

add fullPageOnFails 

### What alternatives have you considered?

there is no workaround in my case

**Comment by PavelMor25** [comment]
Hello @vasilyevi,

We discussed this use case with the team and decided to close this ticket because the existing functionality is sufficient to complete your task. 

You can set the `fullpage` option by default for all screenshots in the configuration file. In the `takeScreenshot` method, pass the `fullPage=false` option. Alternatively, you can [create a custom test action](https://testcafe.io/documentation/404150/guides/advanced-guides/custom-test-actions) based on `takeScreenshot` that uses `fullPage=false` by default.
