### ISSUE TITLE
Private properties problem in hammerhead proxy main.js  

### ISSUE THREAD

**Issue by Lukowalski97** [DevExpress/testcafe#8119]
### What is your Scenario?

While using angular application with https://github.com/markedjs/marked 9.1.6 version there is a problem with my app while accessing it via testcafe. 
In https://github.com/markedjs/marked/blob/f9d08cc1ef5294b1866705860242f78528f8d508/src/Instance.ts#L241 there is a private method #parseMarkdown() which is incorrectly rewritten to new main.js file.

### What is the Current behavior?

during tests it looks like this:
```
class mt {
parse = this.e(dt.lex, ft.parse);
parseInline = this.e(dt.lexInline, ft.parseInline);
....
 #e(u, d) {
  ....
}} 
```

As one can see - # from method call is removed but it's still present in method definition, and when method is called, error is thrown and app does not work. 
In application, without testcafe this problem does not occur. 

### What is the Expected behavior?

In original it looks like this:
```
class mt {
parse = this.#e(dt.lex, ft.parse);
parseInline = this.#e(dt.lexInline, ft.parseInline);
....
 #e(u, d) {
  ....
}}
```

main.js should be properly rewritten, so this method works

### What is the public URL of the test page? (attach your complete example)

-

### What is your TestCafe test code?

It does not depend on actual TestCafe code

### Steps to Reproduce

1. Create an angular app which uses marked.js with proper version
2. Create a testcafe testcase which enters a view that is using marked.js 
3. Run testcase - error should occur in console

### TestCafe version

3.4.0 

### Command-line arguments

using testcafe runner 

### Browser name(s) and version(s)

Chrome 119.0.0

### Platform(s) and version(s)

Ubuntu 22.04

### Other

runner options:
{
  "src": "src/tests",
  "browsers": "chrome",
  "speed": 1,
  "concurrency": 1,
  "skipJsErrors": true,
  "quarantineMode": false,
  "color": true,
  "debugOnFail": true,
  "developmentMode": true,
  "browserInitTimeout": 180000,
  "disableNativeAutomation": true
}

**Comment by PavelMor25** [comment]
Hello @Lukowalski97,

Could you clarify why you run tests in proxy mode? You can run TestCafe in native-automation mode, which should resolve the issue.

Also, In TestCafe 3.5.0, there were several fixes related to handling private fields. Please try to reproduce the issue with v3.5.0 and let us know if it's resolved.

If the issue persists, please add a [minimal working example](
https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue) so that the TestCafe team can research the issue.
