### ISSUE TITLE
skipJsErrors should support many ignore rules

### ISSUE THREAD

**Issue by ChrisLane** [DevExpress/testcafe#8120]
### What is your Scenario?

I have more than one library that throws errors that I can neither catch nor fix that I would like to ignore in TestCafe.
I would like to be able to easily configure TestCafe to ignore these errors separately.

### What are you suggesting?

`skipJsErrors` should accept an array of rules.

**Example**
```JSON
    "skipJsErrors": [{
        "stack": "/.*jquery.*/",
        "message": "/.*User ID.*/ig"
    },
    {
        "stack": "/.*otherlibrary.*/",
        "message": "Something broke!"
    }]
```

### What alternatives have you considered?

For now, I am solving this issue by passing a function that can match against more than one set of ignore rules.

**Comment by PavelMor25** [comment]
Hello @ChrisLane,

We cannot take this enhancement into work, since currently we are fully focused on other tasks. We may reconsider this task priority in the future if we get requests for it. However, if you want, you can make a PR with the described functionality. We will review and accept it if everything is ok.
