### ISSUE TITLE
Native Automation requires https protocol

### ISSUE THREAD

**Issue by czarekeltonjohn** [DevExpress/testcafe#8133]
### What is your Scenario?

We have web applications deployed on internal k8s cluster available by http protocol. Is there any configuration or flag that will allow testcafe v.3.5.0 with native automation enabled to reach such web app using http protocol. We can omit ssl certificate errors using chrome flag, but it seems testcafe is allowing only https (which in my case is always unreachable). Even if I explicetely set page as "http://" in testcafe browser it is "https://"

### What are you suggesting?

Configuration change or flag that will allow native automation using http protocol

**Comment by PavelMor25** [comment]
Hello @czarekeltonjohn,

TestCafe allows you to open HTTPS and HTTP/2 websites in Native Automation mode out of the box. Please share a [minimal working example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue) so that the TestCafe team can research the issue and help you.

**Comment by czarekeltonjohn** [comment]
Hi, let me share with you with my minimal working example.

.testcaferc configured to ignore ssl errors and disable natie automation for sure
```{
  "browsers": "chrome --ignore-certificate-errors",
  "disableNativeAutomation": false
}
```

test.ts  with test of navigating to website served only by http, site cannot be opened because testcafe browser tries to open it by https
```
fixture('MWE')
test('Website served only by HTTP is tried to be opened with HTTPS', async () => {
  await t.navigateTo('http://www.testingmcafeesites.com/')
  await t.debug()
```

<img width="1061" alt="image" src="https://github.com/DevExpress/testcafe/assets/86650360/1e11a7fe-c4cd-4800-b9cc-7a457b2c3b05">

**Comment by PavelMor25** [comment]
Hello @czarekeltonjohn,

We have investigated this issue and found a workaround for it. Since requests in Chrome are automatically upgraded to HTTPS in `Native automation`, you can create a [custom request hook](https://testcafe.io/documentation/402842/guides/intermediate-guides/intercept-http-requests#create-a-custom-request-hook) that will intercept request and change the protocol back to HTTP. Then, you can either [define it globally in the configuration file](https://testcafe.io/documentation/402842/guides/intermediate-guides/intercept-http-requests#define-global-hooks-in-the-configuration-file) or use it at [the fixture or test level](https://testcafe.io/documentation/402842/guides/intermediate-guides/intercept-http-requests#attach-hooks-to-tests-and-fixtures).

**customRequestHookFile.js:**
```javascript
import { RequestHook } from 'testcafe';
 
export default class CustomRequestHook extends RequestHook {
    constructor (requestFilterRules) {
        super(requestFilterRules);
    }

    onRequest(e) {
        e.requestOptions.protocol = 'http:';
    }

    onResponse(e) {
    }
}
``` 

**configuration file:**
```javascript
import CustomRequestHook from './hook.js'

const hook = new CustomRequestHook(/https?:\/\/www.testingmcafeesites.com/)

module.exports = {
    hooks: {
        request: hook
    }
}
``` 

Please let us know your results.

**Comment by wombatka** [comment]
I have the same issue- tried using you workaround but it does not work fully- my url is opened via http - which is ok, but after i login to the application- nothing is loaded- please provide a working workaround. It is critical for me - currenrly all our tests are failing

**Comment by PavelMor25** [comment]
Hello @wombatka,

Could you please create a separate ticket for the issue and share a [minimal working example](https://testcafe.io/documentation/402636/faq/general-info?search#how-to-create-a-minimal-working-example-when-you-submit-an-issue)? This will help the TestCafe team investigate the issue in greater detail.
