### ISSUE TITLE
Incorrect resizeToFitDevice on mac with portaitOrientation=true

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe#816]
``` javascript
fixture('React').page('https://facebook.github.io/react/');

test('Resize to fit device', async t => {
    await t.resizeWindowToFitDevice('Nexus 7 (2013)', { portraitOrientation: true });

    const getWindowHeight = ClientFunction(() => window.innerHeight);
    const getWindowWidth  = ClientFunction(() => window.innerWidth);

    expect(await getWindowHeight()).eql(960);
    expect(await getWindowWidth()).eql(600);
});
```

`AssertionError: expected 896 to deeply equal 960`

**Comment by AndreyBelym** [comment]
We cannot resize a window to the size bigger than the desktop size on Mac. Can you specify your Mac desktop size as well?

**Comment by inikulin** [comment]
@AndreyBelym Maybe we could give warning in that case?

**Comment by AndreyBelym** [comment]
Sure!

**Comment by AndreyBelym** [comment]
## Browser provider API changes:

### canResizeWindowToDimensions(browserId, width, height)
Allows to validate the specified `width` and `height` of browser window `browserId` before the actual resize. The result is `true` if browser window can be resized to the specified dimensions, `false` otherwise.

### hasCustomActionForBrowser(browserId)
Enables feature querying for the specified browser window `browserId`. The function should return an object with the following properties:
`hasResizeWindow` - the browser window supports resizing,
`hasMaximizeWindow` - the browser  window supports maximizing,
`hasTakeScreenshots` - the browser window image can be captured to the file,
`hasCanResizeWindowToDimensions` - the requested window dimensions can be validated before resize.

If a property in the returned object has the `true` value, the provider should have an implemented function with the name corresponding to the property. (e.g. `hasTakeScreenshot` => `takeScreenshot`). The default implementation for `hasCustomActionForBrowser` checks for the function names by calling `hasOwnProperty` on provider object.

### isLocalBrowser(browserId)
Returns `true` if the specified browser `browserId` is a local browser. Default implementation ignores `browserId` and always returns `false`.
