### ISSUE TITLE
please add pathPattern to takeElementScreenshot too

### ISSUE THREAD

**Issue by vasilyevi** [DevExpress/testcafe#8182]
### What is your Scenario?

n/a

### What are you suggesting?

please add pathPattern to takeElementScreenshot too

**Comment by Bayheck** [comment]
Unfortunately, we cannot take this enhancement in work, since currently, we are focused on other tasks. We may reconsider this task priority in the future if we get requests for it. However, if you want, you can make a PR with the described functionality, we will review and accept it if everything is OK.
