### ISSUE TITLE
element.visible is returning false , when in version 3.5.0 returned true

### ISSUE THREAD

**Issue by gabogarcia1** [DevExpress/testcafe#8216]
### What is your Scenario?

As I upgraded the version to 3.6.0 , I was checking my test and most started to fail because "Elements were not visible". I went back to version 3.5.0 and i didn't have the issue

### What is the Current behavior?

As I upgraded the version to 3.6.0 , I was checking my test and most started to fail because "Elements were not visible". I went back to version 3.5.0 and i didn't have the issue

### What is the Expected behavior?

As I upgraded the version to 3.6.0 , I was checking my test and most started to fail because "Elements were not visible". I went back to version 3.5.0 and i didn't have the issue

### What is the public URL of the test page? (attach your complete example)

work repository, cant share

### What is your TestCafe test code?

cant share

### Steps to Reproduce

1.
2.
3.

### TestCafe version

3.6.0

### Command-line arguments

none

**Comment by HJL-bex** [comment]
I am recently seeing a similar issue, where e.g. the 'element is too small to be visible: 89px x 28px'. It seems to be affecting devexpress elements like selectbox inputs or components based on devexpress elements. Not sure if it's because of the latest testcafe version as I saw this happening in a previous version as well. Could it be because of a chrome update?

**Comment by HJL-bex** [comment]
We are using a dx-data-grid, with several dxo-properties and dxi-columns with cell templates. Clicking on the cellTemplate with the data-selector results in a message like "The action target (<own-created-element _ngcontent-ng-c3123921236=""
      data-selector="grid_something_column">...</own-created-element>) is too
      small to be visible: 89px x 28px.

Column: <dxi-column
							cellTemplate="somethingTemplate"
							dataField="someNumber"
							calculateDisplayValue="something"
							dataType="string"
							caption="{{ 'text_to_translate' | translate }}"
							editCellTemplate="somethingEditTemplate"
							[width]="100"
							[renderAsync]="true"
							[allowEditing]="true"
						>

CellTemplate:  <div *dxTemplate="let d of 'somethingTemplate'">
							<own-created-element [something]="d.row.data.somethingNumber" 
                                                                 data-selector="grid_something_column"></own-created-element>
						</div>

**Comment by PavelMor25** [comment]
Hello @HJL-bex,

Thank you for sharing the layout and for the explanation, but we need an example to precisely reproduce the issue.

**Comment by gforepsly** [comment]
I also have the same issue with the latest version 3.6.1.

The error:
The action target (<checkbox _ngcontent-qyn-c312="" test-id="checkbox" class="territory-selector__select-all-item" _nghost-qyn-c45="">...</repsly-checkbox>) is too small to be visible: 320px x 44px.

I can't really share the example, but so many of our tests are failing, it's a big problem for us. It's about an icon that is a checkbox, and the check is for the visibility, but it just fails with this error. Anything I can do about it to avoid this?

**Comment by Bayheck** [comment]
Hello, we understand that the issue affects your solution. However, as was stated previously, we need a working reproducible example of the issue. Without this example, we cannot investigate it.

**Comment by gforepsly** [comment]
Hi,

I've managed to mitigate the issue. I will try and explain our case.

When you locate the html tag of Angular component, the issue exist there (on click, on getting text, on checking visibility..).
Basically, when you have this:

<some-angular-component id="1"> 
    <div id="2">Some Text </div >
</some-angular-component>

const locator = Selector('#1').
t.click(locator) //THIS DOENST WORK, it throws an error as stated above.

const locator = Selector('#1').find('div').
t.click(locator) //THIS WORKS

We just refactored couple of locators and the issue is not present anymore.
