### ISSUE TITLE
Unable to install testCafe on isolated server

### ISSUE THREAD

**Issue by cassnapper** [DevExpress/testcafe#8242]
### What is your Scenario?

I am trying to use testCafe on a server with no internet access. 

### What is the Current behavior?

I followed the install instructions whereby I download the tar file and then npm install from that file. I am getting the following error :
npm error code EAI_AGAIN
npm error syscall geraddrinfo 
npm error errno EAI_AGAIN
npm error request to https://registry.npmjs.org/@babel%2fcore failed, reason : getaddrinfo EAI_AGAIN registry.npmjs.org

THe log file has a lot of other fails trying to access this url.
Why is the installation trying to access a URL when this is supposed to be the approach where the internet is not available ?

### What is the Expected behavior?

To install on the ringfenced server so I can use the product.

### What is the public URL of the test page? (attach your complete example)

n/A

### What is your TestCafe test code?

N/A

### Steps to Reproduce

1.see above
2.
3.

### TestCafe version

testcafe-3.6.2.tar

### Node.js version

v20.15.1

### Command-line arguments

N/A

**Comment by PavelMor25** [comment]
Hello @cassnapper,

Typically, a tar file used for installation does not contain the `node_modules` directory. Instead, the tar file generally contains the configuration and source files, with dependencies expected to be installed separately.

The  issue occurs while `npm` attempts to fetch the required dependencies from the `npm` registry. Since the `node_modules` directory is missing from the tar file, `npm` needs to download these dependencies.

You can try to [install TestCafe from the source](https://testcafe.io/documentation/402834/guides/basic-guides/install-testcafe#install-testcafe-from-source) with a slight adjustment. After completing the first step, copy the `TestCafe` folder to your isolated server. Then, proceed with step two using the `npm link` method.

Please let us know your results.
